### ISSUE TITLE
Superfluous entries in load-path

### ISSUE THREAD

**Issue by doolio** [emacs-ess/ESS#1000]
If ESS is installed using any package manager, then it will already be added to the load-path, and therefore [this line](https://github.com/emacs-ess/ESS/blob/625041ad51038e43ac12e466e3001a252725d88b/lisp/ess-custom.el#L158) can be removed.

For those that don't use a package manager I believe would have the `lisp` directory added to their `load-path` by loading `ess-site.el` and specifically [this line](https://github.com/emacs-ess/ESS/blob/625041ad51038e43ac12e466e3001a252725d88b/lisp/ess-site.el#L56).

For both use cases the `obsolete` directory will be added with [this line](https://github.com/emacs-ess/ESS/blob/625041ad51038e43ac12e466e3001a252725d88b/lisp/ess-custom.el#L162).

**Comment by jabranham** [comment]
Thanks for the bug report, it marks our thousandth since moving to github! :fireworks: 

ess-site is pseudo obsolete which is why that line is duplicated.

**Comment by jabranham** [comment]
@doolio I pushed a commit so that we use the more standard directory-file-name, which should take care of your duplicate entry issue from the issue you linked.

**Comment by doolio** [comment]
Indeed it does. Thank you.
