### ISSUE TITLE
inferior-ess-reload with remote R process

### ISSUE THREAD

**Issue by zauster** [emacs-ess/ESS#1001]
Hey all,

when I load an R-file via TRAMP and then execute `ess-eval-region`, a remote R process is started. However, when I call then `inferior-ess-reload`, a local R process is started instead of a remote one. The `setwd` call that tries to re-set the previous working directory then fails.
One has to manually close the R process, then `ess-eval-region` (or similar) starts again a new remote process.

Though I use spacemacs and found the issue there, I can reproduce the issue also with `emacs -Q -l ~/.emacs.d/elpa/26.3/develop/ess-20200328.1547/ess-autoloads.el`

Could be related to #871. I checked the "suggested" similar issues, but they do not mention this problem.

**Comment by dapritchard** [comment]
The call stack to create the new process appears to be the following, with later calls at the top.
```
start-file-process
exec-path
comint-exec-1
comint-exec
inferior-ess--start-process
inferior-ess
run-ess-r
inferior-ess-reload--override
inferior-ess-reload
```
The issue appears to result due the to value of the `default-directory` variable. `start-file-process` uses the value of this variable to create a file handler for the process, but for the inferior buffer the value of `default-directory` typically has the value of the local filepath, which then results in a local R process being initiated.

**Comment by zauster** [comment]
Thanks a lot @dapritchard!
