### ISSUE TITLE
Flycheck not working with lintr > 2.0.0

### ISSUE THREAD

**Issue by frederic-santos** [emacs-ess/ESS#1002]
**Warning**: this may be a problem unrelated to ESS (but I don't know if the issue is due to `lintr`, flycheck or ESS).

Since the last update of `lintr` package (2.0.1) in February, flycheck does not find anything in R buffers. In a test file with many syntax errors, `flycheck-buffer` does nothing. When coming back to the previous version of `lintr` (2.0.0), everything is fine. This might be a clue towards a `lintr` bug, but v2.0.1 is quite 'old' now, and no issue was opened on the `lintr` GitHub repo for this problem.
Are there some ESS users out there experimenting the same problem with `lintr` 2.0.1?

This is my config:
```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux
```
and I currently run the latest Melpa versions of ESS and Flycheck. The command `flycheck-verify-setup` shows nothing unusual:

```
First checker to run:

  r-lintr
    - may enable:    yes
    - predicate:     t
    - executable:    Found at /usr/bin/R
    - lintr library: present

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot (package: 20200402.1701)
Emacs version:    26.3
System:           x86_64-pc-linux-gnu
Window system:    x
```

Thanks!

**Comment by jabranham** [comment]
Hi - 

ESS doesn't support flycheck, you might try asking over at their repo. FWIW ESS does support flymake in Emacs 26+ and it seems to be working fine with lintr 2.0.1.

**Comment by frederic-santos** [comment]
Hi,
Thanks for your answer! Just in case someone would have the same issue: actually, it seems this was really an ArchLinux (or Manjaro) problem. I followed the instructions given on this thread, and everything works now: https://github.com/flycheck/flycheck/issues/1442
Sorry, ESS was indeed far from being the culprit :)
