### ISSUE TITLE
julia do not insert exit() when stopping inferiour process

### ISSUE THREAD

**Issue by seregaxvm** [emacs-ess/ESS#1009]
When editing ess-julia-mode script with running inferior julia, stopping inferior process scrolls script file to the end and inserts `exit()` string there.

Steps to reproduce:
* <kbd>C-u 20 RET</kbd> <kbd>M-<</kbd> <kbd>\<C-return\> RET</kbd> (empty script with 20 lines, cursor at the beginning and started inferior julia)
* <kbd>C-c C-q</kbd>

Expected behavior:
stopping inferior julia process should not alter cursor position or add text to the file being edited.

**Comment by jabranham** [comment]
This is because we don't respect ess-eval-visibly in ess-quit. That's an easy change to make, but there's also no way to toggle the value and the prefix arg is already taken to mean "don't save workspace" by ess-r-mode...

Here's the diff that makes ess-quit respect ess-eval-visibly:

```diff
diff --git a/lisp/ess-r-mode.el b/lisp/ess-r-mode.el
index 70a85f9b..273dd72c 100644
--- a/lisp/ess-r-mode.el
+++ b/lisp/ess-r-mode.el
@@ -1380,7 +1380,7 @@ selected (see `ess-r-set-evaluation-env')."
         (sprocess (ess-get-process ess-current-process-name)))
     (when (not sprocess) (error "No ESS process running"))
     (ess-cleanup)
-    (ess-send-string sprocess cmd t)))
+    (ess-send-string sprocess cmd)))
 
 (defcustom inferior-ess-r-reload-hook nil
   "Hook run when reloading the R inferior buffer."
```


```diff
diff --git a/lisp/ess-inf.el b/lisp/ess-inf.el
index 0d6b2685..4502c9f5 100644
--- a/lisp/ess-inf.el
+++ b/lisp/ess-inf.el
@@ -2144,11 +2144,12 @@ to the command if BUFF is not given.)"
 ;;;*;;; Quitting
 
 (cl-defgeneric ess-quit--override (_arg)
-  "Stops the inferior process"
+  "Stop the inferior process."
   (let ((proc (ess-get-process)))
     (ess-cleanup)
-    (goto-char (marker-position (process-mark proc)))
-    (insert inferior-ess-exit-command)
+    (when ess-eval-visibly
+      (goto-char (marker-position (process-mark proc)))
+      (insert inferior-ess-exit-command))
     (process-send-string proc inferior-ess-exit-command)))
 
 (defun ess-quit (&optional arg)
```

**Comment by vspinu** [comment]
It probably should save-excurse as well.
