### ISSUE TITLE
Only strip roxy prefix when the whole input is prefixed

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#1020]
See https://github.com/emacs-ess/ESS/commit/1e18deda5ccad9c0f9c54a4cf0ceb5f6c9c1b77f#commitcomment-39806833

**Comment by mmaechler** [comment]
Yes, indeed.  I had also noticed this bug.  In my case it was really "crazy":
Inside an `*.R` file buffer, I used  (via `C-<arrow up>`) the 
`(ess-eval-buffer-from-beg-to-here)` to evaluate hundreds of lines of R, and then "somewhere up there" was a small function with some roxygen headers  that lead to an R error message about a `@` ..
