### ISSUE TITLE
what happened to inferior-STA-program-name ?

### ISSUE THREAD

**Issue by vapniks** [emacs-ess/ESS#1021]
I have some private code which depends on `inferior-STA-program-name`
However, with the latest ESS update (18.10.3snapshot / elpa: 20200613.857) that variable has disappeared.

**Comment by jabranham** [comment]
We're working to split ess stata support into its own package. Until
that's complete, you'll need to get ESS from MELPA-stable.

**Comment by vapniks** [comment]
OK

**Comment by vspinu** [comment]
I thought we moved stata to obsolete and did not removed it. @rsparapa ? I think we should not remove STATA support before the next release.

**Comment by rsparapa** [comment]
Yes, I moved it to obsolete.  But, Alex wanted to do something else, right?
