### ISSUE TITLE
? not working

### ISSUE THREAD

**Issue by dsteuer** [emacs-ess/ESS#1023]
Hi ESS-devs,

I'm using ess-version: 18.10.3snapshot [<unknown>] (loaded from /home/steuer/.emacs.d/elpa/ess-20200619.854/).

Minimal resp. no setup at all, but worked since a very long time:
(use-package ess
  :defer t
  :commands R
  :ensure t)

Today ?merge gave me 
+ Fehler in .ess.help("merge") : konnte Funktion ".ess.help" nicht finden 
and completion on R function names not working.

(could not find function ".ess.help")

My feeling is ESS is moving a bit too fast and becoming somewhat unstable lately. Similar hiccups
from time to time.
A trade-off, sure, but annoying at times.

Remember Shakespeare: 'Wisely and slow, those stumble that run fast' .

Thx for the work on ESS, but keep it working, please! I *really* don't want to use rstudio to write code.
Detlef

**Comment by lionel-** [comment]
Something must be wrong in your setup/installation. Probably ESSR did not successfully load. Maybe try debugging `R-initialize-on-start`.

> My feeling is ESS is moving a bit too fast and becoming somewhat unstable lately

Please be more specific. I see you're using the 2018 version. Were you previously using the dev version on MELPA? In any case, what kind of instability are you thinking about?

**Comment by dsteuer** [comment]
Am Wed, 24 Jun 2020 02:30:52 -0700
schrieb Lionel Henry <notifications@github.com>:

> Something must be wrong in your setup/installation. Probably ESSR did
> not successfully load. Maybe try debugging `R-initialize-on-start`.
>
> > My feeling is ESS is moving a bit too fast and becoming somewhat
> > unstable lately
>
> Please be more specific. I see you're using the 2018 version.

Sorry, no.

As written in my report my version *is*
ess-20200619.854/ from Melpa
and I'm using the melpa version since long.

Do you advice against using melpa and use the released version
from 2018?

> Were
> you previously using the dev version on MELPA? In any case, what kind
> of instability are you thinking about?
>

I hereby promise to write bug reports in the future :-) I had similar,
unspecific and now forgotten minor problems in the last few years.

It was just a feeling, not a useful bug report, I admit.

And to be clear: A lot more thank you for the work than grumpy remarks :-)

Detlef

**Comment by lionel-** [comment]
ah I was confused by the `18.10.3snapshot` part. Some unstability when using the development version is to be expected and bug reports are useful. You can also use MELPA-stable which is pinned to the last released version (18.10.2).

**Comment by lionel-** [comment]
I'll close this since it looks like an installation problem.
