### ISSUE TITLE
ess-eval-region-or-line-and-step : Failing in multiline cases in `*.Rd` \examples{..} section when "namespace mode"

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#1026]
Related to #725 .  Also related to the entry in its help

> Note that when inside a package and namespaced evaluation is in
> place (see `ess-r-set-evaluation-env'), the evaluation of multiline input will fail."

I find this very "unfriendly", and also wrong design:  Inside the \example{} section I do *NOT* want namespaced evaluation.
I will have a version of the package to which the help page belongs *attach*ed in my `search()` path, and want the examples to behave as for a user; i.e., things should not happen in the package namespace, but all in globalenv.

**Comment by mmaechler** [comment]
I've also noticed that namespaced  evaluation happened when it should not have... but I think this happened a lot a while ago, but has been fixed or at least improved a while ago... OTOH, this may just be the kind of R files I had been working with in different time periods.

**Comment by lionel-** [comment]
I'm seeing incorrect namespaced evaluation when running `#' @examples` code in roxygen documentation.

**Comment by mmaechler** [comment]
Aah "exactly":  The once I've seen where  from R code inside  \examples{..}  in man/*.Rd  pages,
and possibly also R code inside  <pkg>/tests/*.R  ..
