### ISSUE TITLE
Where is ess-stata-mode provided?

### ISSUE THREAD

**Issue by tarsius** [emacs-ess/ESS#1033]
`inferior-ess--set-major-mode` may `require` `ess-stata-mode`, but I cannot find a library that provides that feature. (The tools that I use to maintain the Emacsmirror informed me about a user.)

**Comment by jabranham** [comment]
It's in ess-stata-mode.el which was removed from this repo for copyright reasons. We have plans to put it up in a separate repo but no one has gotten around to actually doing that yet. It should still be a part of ess in, eg, melpa-stable.

**Comment by tarsius** [comment]
Thanks for the information!

For future reference:  #1006.

**Comment by jia-j-chen** [comment]
I would appreciate it if ess-stata-mode can be put back up soon. A lot of my work depends on it!

**Comment by BrendanHalpin** [comment]
I've just installed ess version 18.10.3snapshot [elpa: 20200905.822] and come across this. I would really appreciate the re-introduction of stata-mode. For now I'll downgrade ESS.

**Comment by lionel-** [comment]
@tslumley The FSF copyright transfer for stata-mode would still be greatly appreciated.

**Comment by BrendanHalpin** [comment]
Looking at the code, I see an old e-mail address of mine, brendan@essex.ac.uk, in ess-stata-lang.el. The contributed code is probably obsolete and unnecessary, but I am happy to transfer copyright.

**Comment by BrendanHalpin** [comment]
In fact, I did sign a copyright release a year ago (I remembered I had signed one but forgot it covered this code).

**Comment by tslumley** [comment]
I sent it, but apparently it's not good enough, and I would need to get a transfer from the University of Washington, where I was a student, even though they had an explicit policy about not owning student copyrights. I've got no idea how to go about doing that and they don't have any particular reason to cooperate.


 -thomas


Thomas Lumley
Professor of Biostatistics
University of Auckland
________________________________

**Comment by lionel-** [comment]
@tslumley oh I didn't know about that. Thanks for the update!

**Comment by tarsius** [comment]
So we are back to this plan:

> It's in ess-stata-mode.el which was removed from this repo for copyright reasons. We have plans to put it up in a separate repo but no one has gotten around to actually doing that yet.

Right?

**Comment by jabranham** [comment]
That's my understanding, yes. I've made an attempt at this but AFAICT
there's no (easy) way to isolate the git history of those files for a new
repo. If anyone has any tips, greatly appreciated!

**Comment by tarsius** [comment]
Use something like

```
git filter-repo --path lisp/ess-mode.el
```

You can specify multiple `--path` and you might want to use `--path-rename <old_name:new_name>` to move files to the top-level.

See https://github.com/newren/git-filter-repo#how-do-i-use-it.

**Comment by jabranham** [comment]
Thanks! I knew about filter-branch but filter-repo is new to me.

I've put stata mode into https://github.com/emacs-ess/ess-stata-mode, which is private for now. If everyone agrees, I'll make it public and add a recipie to MELPA.

@lionel- @vspinu @mmaechler

**Comment by lionel-** [comment]
Sounds good to me!

**Comment by tslumley** [comment]
?Me too


  -thomas


Thomas Lumley
Professor of Biostatistics
University of Auckland
________________________________

**Comment by vspinu** [comment]
Yes, let's do that.

**Comment by djh1202** [comment]
Was the Stata-mode repo ever made public? I don't see the it...

**Comment by rsparapa** [comment]
What is stopping us from making it public right now?

**Comment by mmaechler** [comment]
It looks public now;  can you confirm you see it, @djh1202  ?

**Comment by tarsius** [comment]
While we are at it `regexp-span` should be renamed to something that begins with the package prefix, maybe `make-regexp-get-span`?

**Comment by rsparapa** [comment]
If we delete make-regexp.el from obsolete, then can we close this issue?

**Comment by tarsius** [comment]
Yes.

**Comment by rsparapa** [comment]
I added make-regexp.el to ESS many years ago.  I did not claim authorship in my FSF paperwork.  It has now been removed.  This Issue is now complete and closed.

**Comment by tarsius** [comment]
Thanks!

**Comment by jia-j-chen** [comment]
Can I ask some basic questions?

I put the files in the public ess-stata-mode repo where other ess package files are. But, when I open a stata code block, it still reports "No such language mode: stata-mode". What else should I do?

**Comment by BrendanHalpin** [comment]
Try this:
```
(setq inferior-STA-start-args "")
(setq inferior-STA-program "stata")

(require 'ess)
(require 'ess-r-mode)
(require 'ess-stata-mode)

```

**Comment by jia-j-chen** [comment]
> Try this:
> 
> ```
> (setq inferior-STA-start-args "")
> (setq inferior-STA-program "stata")
> 
> (require 'ess)
> (require 'ess-r-mode)
> (require 'ess-stata-mode)
> ```

This works for me. Thanks! @BrendanHalpin
