### ISSUE TITLE
Please do not bundle etest

### ISSUE THREAD

**Issue by tarsius** [emacs-ess/ESS#1037]
If at all possible, then a repository used to maintain an Emacs package should not bundle any third-party libraries.

Bundling external dependencies might not cause any issues for users who install the package from Melpa, because packages distributed there can filter out unwanted libraries. But some people (including myself) run packages directly from their repositories (e.g. because that makes it much easier to contribute).

For such users the bundled library may end up on the `load-path`, possibly before the independently installed upstream version.  As a result some outdated version can end up being loaded and that can be very confusing and hard to debug.

I recommend that you never bundle any third-party libraries.  If that is not possible, then I recommend that you put those libraries in a separate directory and alongside a file named `.nosearch`. The existence of this file instructs some tools (such as `normal-top-level-add-subdirs-to-load-path`, my [`borg`](https://emacsair.me/2016/05/17/assimilate-emacs-packages-as-git-submodules/) package manager, and the tools I use to maintain the Emacsmirror) to ignore the containing directory.

*In this case it is not possible to not bundle the external dependency. Melpa does not distribute `etest` and if it started to do so, then it would likely distribute the same version as the one on the Emacsmirror, which is the unrelated and older package by the same name, that can be found at https://github.com/philjackson/etest.*

*So it should be hidden using the `.nosearch` file and be loaded using an explicit relative path.*

Thanks for considering this!

<sub>I have written similar messages many many times so I now [use a template](https://help.github.com/en/github/writing-on-github/working-with-saved-replies). I try to adjust it to match each individual case but it might still not apply 100% in all cases.</sub>

**Comment by lionel-** [comment]
At the moment etest is an _internal_ dependency ;)

**Comment by tarsius** [comment]
Yes, but the heuristics used by the tools used to extract metadata for the Emacsmirror fail to make that determination even though they have been honed on a few thousand packages. By adding the `.nosearch` file you would help them come to the right conclusion.

**Comment by lionel-** [comment]
That makes sense, thanks for the detailed explanation.

**Comment by lionel-** [comment]
By the way, how did https://github.com/philjackson/etest get added to the emacsmirror? I looked up that package before choosing the etest name and it seemed it had only been developed for a short period of time, had no reverse dependencies, and was not distributed in Melpa. It also has `(defun deftest` which looks like it wouldn't play well in the larger ecosystem.

What would happen to the `etest` mirror on emacsmirror if I were to publish my etest package on Melpa? I guess the larger question is whether emacsmirror acts as an authority regarding namespace and package registration.

**Comment by tarsius** [comment]
> By the way, how did https://github.com/philjackson/etest get added to the emacsmirror?

I don't remember. While nowadays I reply mostly on Melpa to learn about new packages, in the past I searched more aggressively.

> What would happen to the `etest` mirror on emacsmirror if I were to publish my etest package on Melpa? I guess the larger question is whether emacsmirror acts as an authority regarding namespace and package registration.

I would expect @riscy to notice before merging. We would want to resolve the conflict before adding your package to Melpa, so one of us would ask you and @philjackson to have a talk. Oh look, I just did. :grinning:

**Comment by philjackson** [comment]
Hey, all. Please consider etest (my version) dead and unused as far as I know. Happy for etest (@lionel- version) to supersede it.

If I need to do anything provide explicit instructions and I'll do it. :smile:

**Comment by lionel-** [comment]
Thanks!

**Comment by tarsius** [comment]
So to answer your earlier question, @lionel-, I would remove the older package and add yours instead.

**Comment by tarsius** [comment]
Thanks!
