### ISSUE TITLE
ESS Dependency on julia-mode

### ISSUE THREAD

**Issue by ywwry66** [emacs-ess/ESS#1041]
Julia-mode is no longer a dependency of ESS on Melpa, which is not true. You may want to investigate on that.

**Comment by lionel-** [comment]
I don't think we've ever specified a julia-mode dependency. We don't want to force all ESS users to install this package in case they don't need it.

ESS is in this awkward phase where it contains multiple packages but hasn't been split up yet. Once split, we'll properly specify the dependencies in a granular way.

**Comment by ywwry66** [comment]
Thanks for answering. It still feels strange to me. I've had julia-mode installed as dependency, and I was prompted "1 package no longer needed" today which points to julia-mode. I don't have any other packages which could potentially require julia-mode other than ESS. 

Anyways, this is not a big issue. Thanks for working on this great project.

**Comment by jabranham** [comment]
> I don't think we've ever specified a julia-mode dependency

We did up until recentlyish. Commit 915cf3187a0eea1719ba2c877714ba74cb2ee995 removes it and contains the rationale.

**Comment by ywwry66** [comment]
Good to know. I should have searched the repository commits history before posting this though.
