### ISSUE TITLE
Binding c to vctrs::vec_c breaks ess-help

### ISSUE THREAD

**Issue by meedstrom** [emacs-ess/ESS#1044]
I like to execute the following snippet for the additional sanity checks. All my R code continues to work fine, and R packages run in namespaces so they work fine too. Expected result: no issues.

    c <- vctrs::vec_c

Actual result: It breaks `ess-display-help-on-object`, which hurts me since I use it all the time. Trying to get help on any function gives me a help buffer containing only the following message.

    + Error: Can't combine `..1` <character> and `..2` <list>.

Somewhere in the ESS codebase, `c()` is being used to combine vectors of different classes, or to do a similar job as `unlist()` or `unname()`. This is not a hygienic use of `c()`, it's better to preprocess inputs with `as.character()` and related functions so that `c()` doesn't have to guess, or to run `unlist()` or `unname()`, depending on the goal. As a simple test to check if you are using `c()` hygienically, you should be able to sub in `vctrs::vec_c()` in the same place without affecting the result.

**Comment by lionel-** [comment]
I don't think you're correct about what is or isn't a hygienic use of `c()`.

On the other hand, we should not evaluate in the global environment like this. But maybe the ESS routines need stuff from the ESSR library. In this case, ideally we'd evaluate in an encapsulated ESSR namespace but there is currently no such namespace. Instead we could evaluate in the ESSR environment attached to the search path which should work correctly in most cases.

**Comment by mmaechler** [comment]
Yes, I've wished several times in the past -- if only we eould protect ESSR calls from such global settings;  less extreme than masking c() is just calling   trace(.) or even worse,  debug(.) on  one of the base functions ESSR uses.
As an R Core developer, I do that rather more often than others, and currently, using ESS (and its tracebug makes it even worse), after I've called debug(.) on such a base function is almost infeasible.

**Comment by lionel-** [comment]
Eventually it might make sense to have a helper process for querying help, completion, srcref, etc. This will be a bit tricky (especially maintaining it up to date when the environment changes, e.g. after updating packages) but this will have many advantages:

- Simplifies how we call R as we don't need to worry about the global env or search path.
- We get completion, jump, etc even when the current process is busy.
- Debugging base functions in the current process is not an issue.
