### ISSUE TITLE
ess-julia-mode, julia-mode and org-mode configuration

### ISSUE THREAD

**Issue by fkgruber** [emacs-ess/ESS#1056]
Hi
What is the proper way to configure julia-mode with orgmode?

I added julia to org-babel-do-load-languages and installed ess and julia mode.

I then created a block code in an org-file with #+begin_src **julia**.  If I type C-c ' to edit the source code, julia-mode is activated but none of the ESS keybindings are  valid. 

On the other hand, if I use #+begin_src **ess-julia**  and type C-c ' then the keybindings work. However, in the org file I can't evaluate the block with C-c C-c anymore. I get the error:
`org-babel-execute-src-block: No org-babel-execute function for ess-julia!`

What am I missing?
thanks
FKG

**Comment by lionel-** [comment]
Hello,

This is not a user forum. Could you ask your question on Stack exchange or on the ESS mailing list please?
