### ISSUE TITLE
ess-command does not preserve .Last.value

### ISSUE THREAD

**Issue by ywwry66** [emacs-ess/ESS#1058]
Hi,

I am not sure if I should post it here or at the company-mode repo. But anyways, .Last.value is totally broken with company-mode turn on. To reproduce this, `M-x R`, then in the R inferior buffer, type `1 + 1` and hit `RET`. Then type in `Last`, wait for company-mode to complete it to `Last.value`, and hit `RET`. Instead of giving a 2, it gives either a long vector of all possible completions or just `character(0)`, depending on whether `company-mode` is already initiated or not. This behavior makes `Last.value` unusable.

Thanks

**Comment by jabranham** [comment]
Thanks for the bug report! This is because `ess-command` does not preserve .Last.value despite promising otherwise. I'll update the issue title to reflect that.
