### ISSUE TITLE
ESS over Tramp on docker container does not forward plots anymore

### ISSUE THREAD

**Issue by nettoyoussef** [emacs-ess/ESS#1059]
Hi, 

Sorry for the lack of details on this issue.
I am available to provide further details if necessary, but right now I am not sure on how to proceed.

I was using ESS over tramp and docker-tramp to acess an R session over a docker container.
My procedure was to simply start the container then open a file (e.g. /docker:root@container_name:path/to/directory/).
After that, I would call "ess-r-mode", and then be pretty much done.
I could generate plots and they would open a new window on my desktop.

However, today I update ESS to the last version on MELPA (commit a694b2), and to my surprise there was no forwarding of 
the plots made on the container anymore. I am not sure which was my previous version (I suppose my last update was around July). 

I tried to install older versions from github using Quelpa (recipe below), but somehow they failed to install correctly and 
I was not able to run ESS in any other version besides the one that is currently on Melpa.

Do you have any advice on what could I do? And what to be done to provide a better bug report?
Thanks!

```lisp
 (use-package ess
  :quelpa 
   (ess
    :fetcher github
    :repo "emacs-ess/ESS"
    :commit "09c1adecf8406d85426d14e5efe2aaba6c59f224"
   )
  :init
  :config
  ;;(ess-toggle-underscore nil)
  (setq ess-eval-visibly 'nowait)
 )
```

**Comment by lionel-** [comment]
I don't think there were any changes related to this. Could you binary search through the commit history until you find the commit where the behaviour changes please?

**Comment by nettoyoussef** [comment]
Hi Lionel, thanks for the fast response.
 
The problem was not ESS-related.
I was being able to show plots with window forwarding through ssh connections but was unable to do the same with 
Docker containers.

Turns out, I was not able to plot them using `docker exec` either, so the problem was with my docker image.

Since it is not so intuitive to setup with ESS, I will provide here a basic configuration that allows someone to plot windows with Emacs + ESS acessing a docker container with tramp + docker-tramp in a linux environment.
This answer was based on this [SO answer](https://stackoverflow.com/a/50356450/7233796).
For Mac OS there are other steps required - see the link for more information. 

This sets up the dockerfile using a rocker image:

```dockerfile
version: '3'

services:
  r_temp:
    image: rocker/verse:3.6.1
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
        - DISPLAY
    command: 
      tail -f /dev/null
```
Then, it is necessary to use `xhost` to setup a shared X11 session between the host and docker container (this should only be
done with trusted images and in a controlled environment, since it can create security leaks).
This can be done either in a script or terminal:

```bash
xhost +si:localuser:$USER
xhost +local:docker
export DISPLAY=$DISPLAY
```
Then, it is necessary to build the image:

```dockerfile
docker-compose up
```

After everything is setup, you can access the particular docker session with
`C-x C-f`
`/docker:user@containter_name:path/to/file`
`ess-r-mode`

It is possible to plot anything then and the plot will show in a new window, like in a local session.

**Comment by lionel-** [comment]
Thanks for the update!
