### ISSUE TITLE
R process shown in two windows instead of one

### ISSUE THREAD

**Issue by tmalsburg** [emacs-ess/ESS#1067]
When I open an `.R` file and execute

```
  M-x ess-eval-region-or-line-visibly-and-step
```

on a line of code when there’s no R process yet, the current window is split and a new R process is started.

Problem: The R process is shown in both windows, not just in the new window.

Environment:
- Emacs version: current master branch with native-comp.
- ESS installed from MELPA.
- Tested with `emacs -q`

**Comment by mmaechler** [comment]
Yes, thank you.  This behavior has started a while ago, but definitely this year ...

**Comment by tmalsburg** [comment]
I had a look.  I think the issue is in `ess-eval-region-or-line-visibly-and-step` where `ess-force-current-buffer` opens a new window and then the subsequent `display-buffer` also switches to the R process in yet another window.  There's an `inhibit-same-window`, but at this point we're in the process window and the `inhibit-same-window` probably doesn't do what it was likely intended to do.

My solution in #1068 solves my immediate problem, but I'm not sure it's the best solution.  It may be better to remove the `inhibit-same-window`. I was also wondering whether `ess-force-current-buffer` actually needs to create a new window.  It's documentation says that it makes sure there is a process.  New windows are not mentioned.  However, `ess-force-current-buffer` is used in many places and some may actually rely on the new window, so I don't feel confident changing anything there.

**Comment by tmalsburg** [comment]
Just checked, removing the `inhibit-same-window` works as well.  Let me know what you prefer and I'll update the PR as needed.

**Comment by tmalsburg** [comment]
The commit that likely introduced the issue is b2778ed23bc765c3370bb33dce8a9a458e3581f7.  From eye-balling it, i get the impression that it may have introduce this issue in a few other places as well.

**Comment by tmalsburg** [comment]
Hm, I think this commit may actually be the culprit: 24da603184ce39246611dd5b8602e769d7ebd5bf  Or some other commit made in this function around that time.  At least this is the code that is responsible for `ess-force-current-buffer` showing the process window. And the time of this commit is more in line with my memory of when this issue first appeared.

**Comment by tmalsburg** [comment]
Last comment for today: I couldn't nail down the root cause but I think the issue is that `ess-force-current-buffer` creates a new window when it shouldn't. There is code from two months ago which aimed at preventing this (21cb413184765ca86138b69f8a3e806a4421bdfe) but it appears not to be working or it misses some cases.  Perhaps @lionel-, author of the commit in question, can help here.

**Comment by lionel-** [comment]
My only comment until I have more time to take a look at this problem again is that we need unit tests :-)

**Comment by tmalsburg** [comment]
Makes sense. Having read a small fraction of the relevant code it quickly became clear that a quick fix may easily introduce more problems than it solves.

**Comment by jabranham** [comment]
I pushed 0ee75821d653ac362c72dbdb219b29244211118f which is indented to stop the worst of this behavior, try it out and let me know if you still experience issues. Thanks for the bug report.

**Comment by tmalsburg** [comment]
My immediate problem is fixed now.  Thanks Alex!
