### ISSUE TITLE
General timeout problems on Julia

### ISSUE THREAD

**Issue by cimentadaj** [emacs-ess/ESS#1084]
I see that the latest version on MELPA introduces a timeout of 1 second to `ess-command`(https://github.com/emacs-ess/ESS/issues/1043, https://ess.r-project.org/Manual/readme.html for version 19.1). I've been trying out Julia with ESS and I can't get help on any object because everything hangs. This sometimes even crashes the Julia REPL directly.

The closest reprex I can do is:

M-x julia
C-c C-d C-d

and then mini buffer says: 'Timeout during background ESS command 'ESS.all_help_topics()'. If I repeat `ess-diplay-help-on-object` many times, maybe 2/3 of the time it hangs but a few times it returns the list of objects to search. This sometimes hangs Julia and I have to reload the REPL.

This problem is not only limited to searching for help on objects. For example, I tried typing `Core.` to get auto-completion of the `Core` module and it doesn't autocomplete anything. When I `company-complete`, the minibuffer returns 'Company: backend company-capf error "Timeout during background ESS command 'ESS.components(Base)" with args (prefix)'.

I'm using MELPA 20201230.1102 on Emacs 26.3 with Ubuntu 20.

I'd be happy to offer more debugging if needed, just let me know.

**Comment by cimentadaj** [comment]
I can understand the context of the 1 second hang from reading the other issues. I'm just trying out Julia (I don't know much about how it works) but it seems that the 'starting up' of some things is generally slower the first time than the second. For example, writing `?rand` in the Julia prompt (no ESS) takes maybe a second or two longer than running it the second time. I notice that also on ESS separately. I believe this is *not* the case for R or other ESS supported languages.

Again, I don't know much but I'm trying to put some context on how this might eventually work in Julia.

**Comment by lionel-** [comment]
Thanks for reporting! Should be fixed.
