### ISSUE TITLE
Not providing the `when` when declaring functions and variables obsolete breaks since emacs-mirror/emacs@32c6732

### ISSUE THREAD

**Issue by d125q** [emacs-ess/ESS#1085]
emacs-mirror/emacs@32c6732 made the `when` argument of `make-obsolete`, `make-obsolete-variable`, `define-obsolete-variable-alias`, and `define-obsolete-function-alias` mandatory.

As far as I can see, https://github.com/emacs-ess/ESS/blob/34237ba8dae301af6d4f884288daa39d2cc25047/lisp/ess-r-package.el#L580 is the only line that needs fixing.

**Comment by jabranham** [comment]
Added, thanks and let me know if you spot any others!

**Comment by AtomicNess123** [comment]
I am getting "Set OBSOLETE-NAME's function definition to CURRENT-NAME and mark it obsolete."
I did not understand how to solve this issue. Thanks!
