### ISSUE TITLE
auto-complete occasionally freezes on function parameters

### ISSUE THREAD

**Issue by gonike** [emacs-ess/ESS#109]
I've been experiencing a number of complete freezes (C-g does not help) when using auto-complete on the R command line in ESS. I'm not exactly sure whether I've also had those while editing R files. These always happen when I'm calling a function and auto-complete is trying to provide me with possible parameter names to insert. See the attached screenshot of a frozen emacs.
![emacs-ess-autocomplete-freeze](https://cloud.githubusercontent.com/assets/1774207/3978957/bb5a531c-284e-11e4-8b9a-b0ddded83483.JPG)

I'm using the official precompiled version of emacs 24.3 for windows, ESS 13.09 and auto-complete 1.3.1. 

Please tell me if I can provide any other useful information. I'm not that deep into emacs and not into elisp at all, so detailed instructions would be helpful.

**Comment by jabranham** [comment]
Auto-complete and ESS have advanced quite a bit since this issue was opened 4 years ago. I'm closing this. If anyone experiences this please open a new issue.
