### ISSUE TITLE
Issues caused by linkification in help buffers

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#1098]
I did some research on the help issues we have been facing for a while. They are caused by a new feature that adds button links to keywords in `ess-help` buffers.

Here is the chronology:

- **PR**: Add links to help buffers https://github.com/emacs-ess/ESS/pull/748
- **PR**: Only insert help links that link somewhere https://github.com/emacs-ess/ESS/pull/772
- **Issue**: False-positive links in help buffers for functions documented in the current topic https://github.com/emacs-ess/ESS/issues/847
- **PR**: Don't link functions documented in the current topic https://github.com/emacs-ess/ESS/pull/848
- **Issue**: False-positive links for documented arguments like `data` https://github.com/emacs-ess/ESS/issues/855
- **PR**: Don't link arguments from functions documented in the current topic https://github.com/emacs-ess/ESS/pull/891

As implemented, linkification works by looking up "fancy quotes" in the help buffer, i.e. quotes that look like this:

```
‘rename()’
```

These fancy quotes are the result of `\code{}` markup in .Rd files. The first PR replaces all these quoted elements by Emacs buttons. Clicking on the button attempts to look up the help for the quoted text. Since there are many `\code{}` elements in the help page for which there is no help available, the linkification was excessive and distracting. The next three PRs filter the quoted elements to only retain those:

- For which a help topic is available. Uses `ess-help-get-topics` to retrieve the list of topics.
- And which don't correspond to a function documented in the current topic or one of their formal arguments.

Linkification is a nice new feature that makes it explicit that a word in the help page has contextual help available. Unfortunately it has several problems:

1. As Martin mentioned, ideally we'd use the parsed Rd files to determine the links, rather than figuring out by ourselves where to add them.

2. The use of `ess-help-get-topics` causes very long hangs on Windows. The more packages attached on the search path, the longer the hangs; @r2evans reported hangs over 5 seconds. I have improved the caching of these topics on the R side in #1080 but this doesn't fix the hangs completely.

3. The current approach to determining the functions and arguments documented is brittle. We regularly send incomplete inputs to R via `ess-command`, which causes infinite hangs (see #1025 and #1095). I have added a timeout to `ess-command` in #1078 to limit the issue and give a friendly error message but we need to fix the hangs in the first place. @r2evans kindly contributed a fix in #1083 but it turns out it doesn't completely solve the issue.

4. The filtering of functions and arguments documented in the current topic currently doesn't work correctly if the relevant functions are not reachable from the global environment. This would be the case with namespace-qualified requests like `?foo::bar`, or when multiple packages export the same function.

(3) can be fixed robustly and I have already started to work on a fix. However, now that I have a better overview of these problems, I wonder if we should just revert the linkification for this release and work on a better approach for the next one. I worry that problems (2) and (4) are going to cause a subpar experience for many users, so I tend to think we should revert. We could turn off that feature by default and keep it in ESS until (1) is solved. This way it would still be available for those that want to use the bleeding edge feature.

What do you think @mmaechler and @jabranham?

**Comment by mmaechler** [comment]
Thank you @lionel- for bringing this up.  

I agree we should revert.  I think ESS should be as "serious" as R (or science for that matter, including statistics, more generally).

You mention my own `1.`  exactly because we guess wrongly necessarily when we treat the arguments of `\code{*}` - albeit now, filtering,  instead of the arguments of  `\link{*}`  -- one problem you haven't mentioned above is the fact that some package authors, including R core, for the base packages,  likes to occasionally use a _bare_ `\link{}`, i.e., one *not* inside `\code{}`, and these are indeed missed completely by our algorithm, i.e.,  we commit (as usual in life) errors of both kinds: not only occasionally providing button-links to the wrong help page, but also missing to provide such links at all.

**Comment by jabranham** [comment]
Fine with me, I guess people can just use html help if they want links. I tried to do it but the tests failed. All tests using this newish "etest" package are failing locally for me so I'm not able to do much more.

**Comment by lionel-** [comment]
@jabranham Bummer. Can you send me the output of `make test` please?

**Comment by lionel-** [comment]
Let's hold on that reversion — I think we can make the current design work reasonably well by retrieving a list of links from the installed parsed Rd. We'll just linkify all words matching the link targets.
