### ISSUE TITLE
help breaks when dot in package name

### ISSUE THREAD

**Issue by r2evans** [emacs-ess/ESS#1101]
```r
library(data.table)
?data.table
```

In the `*help[R:1]data.table*` buffer,

```
# Error in find.package(if (is.null(package)) loadedNamespaces() else package,  : 
#   there is no package called 'data'
```

Currently I need to `print(help("data.table"))` to get at the help.

Versions,

```
GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29
ess-version: 18.10.3snapshot [elpa: 20210126.1119] (loaded from c:/Users/r2/.emacs.d/elpa/ess-20210126.1119/)
```

**Comment by lionel-** [comment]
Sorry that dev ESS is giving you so much trouble with the data.table doc and thanks again for all the testing and reporting!

**Comment by r2evans** [comment]
It's my choice to be on the bleeding-edge. I would prefer for my bug reports to offer more context and possible fixes, I apologize that this one was just a "complaint". Thanks for the commit! (It works for me.)
