### ISSUE TITLE
"fatal" timeouts when rendering `*.Rd`

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#1103]
As asked for on R-help, I've got an improved version of the `arima()` help page from Rolf Turner.
When trying to preview it in ESS,  with my favorite `C-c C-p`  (= `Rd-preview-help` from `rd-mode.el`),
I do not get a timeout occasionally but *everytime* consistently, i.e.,  the timeout has completely disabled the Rd previewing for me
```
ess-command: Timeout during background ESS command ‘.ess_Rd2txt("/u/maechler/R/D/r-devel/R/src/library/stats/man/arima.Rd")’
```

**Comment by lionel-** [comment]
It's strange that it is taking more than 2 seconds to generate the page on your computer though, it's instant when I do it locally on `arima.Rd`.

**Comment by mmaechler** [comment]
yeaah... embarrasing timeouts in our NFS mounted (really expensive super-duper) filesytsem (Windows would call "network drive")
