### ISSUE TITLE
Process restoration with quick C-g

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#1114]
From @vspinu in #1108.

> Actually not, on very quick C-g C-g the proc buffer is still not returned :(

**Comment by lionel-** [comment]
@vspinu Is this with 2 times C-g or 3 times? If 3 times, then Emacs forcibly quits, even inside the process filter. In that case we might not be able to do anything about this besides making a single C-g responsive so the user isn't tempted to 3x it.

**Comment by vspinu** [comment]
Yes, 3 times or more. I didn't know about this 3 times C-g rule :/

**Comment by lionel-** [comment]
What do you think about displaying a message in the process buffer to inform the user about the interruption?

- We'd do this when early exit is detected inside `ess-command`.
- The messaging routine would be run from a 0.2 seconds timer to avoid excessive messaging.

It'd look like this:

```
> 
Interrupting background command...
```

And when process is restored:

```
>
Interrupting background command... Done.
> 
```

If the user sees that a single C-g is producing an effect this may be sufficient to prevent them typing C-g three times.

**Comment by vspinu** [comment]
It won't be very helpful fro me. I habitually type several C-g in a row. It is required now for me in a number of places in emacs, like dynamic completion in the minibuffer for example. So the user is unlikely to pay much attention to those messages. Also, there might be a lot of interrupts in the background process. And those are irrelevant to the user, so better not spam them. 

I was thinking in a direction of a short recurring timer which would check orphan processes stuck in a wrong buffer. The strategy 
can be tricky but doable. We would need to also install buffer-kill-hook in temp buffer to avoid losing processes when output buffers are lost.

**Comment by vspinu** [comment]
As a brainstorming exercise, bringing MPI again here. MPI works by processing process strings without moving the process to a temporary buffer. Thus this issue is non existent there. 

Something similar can be done in ESS command - pile partial strings into a list and optionally output it to an output buffer (but without moving the process). When the terminator is reached do the string processing etc. If going this way then the best strategy might be to merge the two aproaches and devise new `ess-command2` to be based on MPI.

**Comment by lionel-** [comment]
I'd prefer to avoid cleanup like this from a timer. We could store a proc variable at the very start of the filter and check it again to detect early exits from the filter. In that case we clean up.

**Comment by lionel-** [comment]
MPI won't help with cleaning up the internal state of the process if the filter is exited early. We still need a strategy.

(I'm not enthusiastic about an MPI-based ess-command2 - I think the current ess-command works well)

If you have to 3x C-g all the time it sounds like something is wrong with your Emacs. 3x C-g is dangerous because preemptive. It's a last resort.

**Comment by vspinu** [comment]
> MPI won't help with cleaning up the internal state of the process

What stat of the process more concretely? MPI self cleaning is probably even simpler than the ess-command cleaning. 

> (I'm not enthusiastic about an MPI-based ess-command2 - I think the current ess-command works well)

 MPI is asynchronous, and I am pretty sure it's the easiest way forward for the proper `ess-async-command`. `ess-command` is not bad indeed. 

> If you have to 3x C-g all the time it sounds like something is wrong with your Emacs. 3x C-g is dangerous because preemptive. It's a last resort.

Maybe, but regardless, 3x C-g can happen inadvertently, and leaving the process in a wrong buffer is a party breaker.

**Comment by lionel-** [comment]
> I am pretty sure it's the easiest way forward for the proper ess-async-command. ess-command is not bad indeed.

I'm not so sure but that is another discussion.

Regarding cleanup we could unwind-protect an inhibit-protected filter cleanup with early exit detection like we now do in `ess-command`. I think that'll be simple and robust. You'd need a well timed 6x C-g to abort the cleanup.

**Comment by vspinu** [comment]
> You'd need a well timed 6x C-g to abort the cleanup 

Is this for sure? Or 3x would be enough to kick out of both?

Even with 6x it doesn't look reliable to me. A computer might be stuck for whatever reason and then 6C-g will propagate in no-time. 

Why not try zero-process-relocation what I suggested?

**Comment by lionel-** [comment]
Cleaning up after the fact from a timer seems really not ideal to me.

When I try to `C-g` my way out of this:

```elisp
(unwind-protect
    (unwind-protect
        (let ((inhibit-quit t))
          (while t (sit-for 1)))
      (message "foo")
      (let ((inhibit-quit t))
        (while t (sit-for 1))))
  (message "bar"))
```

It's really hard. And I somehow need way more than 6 C-g. So that tells me cleaning up from the filter should be reliable enough, especially since cleanup should be almost instantaneous (we only restore a few variables to original state) so it would be hard to interrupt it like that.

**Comment by vspinu** [comment]
>  a timer seems really not ideal to me.

Yep, I don't like it either. Just suggested it as an idea to diversify the search space a bit.

**Comment by vspinu** [comment]
> Why not try zero-process-relocation that I suggested?

I am pretty confident that we don't need to move the process to a different buffer altogether. The idea is to put the output buffer into a process plist and change [this line](https://github.com/emacs-ess/ESS/blob/983c54bd5c21bd9ae859290d32fb9a8a61509352/lisp/ess-inf.el#L1012) to use the output buffer instead of the process buffer.

**Comment by lionel-** [comment]
I see what you mean now, that's a good idea.
