### ISSUE TITLE
Electric pair mode broken in Emacs master

### ISSUE THREAD

**Issue by ashiklom** [emacs-ess/ESS#1115]
Up until recently, with `electric-pair-mode` enabled, the following would work (`|` is cursor position):

```r
if (x) {
  if (y) {|}
}

# --> hit Enter/RET
if (x) {
  if (y) {
    |
  }  # <-- correctly indented
}
```

However, I updated to the latest Emacs 28 master today, and now the result is this:

```r
if (x) {
  if (y) {
  |
} # <-- not indented!
}
```

However, in Python, the following still works fine:

```r
{
  "a": {|}
}

# Hit RET

{
  "a": {
    | 
  }
}
```

As best I can tell, the commit that broke this was this one: https://github.com/emacs-mirror/emacs/commit/b9d0cdcacbd3da93b4ebfa10d778efb618881ccc

Or at least, if I "revert" this commit by manually redefining `newline-and-indent` to its original definition, I return to the original (correct) behavior.

I'm reporting it here and not to Emacs itself because it seems like this works fine in Python, which suggests something is up with how ESS does indentation. The fix is easy, and the change is very recent and only in bleeding edge GitHub Emacs, so this isn't pressing...but I do think it's worth mentioning.

----

(For anyone else hitting this error, the quickfix is to add the following to your Emacs `init.el`. This is just the original `newline-and-indent` definition).

```lisp
(defun newline-and-indent (&optional arg)
  "Insert a newline, then indent according to major mode.
Indentation is done using the value of `indent-line-function'.
In programming language modes, this is the same as TAB.
In some text modes, where TAB inserts a tab, this command indents to the
column specified by the function `current-left-margin'.

With ARG, perform this action that many times."
  (interactive "*p")
  (delete-horizontal-space t)
  (unless arg
    (setq arg 1))
    (dotimes (_ arg)
      (newline nil t)
      (indent-according-to-mode)))
```

**Comment by vspinu** [comment]
> # --> hit Enter/RET

Do you have some other configuration that pushes the closing `}` on a new line? AFAICT this is no the default.

**Comment by ashiklom** [comment]
I have been using the following to test this:

1. Launch Emacs with no libraries loaded (technically, launching "Vanilla Emacs" from the Doom Emacs sandbox, but this should be effectively the same thing as `emacs -Q` + `(package-initialize)`).
2. `M-x load-library ess-r-mode`
3. `M-x electric-pair-mode`
4. `C-x C-f testfile.R`
5. Enter the code above.

My understanding is that the relevant variable is `electric-pair-open-newline-between-pairs`, which is [enabled by default in electric-pair-mode](https://github.com/emacs-mirror/emacs/blob/master/lisp/elec-pair.el#L118).

**Comment by jabranham** [comment]
I've traced this back to us using newline-and-indent rather than just newline in ess-roxy-newline-and-indent. I think we should just be using newline here anyway since electric-indent-mode has been on by default since Emacs 24.4. I tried that here (https://github.com/jabranham/ESS/commit/2416f5de134662c915b2ef0e605d9678e8040723) but some tests are failing. Since I can't run the tests locally and the literate tests don't print any indicate of why they failed, this is about as far as I can go.

**Comment by jabranham** [comment]
Ah, nevermind I had forgotten to pass the interactive argument to newline. Did that and the tests are running now, will hopefully push soon.

**Comment by lionel-** [comment]
> the literate tests don't print any indicate of why they failed, this is about as far as I can go.

You should get diffs from `(should (string= new expected))`. Can you open an issue with the uninformative output when this happens please?

**Comment by lionel-** [comment]
oh maybe the failures occurred in the old style tests? In that case you can run `make cases` in the test folder to update the case files and then inspect the diffs with `git diff`.

**Comment by jabranham** [comment]
> Can you open an issue with the uninformative output when this happens
please

I was referencing the output we get from travis.

**Comment by lionel-** [comment]
Do you have a link to the travis output?

**Comment by lionel-** [comment]
> Since I can't run the tests locally

oh this is still the case? Can you please post details in an issue.
