### ISSUE TITLE
Should `ess-mode-map` inherit from `prog-mode-map`?

### ISSUE THREAD

**Issue by agreselin** [emacs-ess/ESS#1117]
I use `(define-key prog-mode-map (kbd "RET") #'newline-and-indent)` in my init file. I expected buffers where `ess-julia-mode` is enabled to honor that binding (if nothing because `(derived-mode-p 'prog-mode)` returns `prog-mode`) but saw that the function bound to `RET` is found in `global-map` instead.

So I went to look and found that `ess-julia-mode-map` inherits from `ess-mode-map`, which doesn't have any parent map. Is that on purpose?

Would it be a bad idea to use `(set-keymap-parent ess-mode-map prog-mode-map)` as a workaround?

(Emacs 27.1, ESS 18.10.3)

**Comment by lionel-** [comment]
Good news, in the dev version `ess-mode` derives from `prog-mode` and so its keymap now inherits from the `prog-mode-map`.
