### ISSUE TITLE
julia in win10

### ISSUE THREAD

**Issue by Krisselack** [emacs-ess/ESS#1118]
I tried to get julia in emacs on win10 working (have working environment windows constraint). I have ess installed for R. 
Apparently, if I start a julia process (either through file or M-x julia RET) it hangs. C-g gets me a working emacs back (as I found in this forum), but no repl-prompt is displayed. At least I can send code to julia from script. 

Apart from ESS, I installed julia-mode.el and julia-repl.el. 
Versions: 
Emacs 26.1, 
ESS 18.10.2, 
julia-mode 20200917.713, 
julia-repl 20210124.923

When I run from a file: 
`println("hello world")`

I get the following in the julia-buffer (without lines or anything) : 

> println("hello world")
> hello world

Will that ever be fixed or should I rather use a different editor under windows?

**Comment by vspinu** [comment]
The likely issue is that the prompts are not displayed. This is why the hand. It's likely julia issue under windows. You should be able to see the same with `M-x shell` then start julia there. No prompts from the sub-process means everything else breaks unfortunately.

**Comment by lionel-** [comment]
It doesn't look like we can do anything from our side unfortunately.
