### ISSUE TITLE
I frequently see lisp in my R terminal

### ISSUE THREAD

**Issue by torbjorn** [emacs-ess/ESS#1121]
I am not quite sure how to best reproduce, but right now, more often than not when I type R code manually in the terminal, it spews out lisp there as well:

        > dim( dda2 )
        [1] 252   9
        > (list "" '(("x" . "")) '("x"))
        > (list "" '(("x" . "")) '("x"))
        > dim( dda )
        [1] 516   9
        > dim( dda )
        [1] 516   9
        > (list "" '(("x" . "")) '("x"))
        > (list "" '(("x" . "")) '("x"))
        > dim( dda )
        [1] 516   9
        > (list "" '(("x" . "")) '("x"))
        > (list "" '(("x" . "")) '("x"))
        > dim( dda )
        [1] 516   9
        > (list "" '(("x" . "")) '("x"))
        > (list "" '(("x" . "")) '("x"))
        > (list "" '(("x" . "")) '("x"))
        > dim( dda )
        [1] 516   9
        > (list "" '(("x" . "")) '("x"))
        > (list "" '(("x" . "")) '("x"))
        > (list "" '(("x" . "")) '("x"))
        > dim( dda )
        [1] 516   9
        > dim( dda )
        [1] 516   9
        > dim( dda )
        [1] 516   9
        > (list "" '(("x" . "")) '("x"))
        > (list "" '(("x" . "")) '("x"))
        > (list "" '(("x" . "")) '("x"))
        > dim( dda )
        [1] 516   9
        >

In this inferior R sesion I am just typing `dim( dda )` and hitting Enter. Sometimes (as you can see its not 100% consistent), the `(list "" '(("x" . "")) '("x"))` appears on a new line in the terminal. It doesn't prevent me from finishing the command, and the output of the command is correct. But it is getting messy.

It starts with the 6th character of the command, ie when I hit a `d`. The following `d` also triggers it. the final `a` of the variable name sometimes triggers it. (You see there are sometimes three and sometimes two such lisp lines). The final `)` and enter does not trigger it.

**Comment by lionel-** [comment]
This is fixed in the dev version. You can fix by one of these actions:

- Installing the dev version of ESS through melpa
- Downgrade Emacs to a version before 27
- Adding `(setq ess-can-eval-in-background nil)` to your config file

The last option disables all contextual help (eldoc, completions, ...).
