### ISSUE TITLE
Trailing slash stripped from default-directory in R-mode

### ISSUE THREAD

**Issue by BrendanHalpin** [emacs-ess/ESS#1125]
The value of default-directory is stripped of its trailing slash by ess-eval-region in ess-R-mode.

This creates a problem for completion for find-file and other commands. 

See below for an example: "# default-directory" comments are evaluated by C-u C-x C-e. The code is run by C-c C-r from the source file. 

I can't reproduce this problem in ess-julia-mode. The version of ESS is cloned from the git repository 20 minutes ago. 

```R
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> setwd('/tmp/test/')
> # default-directory "/tmp/test/"
> print(Sys.time())
+ print("Hello World!")
+ 
[1] "2021-03-08 17:05:15 GMT"
> [1] "Hello World!"
> # default-directory "/tmp/test"
```

**Comment by BrendanHalpin** [comment]
I think this is happening in ess-synchronize-dirs and it can be fixed by changing line 2939 

```emacs-lisp
      (let ((lpath (car (ess-get-words-from-vector ess-getwd-command))))
```
to 
```emacs-lisp
      (let ((lpat (file-name-as-directory
	      (car (ess-get-words-from-vector ess-getwd-command)))))
```

**Comment by BrendanHalpin** [comment]
Typo in previous. Should be:
```emacs-lisp
let ((lpath (file-name-as-directory
	      (car (ess-get-words-from-vector ess-getwd-command)))))
```

**Comment by BrendanHalpin** [comment]
A cleaner solution (and one used in ess-dirs) is to but file-name-as-directory into the default-directory assignment itself:

```emacs-lisp
(defun ess-synchronize-dirs ()
  "Set Emacs' current directory to be the same as the subprocess directory.
To be used in `ess-idle-timer-functions'."
  (when (and ess-can-eval-in-background
             ess-getwd-command
             (inferior-ess-available-p))
    (ess-when-new-input last-sync-dirs
      (ess-if-verbose-write "\n(ess-synchronize-dirs)\n")
      (let ((lpath  (car (ess-get-words-from-vector ess-getwd-command))))
        (setq default-directory
              (file-name-as-directory (ess--derive-connection-path default-directory lpath))))
      default-directory)))
```

**Comment by vspinu** [comment]
@BrendanHalpin did you fix this in #1128?

**Comment by BrendanHalpin** [comment]
I think I have: the change certainly fixed one source of the slash being removed. Do I need to close/delete the pull request?

**Comment by BrendanHalpin** [comment]
OK, it isn't properly fixed. I thought it had to do with `ess-synchronize-dirs` in `ess-idle-timer-functions`, but `ess-idle-timer-functions` is nil in the inferior process buffer. I can strip the final slash by C-c C-r from an R buffer.

**Comment by BrendanHalpin** [comment]
I've tracked it down: ess-inf.elc has not been updated and is read instead of ess-inf.el. Byte-compiling the latter seems to resolve the problem.
