### ISSUE TITLE
interactive SAS (linux)

### ISSUE THREAD

**Issue by Pierre-Andre** [emacs-ess/ESS#1126]
## What did you expect to happen?
See the interactive SAS session working

## What actually happened?
When start the interactive SAS session using
M-x SAS
It fails with the following message
inferior-ess--set-major-mode: Wrong type argument: listp, SAS-customize-alist

### system info
- ess-version: 18.10.3
- Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0) of 2020-11-08, modified by Debian
- Doom v2.0.9 
### backtrace
```
alist-get(inferior-ess-mode-syntax-table` SAS-customize-alist)
  inferior-ess--set-major-mode("SAS")
  inferior-ess(nil ((ess-local-customize-alist quote SAS-customize-alist) (ess-language . "SAS") (ess-dialect . "SAS") (inferior-ess-program . inferior-SAS-program) (ess-help-sec-regex . "^[A-Z. ---]+:$") (ess-help-sec-keys-alist . " ") (ess-object-name-db-file . "ess-sas-namedb.el") (inferior-ess-objects-command . "objects(%d)") (inferior-ess-help-command . "help(\"%s\",pager=\"cat\",window=F)\n") (inferior-ess-exit-command . "endsas;\n") (ess-loop-timeout . 500000) (inferior-ess-primary-prompt . "^") (inferior-ess-secondary-prompt . "^") (comint-use-prompt-regexp . t) (inferior-ess-start-args . inferior-SAS-args-temp)))
  SAS()
  #<subr funcall-interactively>(SAS)
  apply(#<subr funcall-interactively> SAS)
  funcall-interactively(SAS)
  #<subr call-interactively>(SAS record nil)
  apply(#<subr call-interactively> (SAS record nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> SAS record nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (SAS record nil))
  call-interactively(SAS record nil)
  command-execute(SAS record)
  counsel-M-x-action("SAS")
```
### more additional details
by the way, the following function `ess-sas-interactive` fails when called interactively
M-x ess-sas-interactive
This function call the function `ess-add-ess-process` which is undefined (well may be the end-user (ie me) is not supposed to use `ess-sas-interactive` (even as a workaround))

**Comment by lionel-** [comment]
Hopefully this will help. Just be aware that SAS-mode is mostly unmaintained AFAIK.
