### ISSUE TITLE
Disabling output delimiter because CMD failed to parse

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#1127]
Not really nice... Again my slow file system (NFS) with 20'000 or more CRAN+Bioconductor packages installed (some of them "duplicated" in different libraries in `.libPaths()`).
ESS or polyR or ??? or something is trying to do things in the background, and locks up my emacs basically,
I press C-g "like crazy" to eventually be able to send a line or a region of code from the R buffer to the `*R*` process.

I see no problem on my laptop where I also have ~15'000 packages installed but on a fast local disk.
... for now I basically cannot use ESS anymore on my desktop and have to use my less comfortable less powerful notebook,
because ESS (or ??) again behaves like crazy doing things in the background (finding all objects in all packages or ????)..

Yes, this is also after I have reverted to work with  `ess-tracebug` enabled  (as by default),..

My `*ESS*` buffer has about 10x the following
```
Disabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parse
```
and the `*Messages*`  buffer has repeatedly
```
Error running timer ‘ess--idle-timer-function’: (error "Timeout during background ESS command ‘getwd()’")
```

**Comment by lionel-** [comment]
This looks like `ess-synchronize-dirs` which is run from an idle timer. It calls `getwd`.

I think this is because ESSR is not properly loaded and doesn't have the new `.ess.command()` installed. Is this with a remote? And are you running the latest dev ESS?

**Comment by mmaechler** [comment]
No, it's not a remote, and yes, I run (almost always, and in this case I have checked)  the latest ESS.

**Comment by lionel-** [comment]
Can you please make sure ESSR is correctly installed and you have `.ess.command()` available.

**Comment by mmaechler** [comment]
Answering in reverse order:
```
> .ess_command()
Error in .ess_command() : could not find function ".ess_command"
>
```

In which sense is ESSR correctly installed?   I see it in  `search()`

If I open a *.R buffer and try sending code to an R session (which is opened automatically as it should) and then things lock up.. until I press 3 x C-g  to be able to send one line of code from `foo.R` to `*R*` before it locks up again...    I can well imagine this all happens while ESSR  is being installed, but wants to do something that would take many minutes when the 20'000+ packages are on sometimes slowish NFS file sytem.

**Comment by lionel-** [comment]
if `.ess.command()` is not found, it means that there is an installation problem. There is a version mismatch between the lisp code and ESSR.

**Comment by mmaechler** [comment]
Well,  my fault:  I looked for `.ess_command()` even when you correctly asked for `.ess.command()` ... the latter indeed exists and is a function in ESSR.

**Comment by mmaechler** [comment]
and 
```
> .ess.command()
Error in paste0(sentinel, "-START") : 
  argument "sentinel" is missing, with no default
Error in paste0(sentinel, "-END") : 
  argument "sentinel" is missing, with no default
> 
```

**Comment by lionel-** [comment]
>  I can well imagine this all happens while ESSR is being installed, but wants to do something that would take many minutes when the 20'000+ packages are on sometimes slowish NFS file sytem.

This is a good point, and I see we still have a timeout of 5 seconds instead of the global 30 seconds we set a while ago. I'll change that.

But now that you've confirmed `.ess.command()` is there, I don't have any clue about what's going on.

**Comment by mmaechler** [comment]
>    Use default timeout in ESSR loading ...

Thank you, @lionel- ,
this helped a lot in any case,  since about 2 weeks or so, my R start up time within ESS (at work only with slowish/bad NFS) had suddenly become considerably slower, needing a couple of seconds instead of ca. 1 second... as it is now again - only after your change above.
I'll have to do teaching preparation and several other things today ... but all looks good now (from only a little usage though); I assume to get to close this in 2-3 days once I'm more sure it's solved.

**Comment by mmaechler** [comment]
Hmm... Today I still get this situation... not a startup problem directly.  But checking a change in R-devel, switching from sending to `*R*` (running a recent R 4.0.4 patched) to
`*R-devel*` (running R-devel with my own not-yet-committed changes).
Switching the process (from the `<test-code>.R` buffer to use `*R-devel*` .. kind of works.), then sending a line with `C-c C-n` works once, but the 2nd time it locks up,  my cursor disappears, the mini buffer says "loading lin ..."
and everything is locked up (for more than 3 seconds; about the my patience definitely ends).

- `*ESS*`  again is full of
Disabling output delimiter because CMD failed to parseDisabling output delimiter because CMD failed to parse.... (about 3000 characters long)

- `*Messages*` has (among other).

```
Loading line:         ## stopifnot(is.numeric(digits), digits >= 1)
Error running timer ‘ess--idle-timer-function’: (error "Timeout during background ESS command ‘getwd()’")
Starting evaluation...
```
and marking the above lines is even horribly slow as ESS basically locks up emacs .. doing its crazy trying and not achieving something...

**Comment by mmaechler** [comment]
Now, in  `*R-devel*` again ((could that be one cause... could it be ESSR is not correctly working in latest R-devel ???))
Emacs so badly locked up,  3 x C-g  does not help,  even the emacs watch `M-x display-time` stops running.  My desktop's load reaches 5 to 6 .. so even switching from Emacs to the browser is slow .....

**Comment by mmaechler** [comment]
... and the watch jumps to the correct time (so emacs is not entirely dead), but the Minibuffer only shows (for 4 minutes now)
```
error in process filter: Quit
```
which I think it shows since it could not even honour my request with  3 x C-g ..... AARRHGHGHGHGGHGHGH

**Comment by mmaechler** [comment]
another 5 minutes later, the watch frozen showing the time of 5 min. ago.  Load on my desktop (`uptime`) is 5.6...
I    `kill -9  <process ID of my emacs>`

what a horrible ESS experience .. sorry.

**Comment by mmaechler** [comment]
... definitely unrelated to `*R-devel*` ...  very simple things with one foo.R script, one `*R*` process running only, and I get the above
```
  error in process filter: Quit
```
in the mini buffer  and non-interruptible  emacs freeze situations  .. (which mostly end after 10 -- 20 seconds or so, but that almost like infinity for all practical purposes).

**Comment by mmaechler** [comment]
Well, I see that  this time,  `"ESSR"` is *not* in the `search()` path at all.
Shouldn't ESS be able to at least  WARN me very prominently and tell the user to do  `M-x .....`  when this happens?

**Comment by mmaechler** [comment]
.... From the  Feb.25  "cannot work anymore"  situation,  I had changed my Emacs startup .. to *not* use 'ESS devel'  for some parts.... and forgot about it... so I had a *mix* of ESS versions loaded as I found now.

... yes, embarrassed ...
