### ISSUE TITLE
ESS/Julia Crashes Aquamacs

### ISSUE THREAD

**Issue by cortner** [emacs-ess/ESS#113]
I am running OS X 10.9.4, Julia v0.3.

I installed the latest Aquamacs, deleted the ESS that comes with it and installed the Git development branch. My `Preferences.el` contains

```
   (add-to-list 'load-path "~/Dropbox/Admin/Aquamacs/ESS/lisp/")
   (load "ess-site")
```

Julia is already in the path; the version of ESS installed is 14.08.

When I start julia with `M-x julia RET`, a  Julia console opens in the _Terminal_ (not in Emacs - is that correct?), and Aquamacs becomes unresponsive to any input. I have to kill it.

The same happens with Vincent Goulet's version of Emacs from
 http://vgoulet.act.ulaval.ca/en/emacs/mac/.

Thank you for any pointers.

**Comment by cortner** [comment]
In my, case the problem was that I used `/Applications/Julia-0.X.X.app/Contents/MacOS/Julia` instead of `/Applications/Julia-0.X.X.app/Contents/Resources/julia/bin/julia`.  The first is an "app" that launches Julia in a separate terminal. The latter is the one that can be called from command-line. I now got ESS-Julia to work in both Aquatics and standard Emacs.

**Comment by justmytwospence** [comment]
When I follow the wiki instructions, my minibuffer displays

```
Type C-h for hep on ESS version 15.09-devel
```

and then the whole Emacs application freezes up, and I have to force quit.
I'm using the `brew cask install julia` version of julia.
