### ISSUE TITLE
Add support for new base R pipe

### ISSUE THREAD

**Issue by cddesja** [emacs-ess/ESS#1136]
Can support for base R's new pipe |> be added? Basically, can it be treated similar to how magrittr::%>% is?

**Comment by jabranham** [comment]
It was in 47eaeaadee343fa1f396a74cfd86ff1d8ac73e73

**Comment by cddesja** [comment]
@jabranham Thanks! Sorry I missed that.

**Comment by cddesja** [comment]
How can I make this pipe be the same color as the %>% pipe? For example, %>% is blue with solarized light but |> is black. Shouldn't it be treated the same way or is this a problem with the theme?

**Comment by jabranham** [comment]
The R pipe will have ess-operator-face, the magrittr pipe will have
ess-%op%-face. I have them set to the same thing (and ess-%op%-face
inherits from ess-operator-face so most others will too). You can check
what face is under point with C-u x =.

**Comment by cddesja** [comment]
Alex, thanks for the quick reply. I think I understand what you're saying,
but I don't understand how to check the face with C-u x =.

When I type C-u x, x gets printed 4 times (i.e., xxxx).

I am sure I am missing something.

**Comment by jabranham** [comment]
Sorry, C-u C-x =

**Comment by cddesja** [comment]
I do see %>% as ess-%op%-face.  However, |> doesn't show up as a single
entity, but a | and > separately, if that makes sense.
Chris
