### ISSUE TITLE
loop: ess-r-mode

### ISSUE THREAD

**Issue by mmahmoudian** [emacs-ess/ESS#1139]
This might easily not be a bug and instead a stupid mistake from my side (noob Emacs user). As far as I can understand, this is different from #912 as I am on Linux and have Melpa as the only repo apart from the default Elpa.

While trying to install ess (Version: 20210403.520) I got the following error over and over again:

> ess-bugs-d.el:28:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

I took a screenshot to show exactly what I see and the full transcript of the errors can be found below the image:
![image](https://user-images.githubusercontent.com/390889/114014593-736a3a00-9871-11eb-862b-f8e2fa7de895.png)

The full error list:
<details>
<pre>
<code>
Leaving directory ‘/home/mehrad/.emacs.d/packages/ess-20210403.520’

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-bugs-d.el at Thu Apr  8 13:17:09 2021
Entering directory ‘/home/mehrad/.emacs.d/packages/ess-20210403.520/’
ess-bugs-d.el:28:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-bugs-l.el at Thu Apr  8 13:17:09 2021
ess-bugs-l.el:29:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-custom.el at Thu Apr  8 13:17:09 2021

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-gretl.el at Thu Apr  8 13:17:09 2021
ess-gretl.el:32:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-help.el at Thu Apr  8 13:17:09 2021
ess-help.el:37:13:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-inf.el at Thu Apr  8 13:17:09 2021
ess-inf.el:35:13:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-jags-d.el at Thu Apr  8 13:17:10 2021
ess-jags-d.el:29:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-julia.el at Thu Apr  8 13:17:10 2021
ess-julia.el:38:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-mode.el at Thu Apr  8 13:17:10 2021
ess-mode.el:30:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-r-completion.el at Thu Apr  8 13:17:10 2021
ess-r-completion.el:31:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-r-flymake.el at Thu Apr  8 13:17:10 2021
ess-r-flymake.el:35:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-r-mode.el at Thu Apr  8 13:17:10 2021
ess-r-mode.el:37:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-r-package.el at Thu Apr  8 13:17:10 2021
ess-r-package.el:31:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-r-syntax.el at Thu Apr  8 13:17:10 2021
ess-r-syntax.el:32:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-r-xref.el at Thu Apr  8 13:17:10 2021
ess-r-xref.el:33:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-rd.el at Thu Apr  8 13:17:10 2021
ess-rd.el:33:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-rdired.el at Thu Apr  8 13:17:11 2021
ess-rdired.el:74:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-roxy.el at Thu Apr  8 13:17:11 2021
ess-roxy.el:59:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-s-lang.el at Thu Apr  8 13:17:11 2021
ess-s-lang.el:32:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-sas-a.el at Thu Apr  8 13:17:11 2021
ess-sas-a.el:29:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-sas-d.el at Thu Apr  8 13:17:11 2021
ess-sas-d.el:34:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-sas-l.el at Thu Apr  8 13:17:11 2021
ess-sas-l.el:49:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-site.el at Thu Apr  8 13:17:11 2021
ess-site.el:56:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-sp6-d.el at Thu Apr  8 13:17:11 2021
ess-sp6-d.el:38:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-toolbar.el at Thu Apr  8 13:17:11 2021
ess-toolbar.el:53:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-tracebug.el at Thu Apr  8 13:17:11 2021
ess-tracebug.el:46:13:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-trns.el at Thu Apr  8 13:17:11 2021
ess-trns.el:33:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess-utils.el at Thu Apr  8 13:17:12 2021
ess-utils.el:35:13:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/ess.el at Thu Apr  8 13:17:12 2021
ess.el:52:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/essd-els.el at Thu Apr  8 13:17:12 2021
essd-els.el:31:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode
Leaving directory ‘/home/mehrad/.emacs.d/packages/ess-20210403.520/’

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/obsolete/ess-eldoc.el at Thu Apr  8 13:17:12 2021
Entering directory ‘/home/mehrad/.emacs.d/packages/ess-20210403.520/obsolete/’

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/obsolete/ess-mouse.el at Thu Apr  8 13:17:12 2021
ess-mouse.el:40:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/obsolete/ess-r-a.el at Thu Apr  8 13:17:12 2021
ess-r-a.el:34:1:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/obsolete/mouseme.el at Thu Apr  8 13:17:12 2021

Compiling file /home/mehrad/.emacs.d/packages/ess-20210403.520/obsolete/msdos.el at Thu Apr  8 13:17:12 2021

</code>
</pre>
</details>

**Comment by jabranham** [comment]
Best guess is that this is some sort of weird installation issue. Try deleting ~/.emacs.d/elpa/ess-* and reinstall.
