### ISSUE TITLE
Symbol’s function definition is void: ess-local-process-name

### ISSUE THREAD

**Issue by my-little-repository** [emacs-ess/ESS#1140]
I am using ess with julia 1.7.0. Ess-version: 18.10.3snapshot [elpa: 20210403.520].

Whenever eldoc triggers, I get the following message in the minibuffer.

    eldoc error: (void-function ess-local-process-name)

So, ess is working correctly but not eldoc. There is no function named ess-local-process-name but there is a variable with that name.

    ess-local-process-name is a variable defined in ‘ess-custom.el’.
    Its value is "julia"
    Local in buffer *julia*; global value is nil

Here is the debug message when I type at the prompt *map(*

    Debugger entered--Lisp error: (void-function ess-local-process-name)
      ess-local-process-name("\\w*> ")
      ess-command("ESS.fun_args(\"map\")\n" nil nil nil nil #<process julia>)
      ess-function-arguments("map")
      ess-julia-eldoc-function()
      apply(ess-julia-eldoc-function nil)
      #f(advice-wrapper :before-until #f(compiled-function (&rest args) #<bytecode 0x12ed189>) ess-julia-eldoc-function)()
      eldoc-print-current-symbol-info()
      #f(compiled-function () #<bytecode 0x202b97>)()
      apply(#f(compiled-function () #<bytecode 0x202b97>) nil)
      timer-event-handler([t 0 0 500000 nil #f(compiled-function () #<bytecode 0x202b97>) nil idle 0])
    
Investigating further, I can see that I get the following error when I start ess.

    ess-command: Symbol’s function definition is void: ess-local-process-name

**Comment by jabranham** [comment]
Hmmm... seems to be working fine for me, though I have julia 1.5.4 (and 1.6 is their latest release - is 1.7 building from the development repo?)

**Comment by my-little-repository** [comment]
Yes, 1.7 is from master. The development branch.

**Comment by my-little-repository** [comment]
Let me sum up what happened. After a system upgrade and the installation of a new version of julia, I got the following error in the ess julia repl. 

    eldoc error: (void-function ess-local-process-name)

Starting an R repl made the error go away. So I guess some initialization process was triggered the first time an R repl was started, and that solved the issue.
