### ISSUE TITLE
Cursor position when using skeleton-pair

### ISSUE THREAD

**Issue by acid-bbq** [emacs-ess/ESS#1141]
I use GNU Emacs 27.1 and ESS 18.10.3snapshot [elpa: 20210331.804].

I have this in my init file:

```
;; enable skeleton-pair insert globally
   (setq skeleton-pair t)
  ;;(setq skeleton-pair-on-word t)
   (global-set-key (kbd "(") 'skeleton-pair-insert-maybe)
   (global-set-key (kbd "[") 'skeleton-pair-insert-maybe)
   (global-set-key (kbd "{") 'skeleton-pair-insert-maybe)
   (global-set-key (kbd "\"") 'skeleton-pair-insert-maybe)
   (global-set-key (kbd "\'") 'skeleton-pair-insert-maybe)
   (global-set-key (kbd "\`") 'skeleton-pair-insert-maybe)
   ;;(global-set-key (kbd "$") 'skeleton-pair-insert-maybe)
   ;;(global-set-key (kbd "<") 'skeleton-pair-insert-maybe)
```

When I am in the R console and the cursor is at the last line of the page, if I type any of the character activated for auto-closing that is, `(, [, {, ', "`), the cursor goes directly on the top of the page and thus there is a blank page below. It does not add a new line at the bottom. It did not happen before I updated ESS.

**Comment by jabranham** [comment]
I can't manage to reproduce this. Have you tried removing that part of your
config, though? electric-pair-mode probably takes care of this need.

**Comment by acid-bbq** [comment]
Yes, when I remove this part from my config, I don't have the issue. But it no longer closes the brackets. 
electric-pair-mode does the job, thanks, but it closes other characters like `<` and adds `>` in e.g. org-mode which I don't want. And I'm not sure we can remove this in electric-pair-mode.

**Comment by lionel-** [comment]
You can disable eletric-pair-mode in org-mode. Or modify the syntax table of org-mode to set `<` and `>` as punctuation characters.

**Comment by acid-bbq** [comment]
Thank you. I've added this to my config as your second proposition:
```
(defun org-change-syntax-less-greater ()
  (modify-syntax-entry ?< ".")
  (modify-syntax-entry ?> "."))
(add-hook 'org-mode-hook #'org-change-syntax-less-greater)
```

It works now for `<`, but now the parenthesis `(` does not close. Other characters `[`, `"`, `{` close normally.

**Comment by lionel-** [comment]
oh now I see I have this in my org-mode config which seems relevant:

```elisp
    (setq-local electric-pair-pairs
                (let ((pairs electric-pair-pairs))
                  (push '(?$ . ?$) pairs)
                  (push '(?= . ?=) pairs)
                  (push '(?/ . ?/) pairs)
                  (push '(?* . ?*) pairs)
                  (push '(?` . ?`) pairs)
                  pairs))
```
