### ISSUE TITLE
Output in command prompt Windows 

### ISSUE THREAD

**Issue by mtvincen** [emacs-ess/ESS#1148]
I am running ess ess-version: 18.10.2 [<unknown>]  loaded from ~/.emacsmd/elpa/ in emacs 27.2 on a windows 10 machine. I am using R version 4.0.5 through Ess. For the most part the set up has worked but I am occasionally getting strange output that shows up in the command line that I am not sure where it is coming from or why it is being printed out. Below is the output that has been coming up recently. Any help with identifying the issue and resolving it would be appreciated
`> 
(list "graphics" '(("x" . "") ("y" . "NULL") ("type" . "l") ("..." . "")) '("x" "..." "y" "type" "formula" "data" "subset" "col" "lwd" "do.points" "cex" "pch"))`

**Comment by lionel-** [comment]
ESS 18.10 is not compatible with Emacs 27. Your options are:

- Use the dev version of ESS.
- Downgrade Emacs.
- Add this to your config: `(setq ess-can-eval-in-background nil)`.

The last one will disable all contextual help though (eldoc, completions, ...).
