### ISSUE TITLE
ESS, Auto-Complete and julia

### ISSUE THREAD

**Issue by Ph0non** [emacs-ess/ESS#115]
I'm very new to emacs but try to use it for programming in julia. The showde auto-completion feature in https://github.com/emacs-ess/ESS/wiki/Julia#completion seems very nice and I try to use it too. AC works and a list with popup window appears but with a warning:

```
Symbol not found. Falling back on apropos search...
```

I installed ESS, cask, auto-complete and popup-el (in `~/emacs/`). The AC .el and .elc files are copied to `~/.emacs.d` like `popup.el`. My `.emacs` file:

```
;; ESS
(add-to-list 'load-path "~(emacs/ESS/lisp")
(setq inferior-julia-programm-name "~/julia/julia")
(require 'ess-site)
(setq ess-use-auto-complete t)
(setq ess-tab-complete-in-script t)

;; Auto-Complete
(add-to-list 'load-path "~/.emacs.d")
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "~/.emacs.d/dict")
(ac-config-default)

;; other
(custom-set-variables
'(cua-mode t nl (cua-base))
'(default-input-method "TeX")
'(show-paren-mode t)
'(text-mode-hook (quote (turn-on-auto-fill text-mode-hook-identify))))
(setq-default cursor-type 'bar)
(set-face-attribute 'default nil :height 90)
(global-visual-line mode 1)
(global-linum mode 1)
```

Miss I something, any suggestions? Do you need more information?

**Comment by bastibe** [comment]
Hi, I'm experiencing the same issue. I'm running Julia 0.3.4 on OS X.

**Comment by cortner** [comment]
same here; Julia 0.3.5 on OS X, GNU Emacs 24.4.1, ESS installed from MELPA on 25 Jan 2015.

(otherwise, this is brilliant - thank you for including Julia!)

**Comment by berceanu** [comment]
Same issue with julia 0.3.5 on Arch Linux.

**Comment by mmaechler** [comment]
Me too (Linux Ubuntu 14.04; github version of ess
             but *only* with emacs    = emacs version 23.04.1 
whereas with  emacs24  (M-x emacs-version = 24.3.1)
command completion *DOES* work.

So it seems that we do require emacs 24.x or even 24.3.  for that part of julia support.

 BTW: The following shows in the   *julia* buffer  also for emacs 24.3.1,
where I don't like the  
    "Terminal not fully functional part"
(yes and that appears also with  Emacs 24.3.1).

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _' |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+2732 (2015-01-16 00:54 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 2e2e4f6 (9 days old master)
|__/                   |  x86_64-linux-gnu

WARNING: Terminal not fully functional
Sc ETH, Primarlehrer, Institutsgründer

**Comment by cortner** [comment]
Just to clarify, auto-complete works fine either in a popoup window or a text buffer. But when one marks a symbol, then the help-text is not displayed (see first post). Interestingly, C-c C-d C-d does display the correct help text (in a text buffer).

**Comment by cortner** [comment]
sorry to keep adding to this: I've now observed, that it depends whether the object is exported from a module or not. For example, if I type 
`Base.sqrt`
then ESS opens up the selection dialogue and displays the correct help-text. But if I type just
`sqrt`
then I get the error message alluded to in the first post.

Maybe this helps figuring out a quick fix?

**Comment by lilinjn** [comment]
I never put in the time to fully track down this issue -- but this is a recap of what I found:
* When ess-julia starts julia it runs this bit of helper code:  https://github.com/emacs-ess/ESS/blob/master/etc/ess-julia.jl
* There are two types of help/doc functionality that ESS-julia provides
  * eldoc based functionality which puts info in the minibuffer -- that seems to work ok
  * AC based functionality which pops up the menu buffer with more hep text -- this does not seem to work
* Presumably for both modes of help there is some emacs-lisp glue code that calls the julia helper code
* I'm guessing the AC glue code is sending blank strings or chopping off a character or something -- but my emacs-fu is not strong enough to trace the calls to the julia helper code.

**Comment by adamczykm** [comment]
Guys, notice that it will work with: Base.show(). Seems like a simple fix would suffice.

**Comment by robsyme** [comment]
@adamczykm: I think that it works with `Base.show()` due to the module exporting the object as mentioned above by @cortner (but I'm not sure how that gets us closer to a fix).
