### ISSUE TITLE
LSP-R fails to start in ESS(R) mode

### ISSUE THREAD

**Issue by ECon87** [emacs-ess/ESS#1153]
Hi,

I am on spacemacs, so I am not sure whether this is an ESS issue or a spacemacs issue. In any case, I am trying to use the lsp server for R files but it fails to start (even after restarts. The lsp--r::stderr file reads:

```
[2021-07-05 09:22:04.206] error handling json:  Error: lexical error: invalid char in json text.
          = dplyr::lag(polls_diff_D_R{"jsonrpc":"2.0","method":"textDo
                     (right here) ------^

Stack trace:
1: parse_string(txt, bigint_as_char)
2: parseJSON(txt, bigint_as_char)
3: parse_and_simplify(txt = txt, simplifyVector = simplifyVector, 
    simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, 
    flatten = flatten, ...)
4: jsonlite::fromJSON(data, simplifyVector = FALSE)
[2021-07-05 09:22:04.248] Error: Unexpected non-empty line
Call: self$read_header()
Stack trace:
1: stop("Unexpected non-empty line")
2: self$read_header()
3: self$fetch(blocking = FALSE)
[2021-07-05 09:22:04.248] exiting

Process lsp-r stderr finished
```

Any help would greatly be appreciated.

**Comment by lionel-** [comment]
This doesn't seem like an ESS issue. I'm not sure which venue would be most appropriate for this question but you might try the ess-help mailing list and ask if anyone has experience with LSP?

**Comment by alexey0308** [comment]
Hi @ECon87 , just in case if you are not aware: one may switch back to the ess-based completion in spacemacs,
if you specify in the layers
```
(ess :variables
  ess-r-backend 'ess)
```
while you looking for solution of the original problem with lsp.

**Comment by ECon87** [comment]
Hi @alexey0308,

Thanks for the suggestions. I just tried that, but it says "No associated ESS process". Maybe there is something wrong with my config. I am also on the develop branch of spacemacs. I don't know if they deprecated support for other backends.

Cheers for the reply.

**Comment by alexey0308** [comment]
you need to do `C-c C-z` or `, '` to start an R process first.

**Comment by ECon87** [comment]
Thank you @alexey0308. That worked.

I will report to the suggested repos.

Thanks again.
