### ISSUE TITLE
Different behaviour for ctrl-a and home at interactive prompt.

### ISSUE THREAD

**Issue by drgibbon** [emacs-ess/ESS#1160]
Hello, I love using ESS but I've noticed that when going through the command history at an interactive R prompt, `home` and `ctrl-a` do not function the same. For me (Emacs 27.2, ESS 20210818.843), `ctrl-a` will put the mark/cursor at the beginning of the R command (which is useful), whereas `home` will put the mark/cursor at the beginning of the _line_  (which is not useful). That is, with `home` the cursor actually goes to the `>` prompt character, instead of the beginning of the R command. I guess there is a trivial fix for this?

**Comment by vspinu** [comment]
`C-a` is bound to `comint-bol`, `home` is bound to `move-beginning-of-line`. You can re-bind home to `comint-bol` if you want the same behavior  

```el
(define-key inferior-ess-mode-map (kbd "<home>") 'comint-bol)
```
