### ISSUE TITLE
Improper parsing of command when using `M-/` for completion.

### ISSUE THREAD

**Issue by bryce-carson** [emacs-ess/ESS#1164]
As per the title, this is the parsing issue I encounter occasionally when I use ess expansions:
```r
> filenamesAndParameters$outputIndFitnessFilename
outputIndFitnessFilename
Error: object 'outputIndFitnessFilename' not found
```

**Comment by lionel-** [comment]
I don't see these symbols in the code base so I'm guessing they come from a script you've opened?

Can you post a full reprex please?

**Comment by bryce-carson** [comment]
Yes, they're objects and columns within an R script I'm working on.

It's an issue that occurs during interactive use, sporadically, so a reprex as I know it wouldn't be helpful, but I can post steps.

- Start an ESS process with R
- create an object, such as a dataframe:
    - ```testDF <- data.frame(apple = 1:3, banana = 4:6)```
- type the object name, `testDF` at the prompt
- add `$a`, to produce `testDF$a`
- Press `M-/` to expand the command line prompt to `testDF$apple`, and press Return

Occasionally, only the expanded part of the name is sent to the comint, `apple` in this case, which will produce an `object not found` error unless something with the same name actually exists.

**Comment by bryce-carson** [comment]
It appears that `M-/` is bound to `hippie-expand`. I can't reproduce the problem now either, so I'm closing this issue.
