### ISSUE TITLE
.ess.eval and .ess.help not working in the latest release ess14.09

### ISSUE THREAD

**Issue by ghost** [emacs-ess/ESS#117]
I was able to run all the functions with ess-eval-function and see help till I updated ess today. 
Could you please fix this bug and tell me where to find the older working version in the meantime ?

Thanks
Anusha

**Comment by biocyberman** [comment]
Thanks to @mmaechler  Running `R-initiialize-on-start` made the documentation search to work again. Haven't checked if it still works when I restart emacs.
