### ISSUE TITLE
default directory changed?

### ISSUE THREAD

**Issue by sfg** [emacs-ess/ESS#1187]
When starting a R process from a Rnw file, R starts in the parent, not in the directory of the file. How can I change this to the previous behavior?

According to #461 I added 

(setq project-find-function nil)
(setq ess-startup-directory nil)

but this does not work. I use ess version 20220201.816 from MELPA.

**Comment by sfg** [comment]
Seems to be a problem on my side: this only happens in one of my directories.

**Comment by vspinu** [comment]
let's keep this open. Wee need a good defcustom to control this behavior.
