### ISSUE TITLE
Integrate with the official julia-mode rather than replacing it

### ISSUE THREAD

**Issue by PythonNut** [emacs-ess/ESS#119]
An official `julia-mode` already exists. Would it be possible for ESS to simply extend the origional instead of replacing it entirely?

(This arose as a product of [JuliaLang/julia #8635](https://github.com/JuliaLang/julia/issues/8635))

**Comment by mturok** [comment]
@vspinu - I see that @Wilfred submitted a pull request to unify ESS and the official julia-mode some time ago:  https://github.com/emacs-ess/ESS/pull/122

Anything one can do to get this moving forward?

Thanks,
Michael

**Comment by mmaechler** [comment]
IIUC, your change's consequence would be that a julia + emacs-ess user would also need to install  "julia-mode" from the julia sources / website (or other ways such as MELPA)? 
I'm just asking... if it is true, I'd want to make sure that would be as seemless as possible ... and for now, 
(where julia is still quite a bit of a moving target!)  even consider bundling  julia-mode with the ESS tarball in our releases.

@wilfred, @mturok : I have added two "inline" comments in your file changes, can you have a look?

**Comment by vspinu** [comment]
Sorry folks. I got completely overwhelmed with two jobs and a reconstruction of the new house.  It's getting a bit easy on my side these days and II hope to look at it soon now.

> 'm just asking... if it is true, I'd want to make sure that would be as seemless as possible

It's true. If ESS is installed from MELPA the julia dependency will be pulled automatically.  We might consider having a contrib directory with up to date julia mode as a fall-back in case machine default julia mode is not has not been found.

**Comment by mturok** [comment]
@vspinu Not at all - and congratulations with the new house.    Happy to lend a hand....but saw that some tests were failing currently (and looks like the pull request is on a very old revision).

**Comment by mmaechler** [comment]
fixed by 7bfcbbda4146e7375a48c4e1fba3582784c49b8f
