### ISSUE TITLE
font locking vectors

### ISSUE THREAD

**Issue by nvall** [emacs-ess/ESS#1192]
Hi, 
Does anyone know if it is possible to font lock a vector that is assigned in a script ? 
For example in the script below I would like to font lock `a`
```
a <- 1
# or
a <- data.frame()
```
Thank you for your help !

**Comment by vspinu** [comment]
Check ESS>Font Lock sub-menu. Select there whatever you want to highlight. What you want is assign operator if I understand you correctly. Don't forget to "Save to custom".

**Comment by nvall** [comment]
Great, it was already set but I have to set a different color. Thank you.
