### ISSUE TITLE
Indentation (again)

### ISSUE THREAD

**Issue by izahn** [emacs-ess/ESS#120]
I know a lot of ink has been spilled trying to explain to people how to customize indentation in ESS, but I'm still not getting it. Here is how ESS wants to indent:
```r
1 +
    mean(rnorm(100)) +
        mean(rnorm(100), na.rm=TRUE) +
            mean(rnorm(100),
                 na.rm=TRUE) +
                     2 +
                         3
```
I don't even follow the logic of what all that whitspace is supposed to mean, but to each his own. The problem is that I can't figure out how to make it sane. What I want is something like 
```r
1 +
  mean(rnorm(100)) +
  mean(rnorm(100), na.rm=TRUE) +
  mean(rnorm(100),
       na.rm=TRUE) +
  2 +
  3
```
but I just can't seem to tame it. Following http://emacs.1067599.n5.nabble.com/indentation-of-ggplot-code-and-ess-13-09-02-td322315.html I set everything to zero;
```lisp
(add-to-list 'ess-style-alist
             '(my-style
               (ess-indent-level . 0)
               (ess-first-continued-statement-offset . 0)
               (ess-continued-statement-offset . 0)
               (ess-brace-offset . 0)
               (ess-expression-offset . 0)
               (ess-else-offset . 0)
               (ess-close-brace-offset . 0)
               (ess-brace-imaginary-offset . 0)
               (ess-continued-brace-offset . 0)
               (ess-arg-function-offset . 0)
               (ess-arg-function-offset-new-line . '(0))
               ))
(setq ess-default-style 'my-style)
```
and I still get 
```r
1 +
mean(rnorm(100)) +
mean(rnorm(100), na.rm=TRUE) +
mean(rnorm(100),
     na.rm=TRUE) +
     2 +
     3
```
Where is the indendation in front of "2 +" and "3" comming from? And how can I turn it off?

Thanks,
Ista

**Comment by otsaw** [comment]
I'm sorry to complain about indentation too, but I can't find right settings anymore either. I'd like to see continuation offset ignored in favor of an open paranthesis or bracket to line up to, i.e.

    foo = x +
        y

but

    foo = foo[x &
              y]

I can't find settings that would give both of the above.

**Comment by vspinu** [comment]
> I can't find settings that would give both of the above.

There are no settings to differentiate these two cases. Consistency was the guiding principle.

**Comment by arbelt** [comment]
This is also the one thing that keeps me going back to RStudio.  I think the issue is that after a multiline function call, the `ess-first-continued-statement-offset` is applied again rather than the continued statement offset, at least from my brief fiddling...
