### ISSUE TITLE
Some errors in R printed only on the same line go off screen. 

### ISSUE THREAD

**Issue by davidbudzynski** [emacs-ess/ESS#1204]
Not sure if this this ESS or Emacs related since I'm relatively new to both but I noted that most data.table's errors don't print correctly: i.e. they all get printed on 1 line instead of breaking into multiple so you can read them. Is there a remedy for this anywhere? Here's an example: 
![image](https://user-images.githubusercontent.com/56514985/177013319-93b34f91-cba0-454a-8a2e-e484af21d899.png)

**Comment by vspinu** [comment]
data table prints very long errors. `M-x toggle-truncate-lines` (don't know what key it is bound by default) to toggle wrapping of lines back and forth.
