### ISSUE TITLE
Freeze when paste to ESS 

### ISSUE THREAD

**Issue by yitang** [emacs-ess/ESS#123]
Hi,

When I paste scripts to ESS buffer, it will freeze immediately, before execution. Sometimes I can stop from hanging by C-g or C-c C-c, sometimes I have to re-start Emacs, worrying some scripts are not saved. 

I have experienced this problem several times on both OS X and Ubuntu, running with Emacs 24.4. 

![screenshot 2014-11-29 12 48 56](https://cloud.githubusercontent.com/assets/6054101/5234502/76ba87a0-77c6-11e4-8ca6-b5c34b9175d0.png)

**Comment by benmaughan** [comment]
I also have the problem on OS X. One workaround is to use `C-'` to open the R block in a temporary ESS buffer. Pasting from there does not seem to hand the ESS prompt.

**Comment by yitang** [comment]
@benmaughan Thanks for sharing your workaround.

**Comment by yitang** [comment]
another user suffered from this problem and asked for help. http://emacs.stackexchange.com/questions/19173/emacs-ess-org-hangs-spins-on-yank

**Comment by kenahoo** [comment]
@vspinu I think that's a misdiagnosis - notice that R isn't actually getting a chance to run the code yet, it's hanging on the *yank*, not the execution.  For me, it seems to depend critically on font-lock-mode being enabled in the buffer where the text comes from too.

**Comment by lionel-** [comment]
Just got bitten by this, also by pasting from an org buffer.

**Comment by yitang** [comment]
@kenahoo thats a good point, I'd try again without front lock mode.

**Comment by jabranham** [comment]
I'm closing this old bug. OS X/macOS has changed considerably since 2016, as have Emacs and ESS. If someone still runs into this, please let us know.
