### ISSUE TITLE
No indentation in ess-jags-mode

### ISSUE THREAD

**Issue by zhenhua-wang** [emacs-ess/ESS#1232]
It seems that there is no indentation in ess-jags-mode. i.e. running `ess-indent-or-complete` on line would insert spaces and running `ess-indent-or-complete` on region would move every line to its beginning.

**Comment by belohli** [comment]
The issue appears to be that the mode doesn't define an `indent-line-function`. A quick fix is 
```
(add-hook 'ess-jags-mode-hook
          (lambda ()
            (setq-local indent-line-function #'ess-r-indent-line)))
```
which makes it indent like R.
