### ISSUE TITLE
Form completions in the background

### ISSUE THREAD

**Issue by otsaw** [emacs-ess/ESS#125]
I really like the `auto-complete` integration in ESS. There's one annoyance however. When I first start typing, I see "Forming completions for ..." in the minibuffer and it blocks for a couple seconds during which I don't see what I type on screen. Would it be possible to form these completions quietly async in the background?

**Comment by vspinu** [comment]
> Would it be possible to form these completions quietly async in the background?

Both R end emacs are single threaded applications. Doing async computation is ridden with perils. There is  a built in ESS support for async commands but it was never used for anything serious as we discovered that for long tasks it can lead to nasty behavior which is catching users by surprise.  

Another way to proceed would be to store common completions (for core packages at least) locally and simply re-read those on startup. That would also speed up loading time on remotes, which could be a pain sometimes.

**Comment by vspinu** [comment]
I am "fixing" this by globalizing R completion for packages. Now the completions for packages will be requested once for the emacs session as opposed to the old "once per R session". This especially helps when you work with multiple sessions or restart your R sessions often. 

I am afraid fetching them in the background is out of the options for now.

**Comment by otsaw** [comment]
Thanks. This should already be helpful.
