### ISSUE TITLE
Symbol value of `font-lock-reference-face is void

### ISSUE THREAD

**Issue by ralmond** [emacs-ess/ESS#1254]
When I open an Rd file, I get this error message, and the font-lock mode only partially works.

```
Symbol value is void font-lock-reference-face
```
This face does not appear in the list of customizable faces.

The in-code reference appears in line 155 of the file `lisp/ess-rd.el`.
I'm guessing that the code needs to check for a binding for that variable and provide one if it does not exist.

```
Emacs-verison:  30.0.50 
ess-version: 18.10.3snapshot [elpa: 20230302.2111] 
```

**Comment by ralmond** [comment]
Adding the following lines to my `.emacs` seems to fix the problem.

```
(defvar font-lock-reference-face 'font-lock-reference-face
  "Face for references in an Rd file.")
(defface font-lock-reference-face
  '((default :inherit font-lock-keyword-face)
    (((class color) (background dark))
     (:foreground "lime green"))
    (((class color)) (background light) (:foreground "dark green")))
  "Face for references in an Rd file."
  :version "0.0")
```

**Comment by yantar92** [comment]
font-lock-reference-face has been removed in Emacs 29 (it was previously obsolete). ess should use font-lock-constant-face instead.

**Comment by yantar92** [comment]
@mmaechler I generally recommend going through the byte-compilation warnings thrown by just released Emacs 29. It will help avoiding such problems in future.

**Comment by HinTak** [comment]
It has been 18.10.3snapshot for a few years now.
