### ISSUE TITLE
Rendering development documentation

### ISSUE THREAD

**Issue by vikasrawal** [emacs-ess/ESS#1255]
I am building an R library. The documentation files, created by Roxygen2, are in man/*.Rd. When I am working in RStudio or even the R console in the terminal, I can use ?myfunction and help(myfunction) to render development documentation after I have loaded the package using devtools::load_all(). But the same does not work when I start R in emacs/ess.

With an R session running in emacs/ess, I get the message: "ess-r-help--build-help-command--unqualified: Can’t find documentation for ‘myfunction’ ".

Is this a known problem? What could be the issue?

Thanks

**Comment by lionel-** [comment]
It's a known problem, that's because ESS catches `?` inputs to run its own doc rendering method, so the shim installed on the search path by devtools never has a chance to run. 

You can work around by wrapping the operator in backticks to prevent ESS from detecting a help command:

```
`?`(myfunction)
```

**Comment by dvictori** [comment]
I just stumbled upon this. So I take this is something that is not going to be changed? It's a minor pet peeves
