### ISSUE TITLE
Ess-remote crash (debug attached)

### ISSUE THREAD

**Issue by zeltak** [emacs-ess/ESS#127]
Hi all

so when i try to connect with ess-remote and after i choose R i get this error

save-current-buffer: Wrong type argument: integer-or-marker-p, nil

here is a debug info: https://paste.xinu.at/XPd3aW/

any clue anyone?

**Comment by jabranham** [comment]
Closing this since the pastebin is gone, OP didn't respond, and it's been nearly 4 years with many changes in ESS since then
