### ISSUE TITLE
ESS website is blank (only displays the header)

### ISSUE THREAD

**Issue by pwaltman** [emacs-ess/ESS#1274]
the repo site (https://ess.r-project.org) only shows the header, with no information or content below it

I've verified this with both chrome and firefox

**Comment by mmaechler** [comment]
>>>>> Peter Waltman 
>>>>>     on Wed, 24 Jan 2024 18:12:24 -0800 writes:

    > the repo site (https://ess.r-project.org) only shows the header, with no information or content below it
    > I've verified this with both chrome and firefox

Thank you, for the heads up.

This was a mistake from ESS core (not me),
now fixed.
