### ISSUE TITLE
Error message about ess-rd.el not providing feature essddr on fresh install of ess v.24.0.1 with emacs 29.1 (Ubuntu 23.10)

### ISSUE THREAD

**Issue by pwaltman** [emacs-ess/ESS#1275]
I'm running in WSL2, which shouldn't be an issue, but stopped working after I upgraded Ubuntu from 22.10 to 23.10.

I gave up on the packaged version from ubuntu, as I got an error from that as well.  For that reason, I chose to install ess manually, however, I get the following error:
`error: Loading file /usr/share/emacs/site-lisp/ess/lisp/ess-rd.el failed to provide feature ‘essddr’`

this also appears after the following message flashes during startup:
`ERROR:ess-etc-directory
Relative to ess-lisp-directory, one of the following must exist:
../etc/ess, ../etc, ../../etc/ess or ./etc`

This error happens regardless of whether or not I byte-compile ess prior to calling `make install` (I've tried both methods).

Any help would be appreciated.

**Comment by rsparapa** [comment]
I don't see that.  But you can provide the feature via adding the line...
(provide 'essddr) 
No idea what that is, but it should get you past the first error.  

And based on your first error, the second error would seem to be that the following directory does not exist...
/usr/share/emacs/site-lisp/ess/etc
Is that true?  But, why not?  That should have been installed with all of the other directories: lisp, doc...  What are the definitions of ess-lisp-directory and ess-etc-directory respectively, i.e., F1 v

**Comment by pwaltman** [comment]
thanks @rsparapa !

It turns out that a previous install (via Ubuntu's package manager) hadn't completely removed the elpa version of ess v18.10.3, which is what was causing the issue with emacs v.29.1.

manually removing it (`sudo rm -r /usr/share/emacs/site-lisp/elpa`) resolved the previous issues that I had reported, and for that reason, I will close this.
