### ISSUE TITLE
Make R aware which source file is in the currently running buffer

### ISSUE THREAD

**Issue by torbjorn** [emacs-ess/ESS#128]
R does not have any mechanism to know which file is being sourced, something like **FILE** in other languages, could emacs lisp be used to make this semi-supported?

Could be something like setting an option in the active R session once code is evaluated in a file, ie option( active_essfile = "/../foo.r" ) or something

In that way R code could actually know where the code is coming from

To me this would have value because I tend to organize projects in directories and sub directories and I use R functions to automatically put images and data files in designated sub directories. Knowing what file is currently running, means it could automatically put files in the right folder.

As it is arranged here I cannot use R getwd() for this

**Comment by lionel-** [comment]
This is something that should be part of the language and not the IDE. Also it's recommended to write your scripts with relative paths.
