### ISSUE TITLE
Question about sed options in Makefile

### ISSUE THREAD

**Issue by plantarum** [emacs-ess/ESS#1292]
I just checked out the latest commit and tried to `make` it, and got hung up at this line:

https://github.com/emacs-ess/ESS/blob/d941b25f10716c307f546bdd9cb85d4ac5c1cf38/Makefile#L25

This fails with the following output:

```
make
********************* VERSIONS **************************
GNU Emacs 30.0.50
ESS 24.01.1
ESSR 1.8
sed: -e expression #1, char 1: unknown command: `.'
```

This is on Ubuntu 20.04. Deleting the string `.orig` fixes the problem.

The online documentation at: 
- https://ess.r-project.org/Manual/readme.html#Installing-from-source
- https://ess.r-project.org/Manual/ess.html#Installing-from-source
indicates that `make` should be all that I need to do, but perhaps that's out of date? I didn't see any INSTALL instructions in the repo top level.

Thanks for any assistance!

**Comment by mmaechler** [comment]
Indeed,  there should not be any space between `-i` and `.orig` ... ... that change is very recent (April 24).
I've now fixed it, in e49c85f9
