### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by BillWeld** [emacs-ess/ESS#1294]
```
$ make
********************* VERSIONS **************************
GNU Emacs 27.2
ESS 24.01.1
ESSR 1.8
*********************************************************
make -C lisp all
make[1]: Entering directory `/home/fatkat/ess-24.01.1/lisp'
test -f ../etc/.IS.RELEASE || wget -qO - https://raw.githubusercontent.com/JuliaEditorSupport/julia-emacs/master/julia-mode.el > julia-mode.el
test -f ../etc/.IS.RELEASE || wget -qO - https://raw.githubusercontent.com/JuliaEditorSupport/julia-emacs/master/julia-mode-latexsubs.el > julia-mode-latexsubs.el
Computing dependencies
sed: can't read julia-mode-latexsubs.el: No such file or directory
emacs -batch -Q  --directory . --directory ./obsolete -f batch-byte-compile ess-julia.el
emacs -batch -Q  --directory . --directory ./obsolete -f batch-byte-compile ess-trns.el
emacs -batch -Q  --directory . --directory ./obsolete -f batch-byte-compile ess-rdired.el
emacs -batch -Q  --directory . --directory ./obsolete -f batch-byte-compile ess-inf.el
emacs -batch -Q  --directory . --directory ./obsolete -f batch-byte-compile ess-r-package.el
emacs -batch -Q  --directory . --directory ./obsolete -f batch-byte-compile ess.el
emacs -batch -Q  --directory . --directory ./obsolete -f batch-byte-compile ess-bugs-d.el
emacs -batch -Q  --directory . --directory ./obsolete -f batch-byte-compile ess-site.el
emacs -batch -Q  --directory . --directory ./obsolete -f batch-byte-compile ess-mode.el
emacs -batch -Q  --directory . --directory ./obsolete -f batch-byte-compile ess-help.el
emacs -batch -Q --directory . --directory ./obsolete -f batch-byte-compile julia-mode.el

In toplevel form:
julia-mode.el:40:1:Error: Cannot open load file: No such file or directory, julia-mode-latexsubs
make[1]: *** [julia-mode.elc] Error 1
make[1]: Leaving directory `/home/fatkat/ess-24.01.1/lisp'
make: *** [lisp] Error 2

```

**Comment by mmaechler** [comment]
I guess it was just a "network" problem aka "internet connection" problem, i.e., the github server not "answering" correctly to the `wget` request?

You can always repeat it manually, and it does work for me:

```
wget -qO - https://raw.githubusercontent.com/JuliaEditorSupport/julia-emacs/master/julia-mode-latexsubs.el > julia-mode-latexsubs.el
ls -l julia-*.el
```
giving
```
-rw-r-----. 1 maechler .... 453307 Jun  7 09:30 julia-mode-latexsubs.el
```
for me, at the moment.

And: You are only seeing this, when *not* installing from an ESS tarball (https://ess.r-project.org/index.php?Section=download) 
or even more recommended and easily:

 just get the `ess`  emacs package from the default emacs package server `ELPA` ( https://elpa.gnu.org  :  ELPA -- GNU Emacs Lisp Package Archive ) .. even though at the moment, our manual still mentions `MELPA` (and `MELPA stable`) only which needs very slightly more work than ELPA for which you can basically just evaluate the following lisp code to get ESS (and polymode etc for `*.,Rnw` and `*.Rmd` i.e. Sweave and Rmarkdown etc):
```
(package-install 'ess)
(package-install 'poly-R)
```

**Comment by BillWeld** [comment]
Thanks! The build works now starting with the current zip file and without any messing with it. I don't think the problem was a network error though because it persisted over multiple attempts. I agree that the emacs package manager is a better way to get ESS and that works great.

**Comment by mmaechler** [comment]
I guess it was just a "network" problem aka "internet connection" problem, i.e., the github server not "answering" correctly to the `wget` request?

You can always repeat it manually, and it does work for me:

```
wget -qO - https://raw.githubusercontent.com/JuliaEditorSupport/julia-emacs/master/julia-mode-latexsubs.el > julia-mode-latexsubs.el
ls -l julia-*.el
```
giving
```
-rw-r-----. 1 maechler .... 453307 Jun  7 09:30 julia-mode-latexsubs.el
```
for me, at the moment.

And: You are only seeing this, when *not* installing from an ESS tarball (https://ess.r-project.org/index.php?Section=download) 
or even more recommended and easily:

 just get the `ess`  emacs package from the default emacs package server `ELPA` ( https://elpa.gnu.org  :  ELPA -- GNU Emacs Lisp Package Archive ) .. even though at the moment, our manual still mentions `MELPA` (and `MELPA stable`) only which needs very slightly more work than ELPA for which you can basically just evaluate the following lisp code to get ESS (and polymode etc for `*.,Rnw` and `*.Rmd` i.e. Sweave and Rmarkdown etc):
```
(package-install 'ess)
(package-install 'poly-R)
```
