### ISSUE TITLE
docstring warnings

### ISSUE THREAD

**Issue by adl** [emacs-ess/ESS#1301]
I get the following warnings with emacs 30.0.50 (one year old):

```
⛔ Warning (comp): ess-custom.el:382:2: Warning: custom-declare-variable `ess-use-inferior-program-in-buffer-name' docstring has wrong usage of unescaped single quotes (use \=' or different quoting such as `...')
⛔ Warning (comp): ess-custom.el:1318:2: Warning: custom-declare-variable `ess-own-style-list' docstring has wrong usage of unescaped single quotes (use \=' or different quoting such as `...')
```

https://github.com/emacs-ess/ESS/blob/80e8befbe2d8ba126edf5bc117660006eaed778f/lisp/ess-custom.el#L382-L384
https://github.com/emacs-ess/ESS/blob/80e8befbe2d8ba126edf5bc117660006eaed778f/lisp/ess-custom.el#L1318-L1321

**Comment by rsparapa** [comment]
Never saw that before.  I checked in a fix.  So take a look and see if that works.  Thanks
