### ISSUE TITLE
breaking change since v24.12.0: could we please consider `poly-mode-*` as optional dependency?

### ISSUE THREAD

**Issue by milanglacier** [emacs-ess/ESS#1306]
In the recent v24.12.0 release, I noticed that several `poly-mode-*` packages have become mandatory dependencies. 

This poses a significant challenge, as the `poly-mode-*` dependencies are intrusive and interfere with other modes. For example, `markdown-mode` (including `*.md`, `*.rmd`) will automatically activate `poly-mode`, which switches the major mode when entering any language block (no matter `c`, `python`, `R` or whatever), regardless of that I have no intend to use polymode with markdown.

Additionally, numerous bugs arise from the context switching of major modes in `poly-mode`. For instance, visual highlighting (when use `evil`) often breaks when `poly-mode` is used within markdown. While I understand that such issues should be reported to the `poly-mode` project, I mention them here to emphasize the broader concerns about making `poly-mode` a hard dependency.

This change feels unnecessarily disruptive. Many users, myself included, rely on `ess` primarily for writing plain R script and prefer it not to interfere with workflows in other contexts, such as markdown (and rmarkdown). The design of `poly-mode` may not appeal to everyone, and some of us prefer to avoid it entirely.

Another things to note is that `polymode` packages are only available on MELPA. While it is reasonable for an ELPA package to have a soft dependency on a MELPA package (e.g., `eglot` has a soft dependency on `markdown-mode`), it feels unnatural for an ELPA package to enforce MELPA as a required package source.  

Thank you for your attention to this matter!

**Comment by milanglacier** [comment]
There is also a concern when using lsp (whether `lsp-mode` or `eglot`) with `poly-mode` + `markdown`:

https://github.com/polymode/poly-R/issues/34

This will make `markdown` unusable with lsp when polymode is activated.

**Comment by milanglacier** [comment]
Instead of add them as dependencies:

```lisp
;; Package-Requires: ((emacs "26.1") (polymode "0.2.2") (poly-noweb "0.2.2") (poly-markdown "0.2.2") (poly-R "0.2.2"))
```

Can we make something like this?

```lisp
(defcustom ess-enable-poly-mode-integration t
  "When non-nil, enable integration with poly-mode."
  :type 'boolean
  :group 'ess
  :initialize 'custom-initialize-default
  :set (lambda (symbol value)
         (set-default symbol value)
         (when value
           (if (fboundp 'poly-markdown+r-mode)
               (message "poly-markdown+r-mode is available")
             (when (y-or-n-p "poly-mode packages are not installed. Install them now? ")
               (let ((packages '(poly-mode poly-noweb poly-markdown poly-R)))
                 (dolist (package packages)
                   (unless (package-installed-p package)
                     (package-install package))))))))
  :require 'ess)

```

**Comment by eyal0** [comment]
I'm seeing an error that I don't understand in the CI of a different project.

https://github.com/flycheck/flycheck/actions/runs/12299679267/job/34326025116?pr=2100

When installing `ess`, it says `Package ‘emacs-27.1’ is unavailable`.  The CI worked fine with the release of late November.

Is this related?  I'm just a contributor to the flycheck project, I don't know much about its CI.

**Comment by milanglacier** [comment]
> I'm seeing an error that I don't understand in the CI of a different project.
> 
> https://github.com/flycheck/flycheck/actions/runs/12299679267/job/34326025116?pr=2100
> 
> When installing `ess`, it says `Package ‘emacs-27.1’ is unavailable`. The CI worked fine with the release of late November.
> 
> Is this related? I'm just a contributor to the flycheck project, I don't know much about its CI.

The *breaking change* is related to new dependencies `polymode` which I think is unnecessary and interfere with other file types.

I think we are talking about two different things

The problem of the flycheck CI looks like that ESS requires `emacs 27.1` but the CI is running on `emacs 26.3`. This is weird, ESS requires `emacs 26.1` in its dependencies spec.

**Comment by vspinu** [comment]
Reverting the change. We will consider creating a special, extended ESS+ package in the future with all the batteries included.

**Comment by milanglacier** [comment]
thanks for the update!
