### ISSUE TITLE
Remove R arrow prettification

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#132]
What is the proper way to customise `R-customize-alist`?

I need to delete the element relative to unicode prettification but I couldn't find a proper hook to run

```
(lambda () (setq R-customize-alist
                          (delete '(prettify-symbols-alist
                                    quote
                                    (("<-" . 8592)
                                     ("<<-" . 8606)
                                     ("->" . 8594)
                                     ("->>" . 8608)))
                                  R-customize-alist)))
```

The hooks I tested either run too early (`R-customize-alist` is not yet defined), or too late (the first R buffer I open, the one that causes ESS to load, has unicode arrows and I have to manually reload it to get rid of them).

Or is there some other way?

**Comment by vspinu** [comment]
There is no easy way to alter R-customize-alist. Even if you add stuff at the top of that list the older values will take effect. That's a big design flaw.  The easiest way to fix this is to set `prettify-symbols-alist` to nil in `ess-mode-hook` (or `R-mode-hook`) and `inferior-ess-mode-hook`.
