### ISSUE TITLE
comments are right aligned upon TAB in ESS[S]

### ISSUE THREAD

**Issue by kcandrews** [emacs-ess/ESS#135]
When I press TAB in an R buffer on a comment line, the entire comment gets right aligned. Is this the intended default behavior for comments which are on their own line?

I'm using ess-version: 14.11 [elpa: 20150108.1239] as reported by emacs.

**Comment by vforget** [comment]
Use two pound signs. Single pound is for another comment type...

**Comment by vforget** [comment]
See

http://stackoverflow.com/questions/13636971/are-there-downsides-with-docstrings-in-r

**Comment by kcandrews** [comment]
Ah, I see. Thanks. I stopped my search at:

http://adv-r.had.co.nz/Style.html

**Comment by vspinu** [comment]
These are standard emacs conventions. See
http://www.gnu.org/software/emacs/manual/html_node/elisp/Comment-Tips.html

>  Ah, I see. Thanks. I stopped my search at: http://adv-r.had.co.nz/Style.html

You cannot ignore 30 years of emacs standards even if Hadley says so ;)

**Comment by mmaechler** [comment]
> Ah, I see. Thanks. I stopped my search at:
> http://adv-r.had.co.nz/Style.html

unfortunately, Hadley is not an ESS lover ... ;-/ ... but rather
employed by RStudio..

It would really be great if they (Rstudio) would adapt to using
the convention we (ESS) inherited from an even older lisp
convention :

  #	   -- at end of line
  ##         -- on its own line, but aligned with lines above
  ###        -- completely "standalone" comment line

but I don't expect it any more now.
Martin

**Comment by kcandrews** [comment]
The only thing is that none of the other Emacs modes I've used aside from Emacs Lisp actually care about this convention.
