### ISSUE TITLE
Julia support in ess-remote incorrectly uses single quotes for strings

### ISSUE THREAD

**Issue by ikirill** [emacs-ess/ESS#137]
Julia support in ess-remote incorrectly uses single quotes for strings, but in julia strings are marked by double quotes only, so running `ess-remote` in a buffer with a remote julia process gives

    julia> options(STERM='iESS', str.dendrogram.last="'", editor='emacsclient', pager='emacsclient',, help.pager='emacsclient', show.error.locations=TRUE)
    ERROR: syntax: invalid character literal

**Comment by vspinu** [comment]
Thanks. Those were R options incorrectly injected into julia process. 

BTW, the recomended use of remotes is [through tramp[(http://ess.r-project.org/Manual/ess.html#ESS-processes-on-Remote-Computers).

**Comment by ikirill** [comment]
The top google result (for me) for "ess remote process" was this page: http://www.xemacs.org/Documentation/packages/html/ess_3.html, which is from 2005 for ESS 5.2.7. I now see I should have paid more attention.

Thanks for pointing out tramp.
