### ISSUE TITLE
comint-history-isearch-backward-regexp (M-r) broken in iESS

### ISSUE THREAD

**Issue by plantarum** [emacs-ess/ESS#140]
To reproduce:

Start a clean Emacs session:
```
emacs -Q
```
Load ESS, start an interactive session:
```{elisp}
(package-initialize) ;; ess installed from melpa
M-x R
```
Enter some commands:
```{r}
ls()
getwd()
```
Try to search interactively through the command history:
```{elisp}
M-r
```
Expecting to see a prompt at the bottom of the buffer, which completes previous commands that match my input, as in `M-x shell` buffers. Instead, the prompt is displayed several lines back, and the regexp search behaves like a re-search-backward, ignoring the R history. That is, instead of bringing matches to the bottom of the buffer, searching moves point up through the text.

```{r}
Regexp history I-search backward: ## This shouldn't be here!!
> ls()
 [1] "binner.document"         "binner.reup"            
 [3] "cor.mat"                 "fixed"                  
 [5] "fragread.document"       "fragread.reup"          
 [7] "multiIntersect"          "multiIntersect.rownames"
 [9] "pcoa.eigs"               "pdetach"                
[11] "reup"                    "tyhead"                 
[13] "tyrelevel"               "tyxtable"               
> getwd()
[1] "/home/tws/scratch"
> ## The prompt should be down here!
```

```{elisp}
(ess-version)
"ess-version: 14.11 [elpa: 20150125.433] (loaded from /home/tws/.emacs.d/elpa/ess-20150125.433/)"

(emacs-version)
"GNU Emacs 24.4.51.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.5)
 of 2015-01-23 on ONOTTAR654746"
```

**Comment by vspinu** [comment]
I cannot reproduce this with the same emacs version.

I recall it happened once to me after a fresh re-install, but restarting
emacs helped. And it never happened again.

There might be some package interfering, you are initializing all your
packages not only ESS.

**Comment by plantarum** [comment]
Hmm. Still happens with this invocation:

```
emacs -Q
```

```{elisp}
(load "/home/tws/.emacs.d/elpa/ess-20150125.433/lisp/ess-site.el")
```

So, no other packages are interfering, and it's consistent between reboots. Doesn't effect shell mode, ESS-specific. And from your experience, specific to *my* ESS. Weird. I'll poke around a bit.

Thanks,

Tyler

**Comment by davidcarslaw** [comment]
I got this too when trying a nightly build of emacs (can't remember the exact version), but went back to 24.4 and all is OK (OS X).

**Comment by vspinu** [comment]
This is a very recent change in comint isearch. I have [reported](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=19710GNU) it to emacs.

**Comment by plantarum** [comment]
Thanks Vitalie! And thanks for the confirmation, David.

**Comment by vspinu** [comment]
This one was fixed [upstream](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=19710).

**Comment by davidcarslaw** [comment]
Thanks very much Vitalie. As an aside I wondered how easy it would be to make this work in helm i.e. it would show the list of candidates that would narrow as you type. That would be very useful I think.

**Comment by vspinu** [comment]
I had in plan to write such thing some time ago, but never got down to it. `M-r` works quite well for me. 

There is [`helm-shell-history`](https://github.com/yuutayamada/helm-shell-history) out there. I've never used it. If you try let me know your opinion.
