### ISSUE TITLE
Can't load package in ESS-developer

### ISSUE THREAD

**Issue by davidcarslaw** [emacs-ess/ESS#141]
i.e. `C-c C-t a` gives "Wrong type argument: numberp, t"

This on Emacs 24.4 OS X

Thanks 
David

**Comment by vspinu** [comment]
I cannot reproduce this. Works fine for me and always did. There were no recent changes to developer code that could affect this behavior, so I have no idea what could go wrong.

**Comment by vspinu** [comment]
Can you post the backtrace?

**Comment by davidcarslaw** [comment]
Here it is. It does print my installed packages to the console though

Debugger entered--Lisp error: (wrong-type-argument numberp t)
  accept-process-output(#<process R> t)
  (or (accept-process-output proc wait) (if (and sec-prompt (process-get proc (quote sec-prompt))) nil (if force-redisplay (redisplay (quote force))) (process-get proc (quote busy))))
  (while (or (accept-process-output proc wait) (if (and sec-prompt (process-get proc (quote sec-prompt))) nil (if force-redisplay (redisplay (quote force))) (process-get proc (quote busy)))) (if (> (- (float-time) start-time) 0.5) (setq wait 0.5)))
  (save-excursion (while (or (accept-process-output proc wait) (if (and sec-prompt (process-get proc (quote sec-prompt))) nil (if force-redisplay (redisplay (quote force))) (process-get proc (quote busy)))) (if (> (- (float-time) start-time) 0.5) (setq wait 0.5))))
  (let ((start-time (float-time))) (save-excursion (while (or (accept-process-output proc wait) (if (and sec-prompt (process-get proc (quote sec-prompt))) nil (if force-redisplay (redisplay (quote force))) (process-get proc (quote busy)))) (if (> (- (float-time) start-time) 0.5) (setq wait 0.5)))))
  ess-wait-for-process(#<process R> nil t nil)
  (if no-prompt-check (sleep-for 0.02) (ess-wait-for-process sprocess nil wait force-redisplay) (goto-char (point-max)) (delete-region (point-at-bol) (point-max)))
  (save-current-buffer (set-buffer buf) (setq inferior-ess-primary-prompt primary-prompt) (setq buffer-read-only nil) (erase-buffer) (set-marker (process-mark sprocess) (point-min)) (inferior-ess-mark-as-busy sprocess) (process-send-string sprocess com) (if no-prompt-check (sleep-for 0.02) (ess-wait-for-process sprocess nil wait force-redisplay) (goto-char (point-max)) (delete-region (point-at-bol) (point-max))) (ess-if-verbose-write " .. ok{ess-command}"))
  (progn (set-process-buffer sprocess buf) (set-process-filter sprocess (quote inferior-ess-ordinary-filter)) (save-current-buffer (set-buffer buf) (setq inferior-ess-primary-prompt primary-prompt) (setq buffer-read-only nil) (erase-buffer) (set-marker (process-mark sprocess) (point-min)) (inferior-ess-mark-as-busy sprocess) (process-send-string sprocess com) (if no-prompt-check (sleep-for 0.02) (ess-wait-for-process sprocess nil wait force-redisplay) (goto-char (point-max)) (delete-region (point-at-bol) (point-max))) (ess-if-verbose-write " .. ok{ess-command}")))
  (unwind-protect (progn (set-process-buffer sprocess buf) (set-process-filter sprocess (quote inferior-ess-ordinary-filter)) (save-current-buffer (set-buffer buf) (setq inferior-ess-primary-prompt primary-prompt) (setq buffer-read-only nil) (erase-buffer) (set-marker (process-mark sprocess) (point-min)) (inferior-ess-mark-as-busy sprocess) (process-send-string sprocess com) (if no-prompt-check (sleep-for 0.02) (ess-wait-for-process sprocess nil wait force-redisplay) (goto-char (point-max)) (delete-region (point-at-bol) (point-max))) (ess-if-verbose-write " .. ok{ess-command}"))) (ess-if-verbose-write " .. exiting{ess-command}\n") (set-process-buffer sprocess oldpb) (set-process-filter sprocess oldpf) (set-marker (process-mark sprocess) oldpm))
  (save-current-buffer (set-buffer sbuffer) (if ess-local-process-name nil (setq ess-local-process-name (process-name sprocess))) (setq primary-prompt inferior-ess-primary-prompt) (ess-if-verbose-write (format "n(ess-command %s ..)" com)) (if no-prompt-check nil (if (process-get sprocess (quote busy)) (progn (ess-error "ESS process not ready. Finish your command before trying again.")))) (setq oldpf (process-filter sprocess)) (setq oldpb (process-buffer sprocess)) (setq oldpm (marker-position (process-mark sprocess))) (unwind-protect (progn (set-process-buffer sprocess buf) (set-process-filter sprocess (quote inferior-ess-ordinary-filter)) (save-current-buffer (set-buffer buf) (setq inferior-ess-primary-prompt primary-prompt) (setq buffer-read-only nil) (erase-buffer) (set-marker (process-mark sprocess) (point-min)) (inferior-ess-mark-as-busy sprocess) (process-send-string sprocess com) (if no-prompt-check (sleep-for 0.02) (ess-wait-for-process sprocess nil wait force-redisplay) (goto-char (point-max)) (delete-region (point-at-bol) (point-max))) (ess-if-verbose-write " .. ok{ess-command}"))) (ess-if-verbose-write " .. exiting{ess-command}\n") (set-process-buffer sprocess oldpb) (set-process-filter sprocess oldpf) (set-marker (process-mark sprocess) oldpm)))
  (let* ((sprocess (or proc (ess-get-process ess-local-process-name))) sbuffer primary-prompt end-of-output oldpb oldpf oldpm) (if sprocess nil (error "Process %s is not running!" ess-current-process-name)) (setq sbuffer (process-buffer sprocess)) (save-current-buffer (set-buffer sbuffer) (if ess-local-process-name nil (setq ess-local-process-name (process-name sprocess))) (setq primary-prompt inferior-ess-primary-prompt) (ess-if-verbose-write (format "n(ess-command %s ..)" com)) (if no-prompt-check nil (if (process-get sprocess (quote busy)) (progn (ess-error "ESS process not ready. Finish your command before trying again.")))) (setq oldpf (process-filter sprocess)) (setq oldpb (process-buffer sprocess)) (setq oldpm (marker-position (process-mark sprocess))) (unwind-protect (progn (set-process-buffer sprocess buf) (set-process-filter sprocess (quote inferior-ess-ordinary-filter)) (save-current-buffer (set-buffer buf) (setq inferior-ess-primary-prompt primary-prompt) (setq buffer-read-only nil) (erase-buffer) (set-marker (process-mark sprocess) (point-min)) (inferior-ess-mark-as-busy sprocess) (process-send-string sprocess com) (if no-prompt-check (sleep-for 0.02) (ess-wait-for-process sprocess nil wait force-redisplay) (goto-char (point-max)) (delete-region (point-at-bol) (point-max))) (ess-if-verbose-write " .. ok{ess-command}"))) (ess-if-verbose-write " .. exiting{ess-command}\n") (set-process-buffer sprocess oldpb) (set-process-filter sprocess oldpf) (set-marker (process-mark sprocess) oldpm))))
  (if (ess-ddeclient-p) (ess-command-ddeclient com buf sleep) (let* ((sprocess (or proc (ess-get-process ess-local-process-name))) sbuffer primary-prompt end-of-output oldpb oldpf oldpm) (if sprocess nil (error "Process %s is not running!" ess-current-process-name)) (setq sbuffer (process-buffer sprocess)) (save-current-buffer (set-buffer sbuffer) (if ess-local-process-name nil (setq ess-local-process-name (process-name sprocess))) (setq primary-prompt inferior-ess-primary-prompt) (ess-if-verbose-write (format "n(ess-command %s ..)" com)) (if no-prompt-check nil (if (process-get sprocess (quote busy)) (progn (ess-error "ESS process not ready. Finish your command before trying again.")))) (setq oldpf (process-filter sprocess)) (setq oldpb (process-buffer sprocess)) (setq oldpm (marker-position (process-mark sprocess))) (unwind-protect (progn (set-process-buffer sprocess buf) (set-process-filter sprocess (quote inferior-ess-ordinary-filter)) (save-current-buffer (set-buffer buf) (setq inferior-ess-primary-prompt primary-prompt) (setq buffer-read-only nil) (erase-buffer) (set-marker (process-mark sprocess) (point-min)) (inferior-ess-mark-as-busy sprocess) (process-send-string sprocess com) (if no-prompt-check (sleep-for 0.02) (ess-wait-for-process sprocess nil wait force-redisplay) (goto-char ...) (delete-region ... ...)) (ess-if-verbose-write " .. ok{ess-command}"))) (ess-if-verbose-write " .. exiting{ess-command}\n") (set-process-buffer sprocess oldpb) (set-process-filter sprocess oldpf) (set-marker (process-mark sprocess) oldpm)))) buf)
  ess-command("print(unique(c(.packages(), .packages(TRUE))), max=1e6)\n" #<buffer  *ess-get-words*> sleep nil t nil)
  (let ((tbuffer (get-buffer-create " *ess-get-words*")) words) (ess-if-verbose-write (format "ess-get-words*(%s).. " command)) (ess-command command tbuffer (quote sleep) no-prompt-check wait proc) (ess-if-verbose-write " [ok] ..") (save-current-buffer (set-buffer tbuffer) (goto-char (point-min)) (while (re-search-forward "\"\\(\\(\\\\\\\"\\|[^\"]\\)*\\)\"\\( \\|$\\)" nil t) (setq words (cons (buffer-substring (match-beginning 1) (match-end 1)) words)))) (ess-if-verbose-write (if (> (length words) 5) (format " |-> (length words)= %d\n" (length words)) (format " |-> words= '%s'\n" words))) (reverse words))
  ess-get-words-from-vector("print(unique(c(.packages(), .packages(TRUE))), max=1e6)\n" nil t)
  (let* ((packs (ess-get-words-from-vector (format "print(unique(c(.packages(), %s)), max=1e6)\n" (if attached-only "NULL" ".packages(TRUE)")) nil t)) (cur-pack (ess-developer--get-package-name)) (sel (ess-completing-read "Add package" packs nil nil nil nil (if (member cur-pack ess-developer-packages) nil cur-pack))) (check-attached (format ".ess_package_attached('%s')\n" sel))) (if (ess-boolean-command check-attached) nil (let* ((fn (if (> (length ess-developer-load-on-add-commands) 1) (ess-completing-read "Package not loaded. Use" (mapcar ... ess-developer-load-on-add-commands) nil t nil (quote ess-developer--load-hist) (car ess-developer--load-hist)) (caar ess-developer-load-on-add-commands))) (cmd (cdr (assoc fn ess-developer-load-on-add-commands)))) (setq cmd (replace-regexp-in-string "%n" sel cmd)) (if (string-match-p "%d" cmd) (progn (let ((dir ...)) (setq cmd (replace-regexp-in-string "%d" dir cmd))))) (ess-eval-linewise (concat cmd "\n"))) (ess-wait-for-process) (if (not (ess-boolean-command check-attached)) (progn (error "Package '%s' could not be added" sel)))) (setq ess-developer-packages (ess-uniq-list (append ess-developer-packages (list sel)))) (ess-developer-activate-in-package sel (quote all)) (message "You are developing: %s" ess-developer-packages))
  ess-developer-add-package(nil)
  call-interactively(ess-developer-add-package nil nil)
  command-execute(ess-developer-add-package)

**Comment by vspinu** [comment]
I suddenly could reproduce this and immediately fixed it. I am puzzled  though, how did it work before? :(.

 Thanks.
