### ISSUE TITLE
Emacs +Ess +R‏(Auto-complete don't work well)

### ISSUE THREAD

**Issue by JayForest** [emacs-ess/ESS#142]
I have installed the auto-complete packages and the latest ess in my emacs. But when I run r in emacs, the auto-complete don't work well. When I type app, I suppose to show like the image in (http://www.emacswiki.org/pics/static/ess-ac3) , but I only can get the list related words in my emacs , cannot display the yellow part shows. 

![no help](https://cloud.githubusercontent.com/assets/10737058/5975175/1dee7dca-a8b8-11e4-8ca5-2b451756ceee.jpg)

I only can get the picture:  
![app](https://cloud.githubusercontent.com/assets/10737058/5975169/0c0e0f08-a8b8-11e4-96a6-fa4c056580a7.jpg)

```
   And I use GNU Emacs 24.4.1 (i686-pc-mingw32) on windows,ESS 14.09;I get the Emacs for Windows Modified from the URL :http://vgoulet.act.ulaval.ca/en/emacs/windows 
```

My auto-complete  configure is following: I wonder the auto-complete whether cannot display the parameter in the yellow part on the widows, thank you very much.
;;auto-complete (add-to-list 'load-path "~/.emacs.d/plugins/auto-complete")
 (require 'auto-complete-config) (add-to-list 'ac-dictionary-directories "~/.emacs.d/plugins/auto-complete/ac-dict") 
(ac-config-default) 
(auto-complete-mode)
 (setq ac-use-quick-help nil)
 (setq ac-auto-start 4) 
 (global-set-key "\M-/" 'auto-complete) 
 ;; Show menu 0.8 second later
 (setq ac-auto-show-menu 0.8) ;; 
 (setq ac-use-menu-map t)
 (define-key ac-menu-map "\C-n" 'ac-next) 
(define-key ac-menu-map "\C-p" 'ac-previous)
 (setq ac-menu-height 12) 
(setq ess-use-auto-complete t)

If I want to get the first picture ,should I  how to set my auto-complete configure

**Comment by vspinu** [comment]
> (setq ac-use-quick-help nil)

You diactivated the quick help. You can also invoke the help manually (this is what I do):

```
(define-key ac-completing-map (kbd "M-h") 'ac-quick-help)
```

**Comment by JayForest** [comment]
I set my auto-complete following you , (define-key ac-completing-map (kbd "M-h") 'ac-quick-help),but I cann't still get the ac-quick-help,I find the reason is that I install the ac-R, it maybe confict with auto-plete, so  I only load the quto-complete,the ac-quick-help can work well,but the auto-complete may slowly, so I still want to load the ac-R,but the Emacs always remand me to "set  ess-dialect"{R| S+|stata |julia | SAS |XLS|Vista } , how to set the default ess-dialect is R ,thank you,！ And while I only use the auto-complete with your (define-key ac-completing-map (kbd "M-h") 'ac-quick-help), the M-h also still cannot work.
