### ISSUE TITLE
Terminal not fully functional

### ISSUE THREAD

**Issue by nessig** [emacs-ess/ESS#143]
Evening folks,

Thanks for all your hard work on ESS so far.

I'm having a bit of trouble getting ESS set up - when I `M-x julia` in emacs, I have two errors of note:

1. Cannot read history file /User/user/.dotfiles/ESS/lisp/.juliahistory, shown in the status bar of emacs

2. and WARNING: Terminal not fully functional from julia.

I've done some googling but can't seem to resolve this on my own - any direction would be appreciated.

cc @leee

**Comment by vspinu** [comment]
> Cannot read history file /User/user/.dotfiles/ESS/lisp/.juliahistory, shown in the status bar of emacs

This is not an error. It's a warning that tells you that you have started julia in that directory for the first time and there is no history saved from previous sessions.

> and WARNING: Terminal not fully functional from julia.

This is a warning from julia and tells you that readline is not available but that should not affect ESS at all. Emacs/ESS deal on their own with subprocesses. 

In a word, you should be able to use julia with both of these warnings.

**Comment by nessig** [comment]
Thanks a lot!

**Comment by datafig** [comment]
I am not able to use the arrow keys to scroll through the history on `julia` session inside emacs. Is this because of `WARNING: Terminal not fully functional from julia.` or is it expected. 

Also I noticed that the file for history is `~/julia_history` and not `~/.juliahistory`

**Comment by vspinu** [comment]
> I am not able to use the arrow keys to scroll through the history on julia session inside emacs.

In emacs you don't use arrow keys. Use M-p, M-n and C-c M-r, C-c M-s. But even better bind `comint-previous-matching-input-from-input` and `comint-next-matching-input-from-input` on M-p and M-n like this:

```
(define-key comint-mode-map [(meta ?p)] 'comint-previous-matching-input-from-input)
(define-key comint-mode-map [(meta ?n)] 'comint-next-matching-input-from-input)
```

**Comment by AMabona** [comment]
Firstly, thanks for the fantastic work you guys have done on emacs-julia integration. It's allowed me to experiment with julia in my preferred development environment.

I know this issue has been closed, but I'm not sure the second point has been addressed. If I run a julia REPL in the terminal, typing `;` takes me into a shell mode for one command, while typing `?` takes me into a help mode. This behaviour isn't replicated in the ESS julia subprocess which seems like a legitimate functionality issue. Are there plans to incorporate these features in the future, or is the thinking that users should use emacs shell subprocesses? What about help mode?

**Comment by vspinu** [comment]
> Are there plans to incorporate these features in the future, or is the thinking that users should use emacs shell subprocesses? 

Everything is possible but someone has to do that. The `;` functionality is a julia trick. I don't think it will ever be implemented. If you want a shell mode `M-x shell` or alternatives will do the job.

> What about help mode?

? key works in ess R but I personally never use it.  It's not a high priority for sure. <kbd> C-c C-d C-d</kbd> or an older ESS specific <kbd> C-c C-v</kbd> are much more convenient IMO.

**Comment by dellison** [comment]
Hey @AMabona, my pull request adding support for using '?' in the `*julia*` buffer was merged this morning! If you're using ESS from MELPA, updating should now get you this feature. It doesn't change the prompt from `julia>` to `help?>` like it does in Julia's regular REPL (nor does it support using `;` for shell commands), but it does allow you to look up documentation conveniently this way in the REPL that ESS provides, in a sort of ESS-R-like fashion. 

I hope this is useful to you!
