### ISSUE TITLE
Installing with emacs from homebrew requires adding to load-path

### ISSUE THREAD

**Issue by khouli** [emacs-ess/ESS#144]
I followed the instructions in the installation documentation to the letter and ran into the following error when starting emacs.

    File error: Cannot open load file, no such file or directory, ess-site

This is very confusing for an emacs newbie like myself. After fighting with this for a while I realized I had to manually add a path to the emacs `load-path` variable.

(add-to-list 'load-path "/Applications/Emacs.app/Contents/Resources/site-lisp/ess")

I happen to be using emacs provided by homebrew. I don't know if that's part of the issue or not.

**Comment by vspinu** [comment]
Yes. This is how ESS always worked. There are plans to simplify the process and completely rely on autoloads, but someone has to do the codding.

**Comment by khouli** [comment]
This might be worth noting in the documentation then, unless it's already there and I missed it.

**Comment by vspinu** [comment]
Yes. It's there in the [docs](http://ess.r-project.org/Manual/ess.html#Installation).  See item 4.
