### ISSUE TITLE
julia: evaluate in module

### ISSUE THREAD

**Issue by tpapp** [emacs-ess/ESS#145]
if some code is enclosed within a 

``` julia
module Name

...

end
```

it would be useful if `C-c C-c` & co evaluated within `Name`. A [discussion on julia-lang](https://groups.google.com/forum/#!msg/julia-users/zhfcT1zs6Qw/Cho6fo1Vm9wJ) suggested that this is feasible, using something like `eval(Name, ...)`, and a few other tweaks to account for line numbers etc. Could possibly use [Jewel.jl](https://github.com/one-more-minute/Jewel.jl).

**Comment by spencerlyon2** [comment]
This would be an excellent feature. Is anyone interested in working on this?

I could potentially pitch in, but I don't know anything about how the julia process and code eval is handled in ess.

**Comment by tpapp** [comment]
After having used Julia for a while, I came to the conclusion that this feature would not be an idiomatic use of the language. So I am closing the issue.
