### ISSUE TITLE
Installation with el-get fails when style files for documentation not present

### ISSUE THREAD

**Issue by krrrcks** [emacs-ess/ESS#146]
Hi, I don't know if that is an issue you want  to care of. If not, just close it. :-)

I tried to install ESS via el-get on an Emacs 24.3. The installaiton just hung somewhere without any notice what happened. After looking into the running processes I saw a "pdflatex refcard" that seemed to hang. I turned out it couldn't find a style file and expected some interaction.

Perhaps it would be an idea to check if all files/software needed to build everything is available or somehow catch those errors.

**Comment by jabranham** [comment]
Generating pdfs in a "default" install (i.e. `make`) is pretty heavy-handed. @lionel- @vspinu can we remove the pdf stuff from the `all` target in `doc/Makefile`?

It would also be nicer to travis since we wouldn't need to install texlive.

**Comment by lionel-** [comment]
I think we should keep it on Travis, it doesn't take much computation time and it allows to check the latex still compiles after changes to the documentation.

Perhaps disable with an envvar? Or disable by default and enable with an envvar?

**Comment by jabranham** [comment]
Fair enough. I do hate scrolling through all the texlive output though. We should probably tell it to run quieter.

> Or disable by default and enable with an envvar?

This is my vote as the current situation basically makes a working texlive installation a requirement for installing ESS.

**Comment by lionel-** [comment]
It looks like we can instruct Travis to fold sections: https://github.com/travis-ci/docs-travis-ci-com/issues/949

**Comment by vspinu** [comment]
How about we have separate targets `doc`, `lisp` and `all = lisp + doc`? The default target should be `all`  though.

**Comment by jabranham** [comment]
@vspinu are you OK with not building the PDF documentation by default? We're currently generating ESS documentation in info, html, text, and pdf documentation for everyone. That seems like overkill at least to me, especially since it means you have to have a working latex install in order for `make all` to run successfully.

**Comment by vspinu** [comment]
Makes sense to me. Tex live is very heavy indeed. Let's see what @mmaechler has to say about this.

**Comment by jabranham** [comment]
I'm going through the Makefile right now and this line:

```
	@echo git HEAD $(shell git rev-parse --short HEAD)
```

in the `version` dependency (which is required by `make all`) means that git is a build dependency of ESS. We should probably remove that as well or at least handle failure.

**Comment by mmaechler** [comment]
I agree that  `make all` should not depend on `git` being present.  
and am ok (not particularly happy though) if it does not build PDFs.  
I do need a substitute however e.g.  make ALL  similar for the PDF.... and the dependency on `version` is I think correct...  Could we have a way to get `version` (cached ?) without `git`... or just a cheap workaround with a _dummy_ version when `git` is not there ?

**Comment by vspinu** [comment]
I think we should small tasks like `doc-info`, `doc-html`, `doc-pdf` which we could combine into other tasks as we see fit. 

Regarding git if no git is available that means it's not from git but from tarball, so picking version from VERSION would be enough in those cases. In any case that `version` target is for information purposes only and could be removed till we figure out something more robust.
