### ISSUE TITLE
Commands sent to R buffer ignored after a system("ssh") command

### ISSUE THREAD

**Issue by davidrosenberg** [emacs-ess/ESS#148]
My workflow is to send commands from an emacs buffer to an R session in emacs via the ESS package.

    a=0;
    system("ssh remotehost ls")
    a = a+1;

When I run the three lines above in rapid succession (i.e. submit them to the R buffer), the value of a at the end is 0. When I run them slowly, a is 1.

I've only had this issue running an ssh command via system. In all other cases, the commands queue up and all run sequentially.

My colleagues have the exact same issue with their R/vim setup. But we don't have the same issue in RStudio.

**Comment by vspinu** [comment]
Likely to be some R issue. ESS simply sends everything you send to R in the order you send. If you open R in emacs shell and paste all the commands in there do you see the same problem?

**Comment by davidrosenberg** [comment]
Yes - same problem when I paste teh commands into R in an emacs shell.  Interesting.

**Comment by vspinu** [comment]
I think it's worth reporting to R folks then.

**Comment by davidrosenberg** [comment]
Here's the bug report: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=16233
