### ISSUE TITLE
ess-r-completion not found

### ISSUE THREAD

**Issue by dickoa** [emacs-ess/ESS#149]
Hi everyone,
I tried to use the latest version of ESS this morning but I realized that there is a problem with ess-r-d.el.
It looks like there is an ess-r-completion.el file missing or it doesn't need to be used inside ess-r-d.

You will find the line that cause the problem here:
https://github.com/emacs-ess/ESS/blob/master/lisp/ess-r-d.el#L48

**Comment by dickoa** [comment]
I think the problem is in the Makefile in the lisp directory.
ess-r-completion is not byte-compiled therefore not sent to /usr/share/emacs/site-lisp when using `make install`.
I just added ess-r-completion.elc to the Makefile and I will do a pull request

Sorry for the noise

**Comment by mmaechler** [comment]
Unfortunately, the pull request #150 lead to a new problem: I've mentioned there, that compilation of `ess-r-completion` ends in a strange 'cl-lib error (emacs 24.3, ubuntu 14.4).
