### ISSUE TITLE
R linter intruding into Julia code

### ISSUE THREAD

**Issue by mindbound** [emacs-ess/ESS#152]
When writing code in Julia, sometimes (especially when declaring modules) I get an error message from r-lintr, which I'm reasonably sure shouldn't happen in Julia mode:

```
Suspicious state from syntax checker r-lintr: Checker r-lintr returned non-zero exit code 1, but no errors were output: Error in if (low > 0L) { : missing value where TRUE/FALSE needed
Calls: lint -> retrieve_lint -> lapply -> FUN -> find_new_line
Execution halted

Checker definition probably flawed.
```

**Comment by vspinu** [comment]
There is no such thing in ESS. It's flycheck's lintr integration what's probably bothering you. Just disable flycheck in ess buffers.

**Comment by mindbound** [comment]
My mistake, thanks for clarifying.

**Comment by sje30** [comment]
@mindbound can we close this?
