### ISSUE TITLE
fix ess-continued-state-offset (dplyr-specific?)

### ISSUE THREAD

**Issue by r2evans** [emacs-ess/ESS#156]
My behavior in ESS recently changed with respect to indentation. I have been successfully setting `ess-first-continued-statement-offset` and `ess-continued-statement-offset` for a while now.

Previously, in my *R* code, re-indenting the block resulted in this code (which is what I want):

```r
library(dplyr)
read.csv('file.csv') %>%
    mutate(X = X+2,
           Y = Y/2) %>%
    filter(X < 5)
```

However, in the last couple of updates (not certain which one did it), the same options now indents to:

```r
library(dplyr)
read.csv('file.csv') %>%
    mutate(X = X+2,
           Y = Y/2) %>%
        filter(X < 5)
```

Specifically, I want the `filter` line indented to the same level as `mutate`, something that has been working fine for the last year or so with my relevant elisp code:

```elisp
(defun my-ess-hook ()
    (smartscan-mode 1)
    (setq ess-nuke-trailing-whitespace-p nil)
    (setq ess-first-continued-statement-offset 4
          ess-continued-statement-offset 0)
    )
(defun my-postinit-ess ()
  "my ess init code run after package-initialize"
  (require 'ess)
  (require 'ess-site)
  (setq-default ess-dialect "R"
                inferior-R-args "--no-save "
                ess-nuke-trailing-whitespace-p nil
                ess-ask-for-ess-directory nil)
  (add-hook 'ess-mode-hook 'my-ess-hook)
  )
(add-hook 'after-init-hook 'my-postinit-ess)
```

A similar example that still ***works correctly***, the default without customizing the two indent variables:

```r
(1+2) +
    (3+4) +
        (5+6)
```

And with the customizations (what I expect to see):

```r
(1+2) +
    (3+4) +
    (5+6)
```

I looked through the diffs and couldn't find anything that affected the two variables I've been using so far. Has something else in the ESS indentation handling changed?

Win8.1_64, emacs-24 installed in an msys2 environment.

```elisp
(emacs-version)
"GNU Emacs 24.4.1 (x86_64-w64-mingw32)
 of 2014-11-08 on CAB8"
(ess-version)
"ess-version: 15.03 [elpa: 20150405.1150] (loaded from c:/Users/r2/.emacs.d/elpa/ess-20150405.1150/)"
```

If it helps, my *R* environment:

```r
sessionInfo()
## R version 3.1.3 (2015-03-09)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 8 x64 (build 9200)
## locale:
## [1] LC_COLLATE=English_United States.1252 
## [2] LC_CTYPE=English_United States.1252   
## [3] LC_MONETARY=English_United States.1252
## [4] LC_NUMERIC=C                          
## [5] LC_TIME=English_United States.1252    
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## other attached packages:
## [1] tidyr_0.2.0 dplyr_0.4.1 r2_0.4.15  
## loaded via a namespace (and not attached):
##  [1] assertthat_0.1  compiler_3.1.3  DBI_0.3.1       digest_0.6.8   
##  [5] htmltools_0.2.6 lazyeval_0.1.10 magrittr_1.5    parallel_3.1.3 
##  [9] plyr_1.8.1      R6_2.0.1        Rcpp_0.11.5     reshape2_1.4.1 
## [13] rmarkdown_0.5.1 stringr_0.6.2   tools_3.1.3    
```

**Comment by r2evans** [comment]
In more research, it sounds similar to (but does not seem to be caused by) [5951ba94](https://github.com/emacs-ess/ESS/commit/5951ba94c1b981786f834b873627392813145f44), and is likely related to recent additions to [73856682](https://github.com/emacs-ess/ESS/commit/73856682b39a3f850668802f97529d70ecf27170). Changes on/about Apr 2 would make sense based on the timeline I have in my mind of when things changed. I have not yet tested some of the other related commits to see if backing them out seems to change what I am seeing.

**Comment by vspinu** [comment]
Yes. I have made %foo% to mean a continuation block instead of a continuation statement. That is, it's indented as if after `else` as opposed to `+- etc`. I had mostly `foreach` specific usage in mind, and forgot about `dplyr`. 

I guess I have to change that back.
