### ISSUE TITLE
indentation with data.table

### ISSUE THREAD

**Issue by yitang** [emacs-ess/ESS#158]
Hi, I upgraded ESS this morning and find this strange indentation when using data.table, for example, 
``` r
dt[y >= 10, list(mean(x == 1),
       mean(x >= 10),
       mean(x >= 100))]
```` 
it seems the second and third lines are indented after `>= ` but in previous version,  they are indented after `,` and it will shows like this:  

``` r
dt[y >= 10, list(mean(x == 1),
                 mean(x >= 10),
                 mean(x >= 100))]
```` 

Obvious the second snippet is more readable, at least for me, so I wonder if there is a way to configure this behaviour?

**Comment by vspinu** [comment]
This is a bug indeed. I will investigate. Thanks.

**Comment by mmaechler** [comment]
You may want to simultaneously look at  the "issue"  `27b` in https://github.com/emacs-ess/ESS/blob/master/etc/R-ESS-bugs.R#L708

**Comment by vspinu** [comment]
> You may want to simultaneously look at the "issue" 27b in https://github.com/emacs-ess/ESS/blob/master/etc/R-ESS-bugs.R#L708

Looks like it's only your problem. I get it indented correctly 

```R

### --- 27b --- [new, 2015-04-09]
print.MethodsFunction <- function(x, byclass = attr(x, "byclass"), ...)
{
    info <- attr(x, "info")
    values <- if (byclass) {
        unique(info$generic)
    } else {
        visible <- ifelse(info$visible, "", "*")
        paste0(rownames(info), visible)
###     ^-- both lines above should start here
    }
### ^-- "}" here

    ## 2nd version:
    val <-
        if (byclass) {
            unique(info$generic)
        } else {
            visible <- ifelse(info$visible, "", "*")
            paste0(rownames(info), visible)
###         ^-- both lines above should start here
        }
###     ^-- "}" here
    invisible(x)
}
```

**Comment by vspinu** [comment]
> I upgraded ESS this morning and find this strange indentation 

I have just checked that out and this is how ESS indented forever. That code is indented just like ordinary functions would do:

```R

foo(y >= 10, list(mean(x == 1),
        mean(x >= 10),
        mean(x >= 100)))
```

Note that even with named argument, the indentation is not at open `(`

```
foo(y >= 10, boo = list(mean(x == 1),
                 mean(x >= 10),
                 mean(x >= 100)))
```

The intention is to save horizontal space. So you should either keep all that list on one line, or move it to the new line. I tend to think like you do, that open `(` should have priority over `=` indentation. Let's see what others think. 

If I have time I will try to implement that and see how other indentation is affected by this change.

**Comment by gonike** [comment]
I think it would be good to change this as you propose. However, there is a corner case where the current behavior should be preserved: When there is nothing in the opening line.

    foo(y >= 10, boo = list(
                     mean(x == 1),
                     mean(x >= 10),
                     mean(x >= 100)))

This comes in very handy when I really need to save horizontal space. And besides, this makes no sense at all:

    foo(y >= 10, boo = list(
                            mean(x == 1),
                            mean(x >= 10),
                            mean(x >= 100)))
