### ISSUE TITLE
Roxygen multi-line hanging block indentation

### ISSUE THREAD

**Issue by gonike** [emacs-ess/ESS#160]
When writing roxygen documation for e.g. a function, pressing enter creates a new line with a comment marker and always puts the cursor at the beginning of that new line behind the comment marker. It would be nice if this behavior could be 'adaptive' s.t. it automatically creates two whitespaces if the current block of text belongs to a `@param`, `@return`, etc. flag. Currently, this has to be made by hand.

A related issue is that running `fill-paragraph` breaks this manually adjusted indentation and removes all additional whitespace in the beginning of a line.

See this example from the [roxygen vignette](http://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html) for the desired documentation formatting, note the *hanging* text blocks in `@param` and `@return`:

    #' Sum of vector elements.
    #'
    #' \code{sum} returns the sum of all the values present in its arguments.
    #'
    #' This is a generic function: methods can be defined for it directly
    #' or via the \code{\link{Summary}} group generic. For this to work properly,
    #' the arguments \code{...} should be unnamed, and dispatch is on the
    #' first argument. 
    #'
    #' @param ... Numeric, complex, or logical vectors.
    #' @param na.rm A logical scalar. Should missing values (including NaN)
    #'   be removed?
    #' @return If all inputs are integer and logical, then the output
    #'   will be an integer. If integer overflow
    #'   \url{http://en.wikipedia.org/wiki/Integer_overflow} occurs, the output
    #'   will be NA with a warning. Otherwise it will be a length-one numeric or
    #'   complex vector.
    #'
    #'   Zero-length vectors have sum 0 by definition. See
    #'   \url{http://en.wikipedia.org/wiki/Empty_sum} for more details.
    #' @examples
    #' sum(1:10)
    #' sum(1:5, 6:10)
    #' sum(F, F, F, T, T)
    #'
    #' sum(.Machine$integer.max, 1L)
    #' sum(.Machine$integer.max, 1)
    #'
    #' \dontrun{
    #' sum("a")
    #' }
    sum <- function(..., na.rm = TRUE) {}

**Comment by vspinu** [comment]
>  It would be nice if this behavior could be 'adaptive' 

Would be very nice indeed. Patches, as usual, are very much welcome.
