### ISSUE TITLE
Live Markdown rendering?

### ISSUE THREAD

**Issue by eddelbuettel** [emacs-ess/ESS#161]
I was just discussing with a colleague how Emacs and `M-x revert-mode` along with RStudio makes for decent (R)Markdown editing, thanks to everything you already added to ESS.

Could preview of the resulting markdown document be added, or is this creeping featuritis?

I'd love something like `M-x compile` with a configurable `compile-command` for turning (R)Markdown into to something visible.  Whenever I look at live markdown rendering, though, folks seem to point to browser-based solutions.  Could we leverage w3 here, or is all this going way out of scope?   If so, please feel free to nuke this ticket right away.

**Comment by vspinu** [comment]
Hi Dirk, I am sure you figured this out by now ;)  Live rendering is out of scope for ESS. The way it's done elsewhere is to have a daemon checking for modifications. I haven't checked the state of rmarkdown recently but such a daemon should be there. I really don't think w3 or similar is an option for such things.

**Comment by eddelbuettel** [comment]
Just out of utter nerdnessness, I recently came across a post (for Emacs 26+ configured appropriately) to add the webkit rendering engine ... so that you end up with a full-featured browser inside Emacs.  So we'll revisit this in two or three years :)
