### ISSUE TITLE
else statements not indented correctly

### ISSUE THREAD

**Issue by bachmeil** [emacs-ess/ESS#163]
I'm using ESS 15.03 (installed from http://cran.r-project.org/bin/linux/ubuntu/README). The default indentation for else statements produces code like this:

```r
if (3 > 2) {
  print("larger")
} else {
    print("smaller")
  }
```

Earlier versions of ESS indented this code correctly.

**Comment by eddelbuettel** [comment]
Uh-oh. Confirmed on Ubuntu 14.10, Emacs 24.3.

That may get annoying :-/

**Comment by vspinu** [comment]
The master is ok. It's a bit awkward that such a basic bug went through unobserved in our [R-ess-bugs.R](https://github.com/emacs-ess/ESS/blob/master/etc/R-ESS-bugs.R). 

It might be worth issuing a patch release just for this bug.

**Comment by mmaechler** [comment]
Well, I *did* add a very similar case to '27b' in that file (https://github.com/emacs-ess/ESS/blob/master/etc/R-ESS-bugs.R) but @vspinu told us (ESS-core) you did not see the bug.. and indeed, I do not see it now, either.  But at the time, I *did* see it and it is exactly the same issue as above...  oh dear, there's "statefulness" somewhere that seems to make things not easily reproducible.

**Comment by mmaechler** [comment]
So, indeed this bug had been fixed in the "master" aka the development version of ESS.
I will release that as  ESS 15.03-1  now.
