### ISSUE TITLE
Some indentation issues

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#167]
Here are a few quirks I found in the indentation logic:

First the behaviour of `ess-close-paren-offset` with '() should be relative to the function's argument list rather than the beginning of line:
```r
# It does not make sense to go back to the beginning of the line here
fun <- function(arg_fun(sub_arg1,
                        sub_arg2
),
                arg) {body}

# This is preferable:
fun <- function(arg_fun(sub_arg1,
                        sub_arg2
                ),
                arg) {body}
```

The second issue concerns the combination of `ess-arg-function-offset-new-line = '(2)` and `ess-close-paren-offset = '(0)`:
```r
# This is how the closing parenthese gets indented when there is no
# argument (typically when we type RET before entering the arguments)
fun(

  )

# Once an argument is entered, the closing parenthese will reindent
# properly
fun(
  arg
)
```
This is irritating because it requires manual indentation. And this affects all dplyr-style code.

**Comment by vspinu** [comment]
```
# It does not make sense to go back to the beginning of the line here
fun <- function(arg_fun(sub_arg1,
                        sub_arg2
),
                arg) {body}
```

Yes. I agree.

> This is irritating because it requires manual indentation. And this affects all dplyr-style code.

That's intentional and the argument goes in favor as follows. You press RET in `fun(|)` and you get

```
fun(
   |)
```

Then you type `arg RET` and you get

```
fun(
  arg
)
```

Otherwise you will have to manually indent after first RET, which is irritating. I assume you are using smar-parents to auto insert empty line after first RET, right? I use that for `{}` and never for `()` because it's often makes sense to close `)` on the same line. 

Anyways, we have to chose between two bads here. Your pattern is less common and it should be a simple task to reconfigure your `smart-parents` to shift the `)` by two spaces to the left. So I am afraid we will probably stick with the current situation on this one.

**Comment by lionel-** [comment]
hmm I see... Too bad, the `smart-parens` behaviour saves typing and feels comfortable.

I guess it would be complicated to somehow detect that `smart-parens` setting and try to indent the whole thing accordingly?

This may introduce other issues though. For example, we'd probably need different behaviours for `offset-new-line` and the regular case. Because it would make sense to have:
```r
fun(
  |
)
```
but if not a new line at opening parenthese, this is probably better:
```r
fun(arg1,
    |)
```

Not a very big deal, I will try your suggestion of switching off `smart-parens` for parentheses.

**Comment by vspinu** [comment]
> I guess it would be complicated to somehow detect that smart-parens setting and try to indent the whole thing accordingly?

Yes. This is not our job. 

> but if not a new line at opening parenthese, this is probably better:

Exactly! 

> Not a very big deal, I will try your suggestion of switching off smart-parens for parentheses.

You don't need to turn it on. I have them on but I am not inserting new line on `(`. You can tweak the indentation in `:post-handlers` hooks to shift it two spaces to the left. This is what I have for `{`. 

```
(sp-pair "{" nil :post-handlers '((my-create-newline-and-enter-sexp "RET")))

(defun my-create-newline-and-enter-sexp (&rest _ignored)
  "Open a new brace or bracket expression, with relevant newlines and indent. "
  (newline)
  (indent-according-to-mode)
  (forward-line -1)
  (indent-according-to-mode))
```

**Comment by lionel-** [comment]
Thanks for the tip.
