### ISSUE TITLE
Unable to start R subprocess in emacs

### ISSUE THREAD

**Issue by aleSuglia** [emacs-ess/ESS#172]
I'm an *archlinux* user and after the last emacs update (current version 24.5.1), Emacs ESS (current version 20150423.923) it's no more able to start an R subprocess using the command 'R'.
When I do it I receive this error:
*ess-load-extras: Symbol's function definition is void: copy-list*

I'll explain exactly which is the sequence of operation which arise the bug:
 - start a new Emacs session
 - from the main buffer I execute 'R' command using M-x
 - The error is displayed and the subprocess is not *visualized*

I've used the term *visualized* because, after I insert the command, the process is started in a specific buffer but it is not immediately opened in the current buffer. 

But I have this problem only if I invoke R from the main buffer, instead if I invoke it from another buffer, Emacs is able to start the subprocess and display it in the current buffer.

Thank you in advance!

**Comment by vspinu** [comment]
`copy-list` is defined in `cl-lib.el`. I will investigate.

For now one of the following should help `(require 'cl-lib)` or `(require 'cl)`.

**Comment by aleSuglia** [comment]
At the moment seems that works. Thank you for your support and I hope that you'll end up with a proper solution.

**Comment by d125q** [comment]
Can confirm the same behavior on Windows 8.1 running *GNU Emacs 25.0.50.1 (x86_64-w64-mingw32)*.

**Comment by jmarca** [comment]
Same problem here, Slackware Current, GNU Emacs 24.5.1 (x86_64-slackware-linux-gnu, GTK+ Version 2.24.27)

Installed ess via MELPA.

(require 'cl) seems to fix the "copy-list" complaint

**Comment by d125q** [comment]
The issue still persists when Company is installed: `ess-load-extras: Symbol's function definition is void: copy-list`

I believe [this is the offending line](https://github.com/emacs-ess/ESS/blob/master/lisp/ess.el#L319).

**Comment by vspinu** [comment]
Same file contains [`(require 'cl)](https://github.com/emacs-ess/ESS/blob/master/lisp/ess.el#L115). 

Make sure you have installed the lates version. You can check that by navigating to the definition of ` ess-load-extras` and check that it indeed has `(require 'cl)` at the start.

**Comment by d125q** [comment]
My ESS version is 20150528.1229. I am not sure if `eval-when-compile` helps.
