### ISSUE TITLE
(Easy) ESS support for reproducible Debian builds

### ISSUE THREAD

**Issue by eddelbuettel** [emacs-ess/ESS#173]
Some of you, @mmaechler included, saw me mention reproducible builds before.  The basic idea is that re-building a package should lead to bit-by-bit identical packages -- and this is easy to automate.  Overall Debianis now in the 80% or 90% range for all packages.

And with very helpful R Core support (and a small patch of mine), and some gentle and productive nudging from the Debian folks driving this, we now have it for R itself, and also for all (or most) r-cran-* packages.  You can see one view via [my QA page](https://qa.debian.org/developer.php?login=edd@debian.org) particularly the third-from-last column 'Rep'. 

For ESS we get [this error report page](https://reproducible.debian.net/rb-pkg/unstable/amd64/ess.html) and it looks like it is only 'tex-compilation date' of the reference card.  Clearly, we could either hard-wire the data to the most recent change, or change the Makefile logic to extract that date from ChangeLog (or, these days, `git log` ?) and paste it in via `sed`.  

Any preferences?  I'd be happy to submit a PR from a branch if there is consensus.  I may upload a manual test to Debian with the date manually fixed just to see that it passes...

**Comment by eddelbuettel** [comment]
I since learned about an alternative using a tool called `faketime` which we would feed the timestamp of the most recent changelog entry as an override to the current system time.

That should work, but currently conflicts with the core build tool we use, `pbuilder`.  So it is wait and see for now...

**Comment by sje30** [comment]
Hi Dirk, any resolution to this -- I think it would make sense for the date of the reference card pdf to match the date of the dominant .tex source.

But isn't this a problem also for the R manuals -- what have you done there?

**Comment by eddelbuettel** [comment]
Open wart at my end for both ESS and R.

Last I looked a suggested hook was to use a shared library to override the clock briefly when the build happens to set a fixed date -- from the `debian/changelog` file as a default.  That didn't work for a package chain reason. I need to check again.  Do you have another pointer, by chance?

**Comment by eddelbuettel** [comment]
[This hint about pdf time stamp 'fixing'](https://wiki.debian.org/ReproducibleBuilds/TimestampsInPDFGeneratedByLaTeX) looks promising. I will try this.

**Comment by sje30** [comment]
> [This hint about pdf time stamp
> 'fixing'](https://wiki.debian.org/ReproducibleBuilds/TimestampsInPDFGeneratedByLaTeX)
> looks promising. I will try this.

that does look interesting.  I have no solutions, but sympathise with
the problem... my approach has been to simply ignore the diff output
relating to creation dates when I've compared manually two pdf files
that I think should be identical.

S

**Comment by eddelbuettel** [comment]
I just fought with this for a while, but without success.  The suggested recipe alters the Makefile to modify the foo.tex -> foo.pdf step.  I would be much happier if I could just modify the pdf file at the end.  Seemingly I cannot.

**Comment by eddelbuettel** [comment]
A little while later ...

```{.sh}
#!/bin/bash
##
##  Override CreationDate and ModDate timestamps in pdf files
##
##  Based in part on 
##     https://wiki.debian.org/ReproducibleBuilds/TimestampsInPDFGeneratedByLaTeX
##  as well as a fair amount of trial and error
##
##  Dirk Eddelbuettel, September 2015
##  Released under GPL-2 or later

set -u 
set -e

if [ $# -lt 1 ]; then
    echo "Usage: $0 file"
    exit 1
fi
file=$1

if [ ! -d debian/ ]; then
    echo "No debian/ subdirectory"
    exit 1
fi

##  Meant for debian/ subdirectories containing file debian/changelog
DEB_DATE=$(dpkg-parsechangelog -S date)
PDF_DATE=$(date -ud "${DEB_DATE}" +D:%Y%m%d%H%M%S-00\'00\')

sed -i -e "s|^/CreationDate (.*)$|/CreationDate (${PDF_DATE})|" \
       -e "s|^/ModDate (.*)$|/ModDate (${PDF_DATE})|" ${file}

MD5=$((echo ${DEB_DATE} && du -b ${file}) | md5sum | cut -c -32)
sed -i "s|^/ID \\[\\(<[0-9A-F]\\{32\\}>\\) \\1]$|/ID [<${MD5}> <${MD5}>]|" ${file}

```

Will try this...

**Comment by eddelbuettel** [comment]
Ooops.   Didn't yet mean to close this.

**Comment by eddelbuettel** [comment]
And I guess what I fully ignore in all that was that [this line in refcard.tex](https://github.com/emacs-ess/ESS/blob/master/doc/refcard/refcard.tex#L27) probably needs a change.

Thoughts?

**Comment by sje30** [comment]
> And I guess what I fully ignore in all that was that [this line in
> refcard.tex](https://github.com/emacs-ess/ESS/blob/master/doc/refcard/refcard.tex#L27)
> probably needs a change.


Does `\SVN $Date$` simply evaluate to the date of last checkin of that
file?  If so, that would be fine wouldn't it?

**Comment by eddelbuettel** [comment]
Yes, working on that now.  I will send a PR for a simple change to `refcard.tex`.  That is the only one generated at the build time.   My script seems to work 'as is' but not as part of the packages.  Currently head-scratching and poking around ...

**Comment by eddelbuettel** [comment]
It would appear that the Debian powers-that-be prefer to wait until pdflatex is fixed upstream to respect the pending SOURCE_DATE_EPOCH patch.  That will deal with the timestamp in the pdf (internal) header.  

We still have to remove the obvious use of date information in the latex macro.  I will send a PR.

**Comment by mmaechler** [comment]
Thank you, Dirk.... looking forward to it.. (( in an ideal world by Sep.22
- but I know we are all volunteers and busy!))

On Sat, Sep 19, 2015 at 4:53 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
@mmaechler Please see [here for  the PR](https://github.com/emacs-ess/ESS/pull/241).

Now for "just ESS" we could solve the reproducibility issue by pre-compiling the `refcard.pdf` just as we pre-build other "static" pdf files.  Then the PDF metadata is fixed, and we're good.

(For the rest of Debian, `pdflatex` is still an open issue.  I can hot-patch pdf files on the shell, but for a reason nobody understands it does not work in the headless `pbuilder` chroot.  Maybe a local issue. I put that to rest as the reproducibility team prefers a more global solution via `pdflatex` anyway.)

**Comment by mmaechler** [comment]
I've merge the PR #241 now.  We are shipping the `refcard.pdf` with the tar ball already, so think this can be closed, no ?

**Comment by eddelbuettel** [comment]
Ahh.  I guess I should build from the tarball then -- I have for the last few years used the svn or git archive.

**Comment by mmaechler** [comment]
Interesting... but we have never committed our `*.pdf`  targets and I believe that would be wrong to do
(even though I know people have start fighting wars about this...)

**Comment by eddelbuettel** [comment]
Hm, the evidence seems to point the other way:

```
edd@max:~/git/ess/doc(master)$ ls -l *pdf
-rw-rw-r-- 1 edd edd  12984 Oct 28  2014 ediff-sas.pdf
-rw-rw-r-- 1 edd edd 180773 Oct 28  2014 ess-demo.pdf
-rw-rw-r-- 1 edd edd 532105 Oct 28  2014 ess-intro-graphs.pdf
-rw-rw-r-- 1 edd edd  81182 Oct 28  2014 ess-intro.pdf
-rw-rw-r-- 1 edd edd 117981 Oct 28  2014 font-cor-s.pdf
-rw-rw-r-- 1 edd edd 132386 Oct 28  2014 font-incor-s.pdf
-rw-rw-r-- 1 edd edd   9305 Oct 28  2014 hilock-sas.pdf
edd@max:~/git/ess/doc(master)$ git log ess-demo.pdf | wc -l
13
edd@max:~/git/ess/doc(master)$ 
```

**Comment by mmaechler** [comment]
@eddelbuettel : Sorry but you have to read more carefully what I wrote before calling "evidence".
None of the above are **targets** (of `make`).
BTW:  `git` is not as nice as `svn` which *does* use correct times (:= "last modification"), but rather uses "clone time".   I've copied the shell script at https://gist.github.com/jeffery/1115504   and apply it to cloned/forked  git directories (on my disk) if I don't forget.  Do apply it to your `ess` directory (it runs recursively also for sub directories) and then do your `ls ..`.

**Comment by eddelbuettel** [comment]
The flipside is also true.  `refcard.tex` last saw an update 23 months.  So why not commit a pdf and use it?
