### ISSUE TITLE
Symbol's function definition is void: window-font-height

### ISSUE THREAD

**Issue by izahn** [emacs-ess/ESS#177]
After updating via MELPA I get `Symbol's function definition is void: window-font-height` errors when running `ess-execute-screen-options`. According to https://github.com/emacs-mirror/emacs/blob/master/etc/NEWS this was introduced in emacs 25 (I have emacs 24.5.1, which is the latest stable release AFAIK).

**Comment by vspinu** [comment]
Ok. Sorry about that. I meant to check that but forgot. Looking into alternatives.
