### ISSUE TITLE
browser problem in ESS 15.03-1 R session buffer

### ISSUE THREAD

**Issue by smckinney2718** [emacs-ess/ESS#178]
browser() break points are not happening when I run R in emacs with ess 15.03-1

From *Messages* buffer:

Loading /Volumes/KilroyHD/kilroy/Software/Gnu/Emacs/ESS/ess-15.03-1/ess-15.03-1/lisp/ess-site.el (source)...

with current R running in Emacs buffer

R version 3.2.0 (2015-04-16) -- "Full of Ingredients"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

> foo <- list(A = 1:5, B = letters[1:5])
> foo
$A
[1] 1 2 3 4 5

$B
[1] "a" "b" "c" "d" "e"

> bar <- lapply(foo, function(x) { browser() } )
Called from: FUN(X[[i]], ...)
Browse[1]> 
Called from: FUN(X[[i]], ...)
Browse[1]> 
> bar <- lapply(foo, function(x) { browser() } )
Called from: FUN(X[[i]], ...)
Browse[1]> 
Called from: FUN(X[[i]], ...)
Browse[1]> 
>

So for some reason the browser() breaks don't happen.  Evaluation skips along and never stops at a browser break.  I am unable to examine things inside a function call.

If I invoke R from a shell, I get this behaviour

> foo <- list(A = 1:5, B = letters[1:5])
> foo
$A
[1] 1 2 3 4 5

$B
[1] "a" "b" "c" "d" "e"

> bar <- lapply(foo, function(x) { browser() } )
Called from: FUN(X[[i]], ...)
Browse[1]> x
[1] 1 2 3 4 5
Browse[1]> 
Called from: FUN(X[[i]], ...)
Browse[1]> x
[1] "a" "b" "c" "d" "e"
Browse[1]> 
> 

Each browser() call yields a Browse prompt where I can type things in and do browsery stuff.

Any idea what is going on in Emacs/ESS *R* buffers that signals browser() inappropriately?

Any guidance / bug fixes appreciated.

Steven McKinney

Statistician
Molecular Oncology and Breast Cancer Program
British Columbia Cancer Research Centre

email: smckinney +at+ bccrc +dot+ ca

**Comment by vspinu** [comment]
>>> smckinney2718 on Wed, 13 May 2015 19:26:55 -0700 wrote:

 >  bar <- lapply(foo, function(x) { browser() } )

In ESS debugger stops on the expression that immediately follows the
browser(), not on the browser() itself. So simply add another expression
after the browser:

    bar <- lapply(foo, function(x) { browser(); 1 } )
    Called from: FUN(1:3[[1L]], ...)
    Browse[1]> 
    debug at #1: [1] 1
    Browse[2]> 

Given that this use pattern is unlikely to happen in practice, it's a
very small price to pay to be able to automatically jump to the source
location.

  Vitalie

**Comment by smckinney2718** [comment]
In my practice it is very likely to happen!
Agreed, the workaround is fine, thanks for the workaround.

Best

Steve
