### ISSUE TITLE
inferior-julia-process-hook?

### ISSUE THREAD

**Issue by Xparx** [emacs-ess/ESS#179]
I want to run some code when starting the julia repl, specifically this code:

    (setq comint-prompt-read-only t comint-prompt-regexp "julia> ")

but I can't figure out what hook to use for the inferior-julia-process so it doesn't affect any other repl, for example.

Is there a reason why the julia prompt is editable, or a bad idea to set it as read only?

**Comment by vspinu** [comment]
It's called `julia-post-run-hook`. 

Why do you need to modify `comint-prompt-regexp`? It's already correct.

Setting readonly prompt will prohibit you from deleting regions of text and cleaning the whole buffer. It's not worth the pain IMO.

**Comment by Xparx** [comment]
Thanks for your answer.
Yes you might be right. I'm just use to the behaviour from other repls.
And I'm not a star on regexp either it seems.

Sorry for the noise.
