### ISSUE TITLE
More thoughts on `ess-indent-from-lhs`

### ISSUE THREAD

**Issue by vspinu** [emacs-ess/ESS#184]
Right now there is a discontinuity:

```
vars_session <- quote(list(
                          ## SESSION DATA
                          sid = as.integer(as.factor(sessionId)),
                          browser = browser, 

vars_session <- quote_list(
    ## SESSION DATA
    sid = as.integer(as.factor(sessionId)),
    browser = browser, 
    
```

I wonder if we can consider nested calls like `foo(bar(baz(` as one monolithic call. 

@lionel-  what do you think?

**Comment by vspinu** [comment]
It actually has more to do with the setting of `ess-offset-arguments-newline`. This made me wonder if we really need `ess-offset-arguments-newline`. Can't we treat `foo(bar(baz` as a monolithic call and simply rely on `ess-indent-from-lhs` to do its job?

**Comment by lionel-** [comment]
hmm I think that would only make sense if `ess-offset-arguments-newline` set to `t` would yield
```r
{
    call1(call2(
        arg1,
        arg2
    )
}    
```

instead of
```r
{
    call1(call2(
              arg1,
              arg2
    )
}
```
Then, it's not really connected to `ess-indent-from-lhs` but to the default behaviour, or maybe a new setting to tweak the argument offsets set to `t`.

**Comment by lionel-** [comment]
I don't really see the connection with `ess-indent-from-lhs` though.

**Comment by lionel-** [comment]
We could have three levels of settings: `'(t)` would be the Rstudio style, then `t` would indent from the first function call when they are consecutively nested as in your example, and `'t` would indent from the innermost call.

**Comment by lionel-** [comment]
well, four levels with `nil` :)

**Comment by vspinu** [comment]
> hmm I think that would only make sense if ess-offset-arguments-newline set to t would yield

Right. And also there is a lhs distinction:

```
call0(results <- call1(call2(
    arg1,
    arg2)
## or
call0(results <- call1(call2(
          arg1,
          arg2)
```

But it's not a common case, so I guess we just go with the second.


> I don't really see the connection with ess-indent-from-lhs though.

I was thinking to allow only two cases:

``` 

## with ess-indent-from-lhs nil
results <- call1(call2(
               arg1,
               arg2))

## with ess-indent-from-lhs t
results <- call1(call2(
    arg1,
    arg2)
```

**Comment by vspinu** [comment]
> We could have three levels of settings: '(t) would be the Rstudio style, then t 

Or we can have one boolean var `ess-indent-treat-chain-calls-as-one`.

**Comment by lionel-** [comment]
I think it would look weird to have the two behaviours at the same time:
```r
call1(call2(
          arg1,
          arg2
)

results <- call1(call2(
    arg1,
    arg2
)
```
So it should probably be treated more generally than only for assignments.

> Or we can have one boolean var ess-indent-treat-chain-calls-as-one.

I'm feeling a bit uneasy with this kind of settings because they only apply in particular configurations. Here it would only apply for offsets set to `t` and ignored in all other cases. From this point of view a new offset type would be clearer. Though that's not a big issue and a new boolean switch is still reasonable.

**Comment by vspinu** [comment]
> So it should probably be treated more generally than only for assignments.

You are right indeed.

> I'm feeling a bit uneasy with this kind of settings because they only apply in particular configurations.

I feel the same about the `ess-indent-from-lhs` which applies only when offsets are set to `t`.

We can add yet another option `'t` but then we should add it to both `ess-offset-arguments` and `ess-offset-arguments-newline` for consistency.

I also don't like explicit quotes`'t` (I have just removed those from the code). I would prefer `((t))` `(t)`, t and nil. Or maybe we can name them with something natural names?

**Comment by lionel-** [comment]
> then we should add it to both ess-offset-arguments and ess-offset-arguments-newline for consistency.

yes that's what I had in mind, and the block offset too.

if we use natural names then we can't use a number instead of the symbol. Though I don't know that anyone will ever do that. Should we enforce consistent indentation size everywhere?

**Comment by vspinu** [comment]
> if we use natural names then we can't use a number instead of the symbol. Though I don't know that anyone will ever do that.

Right. That was the main reason to use `(.)` notation.  

> Should we enforce consistent indentation size everywhere?

Dropping numbers is not really an option. For one, you need `0` level at least and `CLB` style is using non-`ess-indent-offset` indent for `ess-offset-arguments-newline` and it's quite possible that users might prefer different levels in different situation.  I am also not sure we can find nice names for those settings. So let's stick with the current ways. Hopefully we won't need to add yet another "level" in the future.

**Comment by lionel-** [comment]
> I would prefer ((t)) (t), t and nil.

Than would it make sense to have `((t))` refer to the outermost call in case they are chained, `(t)` to the innermost call, `t`for the Rstudio style and `nil` for the opening paren? This has a certain logic to it.

**Comment by lionel-** [comment]
> This has a certain logic to it.

Or maybe `t` should be for opening paren and `nil` for previous indentation, to respect the progression with function calls.

**Comment by vspinu** [comment]
> Than would it make sense to have ((t)) refer to the outermost call in case they are chained, (t) to the innermost call, tfor the Rstudio style and nil for the opening paren? This has a certain logic to it.

I like this. It bring some sugestive meaning to the notation.

**Comment by vspinu** [comment]
BTW, the this is also an example of chained calls:

```
output <- data.table[, list(
                           var1 = stuf1, 
                           var2 = stuf2)]
```

**Comment by lionel-** [comment]
Thinking more about it, I think it would complicate the docstrings too much to add another offset type. So the boolean switch is probably best to keep things clear.

Another solution is to use parameters. According to our discussion we'd have `t` for Rstudio style and `(t)` for ESS style. Then we can add parameters: `(t indent-from-lhs group-chained-calls)`.

If we go this way it's probably best to encapsulate the Rstudio offset in parentheses as well so we can add parameters in the future if needed. Then: `((t))` for Rstudio and `(t)` for ESS?

**Comment by lionel-** [comment]
> so we can add parameters in the future if needed

and that would apply to indentation from opening paren as well, so: `(nil)` ?

**Comment by vspinu** [comment]
> Another solution is to use parameters. According to our discussion we'd have t for Rstudio style and (t) for ESS style. Then we can add parameters: (t indent-from-lhs group-chained-calls).
>  Then: ((t)) for Rstudio and (t) for ESS?
> and that would apply to indentation from opening paren as well, so: (nil) ?

All these to avoid another para in doc string? This is like building a parallel customization engine. It probably should be keyed: `(t :from-lhs t :chained-calls t)`. I prefer not to complicate things further. `indent-from-lhs` and `group-chained-calls` are global in nature and I don't think there is a real need to customize those on per indentation settings.  So let's just add one more boolean variable for chained calls and be done with it.
