### ISSUE TITLE
Distinguish different types of blocks for indentation? 

### ISSUE THREAD

**Issue by vspinu** [emacs-ess/ESS#190]
Currently we treat all blocks similarly. Particularly with `ess-offset-block` set to `(t)` we get:

```
r <- funcall(if (cond1)
    stuff1
else if (cond2)
    stuff2
else
    stuff3)
```

How big of a problem is this? Do we really need to differentiate different blocks? And if so, how?

**Comment by vspinu** [comment]
Some solutions:

1) introduce alignment variables and enumerate block types within each of them:

```elisp
(setq ess-indent-at-open-delim '(arg if-else ...)  
      ess-indent-at-prev-line '(arg-newline ...)
      ess-indent-at-prev-call '(decl-arg ...))

;or

(setq ess-indent-block '((open-delim . (arg if-else ...))
                         (prev-line . (arg-newline ...))
                         (prev-call . (decl-arg ...))))


```

2) One alist of indentation blocks. 

```elisp
(setq ess-indent-block '((arg . open-delim)
                         (if-else . open-delim)
                         (arg-newline . prev-line)
                         (decl-arg . prev-call)
                         ...))
```

3) Instead of a single `ess-offset-block` we can have `ess-offset-delim-block` for `{` and `(` blocks,  and `ess-offset-language-block` for all other stuff `(if, switch, when, for, etc)`. Then we can have `ess-indent-language-blocks` which can be something like `("if" "switch" "when" "for" "expression")`

**Comment by mmaechler** [comment]
I'm surprised.   Look at the e-lisp code above.   
Functional languages such as R should treat function arguments list differently than  "{ .... }" blocks.
Where indentation "to the left" is ok for the latter  it often looks very wrong to me... also in several
setMethod() examples I've seen in R (and package) R source code.

**Comment by vspinu** [comment]
> Functional languages such as R should treat function arguments list differently than "{ .... }" blocks.

I think we are doing it very differently. Most of the indentation custom variables deal directly or affect indentation of function call arguments. Indenting C like languages is tricky. Indenting lisp is trivial.

> for the latter it often looks very wrong to me

I aggree, but we need to tackle this problem comprehensively. One thing here will affect 10 other things.

> also in severa setMethod() examples I've seen in R (and package) R source code.

Please report. I am not aware of any problems. These things should be reported asap so that we can thinn about them and fix before the next release.

**Comment by lionel-** [comment]
I especially like your 3rd solution because it's consistent with how other settings work.

**Comment by vspinu** [comment]
> I especially like your 3rd solution because it's consistent with how other settings work.

Yes. It's my favorite as well.

**Comment by lionel-** [comment]
would function declarations be treated as language blocks?

Actually do we really need to split the setting into delim and language components? It would work well with only one setting `ess-offset-block` with supporting `ess-indent-align-blocks` I think.

**Comment by vspinu** [comment]
> would function declarations be treated as language blocks?

why should it be? It behaves like `{` block, right?

> Actually do we really need to split the setting into delim and language components? It would work well with only one setting ess-offset-block with supporting ess-indent-align-blocks I think.

`ess-indent-align-blocks` is a list of block names to align,  right? It might be simpler, but I am a bit worried about the semantics. `ess-indent-alighn-blocks` will overwrite the value of `ess-offset-block`, right? That's a bit intricate  Would it be simpler to have `ess-indent-blocks` set to a list `("{" "(")` and then `ess-offset-blocks` to apply only to those? 

The problem with all approaches is that ESS needs to know all possible blocks. So that you will need to list all blocks, like `ess-indent-known-blocks`.

**Comment by lionel-** [comment]
> why should it be? It behaves like { block, right?

but right now any block behaves like {

> That's a bit intricate

What I like about it is that we have other `ess-indent-align-` settings so overall I think that would make things simpler to understand because more consistent.

**Comment by vspinu** [comment]
> What I like about it is that we have other ess-indent-align- settings so overall I think that would make things simpler to understand because more consistent.

I see your point. It makes sense. What would we need to list in `ess-indent-align-blocks`? I think I overthought it a bit. Isn't the only problem is ifelse blocks? All others that I have listed are function calls or have `{` semantics. 

So instead of bothering with yet another varable which no one will use, shall we simply hardcode vertical alignment for if else blocks?

**Comment by lionel-** [comment]
I was thinking of allowing overrides for function declarations and if else blocks. The advantage of having a list is that it's extensible if needed. But I could live with a ifelse-specific setting, it'd be less work ;)

**Comment by vspinu** [comment]
> But I could live with a ifelse-specific setting, it'd be less work ;)

The question is, do you need such an override in the first place? 

> The advantage of having a list is that it's extensible if needed.

We can have `ess-indent-align-language-blocks` list to parallel `ess-indent-align-nested-calls`. But I really doubt that will ever be useful besides `else` and `if else`. Moreover, it need to be a regular expression to capture `if else` and `if     else` etc. So I am inclined to simply have a boolean `ess-indent-align-else-blocks`.

**Comment by lionel-** [comment]
> The question is, do you need such an override in the first place?

It'd be nice if we don't hardcode vertical alignment for rstudio compatibility.

> So I am inclined to simply have a boolean ess-indent-align-else-blocks

That sounds good to me.
