### ISSUE TITLE
Indent/Dedent failing for Julia

### ISSUE THREAD

**Issue by cstjean** [emacs-ess/ESS#191]
I had the issue described here:
http://lists.gnu.org/archive/html/emacs-orgmode/2010-05/msg00276.html
It was trivially fixed by adding (require 'cl) at the top of ess-julia.el and calling make -B. I'm not sure how to submit a pull request on github, could someone please fix it directly?

**Comment by mmaechler** [comment]
I did so: 86ae282e6c92944f33e0f74cf0654a5fc6150f5e
