### ISSUE TITLE
No indentation for dplyr chains beginning on the first line of a script

### ISSUE THREAD

**Issue by karawoo** [emacs-ess/ESS#192]
I was testing out some of the recent changes to indentation in ESS with a blank R script, and it appears that dplyr chains beginning on the first line of the script are not indented on the second line, but are indented in subsequent lines:

```r
iris %>%
filter(Species == "setosa") %>%
    select(Sepal.Width) %>%
    head
```

If I start the chain on the second line of the script or later, it behaves as I'd expect:

```r
iris %>%
    filter(Species == "setosa") %>%
    select(Sepal.Width) %>%
    head
```

ggplot calls with `+` seem to be indented normally regardless of where they start.

This isn't likely to affect many people's code since most people won't (and shouldn't) write their R scripts this way. But it did confuse me for a while and strikes me as odd behavior.

**Comment by lionel-** [comment]
thanks I'll look into it.
