### ISSUE TITLE
bidirectional ess-dialect

### ISSUE THREAD

**Issue by yitang** [emacs-ess/ESS#194]
Hi, quite often I found myself copying content (commands or results) from R console to the R script buffer. 

I wonder if we have a similar available *ess-dialect* but for R process buffer so that I could know which R script buffer associated to a R process buffer and simplify my workflow using something like `copy-line-or-region-to-R-bufer`? 

-Yi

**Comment by vspinu** [comment]
Nothing of that kind is available. Copy text, then `C-c C-z` and yank it. To have a separate command for this is an overkill.
