### ISSUE TITLE
Remove "enabling speedbar support" message

### ISSUE THREAD

**Issue by hoffman** [emacs-ess/ESS#197]
[ess-s-l.el](https://github.com/emacs-ess/ESS/blob/d090e1c2bb6b06c3ebb73fdecb72fc21b851a09f/lisp/ess-s-l.el#L867) produces an "enabling speedbar support" message. This extraneous notice along with others make it more likely users will ignore messages in general and miss something important.

Can this be removed?

**Comment by mmaechler** [comment]
I have never seen this message.  Maybe use the traditional  `M-x ess-submit-bug-report`  = the last entry of both ESS / iESS menus... to tell us the exact circumstance when you see it.
Yes, that would be e-mail instead of GH issue.

**Comment by vspinu** [comment]
@mmaechler the message is there as the OP link clearly indicates. I think OP is right, it's a bad style to throw trivial messages like this.

**Comment by hoffman** [comment]
This notice is only shown during byte-compilation or when the file is not byte compiled. It seems my installation of ESS from melpa-stable did not byte-compile, so this message shows up. If I run into that issue again I will investigate and report elsewhere.

Results of `ess-submit-bug-report`:

```
[ess-site.el]: ess-customize-alist=nil 
[ess-site.el _2_]: ess-customize-alist=nil 
(R): ess-r-versions-create making M-x defuns for 
 R-3.0.3-64bit


Emacs  : GNU Emacs 24.4.1 (i686-pc-mingw32)
 of 2014-10-24 on LEG570
Package: ess-mode 15.03 [elpa: 15.3]

current state:
==============
(setq
 ess-language nil
 ess-dialect nil
 ess-ask-for-ess-directory t
 ess-ask-about-transfile nil
 ess-directory nil
 ess-keep-dump-files "always"
 ess-source-directory "C:\\Users\\Michael\\AppData\\Local\\Temp"
 ess-use-ido t
 ess-use-eldoc t
 ess-use-tracebug t
 ess-use-auto-complete t
 ess-use-company t
 ess-eval-visibly-p t
 ess-can-eval-in-background nil
 ess-local-process-name nil
 )
```
