### ISSUE TITLE
Sas syntax highlighting doesn't recognize region starting with '*' ending with ';' as comment. 

### ISSUE THREAD

**Issue by groceryheist** [emacs-ess/ESS#198]
OS: Windows 7
ess: 15.03
emacs: 24.3.1

Pretty self explanatory, easy to reproduce and easy to fix.
I haven't done elisp development before otherwise I'd put together the fix. 
If somebody can make it easy for me by pointing me to the location of the bug I can take a stab at it. 
Thanks.

**Comment by rsparapa** [comment]
Works for me in 15.09
