### ISSUE TITLE
void function some

### ISSUE THREAD

**Issue by gongzhitaao** [emacs-ess/ESS#200]
In the following function in `ess-mode.el` starting from line 1188,

```emacs-lisp
(defun ess-climb-object ()
  (ess-save-excursion-when-nil
    (let (climbed)
      (skip-chars-backward " \t`")
      (while (some (apply-partially '/= 0)        ; <- void function some
                   `(,(skip-syntax-backward "w_")
                     ,(skip-chars-backward "`\"'")))
        (setq climbed t))
      climbed)))
```

I did not find any definition of `some`.  Everytime I try to indent R source code, this error pops up
`Debugger entered--Lisp error: (void-function some)`.

`ess-version`: `15.09-devel`
`emacs version`: `24.4.1`
`OS`: `Ubuntu 15.04`

**Comment by vspinu** [comment]
It's part of cl package.  I have no idea why it doesn't work for you. Try to require `cl-lib` explicitly.

**Comment by gongzhitaao** [comment]
It works!  I'm not sure why `cl` is not loaded automatically.  Thanks.  I think this could be closed.

**Comment by rmcgehee** [comment]
FYI: I just had this same issue trying to get latest ESS working on Cygwin's Emacs (24.5.1). 
requiring ```cl-lib``` did not work, but requiring ```cl``` did.

**Comment by vspinu** [comment]
That's strange. The cl is loaded in ess.el. Anyways. I am requiring cl directly in `ess-mode.el` to fix this.
