### ISSUE TITLE
ess-execute-screen-options failing in  emacs -nw

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#201]
When logging in remotely and for bandwidth reason, using  emacs -nw
the ESS startup now fails with
```
ess-execute-screen-options: X windows are not in use or not initialized
```
and then ESS only partly works (e.g. `.ess.help` is undefined).

If I use  'emacs -nw -f R'  on my own (Linux, gnome 3, ..) computer, the error message is even more cryptical
```
Wrong type argument: stringp, nil
```
and when looking in `*Messages*`, I see slightly more informatively
```
ess-execute-screen-options:Wrong type argument: stringp, nil
```
https://github.com/emacs-ess/ESS/blob/master/lisp/ess-inf.el#L2697  shows that we indeed do sophisticated things just to deal with scaled fonts... but indeed, in the 'emacs -nw' case, several of the functions we call do not work as expected, e.g.,
`(face-font 'default)`   returns  `nil`  instead of a string.

We really need to detect such "no window system" cases, and deal with them gracefully, probably in the (imperfect but robust) way we did this previously.

**Comment by eddelbuettel** [comment]
Interesting. I only start as `--daemon` and then connect.  Does this affect the subsequent text mode for `emacsclient`?
