### ISSUE TITLE
indentation: array(if(..) ... else if(.) ... else ...)    

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#204]
d9bd87a  is an example

**Comment by vspinu** [comment]
@lionel-,  I think you have fixed this in #195 with `ess-align-blocks` override. Am I confused or it started occuring  again?

```
r <- funcall(if (cond1)
    stuff1
else
    stuff2)
```

**Comment by lionel-** [comment]
hmm it seems I didn't take unbraced if-else blocks into consideration. I'll look into it.
