### ISSUE TITLE
Eval large chunks of R code asynchronously?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [emacs-ess/ESS#205]
When I eval a single line or block of R code, it sends it to the R buffer and then I can continue editing while it runs asynchronously. However, if I eval multiple lines, Emacs blocks until after it has submitted the final line or block. This could be easily solved by invisibly wrapping every multi-line eval in curly braces to make it all one block. As a bonus, this would also halt if one line encounters an error instead of blindly continuing to submit the subsequent lines of code.

**Comment by vspinu** [comment]
Have a look at `ess-eval-visibly` and set it to a different value. You can also do it from the menu. 

Wrapping code in blocks without having a full parser  is not an option. You might want to accumulate incomplete code blocks..
