### ISSUE TITLE
Cursor lags on large output in Julia's REPL 

### ISSUE THREAD

**Issue by dfdx** [emacs-ess/ESS#206]
Sometimes, when sending code from edit buffer to Julia's REPL buffer, cursor doesn't go to the end of the REPL buffer, but instead hangs somewhere in the middle. Here's a screencast demonstrating this issue (Dropbox's preview is quite poor, so better to download the file). 

   https://www.dropbox.com/s/q99tcp2xvy1tffp/broken_repl.mkv?dl=0

I use `ess-eval-line-and-step` to send code to Julia's REPL. I tried to manually go to the end of REPL buffer, i.e.: 

```
(ess-eval-line-and-step)
(with-current-buffer "*julia*"
    (end-of-buffer))
```

But even with this hack cursor sometimes stops in the middle of the output. My current guess is that ESS has some timeout to wait for output, but I couldn't find exact code/settings to change, hence this issue. 

Linux Mint 17.1 Cinnamon 64-bit
GNU Emacs 24.3.1
Latest ESS (commit 1ab8da41bc0f98869a7e198a5dc74b020da021b9)

**Comment by vspinu** [comment]
I have noticed this a couple of times with R, but not in a systematic fashion and a session restart usually helps. I think it's likely to be a comint thing. ess-julia's sending mechanism is very basic.

**Comment by jabranham** [comment]
This issue is ~3 years old and ESS has matured quite a bit. I don't see this in R so I'm closing this issue. Feel free to reopen if you still experience it.
