### ISSUE TITLE
`ess-align-continuations-in-calls` should contain `[`?

### ISSUE THREAD

**Issue by vspinu** [emacs-ess/ESS#207]
@lionel-, I think `ess-align-continuations-in-calls` should apply to `[` as well:

```
if(stuff1 &
   !stuff2

dt[stuff1 &
       !stuff2
```

Even more, wouldn't it be more consistent to align continuations in all calls like this:

```
funcall(stuff1 &
        !stuff2)
```

and use continuation in all other cases?

I don't recall discussing this option.

**Comment by lionel-** [comment]
hi @vspinu 

We discussed these issues in #189.

I think we concluded it's best to override the continuation indent for single-parameter calls. That's the case for `if()` and for `()`. Single brackets have multiple parameters so I didn't make an override for them. Though maybe I should have for double brackets?

Either way, we could override all multi-parameter calls if you want. We'd get code like this:
```r
object[stuff1 +
       stuff2, stuff3 +
               stuff4]
```

**Comment by vspinu** [comment]
> Single brackets have multiple parameters so I didn't make an override for them. Though maybe I should have for double brackets?

I see. This makes sense but my brain started getting confused on the difference between if and and `[` in data table. Given that logical subsetting in the second argument doesn't occur that often shall we treat the first argument only?

How about making `ess-align-continuations-in-calls` a list of regexps? Then we can add `[^ \t]+(` and `[^ \t]+\\[`` to that list in order to accommodate first argument of arbitrary calls and subsetting? 

> Either way, we could override all multi-parameter calls if you want.

I don't think that's worth the pain, especially given that in practice multiple multi-line logical subseting arguments almost never occur. So I would stick with this simple cognitive heuristic - immediately preceding `(` or `[` vertically align the logical expression.

**Comment by lionel-** [comment]
> Given that logical subsetting in the second argument doesn't occur that often shall we treat the first argument only?

That was initially the case but you asked to change it to the current behaviour IIRC ;-)

One of the problem is that the setting does not apply solely to logical operators but to all of them. So it may look weird if some operations are indented in the first arg but not the second one.

> How about making ess-align-continuations-in-calls a list of regexps?

I'd have to see if it's possible. I generally try to avoid regexes because they are slow.

How about we just allow `"["` and `"[["` in the list of overrides?

**Comment by vspinu** [comment]
> That was initially the case but you asked to change it to the current behaviour IIRC ;-)

Hm.  My current discomfort has overwriten my memory then:(  

>  the setting does not apply solely to logical operators but to all of them.

Yes. That's the problem. This is why we have the user config.

> How about we just allow "[" and "[[" in the list of overrides?

Will this work? Currently `(` doesn't trigger vertical alignment for all calls; only for stand alone `(`.

**Comment by lionel-** [comment]
> Will this work?

yes, `"("` is treated specially and so would be `"["`.

btw, if we wanted an override for all calls we could allow `t` instead of a list?

**Comment by vspinu** [comment]
> yes, "(" is treated specially and so would be "[".

Can we avoid having special handling? `if` is also treated specially. Shouldn't we just have `if(` substring instead?

`(` doesn't apply to calls.  So we either need something special like `*(` and `*[` to designate function calls or go with standard regexp. I don't think we should be much focused on speed right now. We are using so many `looking-at`s and `looking-back`s that two more places will not make a difference.

I think regexp solution flexible and will satisfy all needs. It will probably help removing all those special treatments form the code, or won't it?

**Comment by lionel-** [comment]
> if is also treated specially

No, the string`"if"` is matched against the call name.

> We are using so many looking-ats and looking-backs that two more places will not make a difference.

But simple `(looking-at)`s are very fast. I think it's a bit yucky to look for a big regex containing all desired cases versus simply comparing the call name to members of `ess-align-continuations-in-calls` as is currently the case.

Plus the current approach handles backquoted function calls which are hard to tackle properly with regexes (though it's true that it doesnt matter so much whether backticks are paired or not, which is the difficult part for a regex...).

**Comment by vspinu** [comment]
> No, the string"if" is matched against the call name.

Yes. That's exactly what I meant. For `(` you are looking at preceding stand-alone `(` for `if` you are looking at call before `(`.

>  think it's a bit yucky to look for a big regex containing all desired cases versus simply comparing the call name to members of ess-align-continuations-in-calls as is currently the case.


I proposed to have a list of simple regexps with uniform convention - if at the begining of the expression any of the regexp matches, we alighn vertically otherwise not. So you will get `if *(` for current `if`,  `[^ \t]*[[(]` for calls and subsettings.  No exception and special treatment and very flexible.

> Plus the current approach handles backquoted function 

We don't need to match backtickes. Some basic heuristics will work just fine.


If we keep the current approach, what would be your proposal more concretely? Note, that including `[` into the list will not work because you will have to treat it similarly to how you treat `(` (i.e. stand alone `(`) which doesn't make sense in R.

**Comment by lionel-** [comment]
> I proposed to have a list of simple regexps with uniform convention

ah yes, then it's perfectly reasonable. Then it's only a matter of what kind of interface we want to provide to users. I feel that a list of regexes does not fit the spirit of the new indentation settings.

> what would be your proposal more concretely?

Just allowing `"["` in the list. I don't think it would make the code much more complex.

> Note, that including [ into the list will not work because you will have to treat it similarly to how you treat ( (i.e. stand alone () which doesn't make sense in R.

Hmm I don't understand this. Function calls, bracket indexing and block wrapping (with `(` or `{`) are all distinctive syntax features of the R language. So they should be treated distinctively, whether we do it with regexes or in elisp.

Or do you mean that for heuristic reasons, if `[` applies to all object indexing no matter the attached name, the same should go for `(`, that is, it should refer to function calls rather than parenthesised blocks? Then we could have `"("` for function calls and `"()"` for parenthesised blocks. Or `"*["` and `"*("` for calls and indexing and `"("` for blocks.

But we'll go with a list of regexes if that's your preference.

**Comment by vspinu** [comment]
> Or do you mean that for heuristic reasons, if [ applies to all object indexing no matter the attached name, the same should go for (, that is, it should refer to function calls rather than parenthesised blocks? 

Yes. This is exactly what I meant. 

> But we'll go with a list of regexes if that's your preference.

Yes. Let's not re-invent the wheel. We will need to differentiate between calls and paren blocks anyways.  Inventing new symbolic notation like`*(`, `(`, `*[` is uniformly worse than using a list of standard regexp.

**Comment by lionel-** [comment]
> Inventing new symbolic notation like*(, (, *[ is uniformly worse than using a list of standard regexp.

You're right. If we had went this way, it'd have been better to mix strings for function names and elisp symbols for special syntax, i.e.
```lisp
(ess-align-continuations-in-calls . ("if" paren-block indexing))
```

Is this how you envision the regex list?
```lisp
(RRR
     (ess-indent-offset . 4)
     (ess-offset-arguments . open-delim)
     (ess-offset-arguments-newline . prev-call)
     (ess-offset-block . prev-line)
     (ess-offset-continued . straight)
     (ess-align-declaration-args . t)
     (ess-align-nested-calls . ("ifelse"))
     (ess-align-continuations-in-calls . ("[ \t]*(" "if[ \t]*(" "[^ \t]+[ \t]*\\["))
     (ess-align-blocks . (if-else))
     (ess-indent-prev-call-lhs . t)
     (ess-indent-prev-call-chains . t)
     (ess-indent-with-fancy-comments . t))
```
or should it be like this?
```lisp
(RRR
     (ess-indent-offset . 4)
     (ess-offset-arguments . open-delim)
     (ess-offset-arguments-newline . prev-call)
     (ess-offset-block . prev-line)
     (ess-offset-continued . straight)
     (ess-align-declaration-args . t)
     (ess-align-nested-calls . ("ifelse"))
     (ess-align-continuations-in-calls
       . ("[ \t]*(" "if[ \t]*(" "[^ \t]+[ \t]*\\["))
     (ess-align-blocks . (if-else))
     (ess-indent-prev-call-lhs . t)
     (ess-indent-prev-call-chains . t)
     (ess-indent-with-fancy-comments . t))
```

**Comment by lionel-** [comment]
on a related note, I was also wondering if we should generalise `ess-align-declaration-args` into `ess-align-args-in-calls` before the September release. This would allow users to enforce vertical alignment for any function calls they would choose, not only for function declarations.

I was thinking to match against function names but now it'd be more coherent to also have a list of regexes.

I'd prefer to avoid the extra work though so if you think that will not be useful that's just as well :)

**Comment by vspinu** [comment]
>    (ess-align-continuations-in-calls . ("[ \t]*(" "if[ \t]*(" "[^ \t]+[ \t]*\\["))

I think we can simplify the last one to `"[^ \t]+\\["`. No need to support bad formating. Keeping it on the same line is better IMO. 

> on a related note, I was also wondering if we should generalise ess-align-declaration-args into ess-align-args-in-calls before the September release. This would allow users to enforce vertical alignment for any function calls they would choose, not only for function declarations.

This is an interesting idea. I think it could be useful for various DSLs. It would make the whole system a bit more consistent. The name should be `ess-align-arguments-in-calls` to be consistent with other names.

> I'd prefer to avoid the extra work though so if you think that will not be useful that's just as well :)

That's for you to decide. If you can implement that, it would be great of course. But if you don't have time, don't bother. You did much more work than anyone would ever had hoped for :)
