### ISSUE TITLE
Emacs Unable to Init

### ISSUE THREAD

**Issue by ArthurZ** [emacs-ess/ESS#208]
Followed the instructions to enable support for Julia in Emacs. However when I launch Emacs I get an error upon M-x julia 
![starterror](https://cloud.githubusercontent.com/assets/701808/9148951/12882ba6-3d60-11e5-98f8-76f46c22ca7a.png)
if I source ess-site.el directly 
emacs -q -l /home/arthur/Julia/ESS/lisp/ess-site.el
I get error
![juliasupportinemacserror](https://cloud.githubusercontent.com/assets/701808/9148953/2a3f6264-3d60-11e5-8dd8-c85f0d51ee41.png)

**Comment by vspinu** [comment]
> Followed the instructions to enable support for Julia in Emacs. However when I launch Emacs I get an error upon M-x julia 

I think you are using an ancient ESS  Julia removed `julia-basic` executable for 1-2 years now. See what 
`inferior-julia-program-name` says. It should say `julia` and if it could not be found on your path you have to set that variable to point to your path.  Make sure you are using most recent ESS anyways.

> if I source ess-site.el directly 

This works for me on a similar linux setup as yours.
