### ISSUE TITLE
Tidy up indentation styles

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#217]
The next ESS version will feature a major redesign of the indentation engine and settings and I think we should take this opportunity to simplify the default styles. They are currently a bit messy because:

- most of the styles are quite similar;
- the names of the styles now seem a bit arbitrary. It is not clear why the C++ or GNU styles are called like that for example.

I think we could narrow them down to 3 styles:

- RRR, which could be renamed to ESS
- RStudio, which would provide compatibility with a major editor
- A "hanging" style. Basically the RRR settings with `ess-offset-block` set to `open-delim`. Compared to RRR, this style would not try to save horizontal space. E.g.:

```r
# Instead of
object <- lapply(object, function(x) {
    body
},
argument)

# The "hanging" or "stretched" style would yield
object <- lapply(object, function(x) {
                             body
                         },
                 argument)
```

The documentation could provide the deprecated styles as a reference for users who were relying on them.

**Comment by vspinu** [comment]
@lionel-  I like the idea and I think we should it now before the release or never. 

The only difference between different non R-studio syles is the main indent-offset (am I right?). This clearly doesn't warrant keeping all those styles. It's simply confusing. User's can customize their main offset if they want. That's much simpler than looking through the styles and figuring out the differences.

If we go this path then DEFAULT should finally be the "default" and should match ESS style which is the recommended style by ESS.  (This is too important to be decided between two of us; ccing @ess-core).

**Comment by mmaechler** [comment]
I like the proposal to add an Rstudio style.
But removing old "loved" styles - that have existed for a very long time is not feasible, at least not in one step IMO:   Quite a few ESS users set the current styles and do so even in different ways, e.g. I have some *file variable* settings for style in some *.R files which are from a collaborative project where the individuals have their own (different!) indentation preferences, but they use a common well defined style for working on these *.R files.

Others set ess-style in their ~/.emacs equivalent and don't want those to stop working.
In particular,   `RRR` is even mentioned in the R manuals ...

This is a typical use case where  back compatibility is important if even to few users.

**Comment by vspinu** [comment]
> But removing old "loved" styles - that have existed for a very long time is not feasible, at least not in one step IMO: 

Indeed. We need a fall back mechanism for styles. How about  having a `ess-obsoleted-styles-alist` which we check when applying a style?

**Comment by ess-core** [comment]
I agree.  Old styles must be retained.

**Comment by ess-core** [comment]
what is the point of that?  we already have a list of styles.  why change
its name?

**Comment by vspinu** [comment]
> what is the point of that? we already have a list of styles. why change its name?

`ess-styles-alist` will be reserved for fewer, simpler styles with more suggestive names.

**Comment by lionel-** [comment]
> ess-styles-alist will be reserved for fewer, simpler styles with more suggestive names.

I agree this would be the way to go. It would make it much easier for users to navigate through the settings.

We could keep the old styles in the deprecated list for a release or two, then start issuing warnings with reference to a documentation item explaining how to move them to personal config files.


> I have some file variable settings for style in some *.R files which are from a collaborative project

If we end up removing old styles some times later, it will be easy to adjust these files. For example the only difference between RRR and C++ right now is that `ess-offset-block` is set to `prev-line` in the former and `prev-call` in the latter. That's only one or two lines to change in the file-local config.


> In particular, RRR is even mentioned in the R manuals ...

Yes it may be unnecessary to rename RRR to ESS. I think it would be nice because it would help give some personality to ESS, but it would be just fine to keep it as RRR.

**Comment by mmaechler** [comment]
What about the current  `DEFAULT` style ... (indentation by 2 instead of 4, among other differences to RRR or C++).  One would assume that the new default remained as much as possible back compatible.
What would its name be?  I'd definitely want to explicitly require it in a file-local variable (for collaboration purposes, see above), so for that file all collaborators use "DEFAULT" where otherwise each my have her own tweaked style (and I will have `RRR`)

**Comment by vspinu** [comment]
Yeh. Having the DEFAULT being the "default" would mean either changing it or adopting it. No way we can keep backward compatibility on this one unless we leave it as it is (aka picking the default values from globals). 

As to collaboration, R-Studio style should do the job in virtually all cases.

**Comment by vspinu** [comment]
I would say let's go for it, but let's leave the semantics of DEFAULT as it is. By default the DEFAULT is exactly as ESS style but with main offset 2 instead of 4.  So only 3 styles: DEFAULT, ESS and R-Studio. 

I am not sure about the "hanging" style. More concretely the name. Can we find a more suggestive name? "stretched" is better IMO. Given that it's so similar to ESS style we should probably prefix it with ESS. Like `ESS-stretched` or maybe `ESS-open-delim`?

**Comment by mmaechler** [comment]
Hmm.. as I said above,  `RRR` has been in the R manuals for many years...  and honestly I don't see the gain of **not** keeping the old list.  We can still say that some styles are recommended... but other pre-defined styles - as combinations of individual tweaks are nice... *and* cheap.  
Even more we could allow users to *add* to the list of names styles themselves.
This is very close to "skins" or "themes" for GUIs... where a few a predefined and come with the application and more themes can be downloaded and installed by users who have different tastes and offer their choices to other users.

So rather make the styles extendible than collapse them to very few.

**Comment by vspinu** [comment]
Ok. I agree that, given the backward compatibility constrains, the benefit is marginal. Let's stick to the status quo then.
