### ISSUE TITLE
Syntax highlighting seems broken in .Rnw files

### ISSUE THREAD

**Issue by cmmp** [emacs-ess/ESS#22]
Hi,

I posted what I think is a bug to ESS-help but got no replies, so I'm posting it here in the hopes a developer sees it.

The problem I'm having is the following:

I'm using a combination of emacs + ESS + Auctex + knitr to edit .Rnw files.
It's working fairly well with the addition of a small function to call
my makefile and generate the final pdf.

A problem I'm encountering is with the syntax highlighting. I think
it's connected to the parsing of the latex input.

Here's an example:

``` tex
\documentclass[a4paper]{article}

\begin{document}

\title{test}

\maketitle

<<chunk1>>=
a = list(x = 1, y = 2)
b = a$x
@

this is the test continued...

\end{document}
```

After the @ everything gets the same color. I think the parser is
getting confused because it expects another dollar sign after a$x, but
that's not latex math notation, it's an R command to select an item
from a list.

You can actually see that the Github highlighter has the same problem, but it's not supposed to know about weaving.

Here's the relevant portion of my .emacs and my package versions:

```
(require 'ess-site)
(ess-toggle-underscore nil) ; desabilite <- no modo ESS.
(setq inferior-R-args "--no-save --no-restore-data") ; dont restore workspace
(setq TeX-PDF-mode t) ; use pdflatex
(load "auctex.el" nil t t)
(load "preview-latex.el" nil t t)
(setq ess-ask-for-ess-directory nil) ;otherwise you are prompted each
time you start an interactive R session
```

Software versions:
emacs 24.1-2
emacs-ess 12.04.4-1
auctex 11.86-3

Any ideas how to solve this?

Thanks,
Cássio

**Comment by jtbates** [comment]
I have the same syntax highlighting issue now with the current version.  Are others experiencing this regression?


package | version
---|---
emacs | 24.4
auctex | 11.89
ess | 20151126.59

**Comment by zhangpj** [comment]
Same issue here.

**Comment by petersaly** [comment]
Hi Everyone,
Although the topic was closed years ago, I have had the same issue with Emacs 26.3 and ESS 18.10.2.
Any suggestion appreciated.
Thanks

**Comment by lionel-** [comment]
Hi @petersaly. Unfortunately noweb is no longer supported and has been removed from ESS. This mode caused long reaching side effects in the Emacs session, causing hard-to-debug issues for unrelated Emacs packages.
