### ISSUE TITLE
Hook functionality from devtools package on ess-dev map  

### ISSUE THREAD

**Issue by vspinu** [emacs-ess/ESS#229]
This is a low hanging fruit.

**Comment by Momus** [comment]
What would also be useful is if running devtools::test() this way didn't add it to the .Rhistory file, since I don't think R has anything resembling Bash's HISTCONTROL
Thanks!

**Comment by jabranham** [comment]
I'm guessing this was fixed and we forgot to close the issue. devtools stuff is in `ess-r-package-dev-map` now.

I'm closing, feel free to reopen if I misunderstood.
