### ISSUE TITLE
correctly find beginning-of-function  (M-C-a)

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#230]
7bfcbbda4146e7375a48c4e1fba3582784c49b8f added an example.

Local functions -- good R programmers use often -- are one case that often break finding the beginning of a function definition.

For changes, care should be taken such that most   

``` r
setMethod(....., ...,  function(...) { 

   lines ....
   lines ....

   lines ....
   lines ....

 })
```

keep working, and this _includes_ for instance

`setAs(.....)`

`setReplaceMethod(...)`

**Comment by vspinu** [comment]
Some clarification.

With 

```
setMethod(
    
    AAA,
    
    function(...) { 

        BBB
        
        inner <- function(...){

            CCC
        }

        DDD
    })

```

`C-M-a` works only from `CCC` position but not from `AAA`, `BBB` and `DDD`.

Also, starting from `CCC` the cursor gets to the start of `inner` function and stays there on subsequent invocations of `C-M-a`. This is also a bug.

**Comment by lionel-** [comment]
See also #251

**Comment by lionel-** [comment]
I said in the other thread that

> to finish the nomenclature, defuns is as general as blocks but includes in addition the innermost enclosing call and the LHS in case those exist.

But should it be the outermost enclosing call instead? Maybe it should be the outermost call, but stop when we find an LHS on the way.

So the entire following snippet would be a defun:
```r
object <- outer_call(argument,
                     inner_call(function(arg) {
                         body
                     }))

```
But in this one,
```r
object1 <- outer_call(argument,
                      param = object2 <- inner_call(function(arg) {
                          body
                      }))
```
the defun would be:
```r
object2 <- inner_call(function(arg) {
    body
})
```

**Comment by vspinu** [comment]
> But should it be the outermost enclosing call instead? Maybe it should be the outermost call, but stop when we find an LHS on the way.

I thin this behavior makes sense for navigation but not for evaluation. It's common to have helper inner function and I never want to evaluate those.

**Comment by lionel-** [comment]
Vitalie, note that this issue is separate from whether we evaluate the outermost defun or the innermost. For this, we agreed on having a setting.

Instead, this issue is about the definition of a defun in itself.

**Comment by jabranham** [comment]
Closing this with the recent work on this end, feel free to open new issues (also, the example you added @mmaechler  works now)
