### ISSUE TITLE
Empty lines interfere with indentation

### ISSUE THREAD

**Issue by vspinu** [emacs-ess/ESS#232]
@lionel- I think the following is a new bug:

```

setMethod("bla", 
          function(xx) {

            if(check1) some <- other
bla
```

The problem seems to be in the empty line after `{`

**Comment by lionel-** [comment]
Here you go

**Comment by vspinu** [comment]
This one seems not to be fully fixed:

```R

setMethod("calcPredictionAccuracy",
          function(x, data, byUser=FALSE, ...) {
              
              if(byUser) fun <- rowMeans
            else fun <- mean
          })
```

**Comment by lionel-** [comment]
I don't think we'll find all of them for the release ;)

**Comment by vspinu** [comment]
I have just found another one.

Is it possible that the code is not generic enough? If it treats each such case separately we will keep finding similar bugs.

**Comment by lionel-** [comment]
I'm trying to make it generic, but at the same time a C-style syntax is complex so the generic solution can't be simple :/

**Comment by lionel-** [comment]
maybe we should have been stricter with the kind of indentation we allow for if-else blocks (i.e. not allow rstudio style).
