### ISSUE TITLE
R support for lambda.r function declarations

### ISSUE THREAD

**Issue by vixr** [emacs-ess/ESS#233]
R functions can be defined in an alternative way using lambda.r

foo(a, b) %as% {
...
}

Sometimes also with a %when% clause.

There are several advantages to lambda.r including type signatures and pattern matching. It would be useful for ess to recognize these patterns as R functions.

**Comment by eddelbuettel** [comment]
:-1: 

Not a fan of pipes and even less so of other random extensions. The ESS developers work _really hard_ to make the existing language and Emacs cooperate peacefully and productively.  I see the above as a distraction.  But then I don't contribute code here so my vote doesn't really count ...

**Comment by vixr** [comment]
I'm curious what the issue with pipes is, they seem like a flexible way of expressing otherwise messy data transformations.

At any rate, I don't see how pipes are relevant - lambda.r is meant to support some semblance of type checking, pattern matching, and other functional idioms. 

I'll admit that the lambda.r package may not that mainstream, so not supporting language extensions is a legitimate critique. On the lambda.r tokens such as %as%, %::%, %when% seem fairly unique.

**Comment by eddelbuettel** [comment]
Fair point re tokens.  My view on pipes is somewhat personal, but their admiration is not quite as widespread as some corners of the the interwebs may suggest.

**Comment by mmaechler** [comment]
I also strongly prefer functional syntax.   And our indentation defaults should primarily do the correct things for functional programming style.
Yes, pipes can be nice for "displaying" a data analysis.  But when you develop the analysis, you shold work with intermediate results, plot them, str() them, etc.... so the pipe is not even natural there.
I see this as a fashion... Of course it will remain.. but I don't believe it will become very wide spread in the long run.   Data analysis is very interactive, very much about looking at intermediate results, and not about one direct long (piped) process from beginning to end.

**Comment by vspinu** [comment]
I have looked at lambda.r and it's interesting idea but it will unlikely ever become mainstream. The complication with yet another layer of types developed mostly for the pattern matching will just scary most of users away (as if we don't already have enough class systems in R).  I see `lambda.r` as an experimental/didactical package.

That being said, we should defenitely support block constructs like `(...) %blah% { ...}`. It's also the case for `foreach` package which has `(...) %dopar$ { ..}` constructs among similar others.

**Comment by lionel-** [comment]
> Data analysis is very interactive, very much about looking at intermediate results, and not about one direct long (piped) process from beginning to end.

This is a misconception on how pipes should be used. A good pipeline is like prose, it has paragraphs. Having some well named intermediate results is helpful to understand the code. The major problem for programming with pipes is that it messes with the tracebacks.

**Comment by vixr** [comment]
Needing to inspect state on the fly should be doable, but right now it seems like too much of a crutch for poor design decisions / recommendations - like imperative programming style for scripts, bits of intermediate state littering the environment/risking incoherency and dynamic typing. I think one of the weaknesses of R is that it's too tailored to interactivity, leading to bad design decisions (e.g. switching types of a piece of data out from under you in a data dependent way). 

The future of productivity is going to be workflows where you can see/reason about data flow state rapidly but also build out a production pipeline as fast as we build one-off scripts and prototypes now. That's going to require better tech such as more functional styles and better type systems (probably leveraging type deduction).

I somewhat disagree about not being able to check state with pipes - at least in dplyr you can always inject a do block and check the intermediate state if you'd like.

Anyway, for the purposes of this issue, pipes is neither here nor there, since lambda.r and its function declaration syntax don't have anything to do with pipes...

**Comment by vspinu** [comment]
This one should be tackled jointly with #230 btw.

**Comment by lionel-** [comment]
hmm... we can introduce a variable `ess-beginning-of-function-function` that you can set to a function of your own. Then when `ess-beginning-of-function` is called, we try it first, and when it returns nil we fall back on the normal function.

That way @vixr will be able to write a lambda.r function finder.

**Comment by vspinu** [comment]
There is `beginning-of-defun-function` which does just that. We should try to rely on it for our evaluation code. 

But as I said before, I think we need to support pattern `foo(a = , b = ) %blah% { }` more generally. That should automatically include `foreach`, `lambda.r` and`magnitr'/`dplyr` pipe stacks. I think it's convenient to be able to navigate with `C-M-a`/`C-M-e` to beg/end of such expressions. Also  evaluation of sub-expressions of such constructs doesn't make sense,  so you cannot go wrong with supporting block evaluation of those.

**Comment by lionel-** [comment]
I don't think we should conflate function definition regions with continuations regions.

There is #51 and #52 that request more general block regions and "thing at point" region, which are more relevant to continuations.

**Comment by vspinu** [comment]
> I don't think we should conflate function definition regions with continuations regions.

I wasn't suggesting that. I was saying that beggining of the pipe should be considered as beginning of the defun, not just any pipe.

> There is #51 and #52 that request more general block regions and "thing at point" region

Indeed. All of these should be fixed simultaneously.

**Comment by lionel-** [comment]
but strictly speaking there is no defun here, we don't have a `function()` call involved. That's why I don't like too much the idea of having `(ess-beginning-of-function)` doing something here, at least by default.

**Comment by vspinu** [comment]
>> On Tue, Sep 15 2015 07:40, Lionel Henry wrote:

> but strictly speaking there is no defun here, we don't have a `function()` call
> involved. That's why I don't like too much the idea of having
> `(ess-beginning-of-function)` doing something here, at least by default.

Well, that's rather standard. There is no a notion of beginning of "block" in
emacs, so modes abuse "defun" for blocks. elisp mode is also very relaxed, it
finds the outermost paranthesis.

We are already handling (or at least supposed to handle) setClass, setGeneric
setMethod which are also not strictly speaking "functions".

**Comment by lionel-** [comment]
> We are already handling (or at least supposed to handle) setClass, setGeneric setMethod which are also not strictly speaking "functions".

But they contain a function and I think can be viewed as function definitions.

> There is no a notion of beginning of "block" in emacs, so modes abuse "defun" for blocks

ah I wasn't aware of that. So in the end it's a matter of what kind of interface we want to provide: conflating functions and blocks or offering more fine-grained methods. I think the latter is the best way as I don't think the former is consistent even if widespread. When I want to eval a function I don't want it to eval the innermost block or even the outermost. It's better to use another method for that.

**Comment by jabranham** [comment]
Closing this, things have changed since ~2015.
