### ISSUE TITLE
company mode does not work with ESS/R for user-defined variables

### ISSUE THREAD

**Issue by YulongNiu** [emacs-ess/ESS#235]
Initially, I found this problem when I was using [Spacemacs](https://github.com/syl20bnr/spacemacs/). It was repeated with a clean Emacs containing only `ess` and `company` packages.

I added more details including an example in syl20bnr/spacemacs#2988.

**Comment by vspinu** [comment]
As I explained on the spacemacs issue list. This is expected. Please reopen if you think something should be done on ESS side.

**Comment by fikovnik** [comment]
Likely this is not ESS issue, but I was wondering if anyone knows how to configure company so the `company-dabbrev` or `company-dabbrev-code` kicks in as well.
This would be really useful for local variables.
