### ISSUE TITLE
Infloop in the indentation of a corner case of ^L in the beginning of the file

### ISSUE THREAD

**Issue by vspinu** [emacs-ess/ESS#236]
This might be something low level.  

Copy the following into a new R file. Note that the first character is "^L", emacs standard page delimiter. Github doesn't show it, so you will need to get into editing mode of my post (top right) and then copy paste from the markdown view. 

```

fun <- function(){
}
```
When done, indent. The indentation engine infloops.

**Comment by lionel-** [comment]
thanks, I fixed the bug and added a check for infloops.
