### ISSUE TITLE
indentation of nested if else 

### ISSUE THREAD

**Issue by vspinu** [emacs-ess/ESS#237]
Another one in the same line

```R

function(bla){
    if(some)
        if(other) stuff1
        else stuff2
        else
```

**Comment by vspinu** [comment]
Does the engine keep breaking? This probably work before. 

 Do you think it's  the time to add our tests to travis?

**Comment by lionel-** [comment]
no this was never handled before. I regenerate the tests each time I modify the code but travis wouldn't hurt.

**Comment by lionel-** [comment]
hmm actually my last commit may have broken this. This wasn't in the test set so that wasn't caught.

**Comment by lionel-** [comment]
Fixed, hopefully in generality.

```r
## 22
if (cond1)
    if (cond2)
        if (cond3)
            stuff1
        else if (cond4)
            stuff2
        else
            if (cond5)
                stuff3
        else
            stuff4
    else if (cond4)
        stuff3
    else
        if (cond5)
            stuff5
    else
        stuff6
else if (cond6)
    stuff7
else
    if (cond7)
        stuff8
```

**Comment by mmaechler** [comment]
Thank you Lionel.   Yes, we have had cases missing in our tests indeed...

Let's hope we --- and some other volunteering testers --- will catch all the bad cases before release.
I will be vacationing ~10 days from Sep.25 ...so if we want a "correct" 15.09 release it should happen in not much more than a week.

**Comment by vspinu** [comment]
> "correct" 15.09 release it should happen in not much more than a week.

Sure. Let's aim for the beggining of next week then. We can always have a patch release 15.09-1 if needed.

**Comment by vspinu** [comment]
@lionel- , not fully fixed unfortunately

```
ddd <- if(test)
    do_this
       else
           do_that
```

**Comment by lionel-** [comment]
can we make braceless if branches illegal? ;)

**Comment by vspinu** [comment]
:) Ask Martin for that. He should have some strings to pull.
