### ISSUE TITLE
is debian dependency on R really necessary?

### ISSUE THREAD

**Issue by kingaa** [emacs-ess/ESS#242]
On the ubuntu network of workstations I administer, I maintain multiple versions of R to faciliate package testing.  These are typically compiled from source and I avoid the debian R packages as redundant.  I was mildly disappointed to find that sometime between ubuntu 12.04 and 14.04, ess gained r-base-core as a dependency.  My question is whether this is actually necessary.

**Comment by eddelbuettel** [comment]
For packages to work within the distro, yes.   It is your usage that is (for your own reasons) non-standard.  You can trivially satisfy the Depends: via a mock package (there is even a tool for that, but the name escapes me) or just install ess locally.

(And for what it is worth the maintainer of the r-base and ess packages is the same person, ie me.)

**Comment by kingaa** [comment]
Thanks for the fast response, Dirk.  I appreciate your taking the time to
explain it.  I'll look into the mock package option.  Thanks again!

On Sat, Sep 19, 2015 at 12:08 PM, Dirk Eddelbuettel <
notifications@github.com> wrote:

> For packages to work within the distro, yes. It is your usage that is (for
> your own reasons) non-standard. You can trivially satisfy the Depends: via
> a mock package (there is even a tool for that, but the name escapes me) or
> just install ess locally.
>
> (And for what it is worth the maintainer of the r-base and ess packages is
> the same person, ie me.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emacs-ess/ESS/issues/242#issuecomment-141683928>.
>



-- 
Aaron A. King, Ph.D.
Ecology & Evolutionary Biology
Mathematics
Center for the Study of Complex Systems
University of Michigan
GPG Public Key: 0x15780975

**Comment by eddelbuettel** [comment]
I'd just circumvent it.  Just install r-base-core --- and the have other versions around maybe simply by prepending / altering the path. It is what I do here (albeit with only r-devel, good enough for me) and it is what we do with the [Rocker](https://github.com/rocker-org/) images for Docker.  There is no issue.  

Feel free to come over to [r-sig-debian](https://stat.ethz.ch/mailman/listinfo/r-sig-debian) if you have questions on tricks, best practices, ... for Debian/Ubuntu deployment, builds, ... of R.

**Comment by mmaechler** [comment]
I think @eddelbuettel  made clear that this is not an issue with ESS development directly, but rather a discussion about debian dependencies which we rather leave to the Debian maintainers -- with big THANK YOU, notably to @eddelbuettel  ! ---   and hence close this here.
