### ISSUE TITLE
Invalid function: ess-save-excursion-when-nil

### ISSUE THREAD

**Issue by fmichonneau** [emacs-ess/ESS#244]
With ess-version: 15.09-beta [elpa: 20150921.336], when trying to indent code, I get the following error message `Invalid function: ess-save-excursion-when-nil`

**Comment by vspinu** [comment]
This is a macro. Something went wrong with the re-compilation. Manually deleting the package directory from ELPA dir and re-installing should help.

**Comment by fmichonneau** [comment]
Thanks @vspinu that did the trick!
