### ISSUE TITLE
Roxygen advice of newline-and-indent is bad

### ISSUE THREAD

**Issue by vspinu** [emacs-ess/ESS#252]
The behavior of RET in roxygen blocks almost never does what I expect. It's non a standard behaviro across emacs and is inconsistent even within ESS. 

I would propose to modify `indent-new-comment-line` instead (bound to M-j by default). M-j is intended to insert comments across emacs, RET is not. The fact that we insert `#` for Roxygen blocks but  not in normal comments makes it even worse.

So the proposal is to move the advice from `newline-and-indent` to `indent-new-comment-line`.

**Comment by lionel-** [comment]
> The behavior of RET in roxygen blocks almost never does what I expect.

What are the use cases where it's better to avoid the roxy prefix on a newline? In my case it almost never happens that I'm in a roxy field and want a newline not to insert the roxy prefix. I could probably live with `M-j` but it'd feel like a regression.

Though I'm sensitive to the argument of standardisation, and it seems like doxygen blocks in c++ are handled with M-j as well for example. And as you said in another post, it's better to avoid advices if we can.

**Comment by lionel-** [comment]
About avoiding advices, I see in cc-mode.el that they use `(substitute-key-definition)` instead of advising functions:
```lisp
  (substitute-key-definition 'indent-new-comment-line
			     'c-indent-new-comment-line
			     c-mode-base-map global-map)
```
We probably should do the same.

**Comment by vspinu** [comment]
> What are the use cases where it's better to avoid the roxy prefix on a newline? 

I commonly have one line `##' @export` doc  after which I expect RET to trigger a new line like it does everywhere else.   I am also used to M-j, so for me it's a double frustration when M-j inserts `#` instead of `#'`.

I am generally oppossing contextual behavior of this sort. It makes your brain deal with "if ... else if ... else .." constructs each time you perform an action. In this case it's RET which is just too low level to be messed with.

> We probably should do the same.

Yes indeed.

**Comment by lionel-** [comment]
> I commonly have one line ##' @export doc after which I expect RET to trigger a new line

So that's for the very last line. In all other cases it does the right thing. That's why I like the current behaviour, it's less expensive for me to erase the whole line when I want to switch to actual R code.

Plus, it's much more common for me to edit existing documentation than to write a new one. And when I do, usually the R function is already there so I never have the problem you describe.

> I am generally oppossing contextual behavior of this sort

I am generally in favour of contextual behaviour :)

I guess it really depends how well you handle context switches. I think this is a typical case where it makes sense to have Emacs adapt to the user, so we should make this optional.

**Comment by lionel-** [comment]
@vspinu @mmaechler 

I have a branch ready which uses key substitution instead of advices, makes M-j behave correctly in roxy fields, and makes insertion of roxy prefix on newlines optional.

Do we want this for the next patch-release or should I wait before pushing it?

**Comment by vspinu** [comment]
Thanks Lionel. I don't mind the behavior of RET that much anymore as long as M-j works as expected. I think you have a point there as most of the time auto insertion of roxy comments makes sense on RET. So as far as I am concerned, this optional behavior might be the default as it is now.

I think this should be pushed before the new release. It's quite an improvement.

**Comment by lionel-** [comment]
here it is. Please test that nothing is broken by removing that advice :)
