### ISSUE TITLE
How to extend the test framework

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#257]
I've been thinking about how to introduce a comprehensive testing framework for ESS. My experience with indentation tests has been very positive and I think we should try working with .R files if possible. Text files have the huge advantage that they make it very easy to write a new test, and any regression is directly picked up by the VCS. Diffing the test file then explicitly and visually exposes what went wrong.

This was easy to set up for indentation because we have only one command (indent the test file) and one kind of output (the indented file). For other tests, we need to:

* specify initial conditions (initial text and point position inside that text)
* specify the test in elisp
* record final conditions (changed text, point position, mark boundaries)

So what I propose is to have two files, one input and one output. The `input.R` file would contain
* named or numbered chunks.
* possibly the code to test (commented out). But that could also go in another elisp file
* The text to operate on. The point position would be marked with some kind of cursor.

For example:

```r
### 1

## (ess-end-of-defun)

##--->
object1 <- function(argument1) {
  object2 <- fun_call(argument2, function(argument3) {
    body<POINT>
  })
}
##<---


### 2

## (ess-end-of-defun)

##--->
object1 <- <POINT>function(argument1) {
  object2 <- fun_call(argument2, function(argument3) {
    body
  })
}
##<---
```

Then the tests would be run as follows:
* scan for a chunk, record the elisp test code and the R code to test
* paste the chunk into a temporary buffer
* go to `<POINT>` and remove it
* execute the test code

Once the test is done, we record final conditions:
* write `<POINT>` where point ended up
* write `<MARK_BEG>` and `<MARK_END>`
* append the output chunk to `output.R`.

This would make it very easy to write new tests and check that no regression occurred.

**Comment by lionel-** [comment]
hmm. On second thought it'd be better to have one file and have the output written right below the input in each chunk. This way we can easily compare input and output. Users could parse the tests to see what a function does etc.

**Comment by vspinu** [comment]
I don't quite understand why do we need a special markup for this Why not use elisp + ert directly?

We can have helper test macros `(ess-with-test-action string-with-point :mark-start foo :mark-end bar &rest body)` where `:mark-start` `:mark-end` are final expected region location if region is active. `body` is optional set of expressions that can contain additional  `ert` assertions.

**Comment by lionel-** [comment]
The reasons are:

* having a visual report of regressions goes a long way to quickly understand what went wrong.
* writing initial conditions and expected output in R code directly is much easier then using ert.

It's not just about the marks, it's also about changes in code layout. Think of the new refilling feature. It should be as easy to write such tests as it is to write indentation tests.

And when we make a mistake with a function in ess-r-syntax.el and all hell breaks loose, it'd be good to  quickly see what's going on. A git diff allows to see many regressions at the same time, from which we can infer the likely cause. We don't have to start deciphering failures of expectation with mark positions etc one at a time.

**Comment by lionel-** [comment]
> A git diff allows to see many regressions at the same time

That's why I never used `run-tests` while working on indentation. I always regenerated the test files to diff them.

**Comment by vspinu** [comment]
> It's not just about the marks, it's also about changes in code layout. Think of the new refilling feature. It should be as easy to write such tests as it is to write indentation tests.

What are other use cases for this except indentation?

> That's why I never used run-tests while working on indentation

How about `M-x ert t RET`? It should point to the exact location and `deftest` which you can `edebug`.

I am not sure it's worth re-inventing the wheel. I am just afraid we will get into writing our own test suit for this. I would first try to achieve this with standard mechanism and if it's not enough expand on it later.

**Comment by lionel-** [comment]
> What are other use cases for this except indentation?

I'd like to implement other code manipulation tools in the future. Moving arguments in a call, swapping if-else branches, maybe some slurping and barfing. We now have the infrastructure for that.

But basically all editing and navigation operations would benefit from this approach.

> I am just afraid we will get into writing our own test suit for this. I would first try to achieve this with standard mechanism and if it's not enough expand on it later.

I think this proposal is worth it and would really help development, but I'm also afraid implementing it would be a time sink. I'll try to implement a sketch when I have a few days time in front of me (not in the short term).

Meanwhile we can try to reuse some tools from lispy for ert testing: https://github.com/abo-abo/lispy/blob/master/lispy-test.el

They use visual markers similar to what is proposed here, but integrated in a classic ert workflow.

**Comment by vspinu** [comment]
> I'd like to implement other code manipulation tools in the future. 

Looks to me that this should be a business for a generic package like `smart-parents`. I think such effort should be better directed into making smart-parents work better with R mode.

> implementing it would be a time sink. 

That's what I am afraid too. In principle It shouldn't matter how tests are written. They should not break often, and when broken should be  relateivelly easy to fix. Elisp + ert allows that. If you think the speedup gain from visual inspection of git-diffs is worth investing time into custom suit, I am 100% fine with that. It's not my time after all ;)

>Meanwhile we can try to reuse some tools from lispy for ert testing: https://github.com/abo-abo/lispy/blob/master/lispy-test.el

Indeed. Good idea to sniff around for such stuff.

**Comment by lionel-** [comment]
> I think such effort should be better directed into making smart-parents work better with R mode.

That's a good idea, but maybe it'll make sense to keep these functions in ESS and have wrappers around them in smart-parens. I expect them to be tightly bound with ess-r-syntax.el, and the latter is not at all ready to be a public api. We'll see more clearly what to do with an actual implementation to stare at.

**Comment by lionel-** [comment]
The lispy stuff works well for R with minor modifications, but they are rather not convenient for multi-line test cases.

**Comment by lionel-** [comment]
ok I have a working version of this literate testing stuff.
Here's how the layout currently looks:

```r
##### Syntax

### 1 ----------------------------------------------------------------

##' (ess-climb-name)
##' (ess-jump-block)

function¶()
  body %>%
    stuff1 %>%
    stuff2

##!
function()
  body %>%
    stuff1 %>%
    stuff2¶


### 2 ----------------------------------------------------------------

##' (ess-end-of-defun)

object1 <- ¶function(argument1) {
  object2 <- fun_call(argument2, function(argument3) {
    body
  })
}

##!
object1 <- function(argument1) {
  object2 <- fun_call(argument2, function(argument3) {
    body
  })
}¶


### 3 ----------------------------------------------------------------

##' (ess-jump-name)

¶"string"

##!
¶"string"


### 4 ----------------------------------------------------------------

##' (ess-jump-object)

¶"string"

##!
"string"¶
```

**Comment by vspinu** [comment]
Looks cool, but how does it work more concretely?

**Comment by vspinu** [comment]
Ah. I got it. `Before` and `after`. Cool.

**Comment by lionel-** [comment]
yes, the second part gets generated or regenerated by applying the lisp commands to the first part in a temporary buffer running R-mode. This uses the lispy framework so we can have both literate tests and ert-style tests with these marked up test cases.

**Comment by lionel-** [comment]
In the future we can extend the syntax to have multiple tests for one input:

```r
```

**Comment by lionel-** [comment]
Maybe it would be clearer to have the test case before the commands then:

```r
### 3 ----------------------------------------------------------------

¶"string"

##1! (ess-jump-name)
##2! (ess-jump-object)

##1>

¶"string"

##2>

"string"¶
```

**Comment by vspinu** [comment]
> Maybe it would be clearer to have the test case before the commands then:

I find this confusing a bit.

> Or simply:

Yes. I think this is the best. It would allow arbitrary chains of transformations.

**Comment by lionel-** [comment]
> It would allow arbitrary chains of transformations.

I wasn't thinking of that at first but that's a very good idea. Here's how I implemented it:

* `##!` always starts a new chain from the original test case
* `##>` continues the test case from the previous test result

So:

```r
### 1 ----------------------------------------------------------------

¶this is a sentence

##! (forward-char)
##! (forward-char)

##> (forward-char)

##! (forward-char)
```

expands to:

```r
### 1 ----------------------------------------------------------------

¶this is a sentence

##! (forward-word)
##! (forward-char)

this ¶is a sentence

##> (forward-char)

this i¶s a sentence

##! (forward-char)

t¶his is a sentence
```

I also added a Makefile. You `make cases` to regenerate both indentation and literate cases, or you can `make indentation-cases` or `make literate-cases`.

**Comment by lionel-** [comment]
@abo-abo you might be interested in this. It expands your testing framework so that tests can be specified in the mode's target language (here, R), with a light markup syntax.

The idea is that it makes it really easy to write a test, and regressions are picked up with `git diff` after regenerating the test results.

And thanks for writing `(lispy-with)`!

**Comment by abo-abo** [comment]
@lionel- Very nice. I was thinking at some point of using org-mode to visualize the tests better, but then I wrote [lispy-view-test](https://github.com/abo-abo/lispy/wiki/lispy-view-test) which does a good job of visualizing the tests.  Most of my tests are read-only, but unraveling a single test into a buffer for editing can be done with a simple `insert`; then pull it back into the test with `lispy-string-oneline`.
