### ISSUE TITLE
[feature request] inline figure

### ISSUE THREAD

**Issue by GuangchuangYu** [emacs-ess/ESS#260]
imaxima can support inline figure:
![](https://raw.githubusercontent.com/GuangchuangYu/ygc_name/master/2005/05/Screen-Shot-2013-09-12-at-%E4%B8%8B%E5%8D%882.16.43.png)

So I think it's possible for ESS too.

**Comment by izahn** [comment]
Possible yes. Desirable? Not sure. You can already have inline figures in emacs generated from R via org-mode, so I don't see any really need to add it to ESS.

**Comment by GuangchuangYu** [comment]
thanks for your reply, I will look into the org-mode.

**Comment by GuangchuangYu** [comment]
org-mode is for writing document, it insert the output back to the source file. Yes, it indeed supports inline image. But I think it would be better in the ESS way.

In my opinion, inline image in the R console (emacs buffer) is more desirable.

**Comment by stardiviner** [comment]
I want this feature too.
Org-mode code snippets together is more complex.

**Comment by xelibrion** [comment]
@izahn would this be a way you recommend http://emacs.stackexchange.com/a/2593/10153?
