### ISSUE TITLE
eldoc error in ess-julia-mode

### ISSUE THREAD

**Issue by stardiviner** [emacs-ess/ESS#262]
Here is the error output after I triggered `debug-on-error`:

```
Debugger entered--Lisp error: (wrong-type-argument sequencep function)
  replace-regexp-in-string("\\\\" "\\\\" function nil t)
  ess-quote-special-chars(function)
  ess-function-arguments(function)
  ess-julia-eldoc-function()
    #[0 "\302 \204
  eldoc-print-current-symbol-info()
  #[0 "\205
  timer-event-handler([t 0 0 100000 t #[0 "\205
```

**Comment by vspinu** [comment]
Can you please provide the context around point? The same function `ess-quote-special-chars` is used for R in multiple places and I have never seen this error.

**Comment by vspinu** [comment]
It would be great if you could step through with edebug and let us know the exact value of `function` in that code. Thanks.

**Comment by stardiviner** [comment]
Sorry, I debug my config files, found one `ess-use-eldoc` function is setted as variable to `t`. This caused this issue.
