### ISSUE TITLE
ess-execute-screen-options triggers font-info error

### ISSUE THREAD

**Issue by mmuurr** [emacs-ess/ESS#264]
I think the SHA: 8fdcebffb9cc70ca215de99c6143e1d13629a890 commit is leading to an error when running ess-execute-screen-options on my installation.
The error is: "Symbol's function definition is void: font-info"
I only run emacs in terminal mode (i.e. no X11 or other GUI), and the error occurs whether in Terminal.app or iTerm2.
(It also occurs with both starting modes: 'emacs' and 'emacs -nw'.)

Below is some system information (that might help in identifying the issue?):

* OS X version 10.10.5
* emacs version: GNU Emacs 24.5.1 (x86_64-apple-darwin14.5.0)
* emacs installed via MacPorts
* R version 3.2.2 (also installed via MacPorts)
* ESS installed via MELPA (version ess-20151031.522)
* Terminal.app version 2.5.3 (343.7)
* iTerm2 version 2.1.4

**Comment by vspinu** [comment]
Thanks. I have changed the terminal was detected. Could you please check if it works.

**Comment by mmuurr** [comment]
Yup, verified as fixed.
Thanks!
