### ISSUE TITLE
indentation:  a <-  `if` .. `else  - haven't we been here?

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#268]
Given our careful regression tests, this must be a new one.... though I do have  strong
deja vu experiences ... 
```{r}
### --- 32 --- 2015-11-07 --- indentation again! --------
{
    yl <- if(strictlim) {
        ylim
    }
          else {
              range(y, ylim)
          }
    ## room below for weights
    dy <- 4*dy
}
## -- 32 b)
{
    yl <- if(strictlim) {
        ylim
    }
          else
              range(y, ylim)
    ## continue
}

```

**Comment by mmaechler** [comment]
I'm re-opening instead of making a new one: as this is so close: i have also added this to  `RRR.R` already:
```{r}
## 28
fun28 <-
    function(x, y)
{
    ans <- if(condition)
               stuff1
           else {
               stuff2
           }
        ## comment
    ans
}
```
the only problem is the indentation of the comment.  I am not sure if this example is minimal, but the two line function definiition *does* play a role.

**Comment by lionel-** [comment]
probably comments in blocks are not indented relatively yet, I'll look into it.
