### ISSUE TITLE
remote ess

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#275]
On the remote host there are several R installations, so in the `~/.profile` on the remote host I specified an `alias` that points the command `R` to the current version.
If I open a remote file with tramp `/ssh:remote:/my_path/file.R` and then want to run a remote R-session I type `C-RET RET` to open an R session on the remote host. Now an old version of R pops up, which is very annoying.
Everything works as intended if I use `M-x shell` `ssh remote` `R` `ess-remote`, which brings up the current version of R. 
The same happens with the remote Julia.
It would be great if the first way respected stuff in the remote `~/.profile`.

**Comment by a13ph** [comment]
@gdkrmr see if this is relevant to your issue (i suspect it is): https://github.com/emacs-ess/ESS/issues/138#issuecomment-70341007

**Comment by gdkrmr** [comment]
adding 
```
(with-eval-after-load 'tramp-sh
  (add-to-list 'tramp-remote-path 'tramp-own-remote-path))
```
doesn't work, I still don't get the same version that I get if i log in by shell.

**Comment by jabranham** [comment]
There's been considerable work done on tramp in the last two years. Do you still have this problem in Emacs 26.1? 

If so, you can change `inferior-ess-r-program` to point to the path of the R executable on the remote machine. 

@vspinu I think we can close this as not an ESS bug, it's a tramp/Emacs issue.

**Comment by vspinu** [comment]
Indeed. It's remote path issue which should be fixed by either adjusting tramp parameters or changing the path on the remote. I am not sure if the latter would work though.
