### ISSUE TITLE
Info documentation fails to build: newfeat.texi

### ISSUE THREAD

**Issue by akhilsbehl** [emacs-ess/ESS#276]
The el-get [recipe](https://github.com/dimitri/el-get/blob/master/recipes/ess.rcp) for ESS is failing for at least the last 3 days when building the documentation (newfeat.texi). The recipe itself hasn't changed for more than a year so I suspect that the issue is on the ESS side.

Included are the build messages (first is the last part ) to help with debugging. Please let me know if I can help with anything else.

Thanks.

````
make[1]: Leaving directory '/home/asb/.emacs.d/el-get/ess/lisp'
cd doc; /usr/bin/make all
make[1]: Entering directory '/home/asb/.emacs.d/el-get/ess/doc'
making Info documentation...
LC_ALL=C LANG=en makeinfo ess.texi
mv -f ess.info info/
LC_ALL=C LANG=en makeinfo --no-validate --plaintext --no-split -o - readme.texi \
| perl -pe 'last if /^Concept Index/;' > ../README
LC_ALL=C LANG=en makeinfo --no-validate --plaintext --no-split -o - announc.texi \
| perl -pe 'last if /^Concept Index/;' > ../ANNOUNCE
LC_ALL=C LANG=en makeinfo --no-validate --plaintext --no-split -o - news.texi > ../NEWS
LC_ALL=C LANG=en makeinfo --no-validate --plaintext --no-split -o - onews.texi > ../ONEWS
making HTML documentation...
mkdir -p html
LC_ALL=C LANG=en makeinfo --html --no-split --css-include=atouchofstyle.css -o html/ess.html ess.texi
LC_ALL=C LANG=en makeinfo --html --no-split --css-include=atouchofstyle.css -o html/readme.html --no-validate readme.texi
##                   ^^^^^^^^^^^^^ (design bug: "FIXME" in ess.texi)
mkdir -p html
LC_ALL=C LANG=en makeinfo --html --no-split --css-include=atouchofstyle.css -o html/news.html allnews.texi
LANG=C texi2dvi --pdf ess.texi
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Arch Linux) (preloaded format=pdfetex)
 restricted \write18 enabled.
entering extended mode
(./ess.texi (/usr/share/texmf-dist/tex/texinfo/texinfo.tex
Loading texinfo [version 2015-10-21.19]: pdf, fonts, markup, glyphs,
page headings, tables, conditionals, indexing, sectioning, toc, environments,
defuns, macros, cross references, insertions,
(/usr/share/texmf-dist/tex/generic/epsf/epsf.tex
This is `epsf.tex' v2.7.4 <14 February 2011>
) localization, formatting, and turning on texinfo input format.)
(./ess-defs.texi) (../VERSION) [1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex
.map}] [-1] Chapter 1 (./currfeat.texi [1])
Cross reference values unknown; you must run TeX again. [2] (./newfeat.texi
[3]
./newfeat.texi:29: Argument of @gobblespaces has an extra }.
<inserted text> 
                @par 
<to be read again> 
                   }
@doacronym ...#3@finish ->{@selectfonts @lsize #1}
                                                  @def @temp {#2}@ifx @temp ...
l.1 @acronym{ESS@gobblespaces }
                               @texinfoc
@scanmacro ...atspaces }@scantokens {#1@texinfoc }
                                                  @aftermacro 
l.29 @item @ESS{}
                 : A test framework has been set up.
?
````

**Comment by mmaechler** [comment]
I don't know `el-get` but am one of the ESS maintainers and would like to help such that
`make` also works for you.
It still works fine for me for the latest github version of ess.   You must give more details.
I am pretty sure its a problem with your local  `texinfo` setup.
I've heard that recently there has been turmoil with with different distribtions repackaging texinfo and similar.

Line 29 of  ess/doc/newfeat.texi   is
```{texi}
@item @ESS{}: A test framework has been set up.
```
which is prefectly correct (but the first use of the `@ESS{}` macro with empty argument..  hence my guess for a texinfo setup problem.

I have
```{shell}
 texi2dvi --version
```
```
texi2dvi (GNU Texinfo 5.2) 5381

Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
``` 
which seems to have been sufficient..

Martin

**Comment by akhilsbehl** [comment]
Hi Martin,

You probably don't remember but we met at the RMetrics conference in Meielisalp, Zurich a couple of years ago. Hello, again. :)

I did notice the empty argument macro too but am not sure if that may have been the reason. I am running texinfo 6.0.1 on ArchLinux. This is my:

````
texi2dvi --version
texi2dvi (GNU Texinfo 6.0) 6363

Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
````
I also checked the ArchLinux archive and it seems that on 21st October, Arch moved from 5.2 (which you have) to 6.0 (which I now have). I could downgrade my package but given that texinfo is so pervasive, I'd rather report a bug with Arch if I can confirm one. How do you advise I proceed?

Thanks.

**Comment by mmaechler** [comment]
Hi Akhil,  I did not remember you, sorry....  nice to meet again ... and thank you for supporting ESS in this way!

Well of course, this does change the picture that your  texinfo is newer than ours and shows these error messages.    How probable is that this is a bug in texinfo 6.0 ?  ... we'll have to ponder that a bit before taking decisions...  or find a very easy workaround with correct behavior in both texinfo < 6 and texinfo >= 6.0

**Comment by stefanhusmann** [comment]
Hello, I have exactly the same problem here. I am also under ArchLinux and tested with texinfo 6.0 from the repos and my AUR package texinfo-svn. The PKGBUILD for the latter is pretty much written the same way as the the official one.

**Comment by stefanhusmann** [comment]
The stable version does not have this problem.

**Comment by mmaechler** [comment]
@stefanhusmann : thank you for the note about the stable version.  I hence close the issue, as it seems clearly a bug in some versions of `texinfo` rather than in ESS.

**Comment by stefanhusmann** [comment]
I do not think so, because I did not configure texinfo at all.

**Comment by stefanhusmann** [comment]
I tracked this a bit down: On Arch Linux there is a texinfo.tex from at least two packages: automake and texlive-plainextra. 
automake: \def\texinfoversion{2013-02-01.11}
texlive-plainextra: \def\texinfoversion{2015-10-21.19}
"kpsewhich texinfo.tex" points to the newer one. When I deinstall texlive-plainextra, the texinfo.tex coming from gets into account, and the compilation of ess.texi succeeds.

**Comment by jwhendy** [comment]
Running into this myself, as well as with another application I tried to build... I'm also on Arch, but have installed texlive manually (not via the Arch package). How did you resolve the issue? I tried moving mine to `~/.texlive/2015/texmf-dist/tex/texinfo/texinfo.tex.bak` but the build still fails:

```
LANG=C texi2dvi --pdf ess.texi
/usr/bin/texi2dvi: texinfo.tex appears to be broken.
This may be due to the environment variable TEX set to something
other than (plain) tex, a corrupt texinfo.tex file, or 
to tex itself simply not working.
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015) (preloaded format=etex)
 restricted \write18 enabled.
entering extended mode
(./txiversion.tex
! I can't find file `texinfo.tex'.
l.1 \input texinfo.tex 
                       @bye
(Press Enter to retry, or Control-D to exit)
Please type another input file name: 
! Emergency stop.
l.1 \input texinfo.tex 
                       @bye
No pages of output.
Transcript written on txiversion.log.
/usr/bin/texi2dvi: quitting.
```

I have `texinfo` and `automake` installed.

Just curious what else you might have done other than "deinstall `texlive-plainextra`"? Thanks!

**Comment by jezcope** [comment]
In case anyone else has problems and comes across this issue through a web search like I did, I worked around this problem by overriding the built-in el-get recipe for ESS with [one that grabs it via `package.el` instead](https://github.com/jezcope/dotfiles/blob/bf704aa481741fc2d482afa123f2db9140899a84/emacs.d/recipes/ess.rcp). I hope that's useful for someone.
