### ISSUE TITLE
key for closing brackets/quotes/etc

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#283]
I don't like the RStudio feature of inserting `()` when I press `(` much, but a key for closing open brackets, etc. would be great, similar to auctex's close environment (`LaTeX-close-environment`, `C-c ]`), would be a great feature.

It should also insert `end` if there are open `function`, `if`, etc.. in julia.

**Comment by lionel-** [comment]
Sounds like this is outside the scope of ESS. The parenthesis feature would definitely fit in an Emacs-wide mode. Maybe there already is such a feature somewhere, but almost all programmers prefer not to insert unbalanced delimiters in the first place.

For the closing `end`, it seems like a feature that would be hard to implement efficiently. For ordinary delimiters, we can rely on Emacs to figure out mismatches, but in this case we'd have to parse the file from the beginning to current point. I think you should just bind a key that inserts `end` unconditionally.

**Comment by lionel-** [comment]
> it seems like a feature that would be hard to implement efficiently

Though there should be such a mechanism to figure out indentation I guess, so actually it should be possible. I'm not familiar with `julia-mode`.

Otherwise you can use something like this:
```lisp
(defun insert-end-below ()
  (interactive)
  (move-end-of-line 1)
  (insert "\nend")
  (indent-according-to-mode)
  (forward-line 1)
  (back-to-indentation))
```

**Comment by vspinu** [comment]
I agree with Lionel that such a feature better be generic. But, Implementing it
generically could be a challenge as languages could have very different and
complex delimiters.

My best bet would be to check id smartparens package already has necessary
constructs for this and customise julia and R side for that.

One enhancement would be to insert all unbalanced delimiters.

  Vitalie
