### ISSUE TITLE
Two Lisp issues

### ISSUE THREAD

**Issue by EVillaArdila** [emacs-ess/ESS#284]
1) Lisp nesting exceeds `max-lisp-eval-depth'
By pressing enter on this file.

![lisp1](https://cloud.githubusercontent.com/assets/8529925/11780953/4ad1adb4-a266-11e5-888b-cf39c60e8367.png)

2) Assertion failed: (eq 10 (char-before))
By typing any other key on the same file.

![lisp2](https://cloud.githubusercontent.com/assets/8529925/11780979/7fcd2872-a266-11e5-8a7b-607914e49975.png)

Emacs Version:
Emacs 24.5.1, GTK+ Version 3.10.8

R Version:
3.2.2

emacs ess Version:
ess-15.09-1
By older ess Versions there is no faulty behaviour.

**Comment by lionel-** [comment]
Can you try with the new patch release please.

**Comment by EVillaArdila** [comment]
I tried with ess-15-09-2 and everything works fine now.
Thanks.

**Comment by lionel-** [comment]
thanks for the report.
