### ISSUE TITLE
turn off undo for process buffer

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#285]
I always get a warning when running loops that print something:

`Warning (undo): Buffer `*julia*' undo info was 12560552 bytes long.
The undo info was discarded because it exceeded `undo-outer-limit'.`

I cannot think of a case where undoing something in the process buffer would be useful. So why not disable undo there completely? This also speeds things up if printing a lot into the REPL.

This can easily be done by `(add-hook 'inferior-ess-mode-hook 'buffer-disable-undo)` in the `.emacs`, but I think, there should be an option/documentation in ESS to do this automatically for process buffers.

**Comment by lionel-** [comment]
That's because the buffer name doesn't start with a space. It should be `" *julia*"` instead of `"*julia*"`.

ESS hosts a copy of Julia-mode but is not where development happens, so could you contact the Julia-mode authors about this please? Or maybe send them a PR while you're at it ;)

https://github.com/JuliaLang/julia/blob/master/contrib/julia-mode.el

**Comment by lionel-** [comment]
@mmaechler @vspinu 

Should we write a note on http://ess.r-project.org/index.php?Section=participate and in the `readme.md` file about how to reach the julia-mode developers?

**Comment by mmaechler** [comment]
that's a good idea... also more clearly saying that it is exactly that one file which belongs to them.

**Comment by gdkrmr** [comment]
Doesn't the same apply to the `*R*` buffer?

**Comment by lionel-** [comment]
oh yes you're right. The R inferior buffer doesn't have a leading space, nor the `m-x shell` buffer for that matter. And I do have undo history in my R buffer.

**Comment by lionel-** [comment]
That was a bit silly of me, if it had a leading space it wouldn't show up in the buffer list etc

**Comment by vspinu** [comment]
`julia-mode.el` has nothing to do with inferiors. That's entirely our thing. 

I find undo in inferior buffers useful occasionally. Given that other inferiors (shell included) don't disable that, we cannot disable undo by default.

**Comment by lionel-** [comment]
we can provide a switch, as @gdkrmr suggested. Maybe it offers some discoverability compared to the option of hooking `buffer-disable-undo` manually.

**Comment by jabranham** [comment]
Closing this since other inferior modes (python, etc) don't disable undo by default. If users want to, it's easy for them to add a hook as posted above.
