### ISSUE TITLE
(fill-paragraph) sends emacs in infinite loop

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#288]
`print("",digits=3) M-q` sends emacs into an infinite loop, I thing the empty string is the culprit.

if this happens, I can interrupt emacs by `kill -s USR2 $emacs_pid` and get the following backtrace:
```
Debugger entered--entering a function:
* command-error-default-function((quit) "" nil)
  recursive-edit()
  debug(lambda)
* eldoc-pre-command-refresh-echo-area()
  recursive-edit()
  debug(lambda)
* command-error-default-function((quit) "" nil)
  recursive-edit()
  debug(lambda)
* command-error-default-function((quit) "" nil)
  recursive-edit()
  debug(lambda)
* command-error-default-function((quit) "" nil)
  recursive-edit()
  debug(lambda)
* command-error-default-function((quit) "" nil)
  recursive-edit()
  debug(lambda)
* command-error-default-function((quit) "" nil)
  recursive-edit()
  debug(error (quit))
  looking-back("\"" 718)
  ess-jump-object()
  ess-jump-call()
  ess-jump-expression()
  ess-jump-parameter()
  ess-fill-args()
  ad-Advice-fill-paragraph(#[(&optional justify region) 
  apply(ad-Advice-fill-paragraph #[
  fill-paragraph(nil t)
  call-interactively(fill-paragraph nil nil)
  command-execute(fill-paragraph)
```

**Comment by lionel-** [comment]
Thanks for the report, I'll look into it.

**Comment by lionel-** [comment]
I can't reproduce the infloop. Where is your point when you M-q? And what version of ESS do you have? Do you have other advices activated on `(fill-paragraph)`?

**Comment by gdkrmr** [comment]
point must be after the `3`, after the `)` it does not work

**Comment by lionel-** [comment]
An advice is a modification of a function that can be applied either by yourself or by major and minor modes. You can investigate which advices are activated with `(describe-function)`.

Can you try with the latest patch release please?

**Comment by gdkrmr** [comment]
`M-x describe-funciton fill-paragraph` has the following line:
``` :around advice: `ad-Advice-fill-paragraph' ``` which is from `ESS`.
I just checked it on master and it does not hang any more, great, thank you a lot!

I guess, the fix is not ready yet, because before I could cycle through these representations:
```
c("a","b","c","d","e")
c("a","b","c",
   "d","e")
c("a",
  "b",
  "c",
  "d",
  "e")
```
using tab for indentation does not work any more either, it gives me `ess-back-and-forth-sexp: Invalid function: ess-save-excursion-when-nil`

**Comment by lionel-** [comment]
looks like your installation of ESS is somehow broken ;)

**Comment by gdkrmr** [comment]
you where right, i reinstalled from melpa (20160123.452) and all the above issues seem resolved.

**Comment by lionel-** [comment]
Cool, thanks
