### ISSUE TITLE
doubtful indentation

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#290]
This is a borderline example, notably as one can argue that it is close to ambiguous because it does not use `{` .. `}` for clarification.   Still I have encountered it the 2nd time now in real code.
Maybe this is intended or unavoidable:  Below is the  `RRR`  style;  if you use `Rstudio`, it is even worse: the `else` indents as if it belonged to the first `if` instead of the 2nd.
```{r}
{
    if(C)
        r <- ## now the next 4 lines should indent more:
        if(cond)
            a
        else
            b
}
```

**Comment by lionel-** [comment]
I was almost missing those indentation reports ;)

The else indentation of Rstudio style is as it should be I think, but definition ops should produce more indentation indeed.

**Comment by vspinu** [comment]
Both our `Rstudio` style and the real `Rstudio` indent this code wrongly:

```R

{
  if(TRUE)
    r <-
    if(FALSE)
      print("true")
  else
    print("false")
}
```

When executed, it prints "false".

**Comment by mmaechler** [comment]
as I said about our 'Rstudio" style... but interesting that you were able to "copy" it including this bug when setting it up!  (and thanks for the giggle from you "I was almost .." ) :+1:

**Comment by lionel-** [comment]
Now fixed. This messes up a bit the weird behaviour of the RStudio style that you mentioned, but I'm a bit tired of struggling to follow RStudio indentation completely... Let's leave it like this until a user complains about those corner cases, which is unlikely.
