### ISSUE TITLE
Executing region containing interactive code freezes emacs

### ISSUE THREAD

**Issue by zarquon42b** [emacs-ess/ESS#292]
If you evaluate a region where interactive functions are called (except in last line of the region) emacs stalls. 
Example:

Evaluating this region freezes emacs:

```r
testfun <- function(x) {
    if (interactive())
        readline("some interaction\n")
        return(1)
    }
a <- 1
b <- testfun()
d <- a+b
```
I assume that ```d <- a+b``` is being evaluated while still waiting for input. Is there a way to prevent this?

**Comment by vspinu** [comment]
This happens when `ess-eval-visibly` is t. Unfortunately there is no way around that. Either customize that variable to something else, or don't use readline.

**Comment by zarquon42b** [comment]
Thanks. Changing the variable does it for me.
