### ISSUE TITLE
Indentation of lists with missing values broke recently

### ISSUE THREAD

**Issue by vspinu** [emacs-ess/ESS#293]
Hi Lionel.

I think one of your recent commits broke the following call. It was working correctly the other day.

```
switch(aa,
       bb = , 
           cc = dd
```

It has to do with missing value.

**Comment by lionel-** [comment]
It was a new issue actually, now fixed.

I'll have to simplify some of the syntax code eventually. I wrote it under the assumption that the SEXP positions of a buffer were cached, but after reading Emacs source code I found out this is not the case. I was using sexp motions as a kind of cheap tokeniser but it's actually not so cheap and they are not great at tokenising.

**Comment by vspinu** [comment]
>  I wrote it under the assumption that the SEXP positions of a buffer were cached

I think the only actual cache is the `syntax-ppss-cache` and all those SEXP motion commands are relying on that.

**Comment by lionel-** [comment]
> and all those SEXP motion commands are relying on that.

Unfortunately not, `(scan-sexps)` directly calls `scan-lists()` in syntax.c, no cache involved.
