### ISSUE TITLE
install.packages in *R* buffer takes ages

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#294]
installing a package in the _R_ buffer takes a long time, and the emacs buffer runs on 100% cpu the whole time because some progress bar is being drawn and refreshed all the time.

**Comment by vspinu** [comment]
What package do you install? It has nothing to do with the progress bar. It's probably your package. Have you tried in the terminal?

**Comment by gdkrmr** [comment]
Installing from terminal/Rstudio works just fine, this happens with 
every package. The Emacs buffer gets filled with `=` from the download 
progress bar.

**Comment by vspinu** [comment]
t's difficult to guess what can be wrong. No-one ever reported this before. I don't see any difference between terminal and ESS installation.

What platform is this? It might be something low level on Emacs side. Can you open R in emacs shell and try there?

**Comment by gdkrmr** [comment]
I generally have problems when scripts print too much, progress bars seem to take this to an extreme. Does the *R* buffer recognize `\r`? It became a little bit better when I disabled undo in the *R* buffer.
I am on Ubuntu 14.04 and I have a self compiled emacs.
So you think this has something to do with my emacs config?

**Comment by gdkrmr** [comment]
the `*shell*` buffer it is much more responsive, there is still some delay but much smaller, I have to try this on another computer.

**Comment by jabranham** [comment]
@gdkrmr Do you still see this or can we close this issue?

**Comment by jabranham** [comment]
I'm closing this issue, feel free to comment and reopen if you still experience this.
