### ISSUE TITLE
Emacs-ESS not closing curly braces within .R files

### ISSUE THREAD

**Issue by KentonWhite** [emacs-ess/ESS#296]
in my .emacs file I have:

```
;; enable skeleton-pair insert globally
(setq skeleton-pair t)
;;(setq skeleton-pair-on-word t)
(global-set-key (kbd "(") 'skeleton-pair-insert-maybe)
(global-set-key (kbd "[") 'skeleton-pair-insert-maybe)
(global-set-key (kbd "{") 'skeleton-pair-insert-maybe)
(global-set-key (kbd "\"") 'skeleton-pair-insert-maybe)
(global-set-key (kbd "\'") 'skeleton-pair-insert-maybe)
(global-set-key (kbd "\`") 'skeleton-pair-insert-maybe)
(global-set-key (kbd "<") 'skeleton-pair-insert-maybe)
```
Auto-completion of the braces (or auto-closing them) will work with everything: .py files, .txt files, even when I am in the R console launched with ESS (M-x R). However, it will not complete the curly braces when the file is an R file (e.g. foo.R). All other skeleton-pair options work everywhere, the only one that does not is the curly braces.

I am using 

- ESS 15.09-2 patched [elpa: 20160225.655]
- GNU Emacs 24.5.1 (x86_64-apple-darwin15.3.0, NS apple-appkit-1404.34)

**Comment by vspinu** [comment]
That's because ESS is binding `{` to `ess-electric-brace` which stopped working at some point. This is historical and I think even precedes `skeleton-pair`. It should be working now. You can always fix such issues by unseting the keys in  ess mode:

```
(define-key ess-mode-map (kbd "{") nil)
(define-key ess-mode-map (kbd "}") nil)
```
