### ISSUE TITLE
make `ess-load-library` generic

### ISSUE THREAD

**Issue by tpapp** [emacs-ess/ESS#299]
If possible, it would be nice to make `ess-load-library` generic, so that I could define it for Julia. Currently it checks `ess-dialect` and aborts if it is not R.

I understand that something more complicated than a simple string expansion (like `ess-setwd-command` for `ess-set-directory`) would be required. Possibly `ess-load-library` could call a `ess-load-library-function` when not `nil`. If would be happy to submit a PR, but not sure how to organize the code, since prompting with completion assumes a list of packages (eg if it is nil, there could be no completion for some dialects). A separate function could govern completion, but maybe that is getting to be too complicated.

In Julia, I would use `Base.reload`, with the assumption that one uses this feature during interactive development.

**Comment by mmaechler** [comment]
Actually, I would be happy if the prompting could be "configured away" even for R.. again because I have 1000's of installed packages in  my .libPaths()  the prompting tends to be too slow... at least occasionally.

**Comment by vspinu** [comment]
Could you please give a command that loads julia's package and another one that gives all installed packages. 

There is also a C-c C-e i that prompts for package to be installed. Is there such a thing for Julia?

**Comment by tpapp** [comment]
@vspinu, the following would list all packages:
```julia
collect(keys(Pkg.installed()))
```
as an array of strings.

`Pkg.add(package_name_as_string)` would install a package (that is registered, installing from a git repo is different but I doubt we need special support for that).

If you can add these for Julia that would be fine, but if you prefer I would be happy to submit PRs once the hooks are in place.

**Comment by tpapp** [comment]
@vspinu, should I try to submit a PR, or is this something you would prefer to do because it involves a reorganization of the code?

**Comment by vspinu** [comment]
If you can manage to provide a PR it would help indeed. I don't plan to re-organize the code. I just don't have time to look at this. Sorry.
