### ISSUE TITLE
ess-list-object-completions and autocomplete

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#301]
currently typing `somelist$` does not open the auto-complete menu when I press `tab`, to get a list of all items, I need to press `M-?` and the list opens in another buffer, which is not so nice. Is there a way to integrate this into an auto-complete menu?

**Comment by vspinu** [comment]
It does work with company. It should in principle work with auto-complete as well but auto-complete is not actively supported or tested anymore. 

You are encouraged to switch to company. There is a much better support for it in Emacs ecosystem and ESS is not an exception.

**Comment by gdkrmr** [comment]
works like a charm, thanks a lot!! maybe you should mention it in the manual ;-)
