### ISSUE TITLE
indentation of 

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#302]
Another indentation error, outside the print statement, they are fine:
```R
print(
    ggplot() +
    geom_point()
)

print(
    a %>%
    b
)

ggplot() +
    geom_point()

a %>%
    b

```

**Comment by lionel-** [comment]
by default we follow the C++ style for indentation of continuations in calls.

You can set `ess-align-continuations-in-calls` to nil to prevent this.

**Comment by gdkrmr** [comment]
thanks, it works
