### ISSUE TITLE
Major mode isn't changing when passing from Latex to chunk in Rnw

### ISSUE THREAD

**Issue by walmes** [emacs-ess/ESS#308]
I updated my ESS from 20160305.530 to 20160314.1338 and noticed that, when working with Rnw files, the major mode isn't changing when passing from Latex to chunk and vice versa. I visit the both versions and I compared them (`git diff`). I found difference in the `ess-autoloads.el`, there are two new lines in the most recent and one line changed in the `ess-r-d.el`. But my guess is about `ess-noweb-mode.el` that has some changes too.

**Comment by marcbrouard** [comment]
I am afraid I am seeing this issue as well, after updating from MELPA. Do not have any more information to add, but if there is anything I can help with, please let me know.

**Comment by vspinu** [comment]
It's probably the consequence of the fix of #305. ess-noweb is doing ugly non-standard things. Please consider switching to polymode. Fixing ess-noweb is a lost battle.
