### ISSUE TITLE
ESS and piping

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#311]
Hi - 

Is there any way that ESS supports autocompletion of piped objects (via magrittr/dplyr) in R? 

For example:

```R
library(nycflights13)

flights %>% 
    select(dep_ ||
```

where `||` represents point should complete "dep_delay"

**Comment by lionel-** [comment]
Not currently. Duplicate of #253

**Comment by LaDilettante** [comment]
#253 was last discussed in 2015. Given how the tidyverse has become very popular, would you consider this work high priority?
