### ISSUE TITLE
New R help broken: ?lm  gives output in *R* buffer in addition to creating a help buffer

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#313]
(see subject).
I hope you can easily reproduce:

Typing  ?<foo>  both shows the help buffer inside *R* and creates a help buffer.

**Comment by vspinu** [comment]
Yep. I can reproduce. Will provide a fix in a second.

**Comment by mmaechler** [comment]
Thanks a lot, @vspinu .. that was very quick indeed!
