### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by rschuetzler** [emacs-ess/ESS#316]
I've had an issue with the later versions (`20160407`) on Windows 10. I updated via melpa, and now Emacs won't start. I tried wiping all my packages and starting fresh, but the same issue has come up again. My Emacs window stays blank, and I can't interact with it at all. 

I know it's ESS, because when I remove it and julia-mode, along with getting rid of the command to install it on startup, things work. Any idea what happened? I wish I could post error messages, but I can't interact with Emacs at all to even see error messages.

Downgraded to Emacs 24.5 (from 25.0.50), and now it seems to be stuck at:

    Checking C:/.../.emacs.d/elpa/ess-20160407.1039/lisp...

**Comment by lionel-** [comment]
That must be linked to a bug that was fixed a few hours ago. This bug caused ess-r-package-mode to be activated in all buffers.

Can you please try again with a very recent version (wait for it to appear on Melpa). The R package mode is probably broken on your machine but it'll be easier to track down why once you can start your Emacs :)

**Comment by rschuetzler** [comment]
Seems to still be an issue. Trying to start up again, and it's downloaded `ess-20160407.1039`, which is the latest version I believe. But it's hung up there, and not finishing the startup sequence.

**Comment by nverno** [comment]
I had the same problem last night.  Running emacs 25.0.91.1 and the latest ess from melpa.  I've removed all packages and tried installing ess from a bare init but it hangs when I suppose it is byte compiling the lisp directory?  At least that is the last message I see before emacs dies.

**Comment by rschuetzler** [comment]
Here's everything I see right now where it's hung up:

```
^L
Compiling no file at Thu [date here]
Leaving directory `c:/Users/.../.emacs.d/elpa/julia-mode-20160327.225'
^L
Compiling file C:/Users/.../.emacs.d/elpa/julia-mode-20160327.225/julia-mode-pkg.el at [date here]
Entering directory `c:/Users/.../.emacs.d/elpa/julia-mode-20160327.225/'
^L
Compiling file c:/Users/.../.emacs.d/elpa/julia-mode-20160327.335/julia-mode.el at [date here]

In julia-mode:
julia-mode.el:619:10:Warning: reference to free variable
    `julia-syntax-propertize-function'
```

And then in the minibuffer:

    Checking c:/Users/.../.emacs.d/elpa/ess-20160407.1039/lisp...

**Comment by lionel-** [comment]
hmm... Could be linked to https://github.com/emacs-ess/ESS/pull/315 cc @alexg0 @tpapp 

Can you put `(setq ess-r-package-auto-activate nil)` at the start of your .emacs please, just to rule out it's not the activation of the new R package dev mode.

**Comment by rschuetzler** [comment]
@lionel- That did it. Got things booted up without any issue (repeated it 2x just to be sure).

**Comment by lionel-** [comment]
Could you try these two expressions anywhere could be relevant to your startup process:

- `(ess-r-package-mode 1)`
- `(ess-r-package-get-info)`

To try and reproduce the hang, so we can hopefully pinpoint the issue.

**Comment by lionel-** [comment]
I think the second one is more likely to cause the hang.

**Comment by rschuetzler** [comment]
You nailed it. `(ess-r-package-mode 1)` works fine, but `(ess-r-package-get-info)` just hangs.

**Comment by lionel-** [comment]
Thanks. Apparently one way to debug hangs it this: `M-x toggle-debug-on-quit`

Then when you C-g you should get a backtrace.

**Comment by rschuetzler** [comment]
```
Debugger entered--Lisp error: (quit)
  file-name-directory("d:/")
  ess--parent-dir("d:/" 1)
  ess-r-package--find-package-path()
  ess-r-package--local-package-info()
  ess-r-package-get-info()
  eval-buffer(#<buffer  *load*-942536> nil "c:/Users/Ryan/dotfiles/.emacs.d/ess-config.el" nil t)  ; Reading at buffer position 1953
  load-with-code-conversion("c:/Users/Ryan/dotfiles/.emacs.d/ess-config.el" "c:/Users/Ryan/dotfiles/.emacs.d/ess-config.el" nil nil)
  load("c:/Users/Ryan/dotfiles/.emacs.d/ess-config.el" nil nil t)
  load-file("c:/Users/Ryan/dotfiles/.emacs.d/ess-config.el")
  load-user-file("ess-config.el")
  eval-buffer(#<buffer  *load*-211750> nil "c:/Users/Ryan/dotfiles/.emacs.d/init.el" nil t)  ; Reading at buffer position 7324
  load-with-code-conversion("c:/Users/Ryan/dotfiles/.emacs.d/init.el" "c:/Users/Ryan/dotfiles/.emacs.d/init.el" nil nil)
  load("C:/Users/Ryan/dotfiles/.emacs.d/init.el")
  eval-buffer(#<buffer  *load*> nil "d:/Ryan/.emacs.d/init.el" nil t)  ; Reading at buffer position 302
  load-with-code-conversion("d:/Ryan/.emacs.d/init.el" "d:/Ryan/.emacs.d/init.el" t t)
  load("d:/Ryan/.emacs.d/init" t t)
  #[0 "\205\262
```

**Comment by rschuetzler** [comment]
This one is just with `(ess-r-package-get-info)`. With both lines, I can't get the Debug message to show up. `C-g` gets my theme to load (instead of the blank white I have before), but I still can't see or do anything.

**Comment by lionel-** [comment]
Thanks. With this backtrace we should be able to fix it.

**Comment by nverno** [comment]
Excellent, seems to be working great now
