### ISSUE TITLE
ess-replace-in-string not defined

### ISSUE THREAD

**Issue by r2evans** [emacs-ess/ESS#317]
[def44a8](https://github.com/emacs-ess/ESS/commit/def44a87e584e501a6854e4d3edad5c7de3f7509#diff-724cde45c58d919c6bb8e85b26faf792) removed the definition of `ess-replace-in-string`, but it's still being used elsewhere. My trigger was trying to create a roxy template:

```
ess-roxy-get-args-list-from-entry: Symbol's function definition is void: ess-replace-in-string
```

**Comment by lionel-** [comment]
Thanks for the report. We're just getting started with a suite of unit tests that should help us detect such issues in the future.

**Comment by r2evans** [comment]
It's also being used in:

1. `ess-inf.el` (`(require 'ess-utils)` is in a `eval-when-compile` block, it might be needed all the time now?
2. Referenced within `ess-install.el` (specifically `save-window-excursion`, and the comment above it lists the old filename).

(I haven't seen problem with these, but it'll likely pop up at some point.)

Thanks for the fast reply!

**Comment by lionel-** [comment]
`eval-when-compile` also evaluates at run time. As for `ess-install.el`, I didn't touch it because I don't know how it works and I don't think it's used anymore. It'll probably go into lisp/old/. cc @vspinu

**Comment by vspinu** [comment]
Not even old/. It should be removed altogether. We will end up auto-loading the whole ESS and there should be no need for ess-install.el or ess-site.el.
