### ISSUE TITLE
Required feature cl-seq not provided

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#321]
I get an error when ESS tries to load. The error is "required feature 'cl-seq' was not provided" 

This is my setup for ESS, and I am using the most recent MELPA build. 

```
  (use-package ess-site
    :ensure ess
    :diminish eldoc-mode
    :config
    (add-hook 'ess-mode-hook
              (lambda ()
                (ess-set-style 'RStudio)))
    (setq ess-offset-arguments 'prev-line)
    (setq ess-ask-for-ess-directory nil)
    (defun my/add-pipe ()
      (interactive)
      (just-one-space 1)
      (insert "%>%")
      (ess-newline-and-indent))
    (define-key ess-mode-map (kbd "M-p") 'my/add-pipe))
```

**Comment by lionel-** [comment]
My bad. I checked Emacs 23 and it looked like it had `cl-seq`. What Emacs version have you got?

Just pushed a change to require `cl` instead. Let me know if that fixes it for you.

**Comment by jabranham** [comment]
I'm running emacs 24.5.1. 

Doesn't look like that commit has made it to MELPA yet, but I'll let you know if it fixes the issue.

**Comment by jabranham** [comment]
Thanks, that seems to have done the trick!
