### ISSUE TITLE
Filling roxygen block fails when text contains backticks

### ISSUE THREAD

**Issue by nfdisco** [emacs-ess/ESS#323]
Calling `fill-paragraph` on the following roxygen block

    ##' If \code{formula} is an object of class \code{mpmTerms} or has a
    ##' `terms' element, then that is returned.  Otherwise the
    ##' \code{formula} argument is coerced to a formula and a new
    ##' terms-like object is constructed.

fails due to the backtick character in the word "terms" on the second line.

    ##' If \code{formula} is an object of class \code{mpmTerms} or has a
    ##' `terms' element, then that is returned.  Otherwise the \code{formula} argument is coerced to a formula and a new terms-like object is constructed.

In addition, weird things happen if `fill-paragraph` is called when the point is on the word "terms-like".  Here I think the problem is the dash.

**Comment by nfdisco** [comment]
A possible solution is to use Rd-mode's syntax table when filling roxy blocks.

    --- ess-roxy.el.orig	2016-04-24 00:17:15.008830053 +0200
    +++ ess-roxy.el	2016-04-24 12:18:47.729759069 +0200
    @@ -66,6 +66,7 @@
     (eval-when-compile
       (require 'cl))
     (autoload 'Rd-preview-help "ess-rd" "[autoload]" t)
    +(require 'essddr "ess-rd.el")
     
     ;; ------------------
     (defvar ess-roxy-mode-map
    @@ -730,19 +731,22 @@
         (goto-char stop-point)
         (line-end-position 0)))
     
    -(defmacro ess-roxy-with-filling-context (&rest body)
    +(defmacro ess-roxy-with-filling-context (examples &rest body)
       (declare (indent 0) (debug (&rest form)))
       `(let ((comment-start "#+'[ \t]+#")
              (comment-start-skip "#+'[ \t]+# *")
              (comment-use-syntax nil)
              (adaptive-fill-first-line-regexp (concat ess-roxy-re "[ \t]*"))
    -         (temp-table (make-syntax-table S-syntax-table))
              (paragraph-start (concat "\\(" ess-roxy-re "\\(" paragraph-start
    -                                  "\\|[ \t]*@" "\\)" "\\)\\|\\(" paragraph-start "\\)")))
    -     ;; Prevent the roxy prefix to be interpreted as comment or string
    -     ;; starter
    -     (modify-syntax-entry ?# "w" temp-table)
    -     (modify-syntax-entry ?' "w" temp-table)
    +                                  "\\|[ \t]*@" "\\)" "\\)\\|\\(" paragraph-start "\\)"))
    +         (temp-table (if ,examples
    +			 (make-syntax-table S-syntax-table)
    +		       Rd-mode-syntax-table)))
    +     (when ,examples
    +       ;; Prevent the roxy prefix to be interpreted as comment or string
    +       ;; starter
    +       (modify-syntax-entry ?# "w" temp-table)
    +       (modify-syntax-entry ?' "w" temp-table))
          ;; Neutralise (comment-normalize-vars) because it modifies the
          ;; comment-start regexp in such a way that paragraph filling of
          ;; comments in @examples fields does not work
    @@ -775,7 +779,7 @@
              (save-excursion
                (back-to-indentation)
                (looking-at "#")))
    -    (ess-roxy-with-filling-context
    +    (ess-roxy-with-filling-context t
           ad-do-it))
        ((and (not (ess-roxy-entry-p))
              (ess-point-in-comment-p))
    @@ -816,7 +820,7 @@
                            (concat ess-roxy-re "[ \t]*@examples\\b") "^[^#]")))
             ;; Refill the whole structural paragraph sequentially, field by
             ;; field, stopping at @examples
    -        (ess-roxy-with-filling-context
    +        (ess-roxy-with-filling-context nil
               (save-excursion
                 (save-restriction
                   (narrow-to-region par-start par-end)

 
The issue with the dash is because it's interpreted as R code, in particular as a continuation and is filled accordingly.  It's not a big deal, because it only happens when the point is on that particular word.

To be honest, I'm not sure if it's best to treat the contents of roxygen comments as R code, or as documentation.  I think I'd go with the latter, but I guess a case could be made for either option.

**Comment by lionel-** [comment]
> To be honest, I'm not sure if it's best to treat the contents of roxygen comments as R code, or as documentation. I think I'd go with the latter

I think ideally we'd want to treat the `@examples` field as R code. But I'm not sure the call and continuations-filling functions know how to deal with code prefixed with `#'`. So probably better to treat everything as documentation for now. Filling of comments in the `@examples` still need to work though.

> A possible solution is to use Rd-mode's syntax table when filling roxy blocks.

This solution looks reasonable. Could you send a PR so I can try this out easily? With a couple of new tests in test/literate/roxy.R.

To write a new test case, you:

- add a numbered header
- then an initial state with `¶` representing point
- then a command or a keybinding prefixed with `##!`. For example:

```r
### 2 ----------------------------------------------------------------

##' some-¶text

##! "M-q"
```
Then you type `make literate` in the test folder to generate the result. If any other snippet changes (use `git diff` to find out), something broke.
