### ISSUE TITLE
File local-variables error: (search-failed "package: \\(.*\\)") when opening .git/COMMIT_EDITMSG

### ISSUE THREAD

**Issue by npostavs** [emacs-ess/ESS#326]
This only seems to occur on Windows. `GNU Emacs 24.5.1 (i686-pc-mingw32) of 2015-04-11 on LEG570`

The error can be reproduced with `emacs -Q -L ESS/lisp -l ess-site ESS/.git/COMMIT_EDITMSG`, where `ESS` is a git clone of this repo (at 9b1eb4f6bd73d3fdfab4c2b87590e69e0dc0bb8b).

`*Messages*` contains:

```
For information about GNU Emacs and the GNU system, type C-h C-a.
Finding all versions of R on your system...
Sorry, no version of R could be found on your system.
(New file)
File local-variables error: (search-failed "package: \\(.*\\)")
```

This error is preventing committing with magit, cf magit/magit#2631

**Comment by lionel-** [comment]
Thanks, should be fixed.

**Comment by npostavs** [comment]
Thanks, it works now.
