### ISSUE TITLE
message  "Making font-lock-fontified buffer-local while locally let-bound!"

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#327]
I see such messages when navigating R help buffers in current "pre-release of ESS 16.04".
Is this something to be fixed?

**Comment by vspinu** [comment]
I don't see this. But it might be related to polymode for examples section.

**Comment by mmaechler** [comment]
Yes, I am using that here..  So we should close the issue, as it is really a polymode one .?

**Comment by vspinu** [comment]
I am not seeing it, so it might be that you are using an old version of polymode. It's surely not an ESS issue.
