### ISSUE TITLE
Commit 6b89391 interferes with Org-mode R evaluation

### ISSUE THREAD

**Issue by jwhendy** [emacs-ess/ESS#328]
Greetings,

A [post](http://thread.gmane.org/gmane.emacs.orgmode/106870) came through the org-mode mailing list about updating ESS and running into issues with evaluation of R source code through org-mode babel. I can replicate, and traced it to the referenced recent commit.

---

Process:

- `cd ~/.elisp/ess`, `git reset --hard 6b89391a13322ff2297fb3895ed665ff2048fc10`, `make clean`
- `emacs -Q`, then `M-x load-file` with this minimal config:
```
(add-to-list 'load-path "~/.elisp/org/lisp/")
(add-to-list 'load-path "~/.elisp/org/contrib/lisp")
(add-to-list 'load-path "~/.elisp/ess/lisp/")

(require 'ess-site)

(org-babel-do-load-languages
 'org-babel-load-languages
 '((R . t)))
```

- create `test.org` file with this src block from the mailing list post:

```
* heading

#+BEGIN_SRC R :session :results values
1
#+END_SRC
```

- execute code with `C-c C-c` inside the block and get this in the `*Messages*` buffer:

```
ess-eval-buffer: Wrong number of arguments: (lambda (start end toggle &optional message) "Send the current region to the inferior ESS process.
With prefix argument toggle the meaning of `ess-eval-visibly';
this does not apply when using the S-plus GUI, see
`ess-dde-send-region'." (interactive "r
P") (ess-force-buffer-current "Process to use: ") (message "Starting evaluation...") (if ess-local-customize-alist nil (ess-setq-vars-local (symbol-value (ess-get-process-variable (quote ess-local-customize-alist))))) (ess-eval-region--normalise-region) (let ((visibly (if toggle (not ess-eval-visibly) ess-eval-visibly)) (message (or message "Eval region")) (proc (ess-get-process))) (save-excursion (ess-send-region proc start end visibly message))) (if ess-eval-deactivate-mark (progn (ess-deactivate-mark))) ...), 5
```

Info:
```
$ emacs --version
GNU Emacs 24.5.1

M-x ess-version
ess-version: 15.09-2 patched [<unknown>] (loaded from ~/.elisp/ess/)

M-x org-version
Org-mode version 8.3.4 (release_8.3.4-753-gda4db33 @ ~/.elisp/org/lisp/)
```

Let me know if you need further information.

**Comment by lionel-** [comment]
We probably need to include an org file in our test suite.

**Comment by jwhendy** [comment]
I can ask more experienced folks to chime in on that if you'd like. I'm a horrible person to ask as I just use these tools but have no knowledge of what's going on behind the scenes.

Someone else could perhaps try to cook up a good org test suite document. I'll post to the list and see what they say.

Thanks!
John

**Comment by mmaechler** [comment]
@lionel-  do you observe the problem with "current ESS" ?
@jwhendy : Could you update your ESS to the development version which is currently release candidate for ESS 16.04 , please ?
If you don't want to get it from here (github) or MELPA, there are now "official prerelase" tar/zip balls available from  [here|ftp://stat.ethz.ch/U/maechler/ESS/)

**Comment by lionel-** [comment]
> do you observe the problem with "current ESS" ?

This issue is caused by an argument that @vspinu recently removed in evaluation functions. Let's wait for him :)

**Comment by lionel-** [comment]
I think this commit also broke two tests by the way Vitalie.

**Comment by vspinu** [comment]
Yes. It was me. That argument wasn't used, so I thought no-one is using it. 

BTW, I think our tests are ready to be included on travis.
