### ISSUE TITLE
ess-r-package-mode functions failing on Windows due to trailing backslash in package path

### ISSUE THREAD

**Issue by JoshOBrien** [emacs-ess/ESS#332]
I just tried out the new ess-r-package-mode, bundled with the pre-release of ESS 16.04, and the first several commands all fail for the same reason.

If, for example, I do `C-c C-w d` from a buffer holding my package's `'DESCRIPTION'` file (in order to run `devtools::document()` on the package), I get this error in the R session that that launches:

    > devtools::document('c:/Josh/Projects/BHS/1) Software/1) R packages/spTools/')
    Error: Can't find 'c:\Josh\Projects\BHS\1) Software\1) R packages\spTools\'.

Removing that trailing backslash to give the following command would fix the problem:

    > devtools::document('c:/Josh/Projects/BHS/1) Software/1) R packages/spTools')

Not surprisingly the same issue affects other ess-r-package-mode commands, like `ess-r-devtools-install-package`, `ess-r-devtools-test-package`, etc.

Thanks.

**Comment by JoshOBrien** [comment]
I'm not at all elisp conversant, but it seems like applying the function `directory-file-name` to the variable `pkg-path` (to strip the trailing slash) somewhere in `ess-r-package-set-package` might fix the problem.

**Comment by lionel-** [comment]
This sounds more like a devtools bug, but I guess there's no harm in removing that trailing slash/backslash.
