### ISSUE TITLE
Starting R inside package source should load the package

### ISSUE THREAD

**Issue by lawremi** [emacs-ess/ESS#333]
The auto-developer-mode feature in ESS is nice. Now that ESS can identify the package containing a source file, could it also optionally load (and optionally attach) the namespace when R is started from that buffer? That way auto-completion, object inspection, eldoc, etc, will work as soon as R is started.

**Comment by lionel-** [comment]
Should this be more general? I.e. we could have a buffer-local variable `ess-r-autoloaded-packages` that could be set to a list of packages to load whenever a R process is attached to the buffer? Then a `ess-r-package-autoload` boolean for the package mode. It would make sense to look up the dependencies in the DESCRIPTION file as well.

**Comment by lionel-** [comment]
> It would make sense to look up the dependencies

Though this would only be useful for `suggests` and when the package hasn't been installed or updated yet.

**Comment by lawremi** [comment]
> we could have a buffer-local variable ess-r-autoloaded-packages

Sounds fine but I'm not sure what the use case would be for a per-buffer customized list of autoloads. There are times when the autoloads are implied by context, but in most cases it is the responsibility of the script itself to load libraries. I could see having a global set of packages to attach during development. 

> this would only be useful for suggests

I could see loading RUnit or testthat if either is listed in the Suggests, and R is started from a test. That would be a file under `tests` although there should be a customizable list of paths, because e.g. Bioconductor puts tests under `inst/unitTests`.

> when the package hasn't been installed or updated yet

Prompting the user to install or update the package while taking into account dependencies is a really good idea. This is related to an issue with developer mode: when we inject code into the package namespace at runtime, we often forget to bump the version or install our changes. If there was some way of marking the package stale, even if only within the same Emacs session, we could prompt the user to reinstall the next time R is started. Maybe that should be filed under a separate issue.

> Should this be more general?

We might think about generalizing across languages, along the lines of #299, although only R is context-aware right now.

**Comment by lionel-** [comment]
> I'm not sure what the use case would be

It's just that if we're going to have the pkg dev mode autoload itself, we might as well implement this on top of a more general variable since it's the same development cost. I've often been annoyed by the lack of eldoc in new buffers.

> I could see having a global set of packages to attach during development.

I thought we were talking about loading. Attaching is a different matter, so should be a different variable.

> Prompting the user to install or update the package while taking into account dependencies is a really good idea.

I'm not sure I understand this. I was thinking about loading pkg dependencies automatically, then I realised that most of the time those deps would be auto-loaded by R anyway.

> We might think about generalizing across languages, along the lines of #299, although only R is context-aware right now.

Yes, Vitalie is interested in making package management more general in ESS as well.

**Comment by lawremi** [comment]
> I'm not sure I understand this. I was thinking about loading pkg dependencies automatically, then I realised that most of the time those deps would be auto-loaded by R anyway.

Maybe I read too much into what you were saying, but I do think it would be a good idea to offer to install the package if it has not yet been installed. The simplest way would be `ess-r-devtools-install-package`, but I am thinking of fixing `install.packages` so that it supports direct package URLs while looking for dependencies in repositories.

**Comment by vspinu** [comment]
> I.e. we could have a buffer-local variable ess-r-autoloaded-packages that could be set to a list of packages to load whenever a R process is attached to the buffer?

This is redundant with .Rprofile. Either site, user or directory specific. I commonly add .Rprofile to my projects such that whenever I start R in that directory all packages are loaded.

> Maybe I read too much into what you were saying, but I do think it would be a good idea to offer to install the package if it has not yet been installed.

Sometimes I am just inspecting the source code of a package and I don't want to install it. 

I think we are missing install-and-load command. Maybe we always want to load a package after an install? Devtools re-loads it anyways if the package is already loaded. 

 > f there was some way of marking the package stale, even if only within the same Emacs session, we could prompt the user to reinstall the next time R is started.

Yes. Happens to me often as well. 

> could it also optionally load (and optionally attach) the namespace when R

I think just loading will not work for eldoc and completion. We need to attach it with current implementation. Or we can enhance the completion system to understand development files and fetch internal variables for that package and dependencies.

**Comment by lawremi** [comment]
> Sometimes I am just inspecting the source code of a package and I don't want to install it.

Which is why I said "offer to", i.e, the user could be prompted. I don't think ESS should ever modify the package library without explicit user consent.

**Comment by lionel-** [comment]
> I think just loading will not work for eldoc and completion.

oh, indeed. Don't know why I thought that was the case.

> Or we can enhance the completion system

We should definitely try to support namespaced symbols such as `foo::bar()` with eldoc and completion. As a bonus, would be great to analyse the package deps in the DESCRIPTION file and have completion/eldoc working with imported functions even if their package is not attached in the R process.

**Comment by lawremi** [comment]
Agreed. To me it seems logical that if user evaluation is happening inside of the namespace, so should all evaluation / symbol lookup.

**Comment by vspinu** [comment]
> Which is why I said "offer to", i.e, the user could be prompted.

I am not sure how to deal with this. Let assume you are in the package source file. ESS wants to show an eldoc completion but the package is not loaded or not even installed yet. What shall we do now? At least two cases to consider:

  1. Package has been installed but might not reflect the current state of the code. Shall we load it in the background and use outdated completion? I think we should. It's not a big deal for the completion. If the user wants to re-install it it's one key press away. (But there is a caching bug right now - all completions except for objects from .GlobalEnv are cached and re-install will not invalidate the package cache. This is easy to fix.)

  2. Package has not be installed yet. What shall we do? We shouldn't prompt from eldoc or company/ac completion. So the best is probably to do nothing.


Back to the stale package issue. How can we implement this stale package detection? Does R store the package install timestamp? If so, then we can check for both, version and install timestamp, and then compare those with the modification timestamps of the package at point.

**Comment by vspinu** [comment]
> We should definitely try to support namespaced symbols such as foo::bar() with eldoc and completion.

I think we do it just fine right now. The missing part is that we don't show completions for internal functions inside package files.

**Comment by lionel-** [comment]
> I think we do it just fine right now.

Both completion and eldoc should work with namespaced symbols when the package is not attached. It has always bugged me that this doesn't work well. 

ESS is not very friendly to users who don't attach everything. That's too bad because it's good practice not to attach every single package used in a project. That's why I fixed help-at-point on namespaced objects last month.

**Comment by vspinu** [comment]
> Both completion and eldoc should work with namespaced symbols when the package is not attached. It has always bugged me that this doesn't work well. 

I don't understand what is exactly bugging your. Completion for namespaced symbols and eldoc work even if packages are not attached. For concreteness, I type `Matrix::spa` and I get all exported objects. Same for non-exported objects with `Matrix:::spa` and  eldoc within those functions.

**Comment by lionel-** [comment]
oh, neither work on my computer. Will try to investigate why when I find the time.

**Comment by lawremi** [comment]
> I am not sure how to deal with this. 

The suggestion to prompt for automatic installation was only in the context of explicitly starting R, or maybe when assigning an R process to a buffer. Starting R in the background is an interesting idea, and I agree about how it should behave. But if someone starts a foreground/visible R process, what should happen? I would guess the background process would either be killed or brought to the foreground, and the buffer would associate with the foreground process.

More ways to use the R process: checking whether a symbol is in scope using the codetools package, "go-to-definition" using R and packages built with source references instead of tags, all sorts of refactoring tasks that would easy to implement in R, etc.

> Does R store the package install timestamp?

It should be easy to find the installation directory and check the modification time on that. Everything would have to happen through the R process so that it works remotely.

**Comment by vspinu** [comment]
>  or maybe when assigning an R process to a buffer.

This might work well actually as every buffer is at some point assigned a sub-process.

> >   Does R store the package install timestamp?
> It should be easy to find the installation directory and check the modification time on that. 

Firstly, the package could be installed from a different source other than the local code base. Secondly, your proposal gives the last modified time of the package directory and not the timestamp of the installation.

In order to have a full picture, we would need at least three things - installed package version, installed location (CRAN, github, local dir etc), last install timestamp.

**Comment by lawremi** [comment]
I don't think we need absolute perfection here. The DESCRIPTION file in the installation directory (not to be confused with the package directory) has a `Built` entry that gives the timestamp, which is a bit cleaner than checking the mtime of the directory. 

But you're right that this breaks down if someone installs from somewhere else. There is no standard way to record the source of the package, although I think `install_github()` does record the github repository. The question is how careful do we need to be. If we wanted to be conservative, we could add an entry to the DESCRIPTION during installation that marks the source directory. If ever we do not see a matching entry, we issue a warning and/or prompt to install. But that will be a false positive if the user installs with something other than ESS. That might be going too far, though. We can always check the version. It's pretty rare in my workflow at least to install one of the packages I develop from another location. Mostly I do that to get the dependencies installed automatically, but we've already talked about solving that issue.
