### ISSUE TITLE
R-3.3.0 endless loop in browser if error sent via `ess-eval-region`

### ISSUE THREAD

**Issue by r2evans** [emacs-ess/ESS#334]
Problem with R-3.3.0 and current ESS. Not a problem with R-3.2.5.

Setup, two buffers:

1. `sample-code.R`:

    foo # undefined variable

2. R buffer (currently using R-3.3.0-64bit)

This works as expected (aka **Expected behavior** both in and out of debugger):

    # highlight "foo" from other buffer, press C-c C-r (ess-eval-region)
    R> foo
    Error in eval(expr, envir, enclos) (from source-code.R!8984SBp#1) : object 'foo' not found
    R>

This enters endless loop (**Actual behavior**):

    R> { browser() ; 1 ; } # "1" to stay in debugger
    debug at #1: browser()
    Browse[1]> 
    # highlight "foo" from other buffer, press C-c C-r
    R> foo
    Error in eval(expr, envir, enclos) (from source-code.R!8984fLv#1) : object 'foo' not found
    R> foo
    Error in eval(expr, envir, enclos) (from source-code.R!8984fLv#1) : object 'foo' not found    
    R> foo
    Error in eval(expr, envir, enclos) (from source-code.R!8984fLv#1) : object 'foo' not found
    # unending

**Versions**:
Win10pro
R: 3.3.0, both 32bit and 64bit
Emacs  : GNU Emacs 24.5.1 (i686-w64-mingw32) of 2016-03-23 on WARLOCK
Package: ess-mode 16.04 [elpa: 20160515.512]

**Emacs current state**:

    (setq
     ess-language "S"
     ess-dialect "R"
     ess-ask-for-ess-directory nil
     ess-ask-about-transfile nil
     ess-directory nil
     ess-keep-dump-files "always"
     ess-source-directory "C:\\Users\\r2\\AppData\\Local\\Temp"
     ess-use-ido t
     ess-use-eldoc t
     ess-use-tracebug t
     ess-use-auto-complete t
     ess-use-company t
     ess-eval-visibly-p t
     ess-can-eval-in-background nil
     ess-local-process-name "R"
     )

Repeat: this does NOT happen with R-3.2.5.

**Comment by lionel-** [comment]
I can't reproduce on master. Are you working on the release ESS or Melpa ESS?

**Comment by r2evans** [comment]
Melpa ESS.

Just confirmed that it's specific to the directory in which the source file is located. For instance, when located in a non-package directory (e.g., `~/Downloads/source-code.R`), the error does not occur. When located within a package directory structure, the error occurs. Does this mean it's related to the devmode auto-package namespace-managing something-or-other (that I really like)?

**Comment by lionel-** [comment]
oops, of course, I can replicate now. Thanks for the report!

**Comment by vspinu** [comment]
I don't see this whatever try. @lionel-, is this a tracebug issue or dev-eval?

```
> version
               _                                          
platform       x86_64-pc-linux-gnu                        
arch           x86_64                                     
os             linux-gnu                                  
system         x86_64, linux-gnu                          
status         Patched                                    
major          3                                          
minor          3.0                                        
year           2016                                       
month          05                                         
day            17                                         
svn rev        70631                                      
language       R                                          
version.string R version 3.3.0 Patched (2016-05-17 r70631)
nickname       Supposedly Educational                     
```

**Comment by lionel-** [comment]
The combination of both I think. I reproduced it by `C-c C-t C-s *some package*` and then evaluating a non existing object in a debug session. I'm travelling so I can't look into it before next week.

**Comment by lionel-** [comment]
I can't track this bug down. Possibly callback related. Doesn't seem to be caused by the new mpi system though. @vspinu you can't reproduce it even when you have namespaced eval active? I tried it with last 3.3.0-patched and it's still there.

**Comment by lionel-** [comment]
it's crippling enough that I had to disable auto-activation of namespaced eval in packages :/

**Comment by vspinu** [comment]
It's R's bug.  I have reported it [here](https://bugs.r-project.org/bugzilla/show_bug.cgi?id=16971).

I have found the workaround for now. Will commit it soon.

**Comment by lionel-** [comment]
Thanks Vitalie!

**Comment by r2evans** [comment]
Ditto, thank you!

**Comment by vspinu** [comment]
Fixed on R side as well.
