### ISSUE TITLE
ESS modes do not play well with git-timemachine, ediff, etc

### ISSUE THREAD

**Issue by nico202** [emacs-ess/ESS#336]
I'm experiencing this: https://github.com/pidu/git-timemachine/issues/18
Any way to get it fixed?
Thanks, Nicolò

**Comment by lionel-** [comment]
Yes, wait for the ESS rewrite :)

**Comment by nico202** [comment]
Perfect, thanks!

**Comment by yvanrichard** [comment]
Any news on this? That'd be really great to get it working

**Comment by lionel-** [comment]
We're slowly getting there but likely not before next year.

**Comment by jabranham** [comment]
These modes work fine for me now, just FYI.

**Comment by lionel-** [comment]
Great thanks!
