### ISSUE TITLE
file.remove warnings, "no such file or directory"

### ISSUE THREAD

**Issue by r2evans** [emacs-ess/ESS#339]
I can't nail exactly when it triggers, but occasionally when I'm debugging a function and either quit-out or continue-out, I get a spurious warning:

    Warning in file.remove(file) :
      cannot remove file 'c:/Users/r2/AppData/Local/Temp/process.R!3976AVi', reason 'No such file or directory'

I understand that these temp files are created when using `ess-eval-region` (or similar functions) for easy sourcing. The only culprit I can find in ESS is in [`.ess.eval` (line 72)](https://github.com/emacs-ess/ESS/blob/199a7114b182dc9d9fd3c1891422bca04d88a779/etc/ESSR/R/.basic.R#L72).

Might it be better to either suppress it or check first? One of these patches:

* Suppress the warning:
    ```diff
--- .basic.R.orig       2016-06-03 12:51:03.705679900 -0700
+++ .basic.R    2016-06-03 12:51:12.866014400 -0700
@@ -69,7 +69,7 @@
     ## create FILE, put string into it. Then source.
     ## arguments are like in source and .ess.source
     cat(string, file = file)
-    on.exit(file.remove(file))
+    on.exit(suppressWarnings(file.remove(file)))
     .ess.source(file, visibly = visibly, output = output,
                 max.deparse.length = max.deparse.length,
                 local = local, fake.source = TRUE)
```

* Check for existence first
    ```diff
--- .basic.R.orig       2016-06-03 12:51:03.705679900 -0700
+++ .basic.R    2016-06-03 12:52:38.019956300 -0700
@@ -69,7 +69,7 @@
     ## create FILE, put string into it. Then source.
     ## arguments are like in source and .ess.source
     cat(string, file = file)
-    on.exit(file.remove(file))
+    on.exit(if (file.exists(file)) file.remove(file))
     .ess.source(file, visibly = visibly, output = output,
                 max.deparse.length = max.deparse.length,
                 local = local, fake.source = TRUE)
```

* Use `unlink` instead, it invisibly returns 1 if it existed, 0 if not, but no warnings.

    ```diff
--- .basic.R.orig       2016-06-03 12:51:03.705679900 -0700
+++ .basic.R    2016-06-03 12:55:37.706627700 -0700
@@ -69,7 +69,7 @@
     ## create FILE, put string into it. Then source.
     ## arguments are like in source and .ess.source
     cat(string, file = file)
-    on.exit(file.remove(file))
+    on.exit(unlink(file))
     .ess.source(file, visibly = visibly, output = output,
                 max.deparse.length = max.deparse.length,
                 local = local, fake.source = TRUE)
```

`ess-version: 16.04 [elpa: 20160515.512] (loaded from c:/Users/r2/.emacs.d/elpa/ess-20160515.512/)` on win10, R-3.2.5

**Comment by lionel-** [comment]
Your existence check seems like the best workaround.

But I don't understand how this can happen. The `cat(string, file = file)` should ensure the file is created. Maybe `string` contains R code that deletes the file in some debugging situations? In that case the file would be deleted by calling `.ess.source()` before `on.exit()` is run.

**Comment by r2evans** [comment]
This is odd, certainly. I'll see if I can find a reproducible trigger. Debugging is a bit onerous since `debug(.ess.eval)` does not work. Is there an easy way to trigger debugging of function in the `ESSR` namespace? I can't figure it out.

Because the filename is not being generated by `tempfile` (which should be something like `.../ESSd2472c91901`), then what is being used to generate the temp file names? I see `.ess.eval` is being called for each of `ess-eval-command`, `ess-eval-visibly-command`, and `ess-eval-visibly-noecho-command`, so could there be a collision on the named temporary file?

(The only place I see `.ess.eval` being called is in `lisp/ess-r-d.el`.) 

     (ess-eval-command                  . ".ess.eval(\"%s\", FALSE, FALSE, file=\"%f\")\n")
     (ess-eval-visibly-command          . ".ess.eval(\"%s\", TRUE, TRUE, 300, file=\"%f\")\n")
     (ess-eval-visibly-noecho-command   . ".ess.eval(\"%s\", FALSE, TRUE, 300, file=\"%f\")\n")

**Comment by vspinu** [comment]
I have never seen such warnings. It might be something Win specific. But are you sure it comes from there? If you apply any of your patches, do you stop seeing those warnings?

**Comment by r2evans** [comment]
I've applied the `file.exists` patch, I'll let you know if I see the bug again. (Unfortunately I haven't been able to reproduce it on-demand.)

**Comment by r2evans** [comment]
Nope, that doesn't fix the problem. If it helps, it seems to happen recently when I'm in the debug/browser mode using `ess-eval-region`

**Comment by r2evans** [comment]
Found a reliable reproduction. While in an R package directory:

    sapply(1:2, function(i) {
      browser()
      1
      2
    })

1. Highlight this code, eval it with `ess-eval-region`. I'm in the debugger.
2. Highlight a line (or two), eval it with `ess-eval-region`. (I don't think the code you highlight must be within the block.)
3. Continue (`M-S-c`) or quit (`M-S-q`) the debugger. I get the "no such file" error every time with this.

This does *not* trigger it if any one single condition below is true:

* Not in an R package directory.
* The entire file is loaded (e.g., with `C-c C-l`), triggering the browser.
* Use `C-c C-n` (`ess-eval-line-and-step`) within the block instead of `ess-eval-region`).

Let me know if there's another way I can help debug this from my end.

**Comment by vspinu** [comment]
We were mistakenly deleting the file twice. Nothing serious.

**Comment by r2evans** [comment]
Thanks again
