### ISSUE TITLE
How to complete on dot?

### ISSUE THREAD

**Issue by ikzk** [emacs-ess/ESS#340]
For example, in ess-julia-mode, after I import a module by `import Plots`, how can I get the completion when I input `Plots.`?

**Comment by vspinu** [comment]
It should be there by default. If it's not, that means completion in julia broke
again for Xth time. Look into ESS/etc/ess-julia.el in the section ### OBJECT
COMPLETION. It should be trivial to fix if you know julia a bit.

  Vitalie

**Comment by ikzk** [comment]
@vspinu Thanks for your reply. The functions there work well. My problem is that the completion only shows up when I enter two characters after the dot `Plots.pl`, but not immediately after I enter the dot.

There is a `jedi:complete-on-dot` variable in the jedi package for python autocompetion, but I did not find a similar option for ess (julia).

**Comment by vspinu** [comment]
Ah. I see. That means it's an elisp problem. In R completion is triggered on $ and @. So it should be triggered on . in julia as well.

**Comment by ikzk** [comment]
@vspinu Thanks for your explanation. Will there be any plan to fix this feature for julia?

**Comment by vspinu** [comment]
Yes. This should be fixed. I got a bit of free time and will try to have a look at it these days.

**Comment by ikzk** [comment]
@vspinu Thanks!

**Comment by vspinu** [comment]
I finally got down to this. What other characters except "." should be considered part of symbol on completion or help lookup?

**Comment by ikzk** [comment]
@vspinu  Thanks! I haven't found any other special characters yet.

**Comment by ikzk** [comment]
@vspinu I just found that `::` might worth consideration. Here is an example

```
function myfunc(a::int)
    a
end
```
where `:: `specifies the type of the argument. Is the autocompletion of the types easy to implement?

**Comment by vspinu** [comment]
Completion of types doesn't make sense in declaration. Anything could follow ::, it's up to you what you put there. Of course we can sniff for all declared types and complete on that, but it looks to me like a very small gain for the bang. Also other company backends (e.g. company-dabbrev-code) will likely pick it up and complete that word anyways.

**Comment by ikzk** [comment]
@vspinu I see. Thanks for your explanation!
