### ISSUE TITLE
To be improved behaviours of julia repl

### ISSUE THREAD

**Issue by ikzk** [emacs-ess/ESS#342]
![ss](https://cloud.githubusercontent.com/assets/18649508/15982389/107bb940-2f54-11e6-8e52-6894d0fbff9b.png)
First, the repl shows a warning every time I start it.
Second, I can even delete the `julia>` prompt with backspace, which generally should be prohibited.

Thanks!

**Comment by vspinu** [comment]
Nothing can we do with the warning. It comes from Julia. 

By "generally" what do you mean? `comint-prompt-read-only` is nil by default, so "generally" prompt is editable. And my personal opinion is that you should it read as such. Read only prompts badly interfere with comint buffer editing.

**Comment by ikzk** [comment]
@vspinu I am not an expert on this, but I tried `julia-shell-mode` and found that there is no such warning message in the repl, though I don't know how they avoid this issue.
For the editable prompt, IMHO, people like me may prefer a repl feels like a "normal" terminal. Maybe I am too used to cider's repl. This is not a usability issue, and it's only a little suggestion. You may take it or not :)

Thanks for your work on this great tool! I'll close this issue since it's mainly comes from my personal taste. You may reopen it if you want.

**Comment by vspinu** [comment]
> but I tried julia-shell-mode and found that there is no such warning message in the repl, though I don't know how they avoid this issue

it probably has to do with `-q` argument which we don't send.

>  Maybe I am too used to cider's repl. This is not a usability issue, and it's only a little suggestion. You may take it or not :)

It's not about taking or not. It's for you to customize `comint-prompt-read-only` or not. Cider's shell is not a true comint shell (at least it wasn't last time I checked).

**Comment by ikzk** [comment]
> It's not about taking or not. It's up to you to customize comint-prompt-read-only or not. Cider's shell is not a true comint shell (at least it wasn't last time I checked).

That works! Thank you. I did not know this option previously.
