### ISSUE TITLE
discussion: sublimity or minimap not working in ess-mode

### ISSUE THREAD

**Issue by r2evans** [emacs-ess/ESS#346]
I've tried both [sublimity](https://github.com/zk-phi/sublimity/) and [minimap](https://github.com/dustinlacewell/emacs-minimap), and though they both work somewhat in other buffers, neither works in ESS (or iESS) buffers. (This fact was mentioned with minimap almost two years ago: dustinlacewell/emacs-minimap#10, no commentary or commits since.)

I don't expect those working on ESS to be responsible for this, this is not a bug report. Do you know what in ESS could be responsible for disabling the functionality?

(I know it's weak, but I swear I played with both of these a year or two ago, so it worked at some point.)

**Comment by vspinu** [comment]
Hm. Not sure why wouldn't that work with ESS.  For me it doesn't work with any mored. `M-x sublimity-mode` produces nothing.

**Comment by r2evans** [comment]
In hindsight, I was trying both and likely confused minimap's actions with sublimity activated. Bummer, it'd be cool to be able to use every now and then. (Even when working on other buffers, minimap was misbehaving, so perhaps neither is at all usable.) Thanks.

**Comment by jabranham** [comment]
Many things have changed since 2016. I'm closing this issue. If you still experience this, feel free to reopen or open a new issue.
