### ISSUE TITLE
Completions via company using melpa package don't work

### ISSUE THREAD

**Issue by jcpetkovich** [emacs-ess/ESS#347]
When trying to complete based on the names contained in objects or lists using the melpa package, I can't get completions to work.

I can reproduce this with the following steps:

1. `emacs -q`
2. setup `package.el`, install ess from melpa, install company.
3. `(load "ess-site.el")`
4. start R shell with `M-x R`
5. try to complete with `iris$P`
6. observe no completions

I'm using the latest version of the melpa package (`ess-20160703.731`).

Interestingly the functions `ess-R-object-completion` as well as `ess-R-complete-object-name` work just fine.

**Comment by vspinu** [comment]
Is this shell or script buffer? Do you see company completion on ordinary names? That is, is it failing on $ names? How about `::` ?

**Comment by jcpetkovich** [comment]
* This is a shell buffer started with `M-x R`.
* I see completions on ordinary names.
* It's failing on `$` names and `::`
* candidates are picked up by `TAB` but not company.
* forcing company to complete gives funny results as below

![2016-07-06-101051_3200x1800_scrot](https://cloud.githubusercontent.com/assets/159257/16620872/19c5738e-4362-11e6-80cb-c5241518b0ec.png)

The setup after wiping `.emacs.d` is:

```
(package-initialize)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
 ("gnu" . "http://elpa.gnu.org/packages/")))

(package-refresh-contents)

(package-install 'company)

(package-install 'ess)

(load "ess-site.el")
```

company-mode is enabled manually in the R buffer.

**Comment by vspinu** [comment]
Ok. I see. This is something recent. I guess it has to do with #329. There have been syntax changes there. Will have a look.

**Comment by jcpetkovich** [comment]
Investigating further (and forgive me if you already guessed this was the case), `company-R-objects` and `company-R-args` both provide no completions at `iris$`, but `company-capf` does.

**Comment by lionel-** [comment]
Indeed it's probably related to changes in the syntax class of `$` and `:`.

**Comment by jcpetkovich** [comment]
I'm trying to debug this or at least bisect it, but I'm not having luck even going back into the commit history of company mode. I've gone as far back as:

    company-mode: 6bf2491
    ESS: 6bf2491

But can't get working completion. Are either of you able to reproduce this? Or am I going crazy O_o

**Comment by vspinu** [comment]
I will fix this today. Sorry, haven't had time so far.

**Comment by jcpetkovich** [comment]
Thanks so much! Works over here as well!
