### ISSUE TITLE
ess taking a *huge* time to load in emacs

### ISSUE THREAD

**Issue by lbraglia** [emacs-ess/ESS#348]
Dear all, 

I've encountered the same problem reported (likely) by @juliangilbey here 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828046

This is without ESS
```
l@p6k:/media/shared$ time emacs -batch -eval '(nil)'
Loading 00debian-vars...
Loading /etc/emacs/site-start.d/50auctex.el (source)...
Loading /usr/share/emacs/site-lisp/auctex.el (source)...
Loading /usr/share/emacs/site-lisp/preview-latex.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Loading /etc/emacs/site-start.d/50emacs-goodies-el.el (source)...
Loading /etc/emacs/site-start.d/50maxima-emacs.el (source)...
Loading /etc/emacs/site-start.d/50python-docutils.el (source)...
Symbol's function definition is void: nil

real	0m0.067s
user	0m0.052s
sys	0m0.012s
```

while this is with ESS

```
l@p6k:/media/shared$ time emacs -batch -eval '(nil)'
Loading 00debian-vars...
Loading /etc/emacs/site-start.d/50auctex.el (source)...
Loading /usr/share/emacs/site-lisp/auctex.el (source)...
Loading /usr/share/emacs/site-lisp/preview-latex.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Loading /etc/emacs/site-start.d/50emacs-goodies-el.el (source)...
Loading /etc/emacs/site-start.d/50ess.el (source)...
Loading /etc/emacs/site-start.d/50maxima-emacs.el (source)...
Loading /etc/emacs/site-start.d/50python-docutils.el (source)...
Symbol's function definition is void: nil

real	2m8.148s
user	0m0.380s
sys	0m0.040s

```

I reproduced what above on my two home Debian Testing boxes (Emacs 24.5.1, ESS 16.04-2)

Any hint? I'm not a lisp programmer but available for further tests/infos

Thanks, best Luca

**Comment by vspinu** [comment]
2 minutes is way to much. It should take fraction of a second. The problem lies most likely within the ess-site.el in the portion that searches for R versions [here](https://github.com/emacs-ess/ESS/blob/master/lisp/ess-site.el#L617-L619). Do you have a network drive or you set `ess-directory-containing-R` to a very big dir?

**Comment by eddelbuettel** [comment]
By default the Debian /Ubuntu machines will have R in `/usr/bin/R` -- which should be found immediately.

(And FWIW I have NFS mounts at work but still launch Emacs / ESS instaneously.)

**Comment by lbraglia** [comment]
I've a standard Debian install of both R and ESS; my `/usr/bin/R` is on a local hard disk

Below the `.emacs` chunk regarding ess
``` lisp
;; -----
;; ESS
;; -----
(require 'ess-site)
;; non stampa i comandi valutati a schermo e velocizza di *molto* emacs
(setq ess-eval-visibly-p nil)
;; non chiede la directory di start e la setta a .
(setq ess-ask-for-ess-directory nil)
;; fixa l'output restituito per mostrarne il piu possibile
(setq comint-scroll-to-bottom-on-input 'this)
;; non salvare l'history
(setq ess-history-file nil)
;; indentazione a 2 C++ like
(setq ess-default-style 'OWN)
(setq ess-indent-level 2)
(setq ess-continued-statement-offset 0)
(setq ess-brace-offset -2)
(setq ess-arg-function-offset 0)
(setq ess-expression-offset 2)
(setq ess-else-offset 0)
(setq ess-close-brace-offset 0)
;; parametri passati per l'invocazione del processo R
(setq inferior-R-args "--no-save --no-restore")
;; disabilita la sostituzione automatica di _ con <-
(ess-toggle-underscore nil)

```

**Comment by eddelbuettel** [comment]
As I suggested to Julian, how about if you remove everything else from .emacs, see how it behaves with just ESS and then add pieces back in one-by-one.

There must be a real bad (and reproducible) interaction somewhere, but so far only Julian and you see it.

I have the packaged ESS and R on a number of different machines and no issues.

**Comment by vspinu** [comment]
Yeh. I think this is the only way to find the culprit. Go to ess-site.el and comment in and out pieces there till you find which part causes the problem.

**Comment by lbraglia** [comment]
ok, i'll test in order

-  commenting not-ess stuff in .emacs (and uncommenting single pieces back)

-  adding/removing packages 

- commenting ess-site.el

asap.. i'll let you know.

**Comment by juliangilbey** [comment]
I've located the culprit on my machine: it's tramp, which is required by ess-inf.  Without ess installed:
`time emacs -batch -q -eval '(nil)'` takes 0.669 seconds real time, while `time emacs -batch -q -eval "(require 'tramp)"` takes 6.309 seconds.  So I guess it's off to tramp to report a problem there...

**Comment by juliangilbey** [comment]
There's a fix for tramp, too; see [Debian bug#810640](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810640).  So this ess ticket can presumably be closed, as it's not an ess bug.

**Comment by lbraglia** [comment]
Confirmed... 

this is **with** ESS

```
l@p6k:~$ cat /etc/resolv.conf
nameserver 8.8.8.8
l@p6k:~$ time emacs -batch -eval '(nil)'
Loading 00debian-vars...
Loading /etc/emacs/site-start.d/50auctex.el (source)...
Loading /usr/share/emacs/site-lisp/auctex.el (source)...
Loading /usr/share/emacs/site-lisp/preview-latex.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Loading /etc/emacs/site-start.d/50emacs-goodies-el.el (source)...
Loading /etc/emacs/site-start.d/50ess.el (source)...
Loading /etc/emacs/site-start.d/50maxima-emacs.el (source)...
Loading /etc/emacs/site-start.d/50python-docutils.el (source)...
Symbol's function definition is void: nil

real	0m0.582s
user	0m0.392s
sys	0m0.024s

```

This ticket can be closed for me too.

Thanks @juliangilbey 

best, Luca

**Comment by davidcsterratt** [comment]
There is a patch for Ubuntu Xenial (16.04) too: https://bugs.launchpad.net/ubuntu/+source/emacs24/+bug/1594166
