### ISSUE TITLE
autocompletion of filenames

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#352]
I am using ess with company backend and in one of my projects i have a folder with 10.000+ files mounted over ethernet, file completion in hangs my emacs for minutes. Is there a way to exclude certain folders from completion or limit the maximum number of files?

**Comment by vspinu** [comment]
It's more for `company-files` backend. There is a variable `company-files--regexps` that you can try to play with. I don't see any other knobs that you can adjusts. 

In any case you will be better off asking this on company issue tracker. Sounds like a valid feature request.

**Comment by gdkrmr** [comment]
ok, thanks
