### ISSUE TITLE
Evaluation stuck for multi-line statements when using ess-eval-region-or-function-or-paragraph-and-step

### ISSUE THREAD

**Issue by rsuhada** [emacs-ess/ESS#353]
In a fresh ess-version: 16.04 [elpa: 20160723.1359] when a dplyr pipe spans multiple lines, the evaluation gets stuck:

This works fine:
> df %>% filter(x==3)

This unfortunately not:
> df %>%
> filter(x==3)

Thank you very much (ess is an amazing package - thank you very much for it!)

**Comment by izahn** [comment]
I can't reproduce that. What exactly did you do and what exactly happened?

**Comment by vspinu** [comment]
I cannot reproduce either.

**Comment by rsuhada** [comment]
Appologies for the late reply.

I've tested it and found the following:

1. it only happens when using
**ess-eval-region-or-function-or-paragraph-and-step** (C-c C-c)

It works OK, if I execute the multi-line block line-by-line with **ess-eval-region-or-line-and-step**

2. It is not limited to dplyr pipes, it seems it happens for any multi-line block, e.g.

> print(paste0("1",
>              "2"))

gets stuck when executed via C-c C-c.

Can you reproduce it this way? In the evening I'll check the behaviour on my home computer too.
Thank you for your patience!

**Comment by vspinu** [comment]
C-c C-c is a basic functionality and it works for all of us. It must be something specific to your system. 

Could you `M-x toggle-debug-on-quit` and when emacs gets stuck `C-g` and post the backtrace here.

**Comment by rsuhada** [comment]
Thank you. Here is the trace:

Debugger entered--Lisp error: (quit)
>   accept-process-output(#<process R> 0.5)
>   ess-wait-for-process(#<process R> t 0.001)
>   ess-eval-linewise("print(paste0(\"1\",\n             \"2\"\n
> ))")
>   ess-send-string(#<process R> "print(paste0(\"1\",\n             \"2\"\n
>             ))" t "Eval paragraph")
>   ess-tracebug-send-region(#<process R> 633 683 t "Eval paragraph" nil)
>   ess-send-region(#<process R> 633 683 t "Eval paragraph" nil)
>   ess-eval-region(632 683 nil "Eval paragraph")
>   ess-eval-paragraph(nil)
>   ess-eval-paragraph-and-step(nil)
>   ess-eval-function-or-paragraph-and-step(nil)
>   ess-eval-region-or-function-or-paragraph-and-step(nil)
>   call-interactively(ess-eval-region-or-function-or-paragraph-and-step nil
> nil)
>   command-execute(ess-eval-region-or-function-or-paragraph-and-step)

**Comment by vspinu** [comment]
Have you customized your prompt?

**Comment by rsuhada** [comment]
Yes, that is the solution. It is actually setting the "continue" parameter
in .Rprofile that caused the problem.
Interestingly in ESS 15.09 this worked correctly, but this is in a no way a
critical feature so I'm happy with the solution!

Thank you very much for your help!
