### ISSUE TITLE
Probable infinite loop when uncommenting an environment with Rnw-mode and AUCTeX

### ISSUE THREAD

**Issue by giordano** [emacs-ess/ESS#354]
Open the following `test.rnw` file with `Rnw-mode`, using AUCTeX's `LaTeX-mode`:

``` latex
\documentclass{article}
\begin{document}

% \begin{equation}
%   1+2=3
% \end{equation}

\end{document}
```

If I try to uncomment the `equation` environment Emacs freezes, apparently because a function enters an infinite loop that you can break with <kbd>C-g</kbd>.  Verified in Emacs 24.5.1.  Doesn't happen if AUCTeX is not used, and doesn't occur in a plain LaTeX file opened with just `LaTeX-mode`, so this may be due to some strange interaction between AUCTeX and ESS.

This has been first reported in AUCTeX's bug tracker: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24079  I wasn't able to find the culprit.  The function that halts is `uncomment-region-default`, but when I `edebug` it, the problem [disappears](https://en.wikipedia.org/wiki/Heisenbug).

**Comment by shawndway** [comment]
I also found that the same happens when I comment out the following

`
\documentclass{article}
\begin{document}

<<echo=FALSE,results='hide'>>
2+2
@

\end{document}
`
When I comment out the chuck, it goes into the infinite look.  This is on Emacs 25.0 and 24.5 with just ESS and Auctex installed.

**Comment by dromney** [comment]
I am also running into this issue. Emacs 24.5.1 on a PC. I am unable to recover the session, i.e. pressing `c-g` even multiple times does not seem to stop this from occurring.
