### ISSUE TITLE
Fontification of built-in help

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#355]
Some sections should be fontified with the dialect engine.

For R, `Usage` and `Examples` sections should be fontified as R code.

**Comment by vspinu** [comment]
The Examples is placed in R mode by polymode automatically. I strongly believe that examples should be editable. Usage highlighting was proposed in the past but I haven't looked into implementing that.

**Comment by lionel-** [comment]
Nice! Looks like I'll have to try the new polymode soon.

**Comment by vspinu** [comment]
> I'll have to try the new polymode soon.

Hm. This feature has been there since inception.

**Comment by lionel-** [comment]
Indeed. I needed a `(require 'poly-R)` in my config. Thanks!

**Comment by vspinu** [comment]
Finally, from today Usage is fortified as well but it's read-only.
