### ISSUE TITLE
ESS crashes Mac OS X when quitting

### ISSUE THREAD

**Issue by mok0** [emacs-ess/ESS#36]
My MacBook runs OS X Mountain Lion 10.8.2. I installed ESS version 12.09-2 from the tar file in the download area.

I can run a ESS session just fine, but when I exit Emacs and confirming that the R process should be killed, the screen immediately becomes grey and the computer reboots.

I have experienced this every time I have used ESS, but not since I realized that ESS was the reason for the reboot.

**Comment by dwisehart** [comment]
Almost two years later, I think this issue has been resolved.  I have not seen it from Mac OS-X El Capitan 10.11.2 (and previous), Emacs 24.5.1 and the latest ESS.

**Comment by vspinu** [comment]
Thanks for letting us know. It's little we can do on ESS side anyways.
