### ISSUE TITLE
Help key shortcuts mismatch?

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#363]
Is anyone else bugged by `d` being bound to help for objects and `o` for demos? This is really confusing I can't get used to that :/

I've just swapped them in my config but I think we should swap the default as well.

**Comment by vspinu** [comment]
C-c C-d C-d is bound to help (doc) in all major EDEs so no chance that could ever be changed. Nor I see any problem with that. I actually forgot about demos option and never used it :/.

**Comment by lionel-** [comment]
hmm, never thought about it in terms of doc. But it's not really descriptive, all keybindings from the doc-map are about doc. But if it's the convention, so be it.

**Comment by vspinu** [comment]
Strange that you find it problematic. `C-d C-d` is easy to type as it's the "doc" command among "doc" commands. Just like the most important command in C-c map is commonly on C-c.

**Comment by lionel-** [comment]
That's because I don't use Emacs keybindings and I just binded the help map to a leader key. So it never occurred to me that `d` was for `doc`, especially since I was thinking in terms of "help for object". The right mnemonic was H → O from that point of view. Maybe we'll discuss it again when Evil has taken over ;)
