### ISSUE TITLE
Change in ESS causing TRAMP to hang at "Sending password"

### ISSUE THREAD

**Issue by cswarth** [emacs-ess/ESS#364]
It sounds crazy that ess could affect tramp but that's what I'm seeing.   With the latest version of ESS from ~~elpa~~ melpa, opening a remote ssh connection via tramp, e.g. `/ssh:usr@machine:`, hangs after printing "Sending password".   When this happens tramp does not prompt for a password the way it normally does; it just goes right to the "Sending.." message.  While searching for a solution I came across [another report of the same bug](http://emacs.stackexchange.com/questions/26555/tramp-hangs-on-sending-password-whenever-ess-is-active).

I tracked the problem down to commit 6892dd2.  Changes introduced in this commit cause tramp to hang.  In fact only the one line change is necessary to cause the problem,
```
-(add-hook 'hack-local-variables-hook 'ess-r-package-auto-activate)
+(add-hook 'after-change-major-mode-hook 'ess-r-package-auto-activate)
```

I don't know why this gives tramp indigestion.  

I am seeing this under Aquamacs on MacOS,
```
ess-version: 16.04 [elpa: 20160825.413] (loaded from /Users/chris/Library/Preferences/Aquamacs Emacs/Packages/elpa/ess-20160825.413/)
[I actually think ess was loaded from melpa, not elpa]

$ /Applications/Aquamacs.app/Contents/MacOS/Aquamacs --version
GNU Emacs 24.4.51.2
[...]

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.6
BuildVersion:   15G31
```

**Comment by lionel-** [comment]
May be related to #362

**Comment by vspinu** [comment]
Thanks @cswarth  for the exact diagnostics. I never noticed this because the problem was not occurring with public key authentification.
