### ISSUE TITLE
Company does not work in scripts unless R process started

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#367]
Hi, and thanks for all your work.

For me, company mode does not work in a script unless I start an R process. Is this intended behavior? 

Thanks!

**Comment by yangdaweihit** [comment]
I met the same problem.

**Comment by eddelbuettel** [comment]
I suspect that is to be expected. If [company mode](http://company-mode.github.io/) shows context-related material for completion, it needs a mechanism to query that material -- and for R context it may need an R process to talk to.

**Comment by vspinu** [comment]
>  Is this intended behavior? 

Yes. The completion is requested from the running R process.

**Comment by stardiviner** [comment]
I have a question, How to create a function to auto start ESS process when first time open R/Julia file buffer. used on hooks like `ess-mode-hook` etc?

**Comment by vspinu** [comment]
You just call the available functions (R, julia etc).

**Comment by stardiviner** [comment]
@vspinu  I setup like this:
```elisp
(defun my-ess-auto-start ()
    (interactive)
    (unless (get-buffer "*ESS*")
      (user-error "ESS inferior process not started")
      (if (yes-or-no-p "Start an ESS inferior process? ")
          (ess-switch-process))))

  (add-hook 'ess-mode-hook #'my-ess-auto-start)
```
But this does not work. Do you know where is wrong?

**Comment by vspinu** [comment]
You are throwing an error there. How can it work?

Just keep the following:

```el
(when (y-or-n-p "Start an ESS inferior process? ")
  (ess-switch-process))
```

**Comment by stardiviner** [comment]
Should I keep `(unless (get-buffer "*ESS*")` line?
Because I need to detect whether ESS inferior process is started.

**Comment by vspinu** [comment]
In your place I would simply use `(ess-force-buffer-current)` in your hook without all those questions. It will silently associate the buffer with the running process if there is only one process running. If there are several, it will prompt. You can force it to prompt even for one process with `ask-if-1` argument. See the doc.

**Comment by stardiviner** [comment]
@vspinu Thanks very much. This help me a lot.
