### ISSUE TITLE
How to type _ ?

### ISSUE THREAD

**Issue by aviralg** [emacs-ess/ESS#368]
Hi,

Inside Emacs R buffer, I am unable to type `_` . Every time I do that, it replaces it with `<-`
Even if this behavior can be disabled through some package settings, it still seems like a bad default.

**Comment by richardsc** [comment]
Just hit `_` twice in a row to get an underscore. Or bind it to a different key (a quick google will tell you how to do that).

What seems like a "bad default" has a long history in *both* R *and* ESS.

**Comment by vspinu** [comment]
There is also `(ess-disable-smart-underscore)` .

**Comment by rsuhada** [comment]
`(ess-disable-smart-underscore)` doesn't work for me, but this does `(ess-toggle-underscore nil)`.
The only problem is that I have to manually execute it in the session. I have the following in the :config part of use-package ess

    (add-hook 'ess-mode-hook
            (lambda ()
              (ess-toggle-S-assign nil)
              (ess-toggle-underscore nil)
              ))

But on restart the pesky `<-` is back... Any tip how to persist the setting over sessions correctly?
Thank you!

**Comment by vspinu** [comment]
I personally do 

```el
(define-key ess-mode-map [?_] nil)
(define-key inferior-ess-mode-map [?_] nil)
```
