### ISSUE TITLE
ess-remote and julia

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#369]
using ess-remote and julia in a *shell* buffer gives me the following error:

ess-remote: Symbol’s value as variable is void: julia-customize-alist

although julia-customize-alist is definded, M-x julia also works fine.

ESS version 20160908.250 from melpa

**Comment by lionel-** [comment]
Should be fixed, could you check please.

**Comment by gdkrmr** [comment]
works on current master thanks!
