### ISSUE TITLE
Emacs 25.1 - *R* getting wrong PAGER environment var, breaking C-c C-v help() in R

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#371]
Today my work desktop was upgraded from Fedora Linux 22 to 24 ... which also brought me Emacs 25.1 ...
..  Somehow my *R* process now (most of the time, but not if I start a *second* R session) gets
```r
> Sys.getenv("PAGER")
[1] "more"
```
instead of  `"cat"`  and this does break R help (with `C-c C-v`) which calls something like
 utils::help("deparse",  help_type = "text")
and this now stops after showing a screen ful  with    "--More--"   
In ESS, this is more hidden and more confusing, because ESS calls help "in the background" in a new buffer,
but because of the "--More--" there,  ESS / R never finishes building up that help page, and *hangs*
(until I press `C-g`)...

Anybody got any clue, why in F24 / in Emacs 25.1,   suddenly the PAGER is set "wrongly" ? 

-------

Yes, a **workaround** is to do
```r
> Sys.setenv("PAGER" = "cat")
```
in R (or in your .Rprofile)....  but I thought we (ESS) would do something like that somewhere in any case?

**Comment by eddelbuettel** [comment]
I don't know the particulars but these things gets set at compile time of R.  I presume you build your own R for `/usr/bin` and `/usr/local/bin` too, not just R-devel -- so can you check that the `cat` binary is found?  

Oh, from my logs on the other distro:

```
checking for /usr/bin/pager... /usr/bin/pager
```

So maybe look at where `/usr/bin/pager` resolves to?

**Comment by mmaechler** [comment]
Thank you Dirk,... Actually, I think the `/usr/bin/pager` hint is not directly relevant here, as Fedora Linux has no `pager` executable, but of course `cat`, `more`, and `less` are all available. 
ESS (as R itself) really looks at  `getOption("pager")`  which for me is  `$RHOME/bin/pager` and that is a very simple `sh` script, using the $PAGER  environment variable ... at least in my setups where I have no `pager` executable.

OTOH,  ESS in several places tries to set "cat" to the pager,  and itself uses the `inferior-ess-pager` variable defined in ‘ess-custom.el’. and when I ask for it, its value is `"cat"`.
It used to be the case that ESS would ensure that this is used in *R*, but it seems no longer working in my current Emacs 25.1 (+ my defaults) setup.

**Comment by eddelbuettel** [comment]
My bad.  `/usr/bin/pager` may be a Debianism.

**Comment by mmaechler** [comment]
To add: This bug must be an "unfortunate" interplay of several parts,  notably ESS  and  emacs (comint / ?), so the "blame" is not on ESS alone :

More "data":  My  emacs  `process-environment`  always contains  `PAGER=more`   also in Fedora 22 (which I still have available via ssh .)    However, on Fedora 22, if I do   'emacs -q -f shell'  in that shell,
emacs has already been smart enough setting up comint, so that
```
mm~ada-3$ echo $PAGER
cat
mm~ada-3$ 
```
i.e., the PAGER is already set  emacs-friendly via comint....
and this is ... what I presume is what then also determines the working of ESS, i.e., I have  
`Sys.getenv("PAGER")   in R  return "cat"  there,   but "more" in Emacs 25.

The bug of ESS is that it does *NOT* do what it is documented:  It does not use   `inferior-ess-pager`  (which is "cat") to have R work with it... and hence the very bad "C-c C-v"  (= display-help-on-object ) no longer working, but rather hanging (with the "--More--" prompt... I see when I interrupt (C-g) and then press [Enter] in the *R* buffer.
