### ISSUE TITLE
Separate bindings for derived modes?

### ISSUE THREAD

**Issue by nverno** [emacs-ess/ESS#372]
I was only using ess for R code until recently, but just started experimenting with its julia support and was wondering why there aren't separate mode maps / derived modes?  

What is the proper approach to specifying mode specific bindings for derived modes?  Roll your own minor mode or is there a customization already?

**Comment by lionel-** [comment]
This is for historical reason. The next iteration of ESS will have proper modes. For now you are stuck with using custom functions that test for `ess-dialect` or writing custom minor modes.

Now that you mention minor modes, we could have one minor mode per dialect to create dialect-specific mode maps...

**Comment by nverno** [comment]
Ok, thanks for the quick response!  Thats fine, I just wanted to make sure I wasn't reinventing something for no reason.  It looks like you guys already have minor modes for dev/package so I was surprised not to find one for R.  Thanks
