### ISSUE TITLE
add autoloads from ess-julia to ess-autoloads

### ISSUE THREAD

**Issue by nverno** [emacs-ess/ESS#374]
Would it be possible to add the autoloads from ess-julia to ess-autoloads?  Are there plans to create autoloads in general instead of needing to require the entire ess ecosystem?

**Comment by lionel-** [comment]
yes there are plans

**Comment by nverno** [comment]
I didn't realize autoloads aren't created within a condition-case statement.  The autoloading works with just the addition of 

```
(require 'ess-comp)
(require 'ess-r-d)
```
