### ISSUE TITLE
R help not output to emacs buffer

### ISSUE THREAD

**Issue by r2evans** [emacs-ess/ESS#378]
Symptom: `?lm` (also `help("lm")`, `help.search("lm")`, similarly for other R functions), the help contents are flashed in an external window (outside emacs). `*Messages*` buffer just adds an empty line, no textual error message.

Per #371, I verified the following, no change:

```r
Sys.getenv("PAGER")
# [1] "cat"
getOption("pager")
# [1] "cat"
getOption("help_type") 
# [1] "text"
```

Per #313, I don't get the same behavior. Just to verify, I added https://github.com/emacs-ess/ESS/commit/e082889b718ec060628bb9bab75f58e78e9526b5 locally and still does not work.

```
GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-09-17
ess-version: 16.09 [elpa: 20160930.1243] (loaded from c:/Users/r2/.emacs.d/elpa/ess-20160930.1243/)
```

**Comment by nverno** [comment]
I had the same thing, resulting from [8dd46cf](https://github.com/emacs-ess/ESS/commit/8dd46cf442a2269dd06d084a98a5aeff11fa7579#diff-f1632d04c646e31a5fda6c2c64d30b9b).

Restting `options(pager="console")` from inferior R fixed it.

**Comment by r2evans** [comment]
This is truly weird -- testing this, it worked. I then put it back to what it was before with the environment and conditions that triggered the error, and it worked (where it failed yesterday). Between yesterday and today, there is no difference in any versions or options set. Sporadic behavior is troubling.

So both `"console"` and `"cat"` work for me at the moment.

Thanks @nverno. I'll close this shortly if I cannot retrigger the problem.

**Comment by nverno** [comment]
@r2evans I wouldn't close it, it is an issue on windows.  You should be able to retrigger it by restarting emacs.

**Comment by mmaechler** [comment]
The change I had committed solved very "broken" behavior in Emacs 25.1 and my setup which ended setting the PAGER environment variable to "more".  The change does what we have documented for years to do -- but must have dropped doing years ago -- namely it ensures the configureable emacs / ESS variable `inferior-ess-pager` is used in R for the pager option.

So, to solve your (Windows only, right ?) problem,  that variable should have been set to `"console"`  on Windows, shouldn't it?     Can you confirm that  `"console"` works fine there ?

**Comment by r2evans** [comment]
Yes, on emacs-25.1 on win10.

Setting `options(pager= "console")` in my `.Rprofile` in not enough, since your patch over-writes it after the R process has started. Using `M-x customize-variable`, setting `inferior-ess-pager` to `console` works for me.

You say *"should have been set"*, is this something that I should have been doing all along? Regardless, might I suggest (a) adding to the documentation and/or (b) using something like the following:

```diff
diff -u lisp/ess-custom.el.orig lisp/ess-custom.el
--- lisp/ess-custom.el.orig     2016-10-03 08:06:07.208166200 -0700
+++ lisp/ess-custom.el  2016-10-03 08:06:08.455162500 -0700
@@ -2161,7 +2161,7 @@
   :group 'ess-proc
   :type '(choice (const nil) file))

-(defcustom inferior-ess-pager "cat"
+(defcustom inferior-ess-pager (if ess-microsoft-p "console" "cat")
   "Pager to use for reporting help files and similar things."
   :group 'ess-proc
   :type 'string)
```

**Comment by mmaechler** [comment]
No, no: Not **you** should have ..., but **we**, the ESS developers should have.  Your patch proposal above seems perfect to me. ...  I think your '(b)' should be enough:   As our documentation has always been saying hat `nferior-ess-pager` is used... (but it had no longer been used for quite some time).

A more careful (and more work) change would be to only call `oprionts(pager = ..)` from R, when that pager looks like R's default pager (which uses the system $PAGER ... and that is unreliable).
