### ISSUE TITLE
Request: saving sessions

### ISSUE THREAD

**Issue by torbjorn** [emacs-ess/ESS#38]
Before I worked with R from emacs, I had a function save.work("some tag") # that would save history and save image and create two files with timestamp and "some tag" in their filename in a dedicated projcet sub directory.

This allowed me to load both data and history from a compiled list of work sessions, and was a fast way to set my mental context back to where I were when I left off.

From emacs unfurtunately savehistory is not available, what other ways is there to achieve this?

It would be nice to have some simple functionality that would:
- save a valid R-history
- save.image
- save the _R_ buffer with all its content
- label and timestamp it in a meaningful way

And then functionality that would restore it later, ie start a R process, load hitsory from last time, load the _R_ buffer content from last time (maybe omitting parts where I by accident print big data objects?), load the data from last time, and essentially bring me back to where I were when I left off.

All of this should be doable, but I wouldn't quite know where to start.

T.

**Comment by hwinkler** [comment]
Another motivation for making savehistory() work from within ESS is that after crashes of Emacs, the next session has an out-of-date .Rhistory, missing the commands from the crashed session. This problem @torbjorn reported still exists.

**Comment by vspinu** [comment]
> the next session has an out-of-date .Rhistory,

That's an annoying problem but it's not quite related to this pull. .Rhistory is handles by `comint` and not by R. Feel free to open a new issue. This should be addressed in a better way than it is now implemented.

**Comment by dwisehart** [comment]
I agree that having savehistory() work from ESS would be a big advantage.  If no one else has, I can open a new issue.
