### ISSUE TITLE
Too smart [Tab] completion wrongly inserts `...=`  e.g., inside `list( )`

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#380]
This is not exactly new... but has not been in 16.04 I think.   I'd really like  to see this fixed before releasing  ESS 16.10 

```r
list(
    a = pi,
    ## <-- pressing [Tab] before/at the 1st '#'  wrongly  *inserts*  `` ...= ''
    )
```

as the comment says, the above is  _magically transformed_ to
```r
list(
    a = pi,
    ...=## <-- pressing [Tab] before/at the 1st '#'  wrongly  *inserts*  `` ...= ''
    )
```

**Comment by vspinu** [comment]
Is it TAB or M-TAB. I can see this happening with M-TAB. TAB is bound to `ess-indent-or-complete` by default.

**Comment by mmaechler** [comment]
It is TAB, and indeed `ess-indent-or-complete`.  It is completion: As `list()`s argument list is *only* `...`, and we are inside `list( . )`,  "machine thinks" to be helpful by inserting what it "thinks" to be the correct argument name plus a `=`.      If you replace `list` by `c`, you do not (yet) see the problem, because `c` formally has another argument besides `...`  (but this will change; has already changed in R-devel).

ESS (and possibly also R's completion engine ?) should *never* propose  `...`  as argument name when it is part of the formal arguments.

**Comment by mmaechler** [comment]
An even easier case: Put "the cursor" at the end of the single `list(` 
```r
list(
```
and now press `[Tab]`  .
The result ist
```r
list(...=
```
emacs' point still at the end of line, i.e., after the  `=`.
@vspinu  do you agree that this is not desired ?

**Comment by nverno** [comment]
A possible solution could be changing the regex in `ess-get-words-from-vector` to 

`"\"\\(\\(\\\\\\\"\\|[.]*[^.\"][.]*\\)*\\)\"\\( \\|$\\)"`

**Comment by mmaechler** [comment]
It's true, formally not language specific.  From the doc string, it is still designed to be used for "S", and "R" is a dialect of "S".  I'll commit something like this,.. in an (concat .) extended form that should be easier maintainable. Thank you @nverno !

**Comment by vspinu** [comment]
This is a (very) bad idea. `ess-get-words-from-vector` is a generic function. This should be fixed in the R completion engine instead. The easiest solution is rarely the correct one.

**Comment by mmaechler** [comment]
@vspinu, yes, as @nverno mentioned, and I acknowledged.  OTOH, the doc string of the function does only mention "S".  I'm happy if you (or someone else via pull request) can provide a better solution.  ESS really must workaround the problem for now.. it is is too embarrassing and cumbersome, and we *did* introduce it from our users' point of view ((also, Rstudio does not exhibit the problem)).... 
so  **please** keep the fix as long it is not replaced by a better fix somewhere else!

**Comment by mmaechler** [comment]
A much better solution : Use  R  to eliminate the `'...='`  because that's the problem, not "..." in itself, nor other `".."` (two '.' are ok!), even `...` is imaginable, but not the version with "="  as a function argument.  Ended with commit   eeba186 (and some aberring non-pushed commits in between)

**Comment by nverno** [comment]
The filtering could be done in `ess-R-get-completions` instead, either in R or emacs.  It seems that when completing arguments, in order to fit in with the current implementation, the first element of the returned completions should be an empty string.  I think altering the command to the following gives the same behaviour as before, except doesn't complete dots.
```
(cmd
 (format
  (eval-when-compile
    (concat "Filter(function(x) grepl(\"^$|[[:alnum:]]\", x, perl=TRUE),"
            ".ess_get_completions(\"%s\", %d))\n"))
  (ess-quote-special-chars prefix)
  (- end start)))
```

**Comment by nverno** [comment]
Oh I hadn't noticed the new message @mmaechler, looks good.  I didn't realize you would want to keep non alphanumerics.
