### ISSUE TITLE
inferior-ess-r-reload asks for a directory every time

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#381]
Is there a way to avoid this?

plus: `inferior-ess-r-reload` should probably be in the `ess-r-package-dev-map` by default.

**Comment by lionel-** [comment]
I think I know what it is, will upload a fix tonight.

If given a keybind it should not be in the package dev map but the general map. I never know what kind of keybindings to assign since I use Evil.

**Comment by gdkrmr** [comment]
I used:
``` elisp
(define-key ess-r-package-dev-map (kbd "C-q") 'inferior-ess-r-reload)
```
because `C-r` is already occupied

**Comment by vspinu** [comment]
It could be on the extra map `C-c C-e C-r`. I think it's a rather handy command.

**Comment by gdkrmr** [comment]
just tried it out (latest master, emacs -Q), ess still asks for the directory if I do `C-c C-e r`. It does not reload the package any more if I am in a package directory.

Is there a way to restart the inferior R buffer in a predefined directory without being asked interactively?  E.g. `(inferior-ess-reload "~/package-dir/")`

**Comment by lionel-** [comment]
ok I thought this was linked to package handling but in fact we need to start ESS with the currently active directory even if `ess-ask-for-ess-directory` is set to `t` (I have set it to nil for years and so had completely forgotten about it). Will push a fix tonight.

**Comment by gdkrmr** [comment]
setting `ess-ask-for-ess-directory` to `nil` does the trick for me!

**Comment by lionel-** [comment]
but it should be fixed without that now

**Comment by gdkrmr** [comment]
reloading works now without asking , even if `ess-ask-for-ess-directory` is `t`, it was just that I did not know about that variable.
