### ISSUE TITLE
add a way to reload documentation files

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#382]
this would be really useful for package development, should probably be bound to `g`.

**Comment by lionel-** [comment]
like C-c C-w C-d?

**Comment by gdkrmr** [comment]
this rebuilds the documentation, but if I do `C-d C-d foo`, the documentation for `foo` opens, then if I change the documentation of `foo` and  do `C-d C-d` it will not show the updated documentation, even if I rebuild and reload the package inbetween.

**Comment by vspinu** [comment]
Try killing the buffer or issue C-d C-d with C-u prefix. ESS doesn't reload the doc if it's already open.

**Comment by gdkrmr** [comment]
In case someone finds it useful:
``` elisp
(defun ess-r-rebuild-doc-and-reload-package ()
  "rebuild documentation and reload current package"
  (interactive)
  (ess-r-devtools-document-package)
  (ess-r-devtools-load-package))

(define-key ess-r-package-dev-map (kbd "C-b") 'ess-r-rebuild-doc-and-reload-package)
```
So after `C-c C-w C-b` I can update the documentation of a function with `C-u C-c C-d C-d`
