### ISSUE TITLE
syntax highlighting in @examples is broke

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#386]
Syntax highlighting in the `@examples` section of Roxygen comments broke a while ago.

**Comment by lionel-** [comment]
what do you mean?

**Comment by gdkrmr** [comment]
it is just in the standard comment color
![screenshot_2016-10-26_10-45-36_2](https://cloud.githubusercontent.com/assets/12512930/19719347/cf0b57c2-9b69-11e6-81d5-d7b339def744.png)

**Comment by lionel-** [comment]
it is disabled by default because it's buggy, you have to turn it on.

**Comment by gdkrmr** [comment]
ok, thanks.
