### ISSUE TITLE
Chunk selection

### ISSUE THREAD

**Issue by AntonioFasano** [emacs-ess/ESS#388]
With my setup, under Windows, `ess-noweb-mark-chunk` leaves out the `@` from the selection.
To include the missing character, I can modify a bit this function:

    (defun ess-noweb-mark-chunk ()
      "Mark the current chunk."
      (interactive)
      (let ((r (ess-noweb-chunk-region)))
        (goto-char (car r))
        (push-mark (1+ (cdr r)) nil t)))

into: 

    (defun ess-noweb-mark-chunk ()
      "Mark the current chunk."
      (interactive)
      (let ((r (ess-noweb-chunk-region)))
        (goto-char (car r))
        (push-mark (+ 2 (cdr r)) nil t)))

Can you please tell me, whether this is the intended behaviour or there is a problem in my setup?

Update: added modified function

**Comment by jabranham** [comment]
ess-noweb stuff is now obsolete, poly-R is the replacement
