### ISSUE TITLE
Julia mode: wrong indentation after anonymous function 

### ISSUE THREAD

**Issue by phipsgabler** [emacs-ess/ESS#396]
If I write

```{Julia}
function bla(bar)
    x = function(x)
        1
    end
        a = 42
    end
```

the stuff after the literal gets automatically indented like shown here - it doesn't seem to recognize the `end`. However, if a space is inserted before the argument, like so:

```{Julia}
function bla(bar)
    x = function (x)
    #           ^
        1
    end
    a = 42
end
```

it works properly. Since the first version is legal code, that should probably be corrected. 

It also gets "better" if an extra `end` is inserted afterwards:

```{Julia}
function bla(bar)
    x = function(x)
        1
    end
        a = 42
    end
end
```

Although that doesn't compile, of course...

(And I think I'm using an up-to-date release, 16.10-1.)

**Comment by kzapfe** [comment]
I have the same issue, i think. Let me check.

**Comment by jabranham** [comment]
I don't see this with current ESS and julia-mode, perhaps it was a bug in julia-mode that they fixed recently? 

Closing this, let me know if you still experience it and I'll reopen.
