### ISSUE TITLE
ess-sas-submit with tramp

### ISSUE THREAD

**Issue by huajie06** [emacs-ess/ESS#397]
Hello,  

When using tramp and say my files is at /ssh:user@server:/home/dir/test.sas.

ess-sas-submit will "cd user@server:/home/dir/test.sas" which would give the error. The substring seems only take the first ":" onward of the ess-sas-file-path?

I'm running emacs on Cygwin, server is Linux.

**Comment by rsparapa** [comment]
Correct, in the *shell* buffer, you will see: cd "/home/dir/test.sas"  However, you get around the error by going into the *shell* buffer and doing: ssh user@server
