### ISSUE TITLE
Feature Request: compile Rmd to PDF 

### ISSUE THREAD

**Issue by paynito** [emacs-ess/ESS#401]
Hi, I tried to write a function for this, I think I have the syntax a little broken. It might be a nice addition to ess.  

    ;; a function to compileRmdToPdf

     (defun compileRmdToPdf () "Compiles the current buffer as a pdf" (interactive)
      (call-process("R -e 'rmarkdown::render("%s", \"pdf_document\")'" buffer-file-name)))

      ;; a keybinding to call it

      (global-set-key (kbd "M-m c p") (lambda () (interactive) 'compileRmdToPdf)) ; compile pdf

**Comment by basille** [comment]
What about something like that:

    (defun ess-render ()
      "Run rmarkdown::render on the visited buffer."
      (interactive)
      (let* ((rmd-buf (current-buffer)))
        (update-ess-process-name-list)
        (cond ((= 0 (length ess-process-name-list))
               (message "No ESS processes running; starting R")
               (sit-for 1); so the user notices before the next msgs/prompt
               (R)
               (set-buffer rmd-buf)
               )
              ((not (string= "R" (ess-make-buffer-current))); e.g. Splus, need R
               (ess-force-buffer-current "R process to load into: "))
              )
        (setq-local ess-dialect "R")
        (ess-force-buffer-current)
    
        (save-excursion
          (let* ((output-format-table (make-hash-table :test 'equal)))
              (puthash "HTML" "html_document" output-format-table)
              (puthash "PDF" "pdf_document" output-format-table)
              (puthash "All" "all" output-format-table)
              (let* ((sprocess (ess-get-process ess-current-process-name))
                     (sbuffer (process-buffer sprocess))
                     (buf-filename (buffer-file-name))
                     (output-format-user (completing-read "Output format: " '("HTML" "PDF" "All")))
                     (output-format (gethash output-format-user output-format-table))
                     (render-cmd
                      (format "rmarkdown::render(\"%s\", output_format = \"%s\")" buf-filename output-format)))
                (message "Running Render on %s" buf-filename)
                (ess-execute render-cmd 'buffer nil nil)
                (switch-to-buffer rmd-buf)
                (ess-show-buffer (buffer-name sbuffer) nil))))))

That will dynamically ask for the output format (possibilities are HTML, PDF or All). It's mostly untested, so let me know weather if dramatically fails, or if other options are worth passing to the function!

**Comment by mmaechler** [comment]
I would very much like to add this to ESS.   Actually we need more of these, notably, `evaluate-current-chunk-and-forward-to-next-chunk` etc.

**Comment by benyomin** [comment]
Yes, I'm not sure if this should actually go in ESS or in poly-mode. So, 
    
    evaluate-current-chunk-and-forward-to-next-chunk

doesn't exist?  I've been using C-<return> on each line. It would nice to be able to execute the current multi-line function.

**Comment by richardsc** [comment]
I second @mmaechler's sentiment that it would be great to have more options for interacting with code chunks in ESS (or polymode). Even though I can't use it for serious work, RStudio has really done a look of good things with making Rmd editing easy (evaluate all chunks, evaluate current and forward to next, etc). E.g.
![image](https://cloud.githubusercontent.com/assets/233584/23133825/e0d2f1f8-f768-11e6-8089-8a0612f3cae9.png)

I typically do the same as @benyomin , just use C-return or perhaps C-c C-c (though this has a weird effect that it includes the ``` at the end of the chunk and causes R to spit an error -- I usually workaround this by leaving a blank line at the end of my chunks).

**Comment by mmaechler** [comment]
Indeed, the current very little options to work with R code in Rmd  are so limited notably against the ever increasing features in Rstudio to do the same,  that I -- who has been using Emacs almost exclusively since about 1991 (!)   have started to switch back and forth between Rstudio and emacs when dealing with *.Rmd.  ... this is just not tolerable any more.   I don't care much where the necessary functionality is added.   To me, adding features to `polymode` is more work because I don't know the code and am mainly interested in the *.Rmd (and *.Rnw) support  and *.Rmd support is much more limited than old ESS' *.Rnw support.

**Comment by vspinu** [comment]
There are two things there, first is compiling the whole buffer to pdf or html. In polimode that's `M-n e` chose Rmarkdown or Rmarkdown-ESS and you get a lot of options from there. 

@richardsc, the chunk evaluation in polymode with C-c C-c doesn't include `'''` that has been fixed years ago. If you have an example of such behavior please open an issue. 

As to @mmaechler  request for various chunks evaluation mechanism, I am really guilty. This is an easy to add feature which I was promising for a while now. 

Could you please compile a list of such chunk evaluation commands that you would like to see?  What should be the key sequence? How about putting them on a separate keymap on `M-n c` (for _c_hunk)?

**Comment by richardsc** [comment]
> richardsc, the chunk evaluation in polymode with C-c C-c doesn't include ''' that has been fixed years ago. If you have an example of such behavior please open an issue.

Ah, you're right. Sorry for the noise. I got so used to my workaround I didn't notice that it wasn't needed anymore! Thanks!

**Comment by mmaechler** [comment]
A separate keymap maybe needed. It does give one key more to type for every such command, so if it can be avoided these would be even more useful....

**Comment by academikuser** [comment]
M-n e   
    M-n e runs the command polymode-export (found in poly-markdown-mode-map), which
    is an interactive Lisp function in ‘~/OneDrive/privatemacslayrs/polymode/polymode-export.el’.
