### ISSUE TITLE
ess-roxy-should-indent-line-p not defined

### ISSUE THREAD

**Issue by plantarum** [emacs-ess/ESS#403]
Hi,

The function [ess-roxy-maybe-indent-line](https://github.com/emacs-ess/ESS/blob/master/lisp/ess-roxy.el#L441) calls the function [ess-roxy-should-indent-line-p](https://github.com/emacs-ess/ESS/blob/master/lisp/ess-roxy.el#L450), but the latter function is not defined. It appears to have been removed in commit [6fa3615f5dcfd87801a42d6c4586ad12b6a1c582](https://github.com/emacs-ess/ESS/commit/6fa3615f5dcfd87801a42d6c4586ad12b6a1c582#diff-09a18b9509d2fed728c02d246a7953fa).

This breaks fill-paragraph for me in R source files. My `fill-paragraph` is advised by `ad-Advice-fill-paragraph` and `pm-execute-narrowed-to-span` (from polymode). I can't find any trace of  `ad-Advice-fill-paragraph` anywhere in my own .emacs.d/ or the ess source files, so perhaps I've managed to secretly break this myself?

Thanks,

Tyler

**Comment by plantarum** [comment]
Ok, I found the source of the first advice, it's from `(defadvice fill-paragraph ...` in `ess-roxy.el`.

**Comment by vspinu** [comment]
I am curious why this didn't emerge earlier. I have no problems with fills. @lionel- I guess the intention of that commit was to replace `    (ess-roxy-should-indent-line-p)` with `ess-roxy-maybe-indent-line`?

**Comment by lionel-** [comment]
Same, I refill roxy paragraph all the time and haven't had a problem, that's strange. It looks like just removing the line should do it, I'll look into it.
