### ISSUE TITLE
function definition indentation not respecting (ess-offset-arguments . prev-line)

### ISSUE THREAD

**Issue by archenemies** [emacs-ess/ESS#407]
Issue #164 is related.

I'm using the "RStudio-" style which is the only one with (ess-offset-arguments . prev-line). It's nice and compact:

      legend("topleft",col=c("black","red","green"),
        lwd=c(1,1,1),
        lty=1,legend=c("116-118Hz","119-121Hz", "Background"))

However, somehow I'm not allowed to have this compactness for function definitions. ESS idents the following like so:

    amp_plot = function(d1,d2, outfile=NULL, correct=F, export=F,
                        show_unsmooth=T
                        ) {

I would like function definitions to be consistent with other instances of argument lists, for instance if I change "function" to "function1" then ESS indents the way I want it to:

    amp_plot = function1(d1,d2, outfile=NULL, correct=F, export=F,
      show_unsmooth=T
    ) {

Can this be fixed, or can someone point me to a workaround? Thank you!

**Comment by lionel-** [comment]
Please see the help for `ess-align-arguments-in-calls`.

**Comment by lionel-** [comment]
and I must add that the style you want is highly unconventional ;)

**Comment by archenemies** [comment]
Yay! Thank you.

> and I must add that the style you want is highly unconventional ;)

You will be assimilated.


P.S. Would it make sense for the "ess-offset-arguments" documentation to point to the aforementioned "ess-align-arguments-in-calls"? Not that I would have necessarily read that, but ...
