### ISSUE TITLE
ess-eval-visibly nil or 'nowait has extra `+` in output

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#409]
Evaluating this code: 

```R
library(dplyr)
mtcars %>%
  group_by(cyl) %>%
  summarize(m = mean(wt),
            n = n())
```

with `(setq ess-eval-visibly t)` (the default) produces this in the iESS buffer: 

```
# A tibble: 3 × 3
    cyl        m     n
  <dbl>    <dbl> <int>
1     4 2.285727    11
2     6 3.117143     7
3     8 3.999214    14
```

While setting `ess-eval-visibly` to `'nowait` or `'nil` produces this:

```
> + + + # A tibble: 3 × 3
    cyl        m     n
  <dbl>    <dbl> <int>
1     4 2.285727    11
2     6 3.117143     7
3     8 3.999214    14
```

Including the `>` and `+` symbols can make the output more confusing to read when it's more complicated since alignment gets messed up.

I'm running Emacs 25.1, ess-version 16.10-1 [elpa: 20170227.802] on a linux system.

**Comment by vspinu** [comment]
There is already a mechanism that tries to insert new lines after +++, but it fails on some occasions, yours being one of them. I am reasonably sure that that mechanism could be improved.

**Comment by jabranham** [comment]
Thanks. If you can point me to that, I can take a look to see if I can improve it. I'm having problems finding that on my own.
