### ISSUE TITLE
make now fails

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#410]
After the commits of yesterday,
my emacs startup  breaks early  -- yes, it has relied on ESS features and on the `ess-utils` filename.

When trying to get an emacs start without errors, I found  that  `make` also stopped working inside the `lisp` directory.

**Comment by mmaechler** [comment]
It did no longer fail after I fixed the other issue #411 .

I of course agree that ESS should not store / have to know where it was built... but it should know where it was *installed* (and where the ./etc/ and other stuff is installed).  In my (probably your?) case, these two places (built / installed)  are the same.
Historically ESS has always "found out itself" where it is installed -- unless the caller defined the `ess-lisp-directory` (and similar variables) itself.... and consequently the 
startup instructions for ESS have always just been something like
>     "load ess-site from your ~/.emacs"
and that had stopped working -- together with `make` -- after the commit series from March 25.

**Comment by lionel-** [comment]
> but it should know where it was installed 

A simple call to `locate-library` should do it. We should probably replace uses of `ess-lisp-directory` with calls to that library.

**Comment by lionel-** [comment]
Sorry Martin, I think I was just confused by the double use of that variable. I think the current definition in `ess-site` is fine, but the one in `ess-utils` (which prevails when users load ESS from non-site loading points) should simply call `locate-library`.

I've implemented that strategy and added some documentation, see https://github.com/emacs-ess/ESS/commit/dd623f1c67c54fb1f9c20403fa976cb1272a5074
