### ISSUE TITLE
ess-roxy-preview-HTML complains about unexpected END_OF_INPUT

### ISSUE THREAD

**Issue by johndoe28** [emacs-ess/ESS#413]
Consider the following code:

##' .. description
##'
##' .. content
##' @title foo
##' @param x 
##' @param y 
##' @param z 
##' @return baz
foo = function(x,y,z = TRUE) {
    baz();
}

If you put point in emacs in the comment and execute the function ess-roxy-preview-HTML, you will get the following error:

foo

Description:

     .. description

Usage:

     foo(x, y, z = TRUE)
     
Arguments:

       x:

       y:

       z:

Details:

     .. content

Value:

     baz

Warning message:
In parse_Rd("c:/Users/xxx/AppData/Local/Temp/RD_13108V6l.Rd",  :
  c:/Users/xxx/AppData/Local/Temp/RD_13108V6l.Rd:20: unexpected END_OF_INPUT '.. content
'
If you execute instead the command ess-roxy-preview-Rd, you will see the generated Rd code is missing a closing brace '}'.

% Generated by roxygen2: do not edit by hand
% Please edit documentation in RtmpMpNQI8/file22343b5692
\name{foo}
\alias{foo}
\title{foo}
\usage{
foo(x, y, z = TRUE)
}
\arguments{
  \item{x}{} \item{y}{} \item{z}{}
}
\value{
baz
}
\description{
.. description
}
\details{
.. content

**Comment by mmaechler** [comment]
I''m also seeing this bug more often than I want.
The bug must be inside  `ess-roxy-preview`  .. I have just pushed a313565f97badfefb289672af45df6311060eef3, 
a slightly nicer formatted version of that, for easier bug fixing.
