### ISSUE TITLE
Allow ESS to work with Stata-SE and Stata-MP

### ISSUE THREAD

**Issue by LaDilettante** [emacs-ess/ESS#414]
Right now `M-x stata` invokes `stata`, which points to Stata-IC, the least powerful version of Stata.

Most users would have Stata-SE, if not Stata-MP. Could we define a new mode for these two? I should be identical to `stata`, just pointing to another executable.

**Comment by lionel-** [comment]
I think where `stata` points to is dependent on your installation. You can change that symlink or you can change the Emacs variable `inferior-STA-program-name`.

**Comment by lionel-** [comment]
(I don't think there's a robust cross-platform way of figuring out the commands location, but if there was we could reopen this)

**Comment by LaDilettante** [comment]
`M-x customize variable RET inferior-STA-program-name` works perfectly.

**Comment by lionel-** [comment]
oups I didn't mean to reopen that. Glad it worked out.
