### ISSUE TITLE
SAS Interactive Session Windows

### ISSUE THREAD

**Issue by kfoley15** [emacs-ess/ESS#417]
Currently an interactive session requires the stdio option which isn't available on Windows.  However there seems to be options to run interactive sessions on Windows using IOM, with the ability to get logs, listings, and results back.  

An example of using such a session through PowerShell can be found [here](https://gist.github.com/FriedEgg/9085229#file-sasworkspaceexample-local-ps1).

My question is if it's possible to leverage this technique to enable local interactive sessions for SAS on Windows?  

I've looked a bit at the source code but my elisp is fairly lacking.  If someone with more knowledge were able to weigh in and give some guidance I'd be happy to contribute with as much grunt work as I can.

**Comment by rsparapa** [comment]
It's theoretically possible.  But we currently have no interest in implementing that ourselves.  Of course, patches welcome.
