### ISSUE TITLE
How to specify a shell when making system call from R code block in org-mode?

### ISSUE THREAD

**Issue by FirasSadiyah** [emacs-ess/ESS#418]
I have a couple of R code blocks in an org file. All of the blocks share the same R session through the `:session *R*` identifier. A couple of code blocks make use of the system() function to 1) load some modules (in a cluster environment) and 2) call some shell commands to process some data and inject the results back in org-mode/iESS. 

My question is how to specify one shell for all the code blocks so that the modules loaded in (1) are preserved for the following commands in (2)?

I tried to pass `:session *R* :session *shell*`, but the code is taking too long to execute and I do not know if it is doing anything. 

* Using ESS layer in spacemacs based on emacs 26, R 3.3.3 and zsh .

**Comment by izahn** [comment]
I don't think there's anything to be done from the ESS side. Either run your code in a babel `sh` block, or, if you must run it through R / `system()`, you might be able to use tmux for session management.

**Comment by vspinu** [comment]
Indeed. This could not and should not be done from ESS/org side. As @izahn said, the best strategy is to figure it on your R session side or sh scripts.
