### ISSUE TITLE
Automatically open .R files in R-mode

### ISSUE THREAD

**Issue by mcandre** [emacs-ess/ESS#42]
Currently, you have to insert the following into `.emacs` in order for `.R` files to open in R-mode:

    (autoload 'R-mode "ess-site.el" "" t)
    (add-to-list 'auto-mode-alist '("\\.R\\'" . R-mode))

Could we please register .R file extensions with R-mode as part of ess installation?

**Comment by davidshepherd7** [comment]
Any plans to fix this?

If not maybe you could add something to the README to describe what users need to do in order to start using R-mode:

    Setup for package.el users
    ===============

    To automatically enable `R-mode` in `.R` files add the following to your init.el file:

        (autoload 'R-mode "ess-site.el" "" t)
        (add-to-list 'auto-mode-alist '("\\.R\\'" . R-mode))


Otherwise people (like me) will assume that it should "just work" and be confused when it doesn't.

**Comment by vspinu** [comment]
> Any plans to fix this?

Yes. I hope to fix this by the next release. Haven't had much time so  far.

**Comment by davidshepherd7** [comment]
Great :)
