### ISSUE TITLE
My ubuntu 17.04, emacs25 ess 16.10 , auto-complete can not be actived,when i start R in emacs.

### ISSUE THREAD

**Issue by bfdddp** [emacs-ess/ESS#422]
My ubuntu 17.04, emacs25 ess 16.10 , auto-complete can not be actived,when i start R in emacs.

Auto-complete can work in my emacs25 correctly.  After M-x  R  RET started R  auto-complete can not be actived. I have to q() and input "M-x  R RET " restarts R. auto-complete works correctly! I install ess15.09, this bug was gone. AC works very well. Please help me .  This is my init.el :+1: 

自动完成 在我 使用 M-x R  RET 后进入R。自动完成不能激活，我只能q（）退出R，重新进入R后自动完成自动加载。使用 ess15.09-2 没有这个bug。谁能帮我解决。我们配置如下：

;emacs插件源
  (require 'package) ;; You might already have this line
(add-to-list 'package-archives
             '("popkit" . "http://elpa.popkit.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize) 
   ;; You might already have this line
;;自动完成
(add-to-list 'load-path "~/.emacs.d/elpa/auto-complete-20170125.1045")
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "~/.emacs.d/elpa/auto-complete-20170125.1045/dict")
(ac-config-default)
;;(auto-complete-mode 1)

**Comment by lionel-** [comment]
I hope you have solved your issue, otherwise please post on the ESS help mailing list.
