### ISSUE TITLE
Emacs version requirements

### ISSUE THREAD

**Issue by izahn** [emacs-ess/ESS#427]
According to http://ess.r-project.org/Manual/ess.html#Requirements ESS requires Emacs 24.3 or higher.  However, `(require 'ess-site)` fails on Emacs 24.3 with `"Cannot open load file" "subr-x`. According to https://github.com/syl20bnr/spacemacs/issues/375 `subr-x` was added in Emacs 24.4. Either the documentation should be updated to indicate that 24.4 or higher is required, or the dependency on subr-x should be removed. I'm happy to submit a pull request if needed, just let me know if the docs or the implementation should be changed.

**Comment by rsparapa** [comment]
Let's fix the docs

**Comment by rsparapa** [comment]
Docs now require 24.4 or higher

**Comment by mmaechler** [comment]
Unfortunately, Ubuntu 14.04 LTS (Long Time Support) has only Emacs 24.3,  and that LTS is still supported for a while.  I do have such a machine - actually my only Ubuntu/debian machine "at my fingertips" at work.
I really would like we get back to use workarounds such that  ESS continues working with a LTS version of a major linux distro.

**Comment by mmaechler** [comment]
@izahn : If you're still willing to look into a PR to circumvent the `subr-x` dependency, that would be nice.

**Comment by ess-core** [comment]
I would like the same (same issue with our stock corporate redhat
distribution :( )

On Mon, Oct 16, 2017 at 6:52 PM, Martin Mächler
<notifications@github.com> wrote:
> Unfortunately, Ubuntu 14.04 LTS (Long Time Support) has only Emacs 24.3,  and that LTS is still supported for a while.  I do have such a machine - actually my only Ubuntu/debian machine "at my fingertips" at work.
> I really would like we get back to use workarounds such that  ESS continues working with a LTS version of a major linux distro.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-ess/ESS/issues/427#issuecomment-336950299
>         [[alternative HTML version deleted]]
>
> _______________________________________________
> ESS-core list: https://stat.ethz.ch/mailman/listinfo/ess-core



-- 
best,
-tony

blindglobe@gmail.com
Muttenz, Switzerland.
"Commit early,commit often, and commit in a repository from which we
can easily roll-back your mistakes" (AJR, 4Jan05).

Drink Coffee:  Do stupid things faster with more energy!

**Comment by mmaechler** [comment]
After just releasing ESS 17.11  -- I've been told by the volunteer porting ESS to SuSE Linux (in way that is also used for Redhat, Fedora)  that our new requirement of ess version >= 24.4   makes it impossible to include the new ESS into SuSE Linux stable.    Is their really no reasonable way to work without that requirement, i.e., to use "cheap substitute" code when `subr-x`  is not available ??

**Comment by lionel-** [comment]
@mmaechler do you have an Emacs < 24.4 on your computer? If yes could you please try to comment out the `(require 'subr-x)` in ess-r-completion.el and recompile ESS?

It looks like I added that line during a cleanup but that may be a merge mistake.

**Comment by dsteuer** [comment]
@lionel-  @mmaechler I'm that volunteer Martin talked about. If I comment out that line I can compile ESS for the current openSUSE Leap 42.3.

**Comment by lionel-** [comment]
Then I'm sorry it's my fault. I vaguely remember @vspinu fixing that subr-x dependence and I must have bring it back after rebasing the codebase cleanup PR that was sitting in the requests for a year :/

**Comment by mmaechler** [comment]
Thank you @dsteuer .  Yes, I have access to a VM running ubuntu 14.04 LTS.  
Of course, if the emacs lisp compilation does not fail, that's a very good indication it's not needed at all.
I'll try to work a bit on that VM.   Should   I consider re-releasing ESS 17.11 (would be nice) or rather call it 17.11-1 (less nice, but being super meticulous ..)

**Comment by lionel-** [comment]
We should probably set up Travis with different Emacs versions too and have it compile ESS and run the tests automatically.

**Comment by izahn** [comment]
I'm personally not motivated to fix it since I agree with @rsparapa's original decision to update the documentation rather than the code. 24.4 is over three years old now. IMO, distributions that insist on shipping old software are responsible for shipping compatable extensions.

All that said, if there is consensus that we really do want to support a three-year-old version of Emacs, I will look into it. Does such consensus exist?

**Comment by mmaechler** [comment]
Well, in this case, it was *so* cheap to fix the problem, we did it.

I strongly emphasize back compatibility in such cases.  I know how computer environments are set and how they change in some organizations.   
Staying with stable / LTSversions of a Linux system is not a bad strategy for a company.
I'd like to not lose those ESS users.

Indeed, my short usage of the ESS version w/o 'subr-x  seems to indicate no problems.  So I *have* commited and pushed it  *and* updated the *.tgz and *.zip  files .. feeling that I'm allowed to do so within 5 hours.  -> closing now.

**Comment by dsteuer** [comment]
If the (require 'subr-x) crawled in by error it seems an easy decision to remove that line again. 
Especially if ESS compiles fine without. But I'm no dev of course, maybe there is more to know about.

A quick read through ess-r-completion.el further seems to indicate that no function of subr-x is used there. So the require probably was just superfluous. Oh, I see Martin was faster than my argument :-)
