### ISSUE TITLE
ess-r-args-insert removes quotation marks (badly)

### ISSUE THREAD

**Issue by hendrikweisser** [emacs-ess/ESS#428]
The utility function `ess-r-args-insert` in "ess-r-args.el", which inserts parameters and their default values to R functions, removes quotation marks (`"`) from default values. This leads to syntactically invalid expressions and strange results for nested quotes (including problems with code highlighting).

For example, the result for `read.table` is this (after `quote=` the highlighting of strings gets confused):
```
read.table(file=, header=FALSE, sep=, quote="', dec=., numerals=c("allow.loss", "warn.loss", "no.loss"), row.names=, col.names=, as.is=!stringsAsFactors, na.strings=NA, colClasses=NA, nrows=-1, skip=0, check.names=TRUE, fill=!blank.lines.skip, strip.white=FALSE, blank.lines.skip=TRUE, comment.char=#, allowEscapes=FALSE, flush=FALSE, stringsAsFactors=default.stringsAsFactors(), fileEncoding=, encoding=unknown, text=, skipNul=FALSE)
```

**Comment by jabranham** [comment]
I'd vote for just removing that function and and while we're at it all of  `ess-r-args.el` in favor of eldoc.
