### ISSUE TITLE
/etc/emacs/site-start.d/50ess.el hangs when starting emacs24 as root

### ISSUE THREAD

**Issue by mcarifio** [emacs-ess/ESS#43]
With ess installed on Ubuntu raring, when start emacs24 as root, the site-wide startup file /etc/emacs/site-start.d/50ess.el hangs emacs startup.

As a workaround, I gzipped the file and emacs starts. But then emacs doesn't speak statistics.

---
# uname -a

Linux larry 3.8.0-22-generic #33-Ubuntu SMP Thu May 16 15:17:14 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

root@larry:/etc/emacs/site-start.d# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 13.04
Release:    13.04
Codename:   raring

root@larry:/etc/emacs/site-start.d# apt-cache show ess
Package: ess
Status: install ok installed
Priority: optional
Section: gnu-r
Installed-Size: 5331
Maintainer: ESS Debian Maintainers ess-debian@r-project.org
Architecture: all
Version: 12.09-2-1quantal0
Depends: dpkg (>= 1.15.4) | install-info, emacs23 | emacs22 | emacs21 | emacsen
Suggests: xlispstat, r-base | r-base-core, pspp, jags
Conflicts: dhelp (<= 0.3.12)
Conffiles:
 /etc/emacs/site-start.d/50ess.el 848ba5caab794872624a0c09f55c7a14
Description-en: Emacs mode for statistical programming and data analysis
 ESS ("Emacs Speaks Statistics") is a GNU Emacs and XEmacs mode for
 interactive statistical programming and data analysis. Languages
 supported are the S family (S 3/4, S-PLUS 3/4/5/6/7, and R), SAS,
 XLispStat, Stata, BUGS and Julia.
 .
 ESS grew out of the desire for bug fixes and extensions to S-mode and
 SAS-mode as well as a consistent union of their features in one
 package.
Homepage: http://ess.r-project.org

Package: ess
Priority: optional
Section: universe/math
Installed-Size: 5331
Maintainer: Ubuntu Developers ubuntu-devel-discuss@lists.ubuntu.com
Original-Maintainer: ESS Debian Maintainers ess-debian@r-project.org
Architecture: all
Version: 12.09-2-1
Depends: dpkg (>= 1.15.4) | install-info, emacs23 | emacs22 | emacs21 | emacsen
Suggests: xlispstat, r-base | r-base-core, pspp, jags
Conflicts: dhelp (<= 0.3.12)
Filename: pool/universe/e/ess/ess_12.09-2-1_all.deb
Size: 1639420
MD5sum: 30071b1812f752567f0493b5fb1bc47c
SHA1: 4e85ff2804f04555e994be75927e78c1d168fb4f
SHA256: 520aa6a01c3c5cf52c3d9909dfb95ebf392dbfd22263d217033468329d42acf8
Description-en: Emacs mode for statistical programming and data analysis
 ESS ("Emacs Speaks Statistics") is a GNU Emacs and XEmacs mode for
 interactive statistical programming and data analysis. Languages
 supported are the S family (S 3/4, S-PLUS 3/4/5/6/7, and R), SAS,
 XLispStat, Stata, BUGS and Julia.
 .
 ESS grew out of the desire for bug fixes and extensions to S-mode and
 SAS-mode as well as a consistent union of their features in one
 package.
Homepage: http://ess.r-project.org
Description-md5: f5e47a5777b8c61804112900078b7e16
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu

**Comment by davidcsterratt** [comment]
It may be that this bug is due to a [bug in tramp](https://bugs.launchpad.net/ubuntu/+source/emacs24/+bug/1594166), which has been causing ess (and hence emacs) to take a long time to start on Ubuntu Xenial (16.04) with emacs 24.5.1.

**Comment by eddelbuettel** [comment]
I am fairly sure it is, so please edit your `resolv.conf` and then close this.  (For what it is worth I (as well as colleagues) run ESS on various Ubuntu 16.04 machines alss having tramp without issue; I did help at least one colleague.)
