### ISSUE TITLE
indentation: embarrissingly "interpreting" syntax in strings

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#432]
Here's a commented code example

```r
## Indentation after string with "*"
fo4 <- function(x, ...) {
    if(length(x) > 0)
        warning("Result gave strings of *different* #{characters}")
                                         x
    ## 'x' wrongly indented -------here: ^
}
```

and "of course" everything back to normal, if you don't use `*` in the string

**Comment by owenRiddy** [comment]
This is likely the same bug as #446 . If that is so, the problem is being triggered by the presence of the # in the string.

**Comment by mmaechler** [comment]
Yes, that was my guess too that the combination of "*" and  "#" was wrongly interpreted  by the current indentation codes.
