### ISSUE TITLE
Remote Machine - ess-sas-sh-command: No such file or directory

### ISSUE THREAD

**Issue by kevinjfoley** [emacs-ess/ESS#433]
I'm getting the error 
> env: c:/.../.emacs.d/lib/ess/etc/ess-sas-sh-command: No such file or directory

when trying to run `SAS` on a remote machine through `plink` as my local machine is Windows.  It seems like `ESS` is looking for `ess-sas-sh-command` on my local machine instead of the server I'm connected to.  

My understanding is that `ESS` should properly handle this situation properly just by having a remote buffer open without me having to change anything else.  Is it possible the issue is because I'm using `plink` instead of `ssh` or is there something else I should be doing?

**Comment by rsparapa** [comment]
I'm not familiar plink.  But, ESS would assume that you are using the *shell* buffer.  I don't use Windows anymore. But, I have tested this with XWin32 which, as I recall, has an ssh.exe which you launch in the *shell* buffer.

**Comment by kevinjfoley** [comment]
`ESS` seems to be running everything on the remote machine fine, for example the .log and .lst buffers open fine are on the remote machine, the issue seems to be it's looking for `ess-sas-sh-command` on the C drive which doesn't exist on the remote machine.

**Comment by rsparapa** [comment]
But, ess-sas-sh-command is only used for interactive SAS.  Are you trying to initiate an interactive sesssion?  I don't think I have ever done that.  ESS' support of interactive SAS is somewhat limited.  You could try the command M-x ess-sas-interactive which is the function that we use for testing to see if that works remotely.

**Comment by kevinjfoley** [comment]
Running `ess-sas-interactive` from the remote shell brings up an interactive session in the shell where I can pass commands and see the results in that shell buffer.

**Comment by rsparapa** [comment]
Yup, this looks like a bug then.

**Comment by rsparapa** [comment]
Also note a related bug Issue 385

**Comment by ShuguangSun** [comment]
This issue need to be checked under new tramp version again or maybe emacs 27. There is a bug in the old version of tramp which add " c:/" to the file name and the remote dosen't recognize it. The most updated version tramp has fixed it.

**Comment by jabranham** [comment]
Sounds like this bug might be fixed, and since it hasn't seen any activity for a year I'm closing it. Feel free to reopen if it's still a problem.
