### ISSUE TITLE
interactive sas on remote unix server--"wrong-type-argument processp nil"

### ISSUE THREAD

**Issue by djh1202** [emacs-ess/ESS#435]
I've been trying to start a remote iESS session using M-x SAS on a remote unix server. Stata and R work fine, but when I try and start a SAS session it opens the four SAS windows but I get this "wrong-type-argument processp nil" error. Below is the backtrace...

Debugger entered--Lisp error: (wrong-type-argument processp nil)
  process-plist(nil)
  process-put(nil funargs-cache #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ( ...)))
  ess-process-put(funargs-cache #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ( ...)))
  (let* ((symbol-string (concat "inferior-" inferior-ess-program "-args")) (switches-symbol (intern-soft symbol-string)) (switches (if (and switches-symbol (boundp switches-symbol)) (symbol-value switches-symbol)))) (set-buffer buf) (inferior-ess-mode) (ess-write-to-dribble-buffer (format "(inf-ess 3.0): prog=%s, start-args=%s, echoes=%s\n" inferior-ess-program infargs comint-process-echoes)) (setq ess-local-process-name procname) (goto-char (point-max)) (if ess-history-file (if (eq t ess-history-file) (set (make-local-variable (quote ess-history-file)) (concat "." ess-dialect "history")) (if (stringp ess-history-file) nil (error "`ess-history-file' must be nil, t, or a string")))) (if ess-history-file (progn (setq comint-input-ring-file-name (expand-file-name ess-history-file (or ess-history-directory ess-directory))) (comint-read-input-ring))) (set-buffer (if switches (inferior-ess-make-comint buf-name-str procname infargs switches) (inferior-ess-make-comint buf-name-str procname infargs))) (set-process-sentinel (get-process procname) (quote ess-process-sentinel)) (let ((conselt (assoc procname ess-process-name-list))) (if conselt nil (setq ess-process-name-list (cons (cons procname nil) ess-process-name-list)))) (ess-make-buffer-current) (goto-char (point-max)) (setq ess-sl-modtime-alist nil) (set-process-filter (get-process procname) (quote inferior-ess-output-filter)) (inferior-ess-mark-as-busy (get-process procname)) (process-send-string (get-process procname) "\n") (if no-wait nil (ess-write-to-dribble-buffer "(inferior-ess: waiting for process to start (before hook)\n") (ess-wait-for-process (get-process procname) nil 0.01)) (ess-process-put (quote funargs-cache) (make-hash-table :test (quote equal))) (ess-process-put (quote funargs-pre-cache) nil) (process-put (get-process procname) (quote accum-buffer-name) (format " *%s:accum*" procname)) (set (make-local-variable (quote syntax-begin-function)) (function inferior-ess-goto-last-prompt-if-close)) (set (make-local-variable (quote font-lock-fontify-region-function)) (function inferior-ess-fontify-region)) (run-hooks (quote ess-post-run-hook)) (ess-load-extras t) (if no-wait nil (ess-write-to-dribble-buffer "(inferior-ess 3): waiting for process after hook") (ess-wait-for-process (get-process procname))))
  (if (and proc (comint-check-proc (process-buffer proc))) (progn (ess-write-to-dribble-buffer (format "(inf-ess ..): popping to proc\n")) (pop-to-buffer (process-buffer proc))) (let* ((symbol-string (concat "inferior-" inferior-ess-program "-args")) (switches-symbol (intern-soft symbol-string)) (switches (if (and switches-symbol (boundp switches-symbol)) (symbol-value switches-symbol)))) (set-buffer buf) (inferior-ess-mode) (ess-write-to-dribble-buffer (format "(inf-ess 3.0): prog=%s, start-args=%s, echoes=%s\n" inferior-ess-program infargs comint-process-echoes)) (setq ess-local-process-name procname) (goto-char (point-max)) (if ess-history-file (if (eq t ess-history-file) (set (make-local-variable (quote ess-history-file)) (concat "." ess-dialect "history")) (if (stringp ess-history-file) nil (error "`ess-history-file' must be nil, t, or a string")))) (if ess-history-file (progn (setq comint-input-ring-file-name (expand-file-name ess-history-file (or ess-history-directory ess-directory))) (comint-read-input-ring))) (set-buffer (if switches (inferior-ess-make-comint buf-name-str procname infargs switches) (inferior-ess-make-comint buf-name-str procname infargs))) (set-process-sentinel (get-process procname) (quote ess-process-sentinel)) (let ((conselt (assoc procname ess-process-name-list))) (if conselt nil (setq ess-process-name-list (cons (cons procname nil) ess-process-name-list)))) (ess-make-buffer-current) (goto-char (point-max)) (setq ess-sl-modtime-alist nil) (set-process-filter (get-process procname) (quote inferior-ess-output-filter)) (inferior-ess-mark-as-busy (get-process procname)) (process-send-string (get-process procname) "\n") (if no-wait nil (ess-write-to-dribble-buffer "(inferior-ess: waiting for process to start (before hook)\n") (ess-wait-for-process (get-process procname) nil 0.01)) (ess-process-put (quote funargs-cache) (make-hash-table :test (quote equal))) (ess-process-put (quote funargs-pre-cache) nil) (process-put (get-process procname) (quote accum-buffer-name) (format " *%s:accum*" procname)) (set (make-local-variable (quote syntax-begin-function)) (function inferior-ess-goto-last-prompt-if-close)) (set (make-local-variable (quote font-lock-fontify-region-function)) (function inferior-ess-fontify-region)) (run-hooks (quote ess-post-run-hook)) (ess-load-extras t) (if no-wait nil (ess-write-to-dribble-buffer "(inferior-ess 3): waiting for process after hook") (ess-wait-for-process (get-process procname)))) (save-current-buffer (set-buffer buf) (rename-buffer buf-name-str t)) (if (and inferior-ess-same-window (not inferior-ess-own-frame)) (switch-to-buffer buf) (pop-to-buffer buf)))
  (let* ((ess-directory (or startdir ess-directory)) (infargs (or ess-start-args inferior-ess-start-args)) (special-display-regexps nil) (special-display-frame-alist inferior-ess-frame-alist) (proc (get-process procname))) (if inferior-ess-own-frame (setq special-display-regexps (quote (".")))) (if (and proc (comint-check-proc (process-buffer proc))) (progn (ess-write-to-dribble-buffer (format "(inf-ess ..): popping to proc\n")) (pop-to-buffer (process-buffer proc))) (let* ((symbol-string (concat "inferior-" inferior-ess-program "-args")) (switches-symbol (intern-soft symbol-string)) (switches (if (and switches-symbol (boundp switches-symbol)) (symbol-value switches-symbol)))) (set-buffer buf) (inferior-ess-mode) (ess-write-to-dribble-buffer (format "(inf-ess 3.0): prog=%s, start-args=%s, echoes=%s\n" inferior-ess-program infargs comint-process-echoes)) (setq ess-local-process-name procname) (goto-char (point-max)) (if ess-history-file (if (eq t ess-history-file) (set (make-local-variable (quote ess-history-file)) (concat "." ess-dialect "history")) (if (stringp ess-history-file) nil (error "`ess-history-file' must be nil, t, or a string")))) (if ess-history-file (progn (setq comint-input-ring-file-name (expand-file-name ess-history-file (or ess-history-directory ess-directory))) (comint-read-input-ring))) (set-buffer (if switches (inferior-ess-make-comint buf-name-str procname infargs switches) (inferior-ess-make-comint buf-name-str procname infargs))) (set-process-sentinel (get-process procname) (quote ess-process-sentinel)) (let ((conselt (assoc procname ess-process-name-list))) (if conselt nil (setq ess-process-name-list (cons (cons procname nil) ess-process-name-list)))) (ess-make-buffer-current) (goto-char (point-max)) (setq ess-sl-modtime-alist nil) (set-process-filter (get-process procname) (quote inferior-ess-output-filter)) (inferior-ess-mark-as-busy (get-process procname)) (process-send-string (get-process procname) "\n") (if no-wait nil (ess-write-to-dribble-buffer "(inferior-ess: waiting for process to start (before hook)\n") (ess-wait-for-process (get-process procname) nil 0.01)) (ess-process-put (quote funargs-cache) (make-hash-table :test (quote equal))) (ess-process-put (quote funargs-pre-cache) nil) (process-put (get-process procname) (quote accum-buffer-name) (format " *%s:accum*" procname)) (set (make-local-variable (quote syntax-begin-function)) (function inferior-ess-goto-last-prompt-if-close)) (set (make-local-variable (quote font-lock-fontify-region-function)) (function inferior-ess-fontify-region)) (run-hooks (quote ess-post-run-hook)) (ess-load-extras t) (if no-wait nil (ess-write-to-dribble-buffer "(inferior-ess 3): waiting for process after hook") (ess-wait-for-process (get-process procname)))) (save-current-buffer (set-buffer buf) (rename-buffer buf-name-str t)) (if (and inferior-ess-same-window (not inferior-ess-own-frame)) (switch-to-buffer buf) (pop-to-buffer buf))))
  (let* ((process-environment process-environment) (defdir (or (and ess-directory-function (funcall ess-directory-function)) ess-directory default-directory)) (temp-dialect (if ess-use-inferior-program-name-in-buffer-name (if (string-equal temp-ess-dialect "R") inferior-R-program-name temp-ess-dialect) temp-ess-dialect)) (temp-lang temp-ess-lang) (procname (let ((ntry 0) (done nil)) (while (not done) (setq ntry (1+ ntry) done (not (get-process ...)))) (ess-proc-name ntry temp-dialect))) (buf-name-str (funcall ess-gen-proc-buffer-name-function procname)) startdir buf method) (ess-write-to-dribble-buffer (format "(inf-ess 1.1): procname=%s temp-dialect=%s, buf-name=%s \n" procname temp-dialect buf-name-str)) (cond ((and (not (comint-check-proc (current-buffer))) (eq major-mode (quote inferior-ess-mode))) (setq startdir (if ess-ask-for-ess-directory (ess-get-directory defdir temp-dialect procname) defdir) buf (current-buffer) buf-name-str (buffer-name) method 1)) ((get-buffer buf-name-str) (setq buf (get-buffer buf-name-str) method 2)) (t (setq startdir (if ess-ask-for-ess-directory (ess-get-directory defdir temp-dialect procname) defdir) buf (if ess-ask-about-transfile (let ((transfilename ...)) (if (string= transfilename "") (get-buffer-create buf-name-str) (find-file-noselect ...))) (get-buffer-create buf-name-str)) method 3))) (ess-write-to-dribble-buffer (format "(inf-ess 2.0) Method #%d start=%s buf=%s\n" method startdir buf)) (set-buffer buf) (ess-setq-vars-local ess-customize-alist) (ess-write-to-dribble-buffer (format "(inf-ess 2.1): ess-language=%s, ess-dialect=%s buf=%s \n" ess-language ess-dialect (current-buffer))) (if startdir (setq default-directory startdir)) (let* ((ess-directory (or startdir ess-directory)) (infargs (or ess-start-args inferior-ess-start-args)) (special-display-regexps nil) (special-display-frame-alist inferior-ess-frame-alist) (proc (get-process procname))) (if inferior-ess-own-frame (setq special-display-regexps (quote (".")))) (if (and proc (comint-check-proc (process-buffer proc))) (progn (ess-write-to-dribble-buffer (format "(inf-ess ..): popping to proc\n")) (pop-to-buffer (process-buffer proc))) (let* ((symbol-string (concat "inferior-" inferior-ess-program "-args")) (switches-symbol (intern-soft symbol-string)) (switches (if (and switches-symbol ...) (symbol-value switches-symbol)))) (set-buffer buf) (inferior-ess-mode) (ess-write-to-dribble-buffer (format "(inf-ess 3.0): prog=%s, start-args=%s, echoes=%s\n" inferior-ess-program infargs comint-process-echoes)) (setq ess-local-process-name procname) (goto-char (point-max)) (if ess-history-file (if (eq t ess-history-file) (set (make-local-variable ...) (concat "." ess-dialect "history")) (if (stringp ess-history-file) nil (error "`ess-history-file' must be nil, t, or a string")))) (if ess-history-file (progn (setq comint-input-ring-file-name (expand-file-name ess-history-file ...)) (comint-read-input-ring))) (set-buffer (if switches (inferior-ess-make-comint buf-name-str procname infargs switches) (inferior-ess-make-comint buf-name-str procname infargs))) (set-process-sentinel (get-process procname) (quote ess-process-sentinel)) (let ((conselt (assoc procname ess-process-name-list))) (if conselt nil (setq ess-process-name-list (cons ... ess-process-name-list)))) (ess-make-buffer-current) (goto-char (point-max)) (setq ess-sl-modtime-alist nil) (set-process-filter (get-process procname) (quote inferior-ess-output-filter)) (inferior-ess-mark-as-busy (get-process procname)) (process-send-string (get-process procname) "\n") (if no-wait nil (ess-write-to-dribble-buffer "(inferior-ess: waiting for process to start (before hook)\n") (ess-wait-for-process (get-process procname) nil 0.01)) (ess-process-put (quote funargs-cache) (make-hash-table :test (quote equal))) (ess-process-put (quote funargs-pre-cache) nil) (process-put (get-process procname) (quote accum-buffer-name) (format " *%s:accum*" procname)) (set (make-local-variable (quote syntax-begin-function)) (function inferior-ess-goto-last-prompt-if-close)) (set (make-local-variable (quote font-lock-fontify-region-function)) (function inferior-ess-fontify-region)) (run-hooks (quote ess-post-run-hook)) (ess-load-extras t) (if no-wait nil (ess-write-to-dribble-buffer "(inferior-ess 3): waiting for process after hook") (ess-wait-for-process (get-process procname)))) (save-current-buffer (set-buffer buf) (rename-buffer buf-name-str t)) (if (and inferior-ess-same-window (not inferior-ess-own-frame)) (switch-to-buffer buf) (pop-to-buffer buf)))))
  (let* ((ess-customize-alist (or customize-alist ess-customize-alist)) (temp-ess-dialect (eval (cdr (assoc (quote ess-dialect) ess-customize-alist)))) (temp-ess-lang (eval (cdr (assoc (quote ess-language) ess-customize-alist))))) (run-hooks (quote ess-pre-run-hook)) (ess-write-to-dribble-buffer (format "(inf-ess 1): lang=%s, dialect=%s, tmp-dialect=%s, buf=%s\n" ess-language ess-dialect temp-ess-dialect (current-buffer))) (let* ((process-environment process-environment) (defdir (or (and ess-directory-function (funcall ess-directory-function)) ess-directory default-directory)) (temp-dialect (if ess-use-inferior-program-name-in-buffer-name (if (string-equal temp-ess-dialect "R") inferior-R-program-name temp-ess-dialect) temp-ess-dialect)) (temp-lang temp-ess-lang) (procname (let ((ntry 0) (done nil)) (while (not done) (setq ntry (1+ ntry) done (not ...))) (ess-proc-name ntry temp-dialect))) (buf-name-str (funcall ess-gen-proc-buffer-name-function procname)) startdir buf method) (ess-write-to-dribble-buffer (format "(inf-ess 1.1): procname=%s temp-dialect=%s, buf-name=%s \n" procname temp-dialect buf-name-str)) (cond ((and (not (comint-check-proc (current-buffer))) (eq major-mode (quote inferior-ess-mode))) (setq startdir (if ess-ask-for-ess-directory (ess-get-directory defdir temp-dialect procname) defdir) buf (current-buffer) buf-name-str (buffer-name) method 1)) ((get-buffer buf-name-str) (setq buf (get-buffer buf-name-str) method 2)) (t (setq startdir (if ess-ask-for-ess-directory (ess-get-directory defdir temp-dialect procname) defdir) buf (if ess-ask-about-transfile (let (...) (if ... ... ...)) (get-buffer-create buf-name-str)) method 3))) (ess-write-to-dribble-buffer (format "(inf-ess 2.0) Method #%d start=%s buf=%s\n" method startdir buf)) (set-buffer buf) (ess-setq-vars-local ess-customize-alist) (ess-write-to-dribble-buffer (format "(inf-ess 2.1): ess-language=%s, ess-dialect=%s buf=%s \n" ess-language ess-dialect (current-buffer))) (if startdir (setq default-directory startdir)) (let* ((ess-directory (or startdir ess-directory)) (infargs (or ess-start-args inferior-ess-start-args)) (special-display-regexps nil) (special-display-frame-alist inferior-ess-frame-alist) (proc (get-process procname))) (if inferior-ess-own-frame (setq special-display-regexps (quote (".")))) (if (and proc (comint-check-proc (process-buffer proc))) (progn (ess-write-to-dribble-buffer (format "(inf-ess ..): popping to proc\n")) (pop-to-buffer (process-buffer proc))) (let* ((symbol-string (concat "inferior-" inferior-ess-program "-args")) (switches-symbol (intern-soft symbol-string)) (switches (if ... ...))) (set-buffer buf) (inferior-ess-mode) (ess-write-to-dribble-buffer (format "(inf-ess 3.0): prog=%s, start-args=%s, echoes=%s\n" inferior-ess-program infargs comint-process-echoes)) (setq ess-local-process-name procname) (goto-char (point-max)) (if ess-history-file (if (eq t ess-history-file) (set ... ...) (if ... nil ...))) (if ess-history-file (progn (setq comint-input-ring-file-name ...) (comint-read-input-ring))) (set-buffer (if switches (inferior-ess-make-comint buf-name-str procname infargs switches) (inferior-ess-make-comint buf-name-str procname infargs))) (set-process-sentinel (get-process procname) (quote ess-process-sentinel)) (let ((conselt ...)) (if conselt nil (setq ess-process-name-list ...))) (ess-make-buffer-current) (goto-char (point-max)) (setq ess-sl-modtime-alist nil) (set-process-filter (get-process procname) (quote inferior-ess-output-filter)) (inferior-ess-mark-as-busy (get-process procname)) (process-send-string (get-process procname) "\n") (if no-wait nil (ess-write-to-dribble-buffer "(inferior-ess: waiting for process to start (before hook)\n") (ess-wait-for-process (get-process procname) nil 0.01)) (ess-process-put (quote funargs-cache) (make-hash-table :test (quote equal))) (ess-process-put (quote funargs-pre-cache) nil) (process-put (get-process procname) (quote accum-buffer-name) (format " *%s:accum*" procname)) (set (make-local-variable (quote syntax-begin-function)) (function inferior-ess-goto-last-prompt-if-close)) (set (make-local-variable (quote font-lock-fontify-region-function)) (function inferior-ess-fontify-region)) (run-hooks (quote ess-post-run-hook)) (ess-load-extras t) (if no-wait nil (ess-write-to-dribble-buffer "(inferior-ess 3): waiting for process after hook") (ess-wait-for-process (get-process procname)))) (save-current-buffer (set-buffer buf) (rename-buffer buf-name-str t)) (if (and inferior-ess-same-window (not inferior-ess-own-frame)) (switch-to-buffer buf) (pop-to-buffer buf))))))
  inferior-ess()
  (let* ((temp-dialect "SAS")) (ess-write-to-dribble-buffer (format "(SAS): ess-dial=%s, temp-dial=%s\n" ess-dialect temp-dialect)) (ess-SAS-pre-run-hook temp-dialect) (setq ess-eval-visibly-p nil) (inferior-ess) (save-excursion (set-buffer "*SAS*") (use-local-map sas-mode-local-map)))
  SAS()
  funcall-interactively(SAS)
  call-interactively(SAS record nil)
  command-execute(SAS record)
  execute-extended-command(nil "SAS" "SAS")
  funcall-interactively(execute-extended-command nil "SAS" "SAS")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by rsparapa** [comment]
Appears to be the same as Issue 385.
