### ISSUE TITLE
no such file or directory Rterm

### ISSUE THREAD

**Issue by mohanr** [emacs-ess/ESS#436]
I have the layer to spacemacs  M-x R doesn't find Rterm.

```

(setq inferior-R-program-name "D:/R/R-3.2.3/bin/x64")
  (setq ess-eval-visibly-p nil)
  (setq ess-ask-for-ess-directory nil)
  (require 'ess-eldoc)
  (setq ess-history-file nil)

**Comment by eddelbuettel** [comment]
It's been a while but I think you want `D:/R/R-3.2.3/bin/x64/Rterm.exe` -- see how the variable name says _program-name_ and not _directory_ ?

**Comment by mohanr** [comment]
I changed that. And it attempted to start the R process. When I switch to that process buffer I see a blank file and this message.
[R] : no process
When I start it myself it starts a R process.

**Comment by eddelbuettel** [comment]
You could try to rely on Vincent Goulet's bundled [emacs installer](https://vigou3.github.io/emacs-modified-windows/) which has all this set up out of the box.

Many people use ESS on Windows. I suspect the issue is local to your end.

**Comment by mohanr** [comment]
Closing since I want to try the specialized emacs for ess.
