### ISSUE TITLE
C++ support for roxygen editing?

### ISSUE THREAD

**Issue by eddelbuettel** [emacs-ess/ESS#439]
Rcpp makes it somewhat easy to write code on the C++ side.  The tooling then carries code over into a generated R file where `roxygenize()` will process any included documentation.

So many of us have gotten to writing documentation _meant for roxygen_ in the C++ file.   

But the editing support is just not there, whereas RStudio does it a little better.   I really know next to nothing about multi-mode but could the existing (and excellent !!) roxygen support for R files be carried over to C++ files?

[ I have the feeling I asked that once before years ago but my either my search-fu lets me down, or my memory is faulty.  ]

**Comment by spencerwoody** [comment]
I've only been able to use awkward workarounds for this (e.g. writing the roxygen comments by hand and then adding a `'` after each `//` using rectangle mode)

This issue is from over a year ago and looks like it's not getting a lot of traction... but fixing this would definitely remove a huge hindrance to efficient documenting in Rcpp

**Comment by jabranham** [comment]
I'll take a look into this after the release this month.

**Comment by eddelbuettel** [comment]
I was once again amazed today how fluid roxygen editing is in R files, but with Rcpp I open write in C++ files too and it would be lovely to have something smoother.

**Comment by jabranham** [comment]
I had some time to look at this today. It's not too terribly difficult. I've got most things working (font lock, auto-inserting the `//' ` when you press enter, etc) already. 

I'll submit a PR once #616 gets merged but if anyone is dying to try it out: https://github.com/jabranham/ESS/tree/roxy-rcpp
