### ISSUE TITLE
Julia and "Sorry, no version of R could be found on your system."

### ISSUE THREAD

**Issue by zimoun** [emacs-ess/ESS#440]
Why the `R` executable is it checked when `julia` files are edited ?

From what I understand, the function `ess-check-R-program-name` from `ess-r-mode.el` is called, which verifies the R installation, even if only pure Julia functionalities are used. 

It does not appear to me straightforward to check the R installation and report information about R when I am working on Julia projects without any R code.

**Comment by ess-core** [comment]
On Mon, Jul 17 2017, zimoun wrote:

> Why the `R` executable is it checked when `julia` files are edited ?
>
>>From what I understand, the function `ess-check-R-program-name` from `ess-r-mode.el` is called, which verifies the R installation, even if only pure Julia functionalities are used. 
>
> It does not appear to me straightforward to check the R installation and report information about R when I am working on Julia projects without any R code.

I will check this.  ESS is historically driven by R developers who
naturally assume R is running.

**Comment by sje30** [comment]
Do you get an error from ESS, or does it still work?

**Comment by zimoun** [comment]
> ESS is historically driven by R developers who naturally assume R is running.

Yes, I agree. And who can live without any R installation ? ;-)

I am just pointing a behaviour which appears to me to be not consistent. And if there is one practical reason about this mechanism or just because historical layers.
If I understand well, the reason is more about history than a practical one.

> Do you get an error from ESS, or does it still work?

`ess-check-R-program-name` returns a `message`, not an error. So it still works. :-)

From I understand, a fix should be to re-write the function `ess-check-R-program-name` by a little bit more generic one. For example, replacing `inferior-ess-r-program-name` by `inferior-ess-dialect-program-name` etc. Using maybe macro?

**Comment by lionel-** [comment]
This function is called in `ess-site.el` which is only an example of configuration file for ESS. We are trying to make ESS more modular but not all ESS modes can be loaded separately yet. Does ess-julia work without loading ess-site?

**Comment by zimoun** [comment]
I think it is not working without `ess-site`.

I am using `use-package`, and ESS have been installed with `:ensure t` months ago.
Whatever.
If ESS has been installed by `package.el`, one minimal config file should be:
```elisp
(require 'package)
(setq package-enable-at-startup nil)
(package-initialize)

(require 'ess-site)
(add-to-list 'auto-mode-alist '("\\.jl$" . ess-julia-mode))
```
which works for me; with e.g., `emacs -q -L ~/.emacs.d/elpa -l mini-conf.el test.jl`.

However, if it is another, e.g., `(require 'ess)` then the error is: `File mode specification error: (void-function ess-julia-mode)`.

**Comment by lionel-** [comment]
> However, if it is another, e.g., (require 'ess) then the error is: File mode specification error: (void-function ess-julia-mode).

I was thinking about `(require 'ess-julia)`, does it work? Otherwise we should make it work.

**Comment by zimoun** [comment]
Yes, it works. Nice !
I will check with my home env to confirm.

Thank you for the tip.

**Comment by lionel-** [comment]
Great!
