### ISSUE TITLE
`ess-R-fl-keyword:%op%` not working

### ISSUE THREAD

**Issue by hieutkt** [emacs-ess/ESS#445]
The font-lock for R %op% operator seems to behave wrongly. The regex fontifies anything between two `%` operators, even between lines. I don't think this is the intended behavior, given operators should be on the same line. This results in wrong fontifications in inferior-ess-mode, when a single percent symbol are often printed (for example in my screenshot when I render a file with `knitr`)

Also I cannot turn off the fontification of `ess-R-fl-keyword:%op%`, as you can also see in my screenshot. Setting `ess-R-fl-keyword:%op%` to `nil` gives no effect.

![screenshot from 2017-07-24 14-37-28](https://user-images.githubusercontent.com/16746470/28512991-6dd009c2-707e-11e7-8d4b-3137949d6e95.png)

This screenshot is taken with ESS version `20170722.1338`,  `GNU Emacs 26.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-07-23`, although I have seen this behavior even when I use the stable `emacs25` version, or when testing with `emacs -q`.

**Comment by lionel-** [comment]
This is on purpose and simplifies the fontifier. `ess-R-fl-keyword:%op%` is a leftover that should be removed as there are no regex involved anymore.

About your issue, we could disable `%%` fontification it in the iESS buffer but what we really need is a different fontification for the output zone and the input zone. That's a difficult problem that I won't have time to tackle for a while.

**Comment by hieutkt** [comment]
Yes, please disable it temporary if you have time.
One small thing I also notice that when I evaluate with `ess-eval-region-or-line-and-step`, with `font-lock-mode` off in the inferior buffer, and without any region marked (just my pointer on the line), the code is written with fontification to the inferior buffer.

Evaluate with any other function (`ess-eval-region-or-line-and-step` with region selected or `ess-eval-region-or-function-or-paragraph-and-step`) does not replicate this behavior:

![screenshot from 2017-07-24 15-23-56](https://user-images.githubusercontent.com/16746470/28514438-2659b948-7084-11e7-945e-81e61f379788.png)

While this is probably another "bug", can you leverage it into a "feature", in which iess copy the fontification of anything that is sent to it?

I am a Emacs-newbie in general, so tell me if this is a stupid idea:)

**Comment by lionel-** [comment]
Probably one of these functions copy the input with text attributes and the other not. The solution for fontification zones is likely to involve text attributes but is not trivial to implement.

**Comment by vspinu** [comment]
> iess copy the fontification of anything that is sent to it?

Unless you have already done so, you will probably switch very quickly to
`(setq ess-eval-visibly t)`. So Input fontification won't be useful anyway.

**Comment by lionel-** [comment]
Do you mean `nil` or `nowait`? I use `nowait`.

**Comment by vspinu** [comment]
Yes. Of course :)
