### ISSUE TITLE
Strings containing '#' cause wrong indentation

### ISSUE THREAD

**Issue by scheidan** [emacs-ess/ESS#446]
Strings containing `#` causes problems with the indentation.
A minimal example:
```R
A <- f("abc") +
    f("abc") + f("abc") + 
    f("abc # abc") +     # <- the '#" causes the trouble
f("abc") +               # wrong
    f("abc")
```
It seems to be independent of the indentation style used.

I use ESS version `20170710.11` on Emacs `24.5.1`.

**Comment by owenRiddy** [comment]
The culprit is ess-code-end-position; it thinks that the # in the string is a comment. I added `(not (ess-within-string-p))` to the defun in ess-mode.el and indenting started working properly.

```
(defun ess-code-end-position ()
  "Like (line-end-position) but stops at comments"
  (save-excursion
    (or (and (re-search-forward "#" (line-end-position) t)
             (not (ess-within-string-p))
             (match-beginning 0))
        (line-end-position))))
```

**Comment by mmaechler** [comment]
I have added your proposal to the code (9ff95c7c5409f997f235358f9664b57cea1e263d),  but it did not help, see 4f6dd0acc5d6fec3231c613d282ae25ae3430343

**Comment by owenRiddy** [comment]
Hmm. Maybe this is more naturally done backwards? This fixed up the test case you found that was still broken, and seems robust. I tried a comment with many hashes in it too.

```
(defun ess-code-end-position ()
  "Like (line-end-position) but stops at comments"
  (save-excursion
    (end-of-line)
    (while (ess-within-comment-p)
      (re-search-backward "#" (line-beginning-position) t))
    (point)))
```

**Comment by nverno** [comment]
An alternative that seems to work as well. It skips whitespace between code and comment, which looks like it may be uneccesary.
```
(defun ess-code-end-position ()
  "Like (line-end-position) but stops at comments"
  (save-excursion
    (or (and (comment-search-forward (line-end-position) 'move)
             (skip-syntax-backward " <" (line-beginning-position))   ;skip '#' and whitespace?
             (point))
        (line-end-position))))

```

**Comment by lionel-** [comment]
The new strategy was twice as slow but I found an efficient and (hopefully) correct way:

```lisp
(defun ess-code-end-position ()
  "Like (line-end-position) but stops at comments"
  (save-excursion
    (goto-char (1+ (line-end-position)))
    (forward-comment -1)
    (point)))
```

Thanks for your help everyone!

**Comment by owenRiddy** [comment]
The efficient introduces an edge case if a multi-line string has a # in it. Elisp foward-comment "... cannot tell whether the comments it traverses are embedded within a string. " [0].

In this case below, ess-code-end-position will incorrectly return the position of the hash on the second line; but the code will still indent properly.

```
A <- f("ABCDEF") +
    f(" I am a #tricky string
stretching multpiple lines") +
    f(g(h("abc # def"), "foo ## bar")) +
```

It might be worth putting a comment to this effect in ess-code-end-position in case it turns out that this causes a problem somewhere other than indenting.

[0] https://www.gnu.org/software/emacs/manual/html_node/elisp/Motion-via-Parsing.html

**Comment by lionel-** [comment]
This looks like a bug in `forward-comment`. Who knew this would be so complicated :/
