### ISSUE TITLE
feature request: ess-erase-buffer

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#448]
`erase-buffer` does not work in `inferior-ess` mode, and emacs gets quite slow, if there are too many lines in the `inferior-ess` buffer and `erase-buffer` does not work, because the buffer is read-only, `read-only-mode` does not work.

**Comment by gdkrmr** [comment]
also: disable fontification in the inferior buffer

**Comment by vspinu** [comment]
Does `commit-clear-buffer` work?

```
C-c M-o runs the command comint-clear-buffer (found in inferior-ess-mode-map),
which is an interactive compiled Lisp function in ‘comint.el’.

It is bound to C-c M-o.

(comint-clear-buffer)
```

**Comment by gdkrmr** [comment]
that works, thanks!
