### ISSUE TITLE
Configuration using .emacs

### ISSUE THREAD

**Issue by mohanr** [emacs-ess/ESS#449]
I have downloaded the Mac version. Wondering how to start it with its own .emacs configuration. My ~/.spacemacs is always used when I type 'emacs' at the terminal.

How does ess know where R is without .emacs ?

**Comment by gdkrmr** [comment]
what is used ist `~/.emacs.d/init.el`, which in turn loads `~/.spacemacs`, I suggest you move `~/.emacs.d` somewhere else and make a separate config folder for your new config and then symlink whatever you currently want to use.

**Comment by mohanr** [comment]
Yes. I moved it. It works now. Thanks.
