### ISSUE TITLE
evaluate rectangular-block as region

### ISSUE THREAD

**Issue by michelk** [emacs-ess/ESS#45]
I use ESS in conjunction with [evil](http://gitorious.org/evil).

Sometimes I would like to evaluate a selected rectangular block. Eg. in 

```
funkyFun(
  x = 5
 ,y = 10
 ,c = 25
)
```

I visually select block

```
x = 5
y = 10
c = 25
```

If I then do `ess-eval-region`, I get

```
R> x = 5
R> , y = 10
Error: unexpected ',' in " ,"
...
```

**Comment by lionel-** [comment]
I also use ESS with Evil but I never encountered a situation where I needed to eval a rectangular region. Could you provide an example where this would be useful?
