### ISSUE TITLE
Add an option to make stata-mode work like the Stata built-in editor to use the  xstata/GUI version

### ISSUE THREAD

**Issue by hliebert** [emacs-ess/ESS#451]
I am currently trying to migrate from Vim to Emacs/Spacemacs. I frequently have to use Stata for work with coauthors. However, running Stata in Emacs isn't quite as useful as using the GUI Version (e.g. for displaying graphs or looking at the data in the spreadsheet viewer). See also the discussion e.g. [here](https://stat.ethz.ch/pipermail/ess-help/2016-February/010914.html).

The built-in Stata do file editor works by just using having commands to execute either the whole file or a selection by writing it to a temp file and then executing that. Would it be possible to add this functionality as on option to ESS? I believe this behaviour could be more useful than the current state. 

I have emulated this in Vim by writing a tmp file and triggering a simple shell script to change to the current GUI window and then execute the file. I have been using it for some time, and it works fine. Unfortunately, I do not know any Emacs Lisp and have no idea how to implement this. I'd happily share my current solution. It's not really elegant, relying on a combination of `xdotool`, `wmctrl`, `xte` and uses the system clipboard, but it works.

**Comment by vspinu** [comment]
I am afraid no-one from the core developers are using STATA on a regular basis or maybe at all. So I am a bit pessimistic about the outcome on this. You will probably have to figure it out yourself, especially if it's such a hacky communication mechanism as focusing STATA GUI window and pasting there. 

You can easily grab a region, save to a file, run your and old shell script on it within emacs. Look at `buffer-substring-no-properties`, `with-temp-file` and `call-process-shell-command`.

**Comment by hliebert** [comment]
Thanks, I suspected as much. Thank you for providing some pointers where to start, I'll have a look. Is there a way to easily disable ess/stata-mode for stata related files?

**Comment by vspinu** [comment]
I think there was a do-mode lying somewhere but I cannot seem to find it anymore.  In any case you can always bind your custom commands in ess-mode-map.
