### ISSUE TITLE
Trying to start R-newest: "No version of R could be found"

### ISSUE THREAD

**Issue by LouisAsh** [emacs-ess/ESS#452]
Hi, I just installed Emacs Modified for Windows, which automatically installed the most recent versions of both Emacs and ESS.

Then, when I open a R file and then try to initialize a R session by clicking on ESS>Start Process>Other>R-newest, I get the error "No version of R could be found". However, I do have R properly installed and running in the folder: C:\R\R-3.4.1\bin\x64\.

I tried initializing Emacs with both:

(setq-default inferior-R-program-name "C:\\Program Files\\R\\R-3.4.1\\bin\\x64\\Rterm.exe")

And also:

(setq-default inferior-R-program-name "C:\\Program Files\\R\\R-3.4.1\\bin\\x64\\R.exe")

Still nothing works. What else could I try? I am running Windows 10 6bits.

Thanks.

**Comment by nverno** [comment]
It doesn't look like your paths match. shouldnt your inferior-R-program-name be pointing to C:\R\R-3.4.1\bin\x64\R.exe

**Comment by LouisAsh** [comment]
Sorry about that, it was a typo here, not in my .emacs. What I have in my .emacs is exactly what should be there:

(setq-default inferior-R-program-name "C:/R/R-3.4.1/bin/x64/R.exe")

**Comment by ess-core** [comment]
Try (setq-default inferior-R-program-name "C:\\R\\R-3.4.1\\bin\\x64\\Rterm.exe")

**Comment by LouisAsh** [comment]
> Try (setq-default inferior-R-program-name "C:\\R\\R-3.4.1\\bin\\x64\\Rterm.exe")
Still does not work.

**Comment by LouisAsh** [comment]
Update: now, whenever I try to send the code with something like ESS>ESS Eval>Eval buffer, it does work. I mean, Emacs opens a R console in a different buffer frame and everything is fine. However, it is still impossible for me to start a R console by without sending code, i.e. with ESS>Start process>Other>R-newest, which is what I would like to do.

**Comment by mmaechler** [comment]
Did you ever try  `M-x R-[Tab]`  (where the [Tab] key should show all versions of R that ESS sees).  For me this gives a whole collection because even on Windows (I only use on a Windowsserver from my Linux) I've installed several versions of R.

**Comment by lionel-** [comment]
Please try the mailing list if you need more help with this.
