### ISSUE TITLE
Default R session for executing code blocks

### ISSUE THREAD

**Issue by fkgruber** [emacs-ess/ESS#454]
Hi
In org-mode and with multiple R sessions if I have an R code and execute code with C-cC-c it will use the default R session for that buffer, or section etc.

However, if I go into ess-mode (C-c') and I try to send a block to the R session either with C-cC-c or C-cC-j or any other command it will ask for which R session to use. however the default R session appears to be randomly selected. Could we make the default R session to be the same default R session for that org-mode section?

Thanks
FKG

**Comment by lionel-** [comment]
Relevant to #416

**Comment by fkgruber** [comment]
I figured a way to solve this issue:
https://www.fredgruber.org/post/ess_emacs_default_r_session/
in summmary use:

```
(defvar tmprs nil)
(defun get-org-current-rsession()
  "When you are in an org file get the current R session based on global header, subtree, property or source code :session property whichever is relevant"
  (setq tmprs (cdr (assoc :session (nth 2 (org-babel-get-src-block-info t)))))
  )

(defun set-ess-R-process()
  "set the process to session stored in tmprs variable"
  (message "Setting R session to %s" (eval tmprs))
  (setq ess-local-process-name (process-name (get-buffer-process tmprs)))
  )


(advice-add 'org-edit-src-code :before #'get-org-current-rsession)
(advice-add 'org-edit-src-code :after #'set-ess-R-process)

```

Now when I go to the edit buffer to edit some R code I can execute any line of code (for example, using C-c C-j) directly to the correct R session no matter how many R session you have running.
