### ISSUE TITLE
Toggle underscore in ess-jags

### ISSUE THREAD

**Issue by DiogoFerrari** [emacs-ess/ESS#463]
For some reasons I can't use "=" in the ess-jag mode anymore. It is converting the char to <-. Does someone know how to untoggle = (and _) in the jags mode?

**Comment by rsparapa** [comment]
JAGS mode is now deprecated

**Comment by lionel-** [comment]
You can disable this with:

```lisp
(define-key ess-bugs-mode-map "=" nil)
```

In the next version it will also work with `ess-jags-mode-map` which is now an alias to the bugs mode map.

**Comment by DiogoFerrari** [comment]
That works
