### ISSUE TITLE
add-hook does not work for jags mode

### ISSUE THREAD

**Issue by DiogoFerrari** [emacs-ess/ESS#464]
I am trying to load automatically rainbow delimiter and rainbow identifier with add hook. It works well for ess-mode, but not for jags mode. When I use jags-mode, I need to run those two mode manually after I open the file in the ess-jag buffer. Would you know how to fix it and load those modes automatically when I open a .jag file?

**Comment by ess-core** [comment]
I think BUGS/JAGS mode should be retired along with OpenBUGS and JAGS.  Most people have
switched to Stan and the emacs mode for it at https://github.com/stan-dev/stan-mode
I am planning to do the same myself.  Therefore, I think this is the last release of ESS with BUGS 
and JAGS support.

-----Original Message-----

**Comment by martynplummer** [comment]
There were 1213 downloads of JAGS from Sourceforge in the last week. It's not dead.

**Comment by rsparapa** [comment]
JAGS mode is now deprecated

**Comment by lionel-** [comment]
`ess-jags-mode-hook` is now an alias of `ess-bugs-mode-hook` (which is the hook that is run by jags-mode).

**Comment by DiogoFerrari** [comment]
Ok, it worked when I set it using bugs mode.
