### ISSUE TITLE
Debian package user reports directory related minor issue

### ISSUE THREAD

**Issue by eddelbuettel** [emacs-ess/ESS#465]
We received [this bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882042) a few days ago which I passed on to the ess-debian list but I haven't heard back.  Just wanted to make sure you are aware. The package is not doing any local modifications.  Ideas?  Can this be suppressed?

Key part of bug report below, all details at link.

```
Package: ess
Version: 17.11-1
Severity: normal

Dear Maintainer,

Upon upgrading ess from 16.10-1 to 17.11-1, I now get this error everytime I start emacs:

Loading /etc/emacs/site-start.d/50ess.el (source)...
ERROR:ess-site.el:ess-etc-directory
Relative to ess-lisp-directory, one of the following must exist:
../etc/ess, ../etc, ../../etc/ess or ./etc

I'm not sure if this is a new variable or if something else has changed. 
Just thought I'd bring this up, in case it is important or an easy fix. It is only
an inconvenience to me.
```

**Comment by ess-core** [comment]
Hi Dirk:

It is definitely not new.  That functionality has been around at least a decade.
I don’t use Debian-flavored Linux, but check to see if any of these directories
exist: ../etc/ess, ../etc, ../../etc/ess or ./etc.  My guess being that they don’t.  
In Debian, where do the ESS etc files go?

Rodney

-----Original Message-----

**Comment by eddelbuettel** [comment]
But that is Debian Emacs Policy material, and has not changed in 10+ years:
- Source: `/usr/share/emacs/site-lisp/ess/`  
- Installed: per emacs major version directory

**Comment by lionel-** [comment]
I think https://github.com/emacs-ess/ESS/commit/098d65c90875a07aa6da6bf438947784d144051a should fix it.

Dirk, can you reproduce this error when you run Emacs with `--no-init-file` (so that the ess/lisp directory is not in the load-path in case you set it up in your config file)?

If yes, could you confirm that replacing the relevant defvar in `ess-utils.el` with the following fixes the error:

```lisp
(defvar ess-lisp-directory
  (directory-file-name
   (file-name-directory
    (if load-file-name
        (file-truename load-file-name)
      (locate-library "ess-utils") )))
  "Directory containing ess-site.el(c) and other ESS lisp files.")
```

The compiled file `ess-utils.elc` should be deleted for this change to take effect.

We need to setup Travis testing before the next release so this kind of things don't happen again when we change the loading files.

**Comment by eddelbuettel** [comment]
@lionel -- will do.  Give me one sec.  

But just to give you context:  installation of the `.deb` on my box tickles builds with emacs24 and emacs25 (as I still have both):

```sh
edd@bud:~$ wajig install /var/cache/pbuilder/result/ess_17.11-1_all.deb                                                                                                                                         
(Reading database ... 417084 files and directories currently installed.)
Preparing to unpack .../result/ess_17.11-1_all.deb ...
Remove ess for emacs24
remove/ess: purging byte-compiled files for emacs24
Remove ess for emacs25
remove/ess: purging byte-compiled files for emacs25
Unpacking ess (17.11-1) over (16.10-1zesty0) ...
Setting up ess (17.11-1) ...
Install emacsen-common for emacs24
emacsen-common: Handling install of emacsen flavor emacs24
Wrote /etc/emacs24/site-start.d/00debian-vars.elc
Wrote /usr/share/emacs24/site-lisp/debian-startup.elc
Install emacsen-common for emacs25
emacsen-common: Handling install of emacsen flavor emacs25
Install ess for emacs24
install/ess: Handling install for emacsen flavor emacs24
Install.log:     85.8% -- replaced with Install.log.gz
Install ess for emacs25
install/ess: Handling install for emacsen flavor emacs25
Install.log:     84.1% -- replaced with Install.log.gz
Processing triggers for doc-base (0.10.7) ...
Processing 1 changed doc-base file...
Processing triggers for install-info (6.3.0.dfsg.1-1) ...
edd@bud:~$
```

When I then start Emacs, I get messages as seen by OP:

```
[...]
Loading /etc/emacs/site-start.d/50dpkg-dev-el.el (source)...done
Loading /etc/emacs/site-start.d/50emacs-goodies-el.el (source)...done
Loading /etc/emacs/site-start.d/50ess.el (source)...
ERROR:ess-site.el:ess-etc-directory
Relative to ess-lisp-directory, one of the following must exist:
../etc/ess, ../etc, ../../etc/ess or ./etc
Loading /etc/emacs/site-start.d/50ess.el (source)...done
Loading /etc/emacs/site-start.d/50git-core.el (source)...done
[...]
```

Will try the change.

**Comment by eddelbuettel** [comment]
But that suggested change didn't fix it.  Same message.

**Comment by lionel-** [comment]
Then I'm not sure what's going on.

It'd be nice to get rid of the path search to begin with. Rodney or @mmaechler do you know why the etc directory isn't hardcoded relative to `ess-lisp-directory`? Why do we need to search through this list: `("../etc/ess/" "../etc/" "../../etc/ess/" "./etc/")`?

**Comment by lionel-** [comment]
oh hmm I think I'm starting to get the problem. Judging from https://packages.debian.org/sid/all/ess/filelist the `etc` folder is something that is defined by distributions? For this reason it was only defined in `ess-site.el` historically and the path search shouldn't have been moved to `ess-utils.el`.

@eddelbuettel I thinks this should do it: https://github.com/emacs-ess/ESS/commit/151b00326d7b63d039ff401de45729bfaebeb429

**Comment by eddelbuettel** [comment]
Sorry, was out shopping.  Might be easiest just for you and me to drop into a screen share.  So yes, we do move files around, and that may violate assumptions you good guys upstream have about your _source_ layout.

**Comment by eddelbuettel** [comment]
Hm, outcome unchanged:

```
Loading /etc/emacs/site-start.d/50emacs-goodies-el.el (source)...done
Loading /etc/emacs/site-start.d/50ess.el (source)...
ERROR:ess-etc-directory
Relative to ess-lisp-directory, one of the following must exist:
../etc/ess, ../etc, ../../etc/ess or ./etc
Loading /etc/emacs/site-start.d/50ess.el (source)...done
Loading /etc/emacs/site-start.d/50git-core.el (source)...done
```

but that is the new deployed file:

```
edd@bud:~/src/debian/Misc/ess-17.11$ diff /usr/share/emacs/site-lisp/ess/ess-utils.el lisp/ess-utils.el
edd@bud:~/src/debian/Misc/ess-17.11$ ls -l /usr/share/emacs2?/site-lisp/ess/ess-utils.elc
-rw-r--r-- 1 root root 40821 Nov 19 15:28 /usr/share/emacs24/site-lisp/ess/ess-utils.elc
-rw-r--r-- 1 root root 40493 Nov 19 15:29 /usr/share/emacs25/site-lisp/ess/ess-utils.elc
edd@bud:~/src/debian/Misc/ess-17.11$ sed -n -e '45,65p' lisp/ess-utils.el

;; Try to detect the `etc' folder only if not alread set up by distribution
(unless ess-etc-directory
  (let ((path-list '("../etc/ess/" "../etc/" "../../etc/ess/" "./etc/")))
    (while (and (listp path-list) (consp path-list))
      (setq ess-etc-directory
            (expand-file-name (concat ess-lisp-directory "/"
                                      (car path-list))))
      (if (file-directory-p ess-etc-directory)
          (setq path-list nil)
        (setq ess-etc-directory nil)
        (setq path-list (cdr path-list))
        (when (null path-list)
          (beep 0) (beep 0)
          (message (concat
                    "ERROR:ess-etc-directory\n"
                    "Relative to ess-lisp-directory, one of the following must exist:\n"
                    "../etc/ess, ../etc, ../../etc/ess or ./etc"))
          (sit-for 4))))))

(defun ess-message (format-string &rest args)
edd@bud:~/src/debian/Misc/ess-17.11$
```

I had reverted the earlier patch, now trying it as well as the newer one.

**Comment by eddelbuettel** [comment]
It all runs (though I get another boat load of messages in the `*ESS*` buffer, but we can address that another time.  When I query via `M-x v` for this variable I get

```
ess-etc-directory is a variable defined in ‘ess-utils.el’.
Its value is nil

Documentation:
Location of the ESS etc/ directory.
The ESS etc directory stores various auxillary files that are useful
for ESS, such as icons.

[back]
```

On my system with the _installed_ ess, you probably want `/usr/share/ess/etc/` per 

```
edd@bud:~$ dpkg -L ess | grep -i icon
/usr/share/ess/etc/icons
/usr/share/ess/etc/icons/README
/usr/share/ess/etc/icons/rbuffer.xpm
/usr/share/ess/etc/icons/rfunction.xpm
/usr/share/ess/etc/icons/rline.xpm
/usr/share/ess/etc/icons/rregion.xpm
/usr/share/ess/etc/icons/splus_letter_small.xpm
/usr/share/ess/etc/icons/splus_letters_large.png
/usr/share/ess/etc/icons/splus_letters_large.xpm
/usr/share/ess/etc/icons/spluslogo.xpm
/usr/share/ess/etc/icons/spluslogo.xpm.safe
/usr/share/ess/etc/icons/startr.xpm
/usr/share/ess/etc/icons/switch_ess.xpm
/usr/share/ess/etc/icons/switchr.xpm
/usr/share/ess/etc/icons/switchs.xpm
edd@bud:~$
```

**Comment by eddelbuettel** [comment]
I have a solution, but it is crude, and may not be portable. 

For every distro-packaged Emacs lisp upstream package, we run a script from `/etc/emacs/site-start.d/` first.  So I just mod'ed `/etc/emacs/site-start.d/50ess.el` by inserting a line

```el
  (setq ess-etc-directory "/usr/share/ess/etc")
```

Helps me, but how do you get other distro packagers to do the same?

**Comment by mmaechler** [comment]
I typically don't chase github issues on Sundays..  ummarizing the above 
1) Yes, it is the `ess-etc-directory` and not the `ess-lisp-directory` which is the issue.
2) Yes, Debian (and derivatives, notably ubuntu), say Debian++, and possibly others have had their own standards about where `<softw_pkg>/etc/`   should live and 
3) that's why this has been set  inside `ess-site.el` with a somewhat versatile/smart default "searching" around so that it at least has worked for 15 years or so on Debian++

**Comment by mmaechler** [comment]
@eddelbuettel 's  "hack" in site start  is a "solution",  and fedora/redhat/.. may be "ok" to use a similar ~~hack~~ solution ...
OTOH the previous setup seems to me both more robust and more self explaining (ess-site --> "site"configurable)

**Comment by lionel-** [comment]
@mmaechler the issue is that `ess-site.el` file should be an example of configuration, I think it shouldn't be mandatory to load it. The only mandatory configuration part should be to add the `lisp` directory to the load path. After this ESS should be loadable either from `ess.el` or from one of the language mode file e.g. `ess-r-mode.el` (the latter loads only the relevant part, e.g. no Julia or SAS stuff). For this reason I think the path search is better in one of the main files (e.g. `ess-utils.el` currently). I searched around and saw similar stuff in other Emacs packages: https://github.com/emacs-mirror/emacs/blob/369c67a6bba8ec36d9b2f29413848f5898a9e1ea/lisp/org/ox-odt.el#L176. 

I know that ESS has worked without issue for 15 years but at the same time it got pretty messy and entangled, especially the loading part, hence my attempts at cleaning up and using more modern standards. I'm sorry that I break things up in the process, I wasn't aware of the realities of ESS distribution and I naively thought that the folder structure of the package was kept identical. I need to read up on these issues and how it's done in other packages, org-mode seems to be a good example case.

@eddelbuettel I think defining `ess-etc-directory` before loading ESS might be the right approach if you're not using one of the "standard" (i.e. from the path search) directories. What I don't understand is how `ess-etc-directory` was set up in previous versions? AFAICS it was only ever defined in `ess-site.el` but the Debian package does not load that file.

**Comment by eddelbuettel** [comment]
It seems to have been define in `ess-site.el` which is AFAIK a common approach.  It is also `ess-site.el` where Vincent tells ESS about the Windows path to `Rterm.exe`, no?

**Comment by lionel-** [comment]
Got it. IIUC `ess-site.el` is just missing a mention of `ess-etc-directory` to signal that it should be configured site-wise then. I'll look into it tonight. I'll also study how these issues are tackled in other Emacs packages.

**Comment by eddelbuettel** [comment]
I think we're on the same page now! Also, and as I may not have mentioned it:  With 17.11, "just" setting the variable is not sufficient. I tried against my 17.11-1.  It also needs one (or both) of your short elisp patches.  Happy to help test if you want me.  Might be easiest / cleanest to work off patches / diffs / new copies / a branch as it is getting a little muddled otherwise with tossing code snippets around.

**Comment by eddelbuettel** [comment]
@lionel: Could I ask you for a favour?  The original thread at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882042 just received a follow-up.  Would be nice to confirm there.  Could you send a quick email?  The address is always ${BUGNUMBER}@bugs.d.o ie here `882042@bugs.debian.org`.

**Comment by lionel-** [comment]
From what I see in other packages (e.g. auctex, org-mode) we shouldn't keep `ESSR`, icons, and friends in an `etc` directory. Everything that is essential to the functioning of ess should be kept with the lisp files (possibly in subfolders inside `lisp/`).

In the meantime I have restored the definition of `ess-etc-directory` within `ess-site.el`. Here is the comparison for all the relevant changes Dirk: https://github.com/emacs-ess/ESS/compare/5de946bb8326331facf2912ba024f616f5f2ea64...master

And the actual patch if that is useful: https://github.com/emacs-ess/ESS/compare/5de946bb8326331facf2912ba024f616f5f2ea64...master.diff

Please let me know of any further issues.

**Comment by eddelbuettel** [comment]
Great.  
Shall I just switch to '17.11' plus the two most recent versions of these two files in master (or your branch)?

**Comment by lionel-** [comment]
Yes that should do it. Let me know if this indeed fixes all problems.

**Comment by eddelbuettel** [comment]
Quick test makes it look good.  Will upload a -2 revision closing the Debian, and I think this can be closed here. 

Big thank you for your prompt and to-the-point help with this!
