### ISSUE TITLE
Unable to properly open R files after last update 17.11

### ISSUE THREAD

**Issue by aceross** [emacs-ess/ESS#471]
After the latest update, ess-20180109.1719, I get the following error message when opening an R file:

` File mode specification error: (void-variable ess-R-fl-keyword:%op%)`

**Comment by lionel-** [comment]
Do you use this variable in your config? I can't see any reference to it in the current ESS source code.

**Comment by aceross** [comment]
Yes, there was a reference in the config. Removing the reference fixes it.

**Comment by lionel-** [comment]
Thanks. This is was an undocumented private variable (we are now namespacing those with `--` to make it more obvious). If other people encounter this problem let us know and we'll go through a deprecation cycle instead of just removing it.

**Comment by vspinu** [comment]
@lionel-, it actually wasn't private. If the user sets ess-R-fl-keyword:%op% in the ESS>font-lock menu and saves the configuration it will end up in .emacs-config. I expect a lot of users will be affected by this. 

I think we should take an extra care when we load font-locking and check if the variable is defined. This would ensure that such issue would not occur if we drop/re-name font-locking variables in the future.

**Comment by lionel-** [comment]
Ah that makes sense, bummer.
