### ISSUE TITLE
 ess-r-xref.el not compiled/installed 

### ISSUE THREAD

**Issue by pascal-niklaus** [emacs-ess/ESS#477]
Installing ESS freshly checked out from GitHub, I got an error message (starting emacs) that ess-r-xref could not be loaded. It seems there is no corresponding .elc file, and it is not installed.

Manually copying it from the checked out repo to site-lisp fixed the issue.

**Comment by pascal-niklaus** [comment]
I had already tried that but it did not work. What I did was a new checkout (I installed a new system on a computer), followed by make and make install. I then repeated everything with a make clean.

The problem is not that the file is not in the repo (it got copied during checkout), it is that it was not installed. I also noticed that there was only the .el but no .elc file after the make... not sure whether that explains that it was not copied.

**Comment by lionel-** [comment]
Could you try again with latest master please.

**Comment by pascal-niklaus** [comment]
Works, this time I get the compiled file and it is installed.

**Comment by lukesonnet** [comment]
Hi Lionel, I just installed a couple of hours ago and got the same error:

```
In toplevel form:
ess-r-xref.el:32:1:Error: Cannot open load file: no such file or directory, xref
Makefile:115: recipe for target 'ess-r-xref.elc' failed
make[1]: *** [ess-r-xref.elc] Error 1
make[1]: Leaving directory '/home/luke.sonnet/ESS/lisp'
Makefile:10: recipe for target 'install' failed
make: *** [install] Error 2
```

I cloned from master about 4 hours after your comment here.

**Comment by atheriel** [comment]
What version of Emacs are you running? `xref` is only present on 25.1 and later.

**Comment by lukesonnet** [comment]
I am running 24.5.1. I saw this in the ESS code when I was looking at Lionel's last commit, so I installed emacs25 after removing 24. Same error.

In any case, I imagine ESS shouldn't break if xref isn't present so that it still works with Emacs 24, no?

**Comment by atheriel** [comment]
No, it probably should not, although I don't think the Makefile currently has the ability to check Emacs's version. Does `(require 'xref)` work on your version of Emacs 25?

**Comment by lukesonnet** [comment]
I must have made an error earlier Emacs 25, because I don't get the `xref` error. I now get this error

```
mv: cannot stat 'ess.info': No such file or directory
Makefile:80: recipe for target 'info/ess.info' failed
make[1]: *** [info/ess.info] Error 1
make[1]: Leaving directory '/home/luke.sonnet/ESS/doc'
Makefile:10: recipe for target 'install' failed
make: *** [install] Error 2
```
In spite of this error, ESS does work in Emacs 25.3.2.

**Comment by jabranham** [comment]
Since this appears to be fixed, I'm closing this issue.
