### ISSUE TITLE
Negative numbers are red in an inferior buffer

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#478]
Sometimes the non-leading-zero digits negative numbers in inferior buffers are red for me.

So for example:

```
     val
   <dbl>
-1.62   
 0.679  
 1.04   
-0.00111
 1.31   
 1.38   
 0.695  
-0.656  
 0.0300 
 0.377  
```

the `1.62` is red (but not the negative sign), and the `111` from `-0.00111` is red (but not the `0`'s), and the `695` from `-0.695` is red. 

This doesn't happen all the time though (but it does happen frequently) and I haven't figured out how to reliably reproduce it yet.

**Comment by vspinu** [comment]
It could be either a glitch in fontification (which is common) or a match of an error regexp (but then you should see a link, not just red).

**Comment by izahn** [comment]
This is an intentional feature of the tibble package. Try it in a terminal, RStudio etc. you'll see it has nothing to do with ESS.

**Comment by jabranham** [comment]
@izahn oh, thanks. That's gross. Wonder why they did that?

Anyway, I'll close this.

**Comment by lionel-** [comment]
I wouldn't disable crayon globally, the tibble package is pretty configurable so you can disable it locally. Also they are taking feedback on the new display.

**Comment by vspinu** [comment]
Looks like it's pillar. Why doesn't it "happen all the time" then?

**Comment by vspinu** [comment]
For the record, this feature is likely to incur performance penalty for large output due to a huge number of search-substitutions and overlay insertions in the comint buffer. 

A simple tibble like this:

```R
# A tibble: 3 x 3
    cyl     m     n
  <dbl> <dbl> <int>
1    4. -2.29    11
2    6. -3.12     7
3    8. -4.00    14
```
results in 
```R
# A tibble: 3 x 3[39m
    cyl     m     n
  [3m[90m<dbl>[39m[23m [3m[90m<dbl>[39m[23m [3m[90m<int>[39m[23m
[90m1[39m    4. -[31m2[39m[31m.[39m[31m29[39m    11
[90m2[39m    6. -[31m3[39m[31m.[39m[31m12[39m     7
[90m3[39m    8. -[31m4[39m[31m.[39m[31m00[39m    14
```

Each of those escapes is parsed, deleted and substituted with an overlay.  

Besides R specific `options("crayon.enabled"=FALSE)` which Alex mentioned you might want to set `ansi-color-for-comint-mode` to `filter` either in `inferior-ess-mode-hook` or globally.

**Comment by lionel-** [comment]
I haven't seen negative impact, probably because tibble outputs are truncated.
