### ISSUE TITLE
Recursive require of ess-r-mode in ess-r-xref

### ISSUE THREAD

**Issue by fuxialexander** [emacs-ess/ESS#480]
I use `use-package` to use ESS. However, after the newest update, I was unable to use `R-mode`. The error message is as the title. After I commented out the `(require 'ess-r-mode)` in `ess-r-xref.el`, things works normally.

Is it a bug or my mis-specification of `use-package`?
My config is as follow:
```lisp
(use-package ess-site :load-path ess-path
  :mode (("\\.sp\\'"           . S-mode)
         ("/R/.*\\.q\\'"       . R-mode)
         ("\\.[qsS]\\'"        . S-mode)
         ("\\.ssc\\'"          . S-mode)
         ("\\.SSC\\'"          . S-mode)
         ("\\.[rR]\\'"         . R-mode)
         ("\\.[rR]nw\\'"       . Rnw-mode)
         ("\\.[sS]nw\\'"       . Snw-mode)
         ("\\.[rR]profile\\'"  . R-mode)
         ("NAMESPACE\\'"       . R-mode)
         ("CITATION\\'"        . R-mode)
         ("\\.omg\\'"          . omegahat-mode)
         ("\\.hat\\'"          . omegahat-mode)
         ("\\.lsp\\'"          . XLS-mode)
         ("\\.do\\'"           . STA-mode)
         ("\\.ado\\'"          . STA-mode)
         ("\\.[Ss][Aa][Ss]\\'" . SAS-mode)
         ("\\.jl\\'"           . ess-julia-mode)
         ("\\.[Ss]t\\'"        . S-transcript-mode)
         ("\\.Sout"            . S-transcript-mode)
         ("\\.[Rr]out"         . R-transcript-mode)
         ("\\.Rd\\'"           . Rd-mode)
         ("\\.[Bb][Uu][Gg]\\'" . ess-bugs-mode)
         ("\\.[Bb][Oo][Gg]\\'" . ess-bugs-mode)
         ("\\.[Bb][Mm][Dd]\\'" . ess-bugs-mode)
         ("\\.[Jj][Aa][Gg]\\'" . ess-jags-mode)
         ("\\.[Jj][Oo][Gg]\\'" . ess-jags-mode)
         ("\\.[Jj][Mm][Dd]\\'" . ess-jags-mode))
  :commands (R stata julia SAS))
```

**Comment by tmalsburg** [comment]
Similar problem in my setup after updating from ELPA:  When I `(require 'ess-site)`, I get the following errormessage:

```
    Debugger entered--Lisp error: (error "Recursive ‘require’ for feature ‘ess-r-mode’")
```

The same happens when I  `(require 'ess-r-mode)`. My Emacs is 26.0.60 compiled from git.

**Comment by tmalsburg** [comment]
Removing the `(require 'ess-r-mode)` in `ess-r-xref.el` seems to fix the issue.

**Comment by vspinu** [comment]
Thanks.  For unclear reason this didn't show up in with my config.

**Comment by sconti555** [comment]
I'm instead experiencing the same error on GNU Emacs 25.3.1 (x86_64-slackware-linux-gnu, GTK+ Version 3.22.21) even after commenting `(require 'ess-r-mode)` in ess-r-xref.el; am I missing something?

Many thanks in advance for any help!

**Comment by sconti555** [comment]
Erm... No, I haven't.  Sorry, rookie oversight; I'll report back tonoght.
 

Thank you for the pointer,


--
Stefano

 
 

Sent: Monday, March 12, 2018 at 9:20 AM

**Comment by lionel-** [comment]
This always bites us as well, Vitalie and I don't compile ESS for that reason ;)

**Comment by sconti555** [comment]
Sounds comforting, I must admit: I did feel very silly at responding to your e-mail.  :-)

 

Cheers!


--
Stefano

 
 

Sent: Monday, March 12, 2018 at 9:26 AM

**Comment by sconti555** [comment]
After compilation all is looking good as Emacs starts without troubles.  Many thanks again for your help, Lionel!
