### ISSUE TITLE
jit-lock-function error for continuous inferior prompt "+"

### ISSUE THREAD

**Issue by ShuguangSun** [emacs-ess/ESS#481]
Not urgent.
For those lines continuing from last line, the prompt will be "+" instead of ">".  It will raise error message:
Error during redisplay: (jit-lock-function 29135) signaled (search-failed "^> ")
Error during redisplay: (jit-lock-function 29197) signaled (search-failed "^> ")
Error during redisplay: (jit-lock-function 29135) signaled (search-failed "^> ")

```R
x <- data.frame(a =1 , b= 2)
x <- x %>%
  mutate(c = 1 - a)

x <- 1 + 2 +
  3
```

Windows, Emacs GNU Emacs 27.0.50 (build 6, x86_64-w64-mingw32) of 2018-02-04
ess-version: 17.11 [elpa: 20180204.901]

**Comment by vspinu** [comment]
Thanks for reporting. Such errors go usually unnoticed because they get swallowed by the message buffer.
