### ISSUE TITLE
Documentation outdated in some parts

### ISSUE THREAD

**Issue by AntonioFasano** [emacs-ess/ESS#496]
`ESS/doc/ess.texi` sections and related examples are primarily focused on S-PLUS and R is only seen as an alternative/special case. This was true in the past, now it should be right the opposite.  I was unable to find clear references to this product on TIBCO website, but according [wikipedia.org/wiki/S-PLUS](https://en.wikipedia.org/wiki/S-PLUS) the latest stable release is 7 years old and, "due to the increasing popularity of the open source S successor R", TIBCO Software itself has released a runtime for R. 

Similarly, the documentation speaks of "MSDOS prompt shell". The latest MSDOS was released in 2000. 
Even if keeping the old jargon for a while made sense, after 18 years from the last release, it doesn't help. Also, since 2009, PowerShell shell is an integral part of Windows, therefore examples should target this shell. Addressing the MSDOS shell might create confusion in new and younger users of Windows and ESS (who did not meet to the MSDOS era).

There are other similar instances (e.g. Cygwin, "new" features relatively old). I wonder whether the old sections are kept by design or there is simply a lack of time to update the documentation to devote more time to developing the project. In the latter case, one could volunteer to update the `ess.texi`.

**Comment by rsparapa** [comment]
Over the last 20 years that I have been involved, we have had 2 or 3 modernizations of the manual.  These were partially successful, but much work remains to be done.  There are several challenges:  ESS has a lot of features and it is a lot of work to properly document; there is so much material that keeping the docs up-to-date is difficult; and ESS is constantly evolving adding more and better features all the time.  Therefore, I'm not optimistic that this situation will ever change.

**Comment by mmaechler** [comment]
yes, to all said above.   If volunteers produce pull requests for improved documentatiion,  notably e.g., about "S-plus" and "MSDOS" .. we'd be happy to incorporate.  Do note that the docs are kept in 'texinfo' syntax  which you should continue using, since it's 'info' output is used much by emacs own info modes.

**Comment by jabranham** [comment]
I should have some time over the next week or so. I'll take a look into this and submit a PR soonish.
