### ISSUE TITLE
disable julia support

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#501]
There is emacs support for the julia language outside of ESS, is there a way to disable julia support in ESS so that I can still use it for R but not julia?

**Comment by vspinu** [comment]
It's not clear what you mean by "disabling". Any file put ins julia-mode.el will use julia mode, any file put in ess-julia-mode.el will use ESS layer on top of julia-mode.el. 

```el
(add-to-list 'auto-mode-alist '("\\.jl\\'" . julia-mode))
```

**Comment by gdkrmr** [comment]
ok, so I simply have to remove  `("\\.jl\\'" . ess-julia-mode)` from `auto-mode-alist`?

**Comment by vspinu** [comment]
No need to remove. just put the above line into the emacs. First one takes precedence.

**Comment by gdkrmr** [comment]
ok great, thanks!
