### ISSUE TITLE
ess-r-devtools-create-package fails if ess-r-package-library-paths is nil

### ISSUE THREAD

**Issue by yutannihilation** [emacs-ess/ESS#503]
The failure itself is not a big problem, but It's a bit hard (at least for me) to see what I should do.

```
ess-r-devtools-create-package: Wrong type argument: stringp, nil
```

**Comment by vspinu** [comment]
I personally never used this command. `devtools::create(...)` does the job.

**Comment by yutannihilation** [comment]
Thanks for the quick fix! I don't figure out when to use `ess-r-devtools-*` command and when to use `devtools::...` on R console yet. (I'm a newbie to Emacs/ESS)

**Comment by vspinu** [comment]
ESS's function is a lightweight wrapper around `devtools::` which picks your development library path (if you have defined one). See the doc/source of the function.
