### ISSUE TITLE
Electric-pair sometimes inserts extra ) in inferior process

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#504]
I'm running into an issue and wondering if anyone else has experienced it. With `electric-pair-mode` on, in an inferior R process:

```
> q(|)
```
with `|` representing point, typing `)` (bound to `self-insert-command`) results in an extra parens:

```
> q()|)
```

but only sometimes. I'm not sure if this is a bug in electric-pair-mode or ESS. Inferior R processes are the only place I've experienced this so far though.

Has anyone else run into this issue?

**Comment by lionel-** [comment]
Hmm I use this mode as well and never got this problem. Do you still see this with `emacs -q`?

**Comment by jabranham** [comment]
No, I don't. I'm assuming that the problem comes somewhere in `post-self-insert-hook`. Mine looks like `(helm-find-files--reset-level-tree electric-pair-post-self-insert-function electric-indent-post-self-insert-function blink-paren-post-self-insert-function)` in an inferior R buffer.

Do you use helm? Maybe it's doing something weird.

**Comment by lionel-** [comment]
I use helm.

**Comment by jabranham** [comment]
What does your `post-self-insert-hook` look like in an inferior buffer? That's what electric-pair-mode relies on to do its thing, but it seems like the order of functions is important. It calls `electric--sort-post-self-insertion-hook` to try to sort stuff, maybe something gets messed up there...

**Comment by jabranham** [comment]
Removing `helm-find-files--reset-level-tree` from `post-self-insert-hook` solves the problem for me. Since this isn't an ESS issue, I'll close this issue and open one on helm's issue tracker.

**Comment by lionel-** [comment]
I have: `(helm-find-files--reset-level-tree electric-pair-post-self-insert-function electric-indent-post-self-insert-function blink-paren-post-self-insert-function)`

**Comment by jabranham** [comment]
Well that's odd that you've got the same thing and don't see this. I'll look into it further...
