### ISSUE TITLE
Request: evaluate block

### ISSUE THREAD

**Issue by torbjorn** [emacs-ess/ESS#51]
As far as I can see, I can evaluate line, paragraph and region. And as far as I can understand, a paragraph is delimited by empty lines.

the paragraph eval is nice, it means I can break up long lines on more lines and still easily run they at once in the inferior process.

How about introducing eval block? It would identify the block that the cursor is in and evaluate it. that means I could easily run a loop in a buffer:

``` r
for( foo in bar ){

  some()

  code()

  here()

  that.can.have()

  air.in.it()

}
```

I could easily evaluate that loop by standing in it and, instead of first selecting all of it and evaluate region.

Now instead I find myself adding ## on blank lines to be able to achieve this with eval paragraph:

``` r
for( foo in bar ){
  ##
  some()
  ##
  code()
  ##
  etc()
}
```

.. which is not desirable

The hs-minor-mode already has code that can detect blocks of code like this, so it should be doable.

**Comment by jabranham** [comment]
This has been open 6 years and people seem lukewarm about it, so I'm closing this issue. If people still want it, feel free to reopen.
