### ISSUE TITLE
Indentation of if-else broken with Rstudio style but works with RRR 

### ISSUE THREAD

**Issue by vspinu** [emacs-ess/ESS#520]
A bit surprising that it works with one style and not another. More surprising that it escapes the tests.

```R

# with Rstudio
new <-
  if (blabla) as.POSIXct(time)
else time

# with RRR
new <-
    if (blabla) as.POSIXct(time)
    else time

```

**Comment by lionel-** [comment]
This is actually the correct output.

**Comment by mmaechler** [comment]
well.. I'm glad to not using it.. ;-b

**Comment by vspinu** [comment]
If Rstudio indents like this it's a bug in Rstudio. I don't think we should indent like this.

**Comment by lionel-** [comment]
It has indented like this for years, it's the result of the application of simple indenting rules. The RStudio style are for compatibility, the goal is to be able to cooperate with RStudio users and not have indentation bounce around as a function of the last person that worked on a file.

**Comment by vspinu** [comment]
I understand the rationale, but it doesn't make it right. If no-one is pushing for change, there will be no change. 

> not have indentation bounce around as a function of the last person that worked on a file.

This is an overrated reason. People work mostly on their own code, plus Rstudio users are unlikely to use such code in the first place because of the incorrect indentation. So, fixing this at Rstudio side is probably close to 100% backward compatible.

**Comment by lionel-** [comment]
I feel very strongly we shouldn't alter RStudio styles in an incompatible way. We already had this discussion when I developed the indentation algorithms btw, it actually took some work to produce the style above.

**Comment by lionel-** [comment]
Maybe we could add some relevant customisation variable to tweak this though?

**Comment by vspinu** [comment]
I guess you mean #290. I didn't care much about Rstudio style back then but now it finally bit me in the butt :/

Is this a known problem at Rstudio? I think if there is even a small chance to fix it there we should push for it. It's a pretty big blunder AFAIC.

> Maybe we could add some relevant customisation variable to tweak this though?

Sounds like a good idea and probably easy to add. Are there other places where you had to "fix" the indentation for R-studio's sake? If so, we could have something like `ess-strict-R-studio-indentation` (t by default) or `ess-correct-R-studio-indentation` (nil by default).

**Comment by lionel-** [comment]
> Is this a known problem at Rstudio?

I don't know. In the tidyverse / r-lib teams we always wrap blocks in curly braces and we avoid using the return value of `if` so this indentation never occurs in our code.

> If so, we could have something like ess-strict-R-studio-indentation (t by default) or ess-correct-R-studio-indentation (nil by default).

Hmm I don't think this is the right approach. I was thinking about making the settings more granular to allow users to write their own RStudio-like style.

Oh but I think you can actually already fix this!

```lisp
(setq ess-align-blocks '(control-flow))
```

It's probably not worthwhile to break down `control-flow` into if-else, while, etc.

**Comment by mmaechler** [comment]
>>>>> Lionel Henry <notifications@github.com>
>>>>>     on Sat, 14 Apr 2018 10:29:19 +0000 writes:

    >> Is this a known problem at Rstudio?
    > I don't know. In the tidyverse / r-lib teams we always wrap blocks in curly braces and we avoid using the return value of `if`

really?   That is so poor in my view.

R *is*  a functional language contrary to many other languages
which similar syntax.

Just because those languages don't have  if() as a function with
a return value (and an optional argument 'else' !)  we should
not write code as if R was much poorer than it is.

**Comment by lionel-** [comment]
> R *is* a functional language contrary to many other languages with similar syntax. 

But it doesn't have truthy NULL unlike normal lisps.

**Comment by vspinu** [comment]
> really? That is so poor in my view.

Agreed. It jars me as bad style when I see  `if (...) {foo <- ...  } else { foo <- ...}`.

> But it doesn't have truthy NULL unlike normal lisps

Yerh, if I could change one thing about the language this would be it. How can one take inspiration from lisp and forget about the nil punning ¯\_(ツ)_/¯?

**Comment by lionel-** [comment]
> You mean the equivalence of nil with FALSE, right?

Yes and as importantly, the equivalence of anything else with TRUE. That's quite different from integers being truthy (lisp idioms vs C idioms).

I'm not sure how this would have played out with logical vectors, you might be right that it could have been confusing.

**Comment by lionel-** [comment]
Though it might well have been _less_ confusing. You'd only use vectors with `ifelse()` and use `NULL` / sentinel with `if` and `while`. Fewer chances of passing a vector where a scalar choice is needed. Not sure what to think about having such different semantics for `|` and `||` though (the latter would essentially become what people define as `%||%`).

**Comment by vspinu** [comment]
> (setq ess-align-blocks '(control-flow))

This works! 

It should be set in a hook or within a custom style (in case someone else wants this).
