### ISSUE TITLE
Google Code Archive documentation deprecated

### ISSUE THREAD

**Issue by miguelmorin** [emacs-ess/ESS#532]
Hello,

I am starting to use `ess-tracebug` and read the two pages on the Google Code Archive, as suggested by the ESS documentation: [a more detailed ess-tracebug documentation with screenshots](http://code.google.com/p/ess-tracebug/) and [a short tutorial](http://code.google.com/p/ess-tracebug/wiki/GettingStarted). The screenshots are missing, the text is hard to read because of incomplete HTML tags, and it is only marginally deeper than the ESS documentation.

I propose to spend some time merging all three pieces of documentation into `ESS/ess.texi`, re-doing the screenshots, and removing the links to Google Code Archive. I could also update the documentation as I suggested in #519, and create a pull request. Any objections?

**Comment by vspinu** [comment]
Yes. I think that page is outdated. I will remove the link once #523 has been merged.

**Comment by miguelmorin** [comment]
Thanks @vspinu , I'll mention `ess-tracebug` there, then revisit or close this issue depending on the documentation update.

**Comment by miguelmorin** [comment]
@jabranham thank you for that, I have been away and only now saw your question along with all the commits.
