### ISSUE TITLE
`ess-dialect` empty in some situation:  M-x R  prompts with a leading ","

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#533]
After  `emacs -q` and   `(require 'ess-site "<my-ESS-devel>/lisp/ess-site.el")`, since very recently,
`M-x R ` prompts in the minibuffer :

    , R (default) staring project directory?  ~/...

Note the initial " ,"   

This must be a consequence of the recent  dialect <-> language  change.  Please fix (carefully).
Code is in `lisp/ess-inf.el`  but I'm not sure if having `ess-dialect` to be `nil` is really the intention or why this part of the code no longer correctly detects if the "," is needed...

**Comment by vspinu** [comment]
Probably caused by #521. @jabranham, any ideas?

**Comment by mmaechler** [comment]
Thank you guys!  Indeed nicely swiftly fixed.
