### ISSUE TITLE
Respect emacs "C-c <letter>" keybinding conventions

### ISSUE THREAD

**Issue by jackkamm** [emacs-ess/ESS#539]
I noticed that ess-noweb-mode binds "C-c h" to "ess-handy-commands". This is bad practice according to the emacs manual:

> Don't define C-c letter as a key in Lisp programs. Sequences consisting of C-c and a letter (either upper or lower case) are reserved for users; they are the only sequences reserved for users, so do not block them.
> 
> Changing all the Emacs major modes to respect this convention was a lot of work; abandoning this convention would make that work go to waste, and inconvenience users. Please comply with it.

Source: https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html

Here are the keybindings I found violating this convention:
```
ess-rd.el:192:    (define-key map "\C-ch" 'ess-handy-commands)
ess-sas-d.el:203:  (define-key sas-mode-local-map "\C-ci" 'ess-eval-line-and-step-invisibly)
ess-help.el:611:    (define-key map "\C-ch"   'ess-handy-commands)
ess-s-lang.el:750:  (define-key ess-mode-map          "\C-cf" 'ess-insert-function-outline)
ess-s-lang.el:751:  (define-key inferior-ess-mode-map "\C-cw" 'ess-execute-screen-options)
ess-noweb-mode.el:275:    (define-key map "\C-ch" 'ess-handy-commands)
```

**Comment by lionel-** [comment]
Good catch. Perhaps we should move these keybindings to `ess-site.el`.

**Comment by jabranham** [comment]
I've had my eye on this for a while. I'm happy to go through and modify these if no one else has done so already.

**Comment by vspinu** [comment]
> I'm happy to go through and modify these if no one else has done so already.

Would be great. 

I think it's safe to remove all those identified by @jackkamm. Some of those are not that useful, others have duplicated proper keys bindings.
