### ISSUE TITLE
R help pages highlighted incorrectly

### ISSUE THREAD

**Issue by mirkhosro** [emacs-ess/ESS#540]
When viewing R documentation using `?` R help pages are highlighted as if it's all R code which makes it difficult to read.
The textual part of the help page should not be highlighted, and only the example section should be syntax highlighted as R code.
I've attached some screenshots that show the problem. I'm using ESS version 20180504.716

<img width="810" alt="screen shot 2018-05-08 at 1 39 05 pm" src="https://user-images.githubusercontent.com/14208489/39773192-4864560a-52c5-11e8-99c4-d41f6e43a1d7.png">
<img width="755" alt="screen shot 2018-05-08 at 1 40 17 pm" src="https://user-images.githubusercontent.com/14208489/39773239-6be4dadc-52c5-11e8-9c9d-9de1711b6500.png">
<img width="765" alt="screen shot 2018-05-08 at 1 41 42 pm" src="https://user-images.githubusercontent.com/14208489/39773284-9306b5fe-52c5-11e8-96a7-ef1f578bf38f.png">

**Comment by vspinu** [comment]
I see this as well. Do you use polymode? I kinda assumed it has to do with it, but haven't had time to check/fix it.

**Comment by mirkhosro** [comment]
Yes, I have polymode 20170307.322 installed. Nice catch!

**Comment by mmaechler** [comment]
Yes, interestingly, I've also observed that just 2 days ago.    Starting string fontification after after a the apostrophe / single quote  may be somewhat newish and really is very impleasant.  It's been the exact same issue that had raised my eyebrows ...

**Comment by plantarum** [comment]
I ran into this too, for both single quotes and percent signs. I'm also using polymode. The following hook has resolved it for me, at least as a temporary fix:

    (defun tws-ess-help-mode-hook ()
      (modify-syntax-entry ?' ".")
      (modify-syntax-entry ?% "."))
    (add-hook 'ess-help-mode-hook 'tws-ess-help-mode-hook)

**Comment by eddelbuettel** [comment]
Yes please. I just got this yesterday from `help(data.table)` which also has a stray aposthrophe.  (And polymode is indispensable otherwise for all the goodness that is mixing R and Markdown.)

**Comment by vspinu** [comment]
Strictly speaking this is not a polymode problem. It's a bit complex how the issue came about but the crux is that font lock was always on in the help buffers but somehow it was dormant all this time, and with recent compilation cleanups it became alive.

I am fixing this by deactivating font-lock in help buffers as it should be.

**Comment by mmaechler** [comment]
Aaahh.. thank you, that's so very releaving  (almost as fresh shower in the summer heat ...)!!

**Comment by vspinu** [comment]
Uff, this one re-emerged after polymode rewrite ...
