### ISSUE TITLE
language server for R

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#554]
FYI: there is a language server for R, I have not tested it and don't know how it compares to lintr 

https://github.com/REditorSupport/languageserver

**Comment by lionel-** [comment]
Thanks for the heads up.

**Comment by vspinu** [comment]
languageserver is designed for statically typed languages and it cannot add much to the dynamic completion systems as the one we already have in ESS.

**Comment by gdkrmr** [comment]
I have tested the R language server now and it has some nice features, such as not completing the function names of a package if it is not imported into your package and local variable names, and it seems relatively smart in detecting which function documentation to open. On the other end all the dynamic stuff is missing, as @vspinu mentioned, e.g. list element name autocompletion does not work.

There is also some serious work going into `lsp-mode` and `eglot`, I think the best thing would be to combine both somehow, maybe by writing a language server backend that uses an inferior R process.

Here is some more discussion: https://github.com/syl20bnr/spacemacs/pull/12929

**Comment by jabranham** [comment]
I've tested the language server a bit too via eglot and am pretty happy with it. It can do some things ESS can't and ESS can do some things it can't. I think ATM ESS is a bit better since it's designed specifically for R and a data analysis workflow, but perhaps in the future we should look into this more.

**Comment by gdkrmr** [comment]
I think the major problem is using both together, loading language server removes all autocompletion for ess (at least in the spacemacs layer).

**Comment by jabranham** [comment]
This is because `eglot-completion-at-point` returns "No matches" rather than nil when it doesn't have completion to offer. Not sure if that's eglot's fault or R's language server. You might check with the eglot devs, they may have a better idea how to debug that code.
