### ISSUE TITLE
Opening paren gets highlighted after for( in( etc

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#563]
Due to the recent changes in #538, the opening paren gets highlighted if I have:

```
for( )
```

or 

```
in()
```

or 

```
function(x)
```

@lionel-

**Comment by jabranham** [comment]
Also in the inferior process, in this part of the startup message:

```
  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

```

the "in" in "in and English locale" and the "in" in "packages in publications" both still get highlighted for me.

**Comment by lionel-** [comment]
oh hmm thanks, I'll look into it. I use a package to colourise parentheses so I didn't notice, I'll add tests.

> the "in" in "in and English locale" and the "in" in "packages in publications" both still get highlighted for me.

Yes these cases are not covered by the new changes. I plan to use a non-regexp approach to fontify these.

**Comment by jabranham** [comment]
Great, thanks! 

Thanks for the improvements, BTW. Especially the non-fontification of most if/in without parens stuff. That was aggravating before.
