### ISSUE TITLE
M-x R buffer name now  `*/my/relatively/long/path/to/R*` when `ess-use-inferior-program-in-buffer-name` 

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#570]
s.Subject:  This has started happening for ca. 1 week now.  I guess it is related to the changes of the function names and making `R` an alias for `ess-run-R` .. but I have not digged.
Previously, if I use  M-x R, the buffer was named `*R*`, `*R:2*` (2nd instance) etc.  The same behavior we still have for the default  `(setq ess-use-inferior-program-in-buffer-name nil)`. But I do want this `t` as I do need to have R buffer names depending on the R version: As R core member, I want to have *R-devel* *R-3.4.4* etc together with *R*... In neither case I want to see the PATH of the executable.

**Comment by jabranham** [comment]
Thanks, I think that's my fault. Can you try #571 and let me know if that fixes it?

**Comment by mmaechler** [comment]
I'm not a git master.. and rather not clone your clone.
It's not just about `R-devel` (which actually did show fine: only 'R' did not).
Can you not check yourself?   This *did* work nicely previously...

**Comment by jabranham** [comment]
Sorry, I should've been more specific. I did check it on my end, and it fixes it for me. It will now show the name of the executable you're running, not the whole path. So if you're running `/path/to/R-devel`, it'll show that.

**Comment by mmaechler** [comment]
and if I run `M-x R-3.4.4`  it will be `*R-3.4.4*`  because the basename of the executable (sh script) is 'R-3.4.4' -- good!    So, I'll merge #571 and will check.

**Comment by mmaechler** [comment]
indeed things seem to behave fine now.

**Comment by jabranham** [comment]
Great! Sorry to have messed it up earlier.
