### ISSUE TITLE
ess 17.10 fails to load {S,R} transcript file

### ISSUE THREAD

**Issue by csrabak** [emacs-ess/ESS#572]
On a GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-26,  ess-version: 17.11 [elpa: 17.11] (loaded from c:/Users/csrabak/.emacs.d/elpa/ess-17.11/)ess-version: 17.11 [elpa: 17.11] (loaded from c:/Users/csrabak/.emacs.d/elpa/ess-17.11/)

Loading a script file (extension .Rt) fails with following message (after an Alt-X ess-transcript-mode issuing in the already loaded file at current buffer):

funcall-interactively: Wrong number of arguments: #[(alist &optional proc) "ÆÇ!È ÉÊ	!ËÌÍ!Î


**Comment by csrabak** [comment]
I cannot find any mention to this behaviour and 17.10 is not specially brand new, so I wonder if I miss something in the process of updating.

This version was installed via ELPA mechanism.

**Comment by jabranham** [comment]
I think you should call `R-transcript-mode`, not `ess-transcript-mode`.

**Comment by jabranham** [comment]
`ess-transcript-mode` is currently marked interactive, but probably should not be, since it will always error because the customize-alist isn't set. I can submit a PR to remove the interactive call.
