### ISSUE TITLE
new smart assign behaves weird

### ISSUE THREAD

**Issue by gdkrmr** [emacs-ess/ESS#584]
I have set `ess-smart-S-assign-key` to `"\M--"`, now `M--` inserts `<-`,  but if I press `M--` two times, `<-` changes to `\255`. Can this be reproduced by anyone?

**Comment by jabranham** [comment]
Yes, `ess-smart-S-assign` is doing what the docstring says. When called twice, it deletes `ess-S-assign` and inserts `ess-smart-S-assign-key`. So `(insert "\M--") inserts `\255`. 

What was the behavior before? It would insert `_`?

**Comment by gdkrmr** [comment]
I actually never used this, but I think it was `_`, maybe this should default to `=` or nothing.

**Comment by lionel-** [comment]
Old behaviour was indeed to insert `_`, that's also how it works in RStudio. Maybe we should check if the key is an ASCII character, and use `_` as default if not the case?

**Comment by gdkrmr** [comment]
I could also imagine cycling `<-`, `=`, and nothing, this would be useful for function parameters. `_` is only useful if `ess-smart-S-assign-key` is bound to `_`

**Comment by vspinu** [comment]
There are at least 5 possibilities: 

  1) Insert <- repeatedly (which R-studio seems to be doing)
  2) Insert last key in the combo (in the OP it's "-")
  3) Cycle to <<-  (I would find this most useful)
  4) Cycle to =
  5) Or cycling through some of 2, 3 and 4 combined

**Comment by jabranham** [comment]
We could have a variable `ess-smart-S-assign-cycle` or some such that allows users to cycle through various symbols?

I don't think we can do 2/3/4/5 by default since people would have no way to type `_`, right?

**Comment by jabranham** [comment]
Here's what I propose:

- We make `ess-insert-S-assign` into a function that inserts `ess-S-assign` and if some new variable `ess-convert-S-assign`? is a string, converts `ess-S-assign` to that string if `<-` is already there. We bind `ess-insert-S-assign` to `_` and make `ess-convert-S-assign`  `_` by default. This preserves the current default behavior.

- We make `ess-smart-S-assign` toggle between insertion of several assignment operators. The operators it toggles through are stored in a new defcustom `ess-smart-S-assign-options`? and by default it could look something like `'("<-" "<<-" "=")`. 

I'm happy to implement this if it sounds good to other people.

**Comment by gdkrmr** [comment]
@vspinu The frequency I use assignment operators in R in order for me is: `<-`, `=`, `->`, `<<-`.
@jabranham I personally don't like the behaviour that `_` inserts assign, because I use `_` all the time in my variable names, but as long as I can turn it off I don't care if the functionality exists.

**Comment by vspinu** [comment]
How many people use `_` for smart assign actually? To me it looks like the the vast majority disable it. So, maybe this refactoring is a good time to disable it by default. I think interfering with such basic keys is a non-standard and offending behavior. Major modes should stick to C-c map.

On the other hand, ideally we should break compatibility for several features simultaneously. v19.04 is  likely to introduce major breaking changes, so we could also wait till then.

What do people think?

**Comment by vspinu** [comment]
> Here's what I propose:

How about for the next release we make `ess-smart-S-assign-key` it accept a list of symbols and make it nil by default. On the other hand, it's not our business to do "smart" keys. There are specialized modes for that.

**Comment by jabranham** [comment]
With the PR I just submitted, you can insert ` <- ` by doing `C-c C-=`.

**Comment by fmichonneau** [comment]
I use `_` for smart assign (and in variable names). On a French keyboard layout, it's a very convenient single keystroke. If the default behavior is changed, I hope it will be easy to remap.

**Comment by mmaechler** [comment]
@fmichonneau -- I agree and also use _ for both assignment, and with doubling for _
