### ISSUE TITLE
Should all path commands abbreviate path?

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#586]
This way paths sent to R are relative to `~`, and this makes it easy to use ESS with R running on e.g. docker with a different user home path (assuming one has symlinked the relevant directories). Any objection?

**Comment by vspinu** [comment]
No objection. This should work better on remotes and looks better in the inferior.

**Comment by vspinu** [comment]
I am labeling this for 18.09. I think it's important to streamline this part. Especially that we have a report on ESS mailing list which seems to be a bug in ESS:

```
## From: "Marcora, Edoardo" 

Looking at the TRAMP debug buffer, this is where things hang...

11:53:28.096969 tramp-send-string (10) # cd /hpc/users/XXX/projects/ad.myeloid/2018-08-22.hgnc_reannot/ &&  exec  env PS1\=/ssh\:XXX\@bode.hpc.mssm.edu\:/hpc/users/XXX/projects/ad.myeloid/2018-08-22.hgnc_reannot/\ \#\$\  TERMCAP\= COLUMNS\=117 INSIDE_EMACS\=26.1\,comint STATATERM\=emacs PAGER\=cat /usr/local/bin/R --no-readline

It calls "/usr/local/bin/R" whereas my R resides in /hpc/packages/minerva-common/R/3.5.1/lib64/R/bin/R
```

**Comment by jabranham** [comment]
That is a result of 2c4e127a73669abb0d0f0b5d42519d7707342a1c where we started using executable-find to set inferior-ess-r-program. We could just change back to "R" instead of using executable-find.

**Comment by vspinu** [comment]
Indeed. Let's go back on that.

**Comment by vspinu** [comment]
I think it's a bit too late for 18.09 for this, so I am relabeling it for 19.04.

Regarding the OP, @lionel- I would be curious to know your setup for running R on dockers. I could come up only with hacks so far.

**Comment by lionel-** [comment]
I don't have a great setup. I just run the container with my projects folder mounted in the same relative path as on my computer. Then I call `ess-remote` in the buffer with R running in the docker and all commands using abbreviated paths work more or less well. It'd be nice to streamline the process.

**Comment by jabranham** [comment]
Have you tried docker.el? I think it integrates TRAMP with docker.

**Comment by vspinu** [comment]
I did, it's for tabular views and basic manipulation of containers and machiens but no tramp integration. There is a docker-tramp.el floating around but I haven't tried it.

**Comment by jabranham** [comment]
I haven't seen a non-abbreviated filename for a while, so I'm closing this. Feel free to reopen if I've missed something.
