### ISSUE TITLE
ESS dissapeared from MELPA?

### ISSUE THREAD

**Issue by rsuhada** [emacs-ess/ESS#590]
After recent upgrade ess-mode can not load for me (Error (use-package): Cannot load ess).
I've noticed it is no longer in MELPA? Is this intended.

Thank you very much!

**Comment by jabranham** [comment]
ESS seems to be in MELPA: http://melpa.org/#/ess

Perhaps you need to do `package-refresh-contents` and/or add melpa to `package-archives`?

**Comment by ReginaldM** [comment]
ess is still listed on the MELPA website, but when I tried to install ess through MELPA it isn't listed emacs itself.

**Comment by vspinu** [comment]
Yes. It's on melpa. I just installed and it works. Try manually removing ESS from elpa folder and try again without use-package.

**Comment by rsuhada** [comment]
Thank you. Can confirm it started working on the same day. I'm 99% positive that at that moment it disappeared (I could not load, and I did check the online interface and wasn't there...). Not sure, maybe was rebuilding?

In any case, we can close it. Thank you.
