### ISSUE TITLE
ess.el should be required

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#592]
Now that we've moved towards autoloading everything, it would be nice if `ess.el` would be required at some point so that people could do:

```
(with-eval-after-load "ess" 
    <ess config>)
```

which is what `use-package` does (kind of) if you `(use-package ess :defer t)`.

Since there's basically nothing in `ess.el` right now, one easy way of doing this would be to rename a file that everything relies on to `ess.el`. I nominate `ess-custom.el` as a candidate.

Any objections?

(related to #589)

**Comment by vspinu** [comment]
This is a good proposal. I just want to mention that I used to think about ess.el in the other way around. Like an entry point for all other files (what we have with ess-site.el) right now. So users could do `(require 'ess)` and load all ess functionality. But addmitedly this is less useful than you propose.
