### ISSUE TITLE
Obsolete several languages?

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#595]
Since the current plan AFAIU is to re-write how ESS mode is defined after the next release, we should probably obsolete all the languages we don't want to rewrite. We can put an entry in newfeat along the lines of:

"Support for several languages have been obsoleted and will be removed in the next release.
Please contact us if you still use these, if there is enough demand we may continue to maintain them. These include..."

And here's a list of files we could obsolete (this leaves support for R, Stata, SAS, julia, and bugs/jags):

- ess-dde
- essd-els
- ess-gretl
- ess-omg-d
- ess-omg-l
- ess-lsp-l
- ess-vst-d
- ess-xls-d
- ess-arc-d
- ess-r-gui
- ess-s3-d
- ess-s4-d
- ess-sp3-d
- ess-sp4-d
- ess-sp5-d
- ess-sp6-d
- ess-sp6w-d

Thoughts?

**Comment by vspinu** [comment]
Good point. :+1

**Comment by jabranham** [comment]
This is done in `next`, closing
