### ISSUE TITLE
org-babel-R output broken by recent ESS commit

### ISSUE THREAD

**Issue by jackkamm** [emacs-ess/ESS#598]
Recent commit 74d5fbbcde8c2aea5d87c82875e37c134d1af4cb ("Improve on + + replacement and offset detection") has broken org-babel-R output.

In particular consider the following example:
```
#+BEGIN_SRC R :session :results output
  print("hello")
#+END_SRC
```
Before the commit, org-babel successfully prints:
```
#+RESULTS:
: [1] "hello"
```
However after the commit it fails to capture the output, simply printing:
```
#+RESULTS:
```
I'm not totally sure, but I think the issue is that org-babel prints an extra token to mark the end of the output, and expects this token to be preceded by a prompt, which it later uses to strip away this token. But it can no longer find the prompt so just strips away the whole output. See also:   `org-babel-R-evaluate-session`, `org-babel-comint-with-output`

EDIT to add: I've also posted this issue to the emacs org-mode mailing list, http://lists.gnu.org/archive/html/emacs-orgmode/2018-07/msg00011.html

**Comment by lionel-** [comment]
Thanks. We definitely should get some org-babel stuff covered by our unit tests.

**Comment by vspinu** [comment]
We are inserting new line after the prompt now. So if ob could slightly modify the lookup regexp it should fix the problem.

**Comment by lionel-** [comment]
> We are inserting new line after the prompt now.

Is it intentional that the newline is always inserted? I find it distracting:

```
> "foo"

[1] "foo"
```

Instead of:

```
> "foo"
[1] "foo"
```

**Comment by jackkamm** [comment]
I'm not so sure the newline after the prompt is the issue, in fact I don't even see it after the offending commit, getting just:
```
> "foo"
[1] "foo"
```
And in fact the raw output in the `*R*` buffer looks exactly the same for my example both before and after the commit:
```
> print("hello")
'org_babel_R_eoe'
print("hello")
[1] "hello"
> 'org_babel_R_eoe'
[1] "org_babel_R_eoe"
> 
```

**Comment by vspinu** [comment]
Output is not changed, but the internals how output is inserted have been changed. Prompt are now inserted without calling the comint filter as an optimization. But org-babel assumes that all output goes through the comint filter; this is how they accumulate it. I guess I will just remove the optimization for the sake of org-mode and other external tools.

**Comment by lionel-** [comment]
Interesting. How large is the performance gain with this optimisation?

**Comment by vspinu** [comment]
Probably not large given that there are few prompts in usual output. The main reason was simplicity, to avoid all that complicated stuff in comint filter and output functions which, I thought, should be never doing anything meaningful with prompts.

Should be fixed now and test added. @jackkamm any other org-babel snippets which we could include in our tests? Different parameters, different output?

**Comment by jackkamm** [comment]
Awesome, thanks for taking care of this so quickly!

An easy way to get a couple more simple tests would be to remove the `:session` parameter and/or use `:results value` instead of output, e.g.
```
#+BEGIN_SRC R :results value
  "hello"
#+END_SRC
```
Varying these 2 parameters yields 4 unit tests which test basic functionality for the common org-mode use cases. I removed the call to `print` because `:results value` expects a returned value instead of printed output; note `print` isn't needed for `:results output` either, allowing to use the same snippet for all 4 cases.

If you wanted to be even more extensive, another thing to test would be org-babel's ability to capture dataframes and print them as tables in the buffer, e.g.
```
#+BEGIN_SRC R :session :results value :colnames yes
  data.frame(x=1:3, y=c("a","b","c"))
#+END_SRC
```
which prints in the buffer
```
#+RESULTS:
| x | y |
|---+---|
| 1 | a |
| 2 | b |
| 3 | c |
```

**Comment by vspinu** [comment]
Perfect. This is exactly what I was looking for. Added.

**Comment by lionel-** [comment]
@vspinu I'm getting strange results with the new filtering stuff (with both current master and master from just after the merge), Emacs blocks during evaluation and output is discarded when an error occurs. I'll post a reprex when I find some time, but just a heads up that this is not ready for release yet.

**Comment by jackkamm** [comment]
I'm also noticing blocking in R buffers since updating, even during editing -- possibly caused by autocompletion (company) waiting for inferior ESS?

**Comment by fkgruber** [comment]
It would be nice if the testing also include the case of a remote R session.
```
#+BEGIN_SRC R :session :results value :colnames yes :dir /ssh:server:~/
  data.frame(x=1:3, y=c("a","b","c"))
#+END_SRC
```
should still print

```
#+RESULTS:
| x | y |
|---+---|
| 1 | a |
| 2 | b |
| 3 | c |
```
