### ISSUE TITLE
ess-rutils-help-start.R not found error when starting R

### ISSUE THREAD

**Issue by jrvarma** [emacs-ess/ESS#599]
After executing `(require 'ess-rutils)`, starting `R` causes an error:

`ess--inject-code-from-file: Opening input file: No such file or directory, .../etc/ess-rutils-help-start.R`

`ess-rutils.R` adds the command `(ess--inject-code-from-file ess-rutils-rhtml-fn)` to the `ess-r-post-run-hook` and defines `ess-rutils-rhtml-fn` to be `ess-rutils-help-start.R` in the `ess-etc-directory`. 

`ess-rutils-help-start.R` used to be there in version 17.11, but the error has started after upgrading.

**Comment by jabranham** [comment]
Looks like it was removed in 8708bad591d5ca2c59892cec29bc6f851e3ae523 @vspinu

**Comment by vspinu** [comment]
Yeh. That functionality predates ESSR and I missed it by accident.
