### ISSUE TITLE
Prompts are not displayed on a newline after evaluating empty string

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#600]
With cursor at an empty prompt:

```
> *cursor*
```

Hitting RET several times produces this:

```
> > > *cursor*
```

Instead of

```
>
>
> *cursor*
```

**Comment by lionel-** [comment]
Possibly related: Hitting RET here:

```
> Sys.sleep(3)*cursor*
```

does not result in a newline for the duration of the command. When evaluation is finished the prompt looks like this:

```
> Sys.sleep(3)>*cursor*
```

**Comment by lionel-** [comment]
Another case:

```
> invisible("foo")*cursor*
```

RET


```
> invisible("foo")>*cursor*
```

Without `invisible()` I get expected result.

@vspinu @jabranham would it be possible to cover all these cases in unit tests?

**Comment by vspinu** [comment]
Yeh. This is a consequence of the most recent commit where I asked comint not to insert new lines. I thought that the only consequence of this is that no new prompt is displayed on empty input which is not a big deal, but your issues is with empty output. 

I will have a look, but it's hard without complicating the logic. I will implement something simple and approximate which should work in 99.99% of cases.

**Comment by lionel-** [comment]
That's good, I see every new bug as an opportunity to increase our test coverage :)

**Comment by lionel-** [comment]
I've been getting lots of extra newlines in output lately. This works fine:

```r
> ﻿letters
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r"
[19] "s" "t" "u" "v" "w" "x" "y" "z"
>
```

But this doesn't:

```r
> list(letters)
[[1]]
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r"
[19] "s" "t" "u" "v" "w" "x" "y" "z"

>
```

**Comment by vspinu** [comment]
This is how R works in terminal as well. Not ESS specific.

**Comment by lionel-** [comment]
Oh hmm... damn. Maybe worth a little patch to the R printer.

**Comment by lionel-** [comment]
I think the extra lines I've been seeing come from `ess-eval-line`. Can you confirm?

**Comment by vspinu** [comment]
Which extra lines? There is only one in your example (`list`) and that one comes from R's printer.

**Comment by lionel-** [comment]
Not on that example, on any line. I can't reproduce with -Q so something in my config seems to be causing issues.

**Comment by lionel-** [comment]
Here is a reprex with ESS later than https://github.com/emacs-ess/ESS/pull/576

```lisp
(setq ess-eval-visibly-p 'nowait)
```

Then within an R file:

```
"foo" <C-c C-J>
```

Output:

```r
> "foo"

[1] "foo"
```

**Comment by vspinu** [comment]
Right, it's a nowait thing. Will check.
