### ISSUE TITLE
ESS modifes built-in variables in ess-noweb-mode

### ISSUE THREAD

**Issue by bbo2adwuff** [emacs-ess/ESS#609]
ESS modifes built-in variables in:
https://github.com/emacs-ess/ESS/blob/d947e772639fb8b5957ea3afbbebff583e9a46cf/lisp/ess-noweb-mode.el#L411-L426

That can break other modes, see
https://github.com/abo-abo/swiper/issues/1660

**Comment by jabranham** [comment]
Yes, ess-noweb is broken in more ways than one. Personally I think it should be removed from ESS.

I would like to see a new package that uses edit-indirect (https://github.com/Fanael/edit-indirect) to replicate org's edit-src behavior for Rnw files. 

Users of Rmarkdown can just put those files in markdown-mode, which already supports edit-indirect if it's installed.

**Comment by lionel-** [comment]
edit-indirect might also be useful for roxygen `@examples` blocks.

**Comment by vspinu** [comment]
We are really bad citizens on this one. Will remove ess-noweb immediately after the release. I have looked at this issue 2 years ago in #305 and I didn't find a good solution to make those hooks non-permanent. See also #215 where it broke helm similarly.

**Comment by jabranham** [comment]
ess-noweb stuff is now obsolete, poly-R is the replacement
