### ISSUE TITLE
Compiling *.el now *breaks* functionality

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#612]
I don't know for how long... just noticed it now.  As I always automatically compile the lisp/*.el files after `git pull`..

To reproduce, type `make`  in the toplevel ess directory.
Then   `emacs -f R`  and within *R* buffer, use

`C-c C-v`  (which aims opening a help page in a buffer)

---> I get an error.

The `*Messages*` buffer then ends with

>  inferior-ess-mode-hook: Increasing ess-loop-timeout..
> Type C-h m for help on ESS version 17.11
> ess-tracebug mode enabled
> Forming completions for .GlobalEnv...done
> Forming completions for ESSR...done
> Forming completions for package:graphics...done
> Forming completions for package:grDevices...done
......
> Forming completions for Autoloads...done
> Forming completions for package:base...done
> Retrieving RDS aliases...done
> ess-s-get-help-topics-function: Invalid function: with-ess-process-buffer

and indeed,  `with-ess-process-buffer` is not a function but a macro (defined in `ess-inf.el`).

**Comment by jabranham** [comment]
I'm having problems reproducing this. Can you capture the error with debug-on-error set to t and post the backtrace?

**Comment by vspinu** [comment]
I think it's some sort of cross compilation issue. Some old elcs are loaded for you. `make clean` should be fixing those.

**Comment by mmaechler** [comment]
@vspinu : no it's not as simple.  Cleaning out old *.elc and compiling from scratch was of course the first thing I tried (*before* opening an issue)..

The reason you seem not to reproduce is that of course we all load other emacs packages at startup, whereas for me it bombs and for you it doesn't .    

Still the errors message is pretty clear: One of our functions expect a function but only gets a macro..
That's pretty clear, no?

Yes, I'll send the backtrace ..

**Comment by vspinu** [comment]
I can reproduce. Such errors have to do with missing require during the compilation. Will have a look.

**Comment by mmaechler** [comment]
Thanks in advance @vspinu .   Strange that you can't reproduce @jabranham ... Does `make` not work for you?  Did you try hard?
To reproduce, inside the  `ess/lisp/`  directory:
```
emacs -Q -l ess-site.el  -f toggle-debug-on-error -f R
```
then (after choosing the directory in which to run), R starts, and "inside"  the  *R*  buffer, you type
`C-c C-v`  to ask for help.
Then the following is produced into the backtrace buffer: 
```

Debugger entered--Lisp error: (invalid-function with-ess-process-buffer)
  with-ess-process-buffer(nil nil "NULL" (".filled.contour" "abline" "arrows" "assocplot" "axis" "Axis" "axis.Date" "axis.POSIXct" "axTicks" "barplot" "barplot.default" "box" "boxplot" "boxplot.default" "boxplot.matrix" "bxp" "cdplot" "clip" "close.screen" "co.intervals" "contour" "contour.default" "coplot" "curve" "dotchart" "erase.screen" "filled.contour" "fourfoldplot" "frame" "grconvertX" "grconvertY" "grid" "hist" "hist.default" "identify" "image" "image.default" "layout" "layout.show" "lcm" "legend" "lines" "lines.default" "locator" "matlines" "matplot" "matpoints" "mosaicplot" "mtext" "pairs" ...))
  ess-s-get-help-topics-function("R")
  ess-find-help-file("Help on")
  (list (ess-find-help-file "Help on"))
  (progn (ess-force-buffer-current) (if current-prefix-arg (progn (ess-process-put (quote sp-for-help-changed\?) t))) (list (ess-find-help-file "Help on")))
  call-interactively(ess-display-help-on-object nil nil)
  command-execute(ess-display-help-on-object)

```

**Comment by jabranham** [comment]
Ah, I can reproduce that, thanks. 

I'm in the middle of preparing a patch to deal with a large number of these such warnings and errors, I should be able to submit a PR soon (today). 

Eventually I'd like to get it set up so that Travis errors on byte compiler warnings during compilation, which will eliminate these types of bugs.

**Comment by mmaechler** [comment]
Indeed the bug is fixed.  thank you!
