### ISSUE TITLE
`ess-smart-S-assign` does not work in polymode due to `ess-r-syntax-table`

### ISSUE THREAD

**Issue by theGreatWhiteShark** [emacs-ess/ESS#613]
When using a combination of R + Markdown in the package [polymode](https://github.com/vspinu/polymode) the `ess-smart-S-assign` function does not work in the R code chunks enclosed by three backquotes. (see https://github.com/vspinu/polymode/issues/147)

The problem is caused by the definition of the backquote in the syntax-table of R within ESS. There it is set to behave like a string delimiter. 

``` lisp
;; from /lisp/ess-r-mode.el line 226
(modify-syntax-entry ?` "\"" ess-r-syntax-table)
```

This causes the `syntax-ppss` function within the `ess-smart-S-assign` function to mistake the R code chunk for a string (opened by the third backquote). 

This problem seems to be only present in Emacs versions later than 25.3.

Could the definition of the backquote be changed to a paired delimiter instead? What problems could be caused by doing so?

**Comment by jabranham** [comment]
I'm not sure how to switch this and keep `ess-backquoted-face` using syntactic font lock.

**Comment by vspinu** [comment]
This is a more general problem which should be fixed on polymode side. I will have some time to dig into this and other issues over this week.

**Comment by vspinu** [comment]
It's fixed in polymode's `next` branch. It's emacs26 issues quite unrelated to ESS.
