### ISSUE TITLE
ctrl+enter does not insert linebreak

### ISSUE THREAD

**Issue by philiparvidsson** [emacs-ess/ESS#620]
# description

using ctrl+enter in emacs with ess does not insert a newline, which sometimes causes usability problems

# how to reproduce
1. start emacs
2. enable ess-mode
3. type a trivial R-statement
4. press ctrl+enter

# expected results

the line is evaluated and a new line is inserted below the statement

# actual results

the cursor is moved back to the beginning of the same line

# additional info

the newline should be inserted when the cursor is at the end of the buffer, otherwise just move the cursor to the next line (or statement)

**Comment by vspinu** [comment]
What usability problem are you talking about?

> the line is evaluated and a new line is inserted below the statement

C-RET is bound to ess-eval-region-or-line-and-step which is an evaluation command. It cannot and should not do editing in the buffer. C-RET is undefined in other modes so I don't see any usability issues here. 

 If you want a different behavior then you should write your own command or rebind C-RET to an existing command, but it's not possible to change that on ESS side.
