### ISSUE TITLE
error in process filter: Invalid byte opcode: op=183, ptr=27

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#622]
One of the very latest changes made ESS unusable for me (with R).
Reprex:     `emacs -f R foo.R`
and then in `foo.R` try to send a line of R code to the `*R*` buffer.  
In a simple case, the line is sent, and the answer is printed, in other case that does not even happen.
In any case the R process buffer subsequently seems to "hang" ... not interruptable by `C-g` or `C-c C-c`.

The `*Messages*` buffer shows                  

```
error in process filter: ess--replace-long+-in-prompt: Invalid byte opcode: op=183, ptr=27
error in process filter: Invalid byte opcode: op=183, ptr=27

```

I do have non default settings and the bug does not show with

```
 echo '1+2' > foo.R
 emacs -Q -l ~/emacs/ess/lisp/ess-site.el -f R foo.R
```

but I'd prefer to do R coding to today rather than ESS debugging...

**Comment by lionel-** [comment]
Sounds like an old elc is lingering in your repo? Does a `make clean` fix things?

**Comment by lionel-** [comment]
Or perhaps in your config folder given it doesn't occur with `-Q`?

**Comment by mmaechler** [comment]
Thank you @lionel-  .. I tried to `git checkout master{2018-07-28}`   but had a typo there and ended up with git - mess (detached head)....  which lead me to a completely new clone and `make`  which indeed did resolve the problem.   So  your diagnosis about a stray `*.elc` was probably correct and I could have save quite a bit of your and my time... helas..

**Comment by vspinu** [comment]
Invalid op-code happens when you compile with newer emacs and then open with an older one.

**Comment by smonff** [comment]
A *solution* to this is to delete all compiled EmacsLisp files in the user's Emacs directory
   
    cd ~/.emacs.d/
    find . -name "*.elc" -type f 

Once you are satisfacted by what the find command returns (it should only return `.elc` files), delete them with the `-delete` option:

    find . -name "*.elc" -type f -delete

Then restart Emacs and they will be regenerated when needed.
