### ISSUE TITLE
new in ess-20180808.852 : incorrect startup.

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [emacs-ess/ESS#627]
Following solution of issue [#623](https://github.com/emacs-ess/ESS/issues/623), on another machine, I uninstalled the Debian ESS packages and (re-)installed afresh `ess` from MELPA.

It doesn't start correctly : I get the following in the \*Messages\* buffer (it also flashes in the echo area)
```
load ESSR: + + + Error in file(filename, "r", encoding = encoding) : 
  impossible d’ouvrir la connexion
De plus : Warning message:
In file(filename, "r", encoding = encoding) :
  impossible d’ouvrir le fichier ’/home/charpent/.emacs.d/elpa/ess-20180804.1351/etc/ESSR/R/.load.R’ : Aucun fichier ou dossier de ce type
```

Other symptoms : 
* no tab completion ;
* no help in the echo area what typing code ;
* no online help (trying `?glm` gives me `Error in .ess.help("glm") : impossible de trouver la fonction ".ess.help"` in the echo area (and in the \*Messages\* buffer.

I'll temporarily uninstall MELPA's ess and revert to Debian's ess package, but I'm willing to help debug this one.

**Comment by EmmanuelCharpentier** [comment]
The problem seems to have been fixed by forced reinstallation and *restarting emacs* once more. I might have overseen a forgotten emacs server process, whih may have prohibited the previous restart...

For the moment, I keep this issue open, and I'll close it if/when I'm convinced that this was the case.

**Comment by jabranham** [comment]
Yes, that's Emacs complaining that it can't open the file /home/charpent/.emacs.d/elpa/ess-20180804.1351/etc/ESSR/r/.load.R. Since this file does indeed exist in ESS, sounds like an installation problem. To resolve you should close Emacs and do something like:

```
rm -rf ~/.emacs.d/elpa/ess-*
apt-get --purge remove emacs-ess
```

then start Emacs and do `M-x package-refresh-contents`, `M-x package-install ess`.

After all that finishes, you should be good-to-go.

**Comment by EmmanuelCharpentier** [comment]
That's (about) what I did. I may have missed it the first time, possibly because of a forgotten emacs server (no visible window).

ATM, it looks good. I'm giving myself a bit of time before closing the issue.

**Comment by jabranham** [comment]
:+1: let me know if you run into any more issues. I also hang out in #emacs on IRC (freenode)

**Comment by EmmanuelCharpentier** [comment]
> let me know if you run into any more issues. I also hang out in #emacs on IRC (freenode)

My goddamn corporate firewall won't let me IRC... But your promptness to answer lets me think that Github issues are almost as instantaneous... ;-)

**Comment by EmmanuelCharpentier** [comment]
OK. I'm satisfied that PEBCAK... Closing.
