### ISSUE TITLE
ESS cannot be installed from melpa-stable

### ISSUE THREAD

**Issue by gbrunick** [emacs-ess/ESS#629]
Currently when I run list-packages from a new install of Emacs 26.1, I see:

```
ess is an incompatible package.

     Status: Incompatible because it depends on uninstallable packages.
    Archive: melpa-stable
    Version: 17.11
     Commit: a218dec600c25687a81419e42b555141911504c6
    Summary: Emacs Speaks Statistics
   Requires: julia-mode-0.3 (not available)
   Homepage: http://ess.r-project.org

```

My repo settings are

```

(setq package-archives
      '(("gnu" . "http://elpa.gnu.org/packages/")
        ("melpa-stable" . "http://stable.melpa.org/packages/")))

```

Apologies in advance if this is user error.

**Comment by jabranham** [comment]
Sounds like you can't install julia-mode for some reason. Perhaps an
outdated Emacs?

I'm on a weird network right now and can't check what julia-mode requires,
but that's what you need to look at.

**Comment by vspinu** [comment]
AFAICS melpa stable is not even recommended by melpa maintainers. 

We could go either by not listing julia-mode as a dependency or by asking julia-mode maintainers to push a tag. Should be easy enough.

**Comment by jabranham** [comment]
Yes, melpa stable is probably not the best way to install most packages, and this is a decent example of one of the ways it's not great.

You can install ESS from melpa-stable so long as you also have melpa in `package-archives`. You'll have to tell `package.el` to prefer the melpa-stable version with either `package-archive-priorities` or `package-pinned-packages`. 

I'd prefer not to bother the julia-mode people with pushing a tag. If they haven't bothered to so far, they probably have a good reason, and it's unlikely they'd remember to push a new tag after releasing new features.

**Comment by vspinu** [comment]
For the reference one can selectively pin packages to different archives like:

```el
(add-to-list 'package-pinned-packages '(ess . "melpa-stable") t)
```
