### ISSUE TITLE
R secondary prompt removed

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#636]
I guess as a consequence of #630 now if you do in the inferior R buffer:

```
> 1 + 
```

and hit RET 3x, you 'll get: 

```
> 1 +


```

and you should get: 

``` 
> 1 + 
+ 
+ 
```

**Comment by vspinu** [comment]
I added a tweak to get rid of  extra + + when you eval functions for example. Those are less than helpful in nowait case and I was wondering what would be the side effect of it. Well, ... you found it pretty quickly ;)
