### ISSUE TITLE
Output with % in vector names error

### ISSUE THREAD

**Issue by ran-sharon** [emacs-ess/ESS#657]
Hi,

I encountered this issue when using quantile. There seems to be a problem with named vectors with % in their names.
The error I get can be reproduced by:
`> quantile(rnorm(100), 0.5)`
Also reproducible by:
`> setNames(seq(5), c("1%","2%","3%","4%","5%"))`

My messages buffer shows the following line:
`error in process filter: ess--flush-accumulated-output: Format string ends in middle of format specifier`

Thanks, I really appreciate the effort.

**Comment by vspinu** [comment]
The string gets pass as format somewhere. Will have a look as soon as I can. Thanks for the report.

**Comment by vspinu** [comment]
I cannot reproduce this nor I can see where this could be coming from. What is the ESS version on your side?

**Comment by ran-sharon** [comment]
Not sure, I installed via MELPA, adding something like the following to my .emacs file (I don't remember exactly what it was):
```
 (use-package ess
  :ensure t
  :init (require 'ess-site))
```
Now I've deleted that and used apt-get install ess, which got me the 17.11 version, which seems to be working fine. I think the previous version might have been 17.08, but I'm not sure.

**Comment by vspinu** [comment]
I see. I think you were just unlucky to have pulled broken version of ess. It's most likely the same issue as in #639. 

BTW, you no longer need `(require 'ess-site)` the whole pacakge is auto-loaded.

**Comment by ran-sharon** [comment]
You're probably right. Anyway, thanks for looking into it.
