### ISSUE TITLE
ess-remote in emacs 26.1

### ISSUE THREAD

**Issue by LZeitler** [emacs-ess/ESS#658]
I'm running ESS 17.11 and the ess-remote command does not seem to exist in emacs 26.1 after updating to a new machine and new emacs. 

`M-x shell`
`ssh usr@server`
`R`
`M-x ess-remote` -> "[No match]"
Any ideas?

**Comment by vspinu** [comment]
I presume you are using ESS from MELPA. `ess-remote` wasn't autoloaded. Should be fixed now.

**Comment by LZeitler** [comment]
Cool stuff! Updated and had to install julia-mode as well, then it worked again.
