### ISSUE TITLE
Effectful style configuration

### ISSUE THREAD

**Issue by jcubic** [emacs-ess/ESS#661]
I have code like this:
```
tags$div(
      bar
      baz
    )

foo <- if(xxx) {
         xxx
       } else {
         yyy
       }
```

is it possible to make it indent like this?

```
tags$div(
  bar
  baz
)

foo <- if(xxx) {
  xxx
} else {
  yyy
}
```

the same happen to:
```
tibble::tibble(
          foo()
        )
```

**Comment by lionel-** [comment]
Try hooking `(ess-set-style 'RStudio- 'quiet)` in `ess-mode-hook`. See `ess-style-alist` for finer-grained config.

**Comment by jcubic** [comment]
adding `quiet` works, I was using `(ess-set-style 'RStudio-)` thanks. and thanks for this project now it's perfect.

**Comment by lionel-** [comment]
`quiet` shouldn't change the behaviour, just the verbosity. The effects of this function are always local so you likely need to hook it in `ess-mode-hook` to have the changes take effect everytime you open an R file.

We should probably make the `ess-style` configuration variable effectful at any time, then you'd just need `(setq ess-style 'RStudio-)` somewhere in your config.

**Comment by jcubic** [comment]
this is exactly what I've had this in my config, `setq` but not in hook and I take this code from some example so that snipped should be updated. Maybe it was in Emacs wiki.

**Comment by jabranham** [comment]
> We should probably make the ess-style configuration variable effectful at any time, then you'd just need (setq ess-style 'RStudio-) somewhere in your config.

Yes, and it would be nice if we could let people set it in `.dir-locals` or as a file-local variable too

**Comment by mmaechler** [comment]
Hmm, yes  file-local  variable is very desirable for the ESS style.
I'm pretty sure I had done this in the past (say 2 yrs ago) and it did work then ... but maybe I've been wrong and it did not work in all cases ?

**Comment by mmaechler** [comment]
Excellent @lionel- !   Indeed now that I understand what you meant by  "effectful",  I do even more agree that it would be nice, exactly because I would want to use it directly as local variable instead of having to use such a function call.

**Comment by mmaechler** [comment]
and also, of course I was wrong 5 days ago, when I vaguely remembered having used it... the vague memory was only correct that I had *achieved* its effect but not by simple variable setting.
