### ISSUE TITLE
Adjust options("width") in ESS

### ISSUE THREAD

**Issue by mattfidler** [emacs-ess/ESS#666]
I was wondering if we could adjust the `options("width")` on emacs resize.  It seems like a possibility.  On windows the `options("width")` is always `80`.

**Comment by mattfidler** [comment]
Hm Issue #666, seems a bit evil...

**Comment by jabranham** [comment]
You can use `ess-execute-screen-options`, but I'm guessing that hooking it into `window-change-configuration` will cause a world of problems if the inferior process is busy and you try to change anything with the window layout.

**Comment by mattfidler** [comment]
You are right of course.

**Comment by jabranham** [comment]
It shouldn't be too difficult to make `ess-execute-screen-options` wait for the process to be not busy. I don't have time right now but can look later. Or someone else can if they have the time :-)

**Comment by mattfidler** [comment]
I agree.  I was just thinking it would be nice...

**Comment by vspinu** [comment]
Even if we could overcome the "busy" problem I don't think we should have it by default. I often set width, then go and execute some code, then go and inspect the printed output. If width is reset automatically I cannot do that anymore. 

The workflow habits will likely depend on the wiindow configuration. On wide screens (most of them these days) people tend to work with left-right window split which would render this feature inconvenient. 

I think the best workflow improvment we can hope for is to have `ess-cycle-window-configuration` which would toggle between a few preset options; at least two, narrow (half frame) and wide (full frame).

**Comment by lionel-** [comment]
> I often set width, then go and execute some code, then go and inspect the printed output. If width is reset automatically I cannot do that anymore.

This is a rather specialised use of ESS. Developers can disable the auto-width when needed.

>  On wide screens (most of them these days) people tend to work with left-right window split which would render this feature inconvenient.

I don't understand. Isn't this the use case where auto-width would shine?

**Comment by vspinu** [comment]
> This is a rather specialised use of ESS.

It's an obvious use case which cannot be achieved with auto-width on.

To be clear about the workflow. I switch to inferior, maximize window, do `C-c C-e C-w` then `C-c C-z` to move to the script buffer. Then execute commands. At this point I expect my width to stay the same. 

I do it very often when I deal with large tables and I don't see a good alternative to this except the toggling command which I already proposed. 

> I don't understand. Isn't this the use case where auto-width would shine?

Auto width would shine if people would use R in top-bottom. This way they would have maximum width all the time. In the left-right split the only option for people to get larger width is to switch to top-bottom split which is rather inconvenient.

**Comment by vspinu** [comment]
> I would find it useful to prevent the output from being too wide, which is what I'm often struggling with.

But for this case you already have `ess-execute-screen-options`, while for the opposite we don't have anything. 

I think the cycling command could go through a list of the form `(auto half-frame full-frame)` which could contain numbers for exact widths). So we always start with auto but changing size is one key away. This would definitely work better for me than the current setup and should make you guys happy.

**Comment by jabranham** [comment]
I'm working on this and should have a PR this weekend where we can merrily disagree about the defaults over concrete code :-)

**Comment by jabranham** [comment]
This is now in the `next` branch which will be merged into master shortly after release (later this month or early next month)

**Comment by mattfidler** [comment]
Thank you @jabranham
