### ISSUE TITLE
`M-x R-3.4.3` no longer creates a buffer named `*R-3.4.3*`

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#672]
This happens only for a couple of days (upto 10?) .. but is a PITA for me.
Yes, this was a feature that not so many people used, but believe me,  R core members have been very happy with it for ca. 20 years ....

Please re-instantiate (the more general case):  `M-x R-3.5.1`  --> buffer named `*R-3.5.1*` etc etc.

**Comment by jabranham** [comment]
Can you include what does happen (an error, message, hangs Emacs, etc)?

Sorry if you've made any edits since the original report; github.com is
down for me (and https://status.github.com/messages suggests I'm not
alone).

**Comment by mmaechler** [comment]
Yes, indeed @vspinu.  It's `*R:2*` or `*R:3*` for me, as of course I'm already running one other R version.... but it is crucial that the buffers are named more usefully and self-explainably.

**Comment by mmaechler** [comment]
yes (of course)  .. I wanted to say.  But now I see the reason is that you *CHANGED* its name, and so my previous setting was no longer used...
Do we really want to frustrate all users who have set the old name to 't' ?

**Comment by mmaechler** [comment]
Thank you, Alex.  The first change (ion May 23) was no problem doe me, at all so the aliasing then worked fine.
The problem for me started when you did your "fix" two weeks ago.  For me it has been the contrary of a fix.  I do have the very regular  
```
(custom-set variables
   ....
   ((long list of a "feeled" 100 lines))
)

where the line that worked till recently was

 '(ess-use-inferior-program-in-buffer-name t)

even more crazily,  `C-h v` that, I'm told that that is  the *correct* variable name and that the version with the extra `-name` in it is deprecated.  But the behavior I now see is the contrary:  The version without the `-name` is no longer working and I need to use the one *with* a `-name` .. which is said to be deprecated ????

((Yes, I'm very very regularly `git pulling` the master branch, and subsequently calling `make` and work with that all day on both of my regularly used (Linux Redhat) environments.

**Comment by vspinu** [comment]
A wild guess here. It might have something to do with the order in which that defalias is declared. It's only very recently that emacs 27 requires the defalias before the declaration. Could it be that it has different effect on older emacses? Would be pretty crazy though, but what Martin describes looks crazy.

**Comment by jabranham** [comment]
@vspinu - No, nothing has changed except the new byte compile warning since it's possible to overwrite user customizations in specific circumstances when you alias stuff.

@mmaechler --- I've added a few unit tests in #678 that can't reproduce this either. Here's a few ideas for you:

- you put `(custom-set variables` in your comment above, but it's missing a hypen `custom-set-variables`. Was that just a typo?

- Have you done `make clean` and then recompiled ESS? 

Aside from those two things I'm not sure what the issue could be. The code is very clear that `ess-use-inferior-program-in-buffer-name` is the preferred variable. What version of Emacs are you using? I'll try to replicate this with your version I guess.

**Comment by mmaechler** [comment]
Okay, I've started emacs and use `M-x ielm` to show:
```
ELISP> emacs-version
"26.1"
ELISP> ess-use-inferior-program-in-buffer-name
*** Eval error ***  Symbol’s value as variable is void: ess-use-inferior-program-in-buffer-name
ELISP> ess-use-inferior-program-name-in-buffer-name
nil
ELISP> 
```
even though I have had (for years) in my  `~/.emacs`
```
(custom-set-variables
          ;; .....
          ;; .....
 '(ess-use-inferior-program-in-buffer-name t)
          ;; .....
          ;; .....
 )
```
This has worked fine till recently and seems to have been broken by 60d7222, (~ 2 weeks ago) or another relatively recent change.

**Comment by vspinu** [comment]
I also cannot reproduce this with any combination of emacs builds and
runtimes and `custom-set-variables`. Would be really useful to get to the
bottom of this.

> since it's possible to overwrite user customizations in specific
circumstances when you alias stuff.

I never heard of this. How can we overwrite user customization by aliasing?

**Comment by jabranham** [comment]
@vspinu Here's the original bug report to emacs-devel: https://issues.guix.info/issue/5950 (ignore the guixsd stuff, it's just a prettier website than debbugs but it's the same info). Here's the ert test they added to check for this:

```elisp

(ert-deftest defvaralias-overwrite-warning ()
  "Test for Bug#5950."
  (defvar eval-tests--foo)
  (setq eval-tests--foo 2)
  (defvar eval-tests--foo-alias)
  (setq eval-tests--foo-alias 1)
  (cl-letf (((symbol-function 'display-warning)
             (lambda (type &rest _)
               (throw 'got-warning type))))
    ;; Warn if we lose a value through aliasing.
    (should (equal
             '(defvaralias losing-value eval-tests--foo-alias)
             (catch 'got-warning
               (defvaralias 'eval-tests--foo-alias 'eval-tests--foo))))
    ;; Don't warn if we don't.
    (makunbound 'eval-tests--foo-alias)
    (should (eq 'no-warning
                (catch 'got-warning
                  (defvaralias 'eval-tests--foo-alias 'eval-tests--foo)
                  'no-warning)))))
```

In emacs-27, there are byte compile warnings AND runtime warnings when you lose info to this.

@mmaechler Somehow you're loading an older version of ESS. That's the only explanation I see for `ess-use-inferior-program-in-buffer-name` not being defined. Perhaps you've somehow got Fedora's ESS 17.11 installed and Emacs is loading that? Or old `.elc` files somewhere?

**Comment by mmaechler** [comment]
You are right @jabranham : Somehow our IT people managed to get the `emacs-ess` fedora package onto my desktop even though they promissed they would stop doing that (I had removed it immediately after upgrading to F 28). .. so indeed ESS 17.11 was loaded *before*  my ~/.emacs (and other) emacs initialization had a chance to kick in ...... 

Note that this has happened before, not just to me,  and is pretty nasty and not so easy to debug for the inexperienced.  I *had* quickly found the problem when it appeared after the OS upgrade, and I quickly solved it ... but I wrongly believed our (in generally very good and reliable) IT staff when they told me they'd take it (the `emacs-ess` fedora package)  *out* of the departmental wide fedora package repos...

In an ideal world -- and maybe in the near future after 18.09 when you trash and rewrite everything (;-) it will be easily possible to replace an already loaded version of ESS by "my current new" one ?

Thank you for your help .. and I do apologize for not checking the system-wide startup this time.

**Comment by jabranham** [comment]
You can tell Emacs to always prefer your user installation of ESS by putting the path to it *before* the path to the system-wide installation in `load-path`, I believe. 

> easily possible to replace an already loaded version of ESS by "my current new" one ?

This isn't possible to do completely cleanly, but it *is* possible to just reload all the `.el` files. Org has `org-reload` which we could look at and see if we could modify it for ESS.

**Comment by mmaechler** [comment]
unfortunately *no* : I had done that (putting my stuff in front of
the `load-path` forever, i.e., since emacs 18.59 IIRC):

Debian (and its derivatives incl Ubuntu) and Fedora and ... not
only add to the load path, they *also* load corresponding
startup files.  In our case,
```
  (require 'ess-site)
```
has happened already before my `~/.emacs` starts being read.

Even if we no longer require that,  "they" continue to use older ESS which *does* require it; e.g.
Ubuntu 18.04 is an LTS and will be in use for many years to come, e.g. in companies who want stability in their software.

I assume in the future, the "system" ess package will only define some autoloads.. such that
setting the load-path will work. .. and hope that will solve the problem in a year or so..

Well, if ESS 18.09 will be back compatible enough such that it is accepted into the mainstream distribution `emacs-ess` packages  ((one reason to be nice to the maintainers of those .. hint,hint! ;-)))

**Comment by eddelbuettel** [comment]
Regarding Ubuntu 18.04 LTS and other Ubuntu builds:  Michael Rutter always rebuilds my Debian package for use in the [CRAN Ubuntu repo mirrored everywhere](http://cloud.r-project.org/bin/linux/ubuntu) so staleness is not an issue.    You get ESS from there post-release just as you get R.   (I know your use case is different as you compiled everything from source, but you are also unusual in that regard and many people do get their ESS from there.)

**Comment by vspinu** [comment]
> Here's the original bug report to emacs-devel: https://issues.guix.info/issue/5950
Uff. This one is pretty bad. The issue stayed hidden for 8 years till those warning were finally introduced. I think pretty much everyone was defaliasing after defvar all this time.
