### ISSUE TITLE
Error with tracebug

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#674]
Tracebug recently stopped working for me. I don't have time to investigate but I see these errors:

```
error in process filter: ess--dbg-find-buffer: No catch for tag: --cl-block-nil--, nil
error in process filter: No catch for tag: --cl-block-nil--, nil
```

Can anyone confirm?

**Comment by jabranham** [comment]
Tracebug is still working on my end. How recent is "recently" and can you catch this with the debugger and give a backtrace?

**Comment by lionel-** [comment]
Pretty recently, but something may be messed up on my computer. The backtrace isn't very informative:

```
  throw(--cl-block-nil-- nil)
  ess--dbg-find-buffer("file.r")
  ess--dbg-create-ref-marker("file.r" "88" nil)
  ess--dbg-goto-ref(nil "file.r" "88" nil)
  apply(ess--dbg-goto-ref nil ("file.r" "88" nil))
  ess--dbg-goto-last-ref-and-mark(#<buffer  *ess.dbg.R*> nil)
  inferior-ess-tracebug-output-filter(#<process R> "debug at file.r#88: NULL\nBrowse[2]> ")
```

**Comment by jabranham** [comment]
I'm guessing `(featurep 'cl)` returns `nil` for you?

Try requiring it and see if that fixes it

**Comment by lionel-** [comment]
It is `t`. This looks like an internal issue of non-local exit within a cl function but that's weird it doesn't appear in the backtrace.

**Comment by lionel-** [comment]
It does, thanks!

**Comment by vspinu** [comment]
That `ess--dbg-find-buffer` was on my todo list for 18.09. There are multiple problems with it but now it's probably too late. That cl-return should go; hopefully I will remember to remove the `(require 'cl)` then.

**Comment by jabranham** [comment]
Wouldn't it be enough (for this problem) to do `cl-defun` rather than `defun`? Then we wouldn't need cl at compile time (though still do for lexical-let in ess.el, but that's for another day I suppose)

**Comment by vspinu** [comment]
Not sure how that could help. Cl-return is intended for the dolist as you spotted rightly. 

Yeh. Lexical-let is a must-do for 19.04 once we have fewer files to deal with.

**Comment by jabranham** [comment]
I'm not super familiar with common lisp, but wouldn't using `cl-defun` allow `cl-return?`:

```
cl-defun is an autoloaded Lisp macro in ‘cl-macs.el’.
<...>
Like normal ‘defun’, except ARGLIST allows full Common Lisp conventions,
and BODY is implicitly surrounded by (cl-block NAME ...).
```

```
cl-block is an autoloaded Lisp macro in ‘cl-macs.el’.

<...>
Code inside the BODY forms can call ‘cl-return-from’
```

**Comment by vspinu** [comment]
You need to define a block, so yes. It could be rewritten with that cl-block or something. Never used it. But it could also be rewritten with a while loop and a bunch of other constructs, notably seq-find which we will use once we get rid of 24.
