### ISSUE TITLE
inferior-ess-...-hook

### ISSUE THREAD

**Issue by nverno** [emacs-ess/ESS#700]
It would be useful to have mode specific `inferior-ess-...-hook` variables.
Currently, I need to add multiple hooks to `inferior-ess-mode-hook` with 
conditions like `(when (string= ess-dialect ...))`. Or am I just doing that wrong?

**Comment by jabranham** [comment]
That's the correct way to do it. We'll have mode specific hooks once #616 gets merged as `define-derived-mode` automatically runs the proper hooks.

**Comment by nverno** [comment]
Oh nice, that will be a major improvement!

**Comment by nverno** [comment]
I only use R and occasionally julia, but Ill keep let you know if anything fishy happens
