### ISSUE TITLE
Should ess-fl-keyword:%op% default to t?

### ISSUE THREAD

**Issue by MilesMcBain** [emacs-ess/ESS#702]
So I updated my ESS and my `%%` operators no longer highlighted. It seems like they used to by default but now I have to set `ess-R-font-lock-keywords` with `ess-fl-keyword:%op%` equal to `t`.

The documentation on how to do this is really bad. The manual just says I can set `ess-R-font-lock-keywords` if I desire with no explanation of the keywords. Newfeat just says: 

>    The user can easily customize those by adding new keywords. These variables can also be interactively accessed and saved through @kbd{ESS/Font-lock} submenu.

I am a new ESS user but I can tell you I did not choose to use an editor like Emacs to stuff around selecting menu options each time I open an R file. So don't kid yourselves that this is a user friendly alternative to configuration.

Eventually by doing a global search on this repo I found the pattern for configuring these in ess-custom.el.

My suggestion is to flip this back to true by default for operators. Also the documentation of this facility needs improvement. It might be worth directing users to the example configuration in the relevant sections of the documentation.

Edit: I could make a PR to improve the documentation if you have any guidance on the best place to do that.

**Comment by lionel-** [comment]
They were only highlighted by default because of a bug. The bug has been fixed, and the default is now applied as it was in older releases. The usual way of setting this stuff is with the custom system in the menu. Otherwise you configure the `-keywords` variable in your dot file.

PR for improving the doc is welcome.

**Comment by jabranham** [comment]
> The manual just says I can set ess-R-font-lock-keywords

Perhaps we should link here to how to customize variables `(info "(emacs) Easy Customization")`

> each time I open an R file. 

the menu also lets you save your customizations so you don't have to do this each time you open a file.

If you want to change the documentation, the file to look at is `doc/ess.texi`.

**Comment by lionel-** [comment]
In fact, since the default has effectively changed for at least one release, it'd make sense to set it to `t` by default. I don't think we have had a complain about fontification of `%op%` syntax.

**Comment by MilesMcBain** [comment]
@lionel- Your bug was my feature apparently :)

@jabranham Thanks for the intro to Easy Customization, aka `customize`, I've never used this before,  so I don't really no the conventions but I didn't find anything under 'Faces' or 'Font Lock' for ESS. Using the search nothing much came up for ESS.

At any rate, I have my ESS related config altogether in a Spacemacs layer, so the easy interface or the facility to save to custom from the menu are not useful since they won't update my layer config.

**Comment by lionel-** [comment]
Ah good catch, we probably need to update the regexps, I'll take a look.

**Comment by lionel-** [comment]
The toggling should be fixed. I have turned on `%op%` by default since that was the effective default for more than a year and no one complained. This is a strong sign that it was a good default.
