### ISSUE TITLE
What happened to Customising ESS documentation?

### ISSUE THREAD

**Issue by MilesMcBain** [emacs-ess/ESS#703]
I was looking at improving the docs re: #702. I think the root cause is the extremely brief section on customization in the manual.  So I started trying to fill it out a bit [here](https://github.com/MilesMcBain/ESS/commit/a909f37a11f1338186b9b91f8c73f3be6b7a10c5), but then I stumbled upon this, which while not complete, is actually way better then what is there now: ftp://ess.r-project.org/ESS/ESS_html-o/ess_12.html#SEC78

So this looks like an old version of the now brief 'Customizing ESS' section in the manual. Was this once in the manual? Why was it removed?

As far as I can see the hooks and keymaps are not documented anywhere else and that  makes customization challenging.

**Comment by jabranham** [comment]
The customizing ESS portion of the manual should probably just be a link to `(emacs) Customization` and also `(emacs) Apropos` which describes all of this in more detail. 

If ESS adopted the modern convention to prefix all of its functions and variables, finding all the hooks ESS provides would be as easy as `M-x apropos-user-option RET ess-.*-hook`. But it doesn't so you have to check for R-.*-hook and the other languages too if you want.

**Comment by MilesMcBain** [comment]
I take your point but there are some quirks unique to ESS like having to check the `ess-dialect` to do per-language configuration that should probably be documented?

I also think it would be great as a user if I went to that section and found a couple of common examples, like disabling smart assign or creating a keybinding for `%>%`.

**Comment by MilesMcBain** [comment]
I was thinking about checking the dialect. Cool that's going away.:+1:

The manual doesn't explicitly say how to disable smart assign. The only ref I can find to it is notes about how the S-assign related variables are going to be removed.

Is it expected that one would `(setq ess-insert-assign nil)` to disable smart assign? That could be documented.

I see your perspective about the manual, I guess I have found actual configuration examples more useful to getting up and running in ESS than manuals that discuss matters in the abstract. It's partly why I started this repo: https://github.com/milesmcbain/esscss - feel free to add your own!

Of course the downside of this approach is that my understanding of things is not as complete as it could be.

**Comment by jabranham** [comment]
Setting `ess-smart-S-assign-key` to `nil` should disable the smart underscore. This is going to change shortly after the 18.09 release though. We're removing the smart underscore by default. Users who want it should bind `ess-insert-assign` in `ess-mode-map` and/or `inferior-ess-mode-map`. 

When I was getting started with ESS I also found it helpful to look at other's config to find useful options. I don't do a ton of customization to ESS in [my own config](https://gitlab.com/jabranham/emacs), but feel free to add it to your repo if you think it'd be useful (open init.el and search for "use-package ess" to find the ESS stuff). Perhaps we should set up github's wiki to share community resources that might be useful but aren't in ESS itself for one reason or another. I've noticed a lot of people write a function to insert `%>%` and a newline, for example.

**Comment by mmaechler** [comment]
Well, well.     Remember that a big part of the ESS users are old timers... and some of them have the behavior ingrained in their fingers.   I hope that we will be able to activate it easily rather than complicatedly...

**Comment by jabranham** [comment]
@mmaechler this was discussed a few times, most recently (I think) in #673. To activate again, users can bind `ess-insert-assign` to a key of their choice in any of the various `-mode-map`s that users want it active in:

```elisp
(define-key ess-mode-map (kbd "_") #'ess-insert-assign)
(define-key inferior-ess-mode-map (kbd "_") #'ess-insert-assign)
```

I'm hopeful that the longtime ESS users will forgive us for making them place one or two lines in their init file. Underscores are widely used today in R code (e.g. ggplot2). The few people I've converted to ESS have given me bewildered looks when they press `_` and ` <- ` is inserted instead.

**Comment by mmaechler** [comment]
I'm not disagreeing with the plan to disable it by default.  Sorry for the confusion. Rather I wanted an easy way to re-activate the previous default.
I can live with the above too lines ... which we should put in the docu somewhere prominently (probably only in the `next` branch).

Also we should (in the same place?)  emphasize the alternative  `[Alt] -`  which I had wanted to adopt myself, but just not yet succeeded.

**Comment by jabranham** [comment]
I'll work on removing the smart key stuff today and make a PR to the `next` branch. I'll be sure to mention those two lines to keep the current behavior.

**Comment by jabranham** [comment]
I think everything here has been addressed, at least on `next`. @MilesMcBain let me know if that's not the case and I'll reopen the issue.
