### ISSUE TITLE
[Tab] completion inserting `recursive=`  inside `c( )` 

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#708]
Related to (the closed) #380 , but different. Also I don't think a solution could be similar as there:
Here's a reprex,
```r
## this is a bug from the average user's point of view:
c(
    a = 1,
    ## <-- pressing [Tab] before/at the 1st '#' wrongly *inserts*   'recursive = '
    z = 26
)
```
Strictly speaking, this is not incorrect, because apart from the initial `...` , the `recursive` *is* an argument of `c(*)`  though quite rarely used.

We could attribute the "bug" to R's completion engine, but I think we should just work around this.
Either unconditionally, or make this behavior configurable, or insert only after the 3rd  `[Tab]` or ??
The first [Tab] (and often the 2nd too) is about getting correct indentation.

**Comment by vspinu** [comment]
We could cache `c()` without the arguments. The simplest solution I could think of.

**Comment by mmaechler** [comment]
Yes, following Einstein is a good idea..

**Comment by vspinu** [comment]
@mmaechler You were right, our tab completion goes directly to R completion. ATM our code (see `ess-r-object-completion`) is simple and elegant.  Fixing this would require a workaround around R completion which would complicate things quite a bit.  Would you mind leaving this as it is?

**Comment by mmaechler** [comment]
ehhm... no.   It's really wrong to happen,  and it's very inconvenient, when building named or unnamed vectors (including `list`s), using `c`.     But I agree that it should not be fixed for 18.10  and of course it would also be satisfying if change (or just "customization" ?) was possible on the R side (which I do not know at all).

**Comment by vspinu** [comment]
Ok. Let's then sleep a bit on this one. I have in plan to enhance the completion framework for 19.04. Will keep in mind this issue.

**Comment by mmaechler** [comment]
Actually,  R's  completion generator *is* configurable as I found (not "to the end") and then got pointed to a solution here -- we (`ESS`) should I think implement, before something like this may be added to R itself:

```r
  utils:::.addFunctionInfo(c = c("recursive", "use.names"))
```

This will *list* both completions (correctly) but will *not* complete,  and that's already much better than the current behavior.   So let me revert what I said above, and do add this even for 18.10 ?!!

**Comment by vspinu** [comment]
Good idea. Can be something like 

```R
if (!is.null(utils:::.addFunctionInfo)) {
  utils:::.addFunctionInfo(c = c("recursive", "use.names"))
}
```
in our `etc/ESSR/R/completion.R`.

**Comment by mmaechler** [comment]
I've added a version of the above  in  f1267b3  which does fix the issue in "the best way" I think.

**Comment by vspinu** [comment]
Ok. But that FN assignment is not "the best" as it's not removed when it's not a function. Not a biggie though.

**Comment by mmaechler** [comment]
you are right, clearly "sub optimal".
