### ISSUE TITLE
Inferior hangs Emacs after interrupting printing

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#710]
Can anyone else reproduce this?

```r
data <- rep(list(mtcars), 100)
x <- rep(letters, 500)
```

If you let `print(data)` run to completion, `print(x)` runs normally:

```r
print(data)
print(x)
```

If you interrupt `print(data)`, `print(x)` freezes Emacs freezes for a while, even on `C-g`. Subsequent printing freezes as well, the inferior has to be killed and restarted.

```r
print(data)
# C-c C-c
print(x)
```

I thought this was a reprex for the freezes that @mmaechler mentioned, but I can reproduce them on 17.11 as well.

**Comment by jabranham** [comment]
I can't reproduce but I'm not using the same environment as you. I'm on my branch (#616) this morning. Should have time later to try on master. What's the value of ess-eval-visibly that you're using?

**Comment by lionel-** [comment]
I can reproduce this with all values of `ess-eval-visibly`, with and without my config loaded.

**Comment by jabranham** [comment]
I can't reproduce this on current master. Here's what I'm doing:

```
emacs -Q -L (path to ess-lisp-directory)
(require 'ess-r-mode) C-x C-e
M-x R RET RET
data <- rep(list(mtcars), 100)
x <- rep(letters, 500) RET
print(data)
C-c C-c
print(x)
```

I've tried with `ess-eval-visibly` `t` and `'nowait`. 

This is with Emacs 27.0.50 built about a week ago on GNU/Linux.

**Comment by vspinu** [comment]
Cannot reproduce either.

**Comment by lionel-** [comment]
With `-Q` it goes away, but not when I disable my ESS config... I'll keep investigating.

**Comment by lionel-** [comment]
It was because of the `xterm-color` comint preoutput filter. Doesn't happen with the `ansi-color` output filter. I started using the former because it has wider support of ansi codes but apparently it's not bug free.

**Comment by lionel-** [comment]
Upstream issue with a potential fix: https://github.com/atomontage/xterm-color/issues/23
