### ISSUE TITLE
Improve ELT error messages

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#713]
Is there a way to see where in the "literate" tests an error occurs? All Travis tells me is 

```
     ((should
       (string= src-string output))
```

and then it echos the whole file into the buffer.

**Comment by lionel-** [comment]
Not yet, I need to implement this. Only `should` expectations provide fine-grained reporting atm. If you get this output, it means that the output of one chunk has changed.

Run `make literate-cases`, then you can find out the differences in the git diff.

**Comment by jabranham** [comment]
After applying the commit in #712 I ran `make literate-cases` the the only diff I get is:

```diff
diff --git a/test/literate/keybindings.R b/test/literate/keybindings.R
index f3c0671a..f4c89885 100644
--- a/test/literate/keybindings.R
+++ b/test/literate/keybindings.R
@@ -18,6 +18,7 @@ foo_¶
 
 foo_ <- ¶
 
+
 ### 3a Binding `ess-insert-assign` to simple key ---------------------
 
 foo¶
```

Does that one newline cause the test to fail?

**Comment by lionel-** [comment]
Have you changed the case manually? If so you need to rerun `make literate-cases`, the whitespace is regenerated each time to keep it deterministic.

This really needs a README and some documentation.

**Comment by jabranham** [comment]
Yes I did since the tests there needed updating when we removed that variable. I'll add that whitespace and hopefully travis will be happy now.

**Comment by lionel-** [comment]
This isn't about Travis, you can also run `make` in the tests folder locally to make sure.

**Comment by jabranham** [comment]
ESS's tests fail for me locally because they don't run in a clean environment.

**Comment by lionel-** [comment]
It seems to work now. So basically the process when you have modified a literate test is to regenerate the cases, check that everything is ok in the diff, and only then commit.

For adding a case:

* Add a header, a starting chunk, some test code commented with `##!`, and then regenerate the cases to materialise the output chunk.

* Add more tests to the same case with multiple `##!` blocks separated by whitespace. Regenerate the cases to materialise all corresponding chunks.

* If a comment block uses `##>` instead, it means the test is applied to the output of the previous test rather than the starting chunk.

So only the starting chunk is determinant for the tests, all the other chunks are regenerated each time from the starting chunk + comment blocks.

**Comment by vspinu** [comment]
>  the whitespace is regenerated each time to keep it deterministic.

Hmm, what does this mean? Is this really needed?

> This really needs a README and some documentation.

Would be great!

> Add more tests to the same case with multiple ##! blocks separated by whitespace. 

Could we move to markdown for this?

**Comment by lionel-** [comment]
> Hmm, what does this mean? Is this really needed?

It simplifies the implementation and keeps things tidy.

I'm not sure markdown is right here, the point of these tests is to be editable in R-mode. I guess with polymode it might make sense. Alternatively we could use lentic, but last time I used it a few years ago I experienced dramatic data loss.

It's currently painful to edit the comments, but once we have pop-to-buffer editing for roxygen examples we can use it as well for the ELT comment blocks.

**Comment by vspinu** [comment]
After the rewrite polymode works without major issues AFAIK but even with plain markdown it's still better because you wouldn't need to comment with `##>` the elisp code.

**Comment by lionel-** [comment]
@jabranham When I run the cases on a fresh master it got very slow and I'm getting these errors at each case:

```
Warning [flymake  *temp*-581853]: Disabling backend ess-r-flymake because (file-error Creating pipe Too many open files)
Warning [flymake  *temp*-581853]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
```

Does this ring any bell?

**Comment by lionel-** [comment]
Surely the default ulimit ought to be enough?

**Comment by jabranham** [comment]
I'd think so but it depends on the distro you're running. Did you try increasing it to see if that fixed the issue?

BTW - the second warning you posted above is normal. That's flymake (correctly) complaining that it can't enable the "legacy" backend.

**Comment by lionel-** [comment]
I see a `ulimit -n` of 256 in eshell (with which I run unit tests). That's kind of small, but I never got this error before and it used to be faster. Something is strange.

**Comment by jabranham** [comment]
That seems much too small. `ulimit` is per-shell I think, so I think that it will apply from wherever Emacs was started from, right? Seems easy to hit 256 open files from an entire Emacs session.

`ulimit` doesn't work for me in eshell at all. I think `ulimit` is a shell method, so I'm a little confused how your eshell works and mine doesn't.

For me in bash, `ulimit -n` reports 1024.

**Comment by lionel-** [comment]
That's a good question: does eshell get 256 for itself or does it share the limits with Emacs.

In shells outside Emacs I get 4864.
