### ISSUE TITLE
Why different mechanism for `ess-eval-line` and `ess-eval-line-and-step`?

### ISSUE THREAD

**Issue by ashiklom** [emacs-ess/ESS#720]
I'm having trouble coming up with a MRE, but I occasionally and unpredictably hit a weird problem where `ess-eval-line` and `ess-eval-line-and-step` seem to be running different R processes, even though they send code to the same buffer. The exact behavior is that objects that I create via `ess-eval-line` are unavailable to code sent via `ess-eval-line-and-step`. E.g. In the code below, if I run `ess-eval-line` on Line 1 and then run `ess-eval-line-and-step` on Line 2, I get `Error: object 'x' not found`. However, if I run Line 2 with `ess-eval-line` instead, it evaluates just fine.

```r
x <- 10     # Line 1
y <- x + 2  # Line 2
```

I looked at the source code for both of these functions and was surprised to see how different they are. I was expecting `ess-eval-line-and-step` to just be something like `(ess-eval-line) (ess-next-code-line)`. However, they seem to use very different mechanisms for sending code to the process buffer. [`ess-eval-line`](https://github.com/emacs-ess/ESS/blob/master/lisp/ess-inf.el#L1736-L1745) uses [`ess-eval-region`](https://github.com/emacs-ess/ESS/blob/master/lisp/ess-inf.el#L1566-L1590). Meanwhile, [`ess-eval-line-and-step`](https://github.com/emacs-ess/ESS/blob/master/lisp/ess-inf.el#L1779-L1798) uses [`ess-eval-linewise`](https://github.com/emacs-ess/ESS/blob/master/lisp/ess-inf.el#L1480-L1545), and also includes a call for `ess-force-buffer-current`, which I suspect may be causing the bug I describe above in some edge cases. Why are these two functions so different? Why not use the same mechanism for both functions?

**Comment by vspinu** [comment]
This difference is not good I agree. Do you evaluate inside a package by any chance?

**Comment by ashiklom** [comment]
Thanks for the quick reply! Yes, I'm working inside a package. My development workflow often involves setting the function arguments as variables in a scratch buffer and then running function code line-by-line from within the package code files. If R processes are somehow (re-)assigned based on buffer names part of the way through, then me jumping between buffers in completely different directories (or, for a `*scratch*` buffer, not in a file at all) could be part of the problem.

**Comment by ashiklom** [comment]
Testing more carefully, I can confirm that the problem specifically occurs when evaluating inside a package. To reproduce:

1. Start a blank Emacs session: `emacs -q`
2. Run `(package-initialize) (require 'ess)`
3. Open an R script located inside an R package: `C-x C-f /path/to/package/R/function.R`
4. Enter the following code:

    ```r
    x <- 5
    x + 5
    ```

5. Run the first line with `ess-eval-line`. Then, try to run the second line with `ess-eval-line-and-step`. This should throw the error `Error: object 'x' not found`. However, running the second line with `ess-eval-line` should work fine.

**Comment by ashiklom** [comment]
A bit more info, in case it's useful:

Running `ess-eval-line-and-step` inside a package just sends the R code exactly as is to the process buffer, without doing anything else. _However_, running `ess-eval-line` causes the package to be loaded before the command is run.

Also, objects created by `ess-eval-line-and-step` seem to be available to `ess-eval-line`, but not the other way around.

**Comment by ashiklom** [comment]
Experimenting locally, re-defining `ess-eval-line` (and `ess-eval-line-and-step`) as follows seems to fix this problem? Could probably use more testing though.

```emacs-lisp
(defun ess-eval-line (&optional simple-next even-empty invisibly)
  "Evaluate the current line visibly.
If SIMPLE-NEXT is non-nil, possibly via prefix arg, first skip
empty and commented lines. If 2nd arg EVEN-EMPTY [prefix as
well], also send empty lines.  When the variable `ess-eval-empty'
is non-nil both SIMPLE-NEXT and EVEN-EMPTY are interpreted as
true."
  (interactive "P\nP"); prefix sets BOTH !
  (ess-force-buffer-current "Process to load into: ")
  (save-excursion
    (end-of-line)
    (let ((end (point)))
      (beginning-of-line)
      ;; go to end of process buffer so user can see result
      (ess-eval-linewise (buffer-substring (point) end)
                         invisibly 'eob (or even-empty ess-eval-empty)))))

(defun ess-eval-line-and-step (&optional simple-next even-empty invisibly)
  "Evaluate the current line visibly and step to the \"next\" line.
If SIMPLE-NEXT is non-nil, possibly via prefix arg, first skip
empty and commented lines. If 2nd arg EVEN-EMPTY [prefix as
well], also send empty lines.  When the variable `ess-eval-empty'
is non-nil both SIMPLE-NEXT and EVEN-EMPTY are interpreted as
true."
  ;; From an idea by Rod Ball (rod@marcam.dsir.govt.nz)
  (interactive "P\nP"); prefix sets BOTH !
  (ess-eval-line simple-next even-empty invisibly)
  (if (or simple-next ess-eval-empty even-empty)
      (forward-line 1)
    (ess-next-code-line 1)))
```

**Comment by jabranham** [comment]
Why in the world is `ess-eval-line` currently so complicated? Can't we just do:

```elisp
(defun ess-eval-line (&optional vis)
  "Send the current line to the inferior ESS process.
VIS has same meaning as for `ess-eval-region'."
  (interactive "P")
  (ess-eval-region (line-beginning-position) (line-end-position) vis))
```

**Comment by ashiklom** [comment]
I agree with @jabranham suggestion above. Also, a more general fix than the one I posted previously is to revise `ess-eval-region` to look more like what `ess-eval-line-and-step` currently looks like. I.e. something like this:

```emacs-lisp
(defun ess-eval-region (start end &optional simple-next even-empty invisibly)
  "Send region from START to END to inferior ESS process.
If SIMPLE-NEXT is non-nil, possibly via prefix arg, first skip
empty and commented lines. If 2nd arg EVEN-EMPTY [prefix as
well], also send empty lines.  When the variable `ess-eval-empty'
is non-nil both SIMPLE-NEXT and EVEN-EMPTY are interpreted as
true."
  (interactive "rP\nP")
  (ess-force-buffer-current "Process to load into: ")
  (ess-eval-linewise (buffer-substring start end)
                     invisibly 'eob (or even-empty ess-eval-empty)))
```

I _think_ this should fix everything downstream that calls `ess-eval-region`. That said, there is a bunch of other stuff currently called by [`ess-eval-region`](https://github.com/emacs-ess/ESS/blob/master/lisp/ess-inf.el#L1566-L1603) -- not sure how dangerous it is to drop all of that.

**Comment by jabranham** [comment]
This is a bug in tracebug. Disabling tracebug "fixes" it. I haven't looked fully into it yet but my guess is that tracebug and r-package clash somehow in determining what exactly to send to the process.

**Comment by mmaechler** [comment]
so, it really is an  ess-tracebug bug if I understand correctly... or at least only triggering with tracebug active.   That's very much along my own experience which found that tracebug would "suck" occasionally..  maybe fixing this here will be fixing my own bad experiences ?? 

More importantly, is this important enough to get into `18.10`?

**Comment by jabranham** [comment]
I'm not sure what an appropriate fix would be. Tracebug and package mode are competing to send the code to the inferior process and tracebug is currently winning. 

I don't think this is essential to get right for 18.10 since the bug has been there a long time (possibly in 17.11 though I haven't checked) and this is the first time it's been reported. But perhaps @vspinu or @lionel-  have stronger opinions.

**Comment by vspinu** [comment]
It's not a bug, it's just that it is, those functions use different evaluation mechanisms. ess-eval-linewise should never be used in those functions. It's only for interactive line by line eval which must be echoed as they are. All other stuff goes through `ess-eval-visibly`, namespace evaluation when appropriate and through source references injection. Will fix by the end of the day. This should go into 18.10.

**Comment by jabranham** [comment]
@vspinu That didn't fix this issue:

```
x <- 1
x+1
```

doing C-j on the first line and C-n on the second results in an error about x not being found.

**Comment by vspinu** [comment]
It does for me.

**Comment by jabranham** [comment]
in a package with tracebug on?

**Comment by vspinu** [comment]
yes.

**Comment by jabranham** [comment]
I'm not sure how you're not seeing this error. I've recompiled all the byte code and restarted emacs and I still see it any time I evaluate the second line separately from the first. Note that your commit was a subset of what I proposed in #721 and it didn't fix this issue for me there either.

**Comment by jabranham** [comment]
Oh, I forgot I'm working on a computer without devtools. Sorry!

**Comment by vspinu** [comment]
This functionality is internal to ESS. It doesn't require devtools. You should at least get some meaningful errors.

**Comment by jabranham** [comment]
Doing `C-c C-w C-l` then evaluating the code doesn't give me an error. before loading the package it complains:

```
Error in eval(ei, envir) (from <filename>!xgEMQe#1) : object 'x' not found
```
