### ISSUE TITLE
18.10 fails without julia-mode

### ISSUE THREAD

**Issue by chasberry** [emacs-ess/ESS#726]
I thought juilia-mode was optional. With 18.10, I get

> Warning (initialization): An error occurred while loading ‘/Users/cberry/.emacs’:
> 
> error: Required feature ‘julia-mode’ was not provided

which terminates my initialization.

**Comment by jabranham** [comment]
julia-mode is a dependency of ESS. You'll have to install it. If you installed it from the tgz or zip file it's under the lisp/ directory. If you installed from git you'll have to download it (currently `make all` in the lisp subdrectory does that for you)

**Comment by chasberry** [comment]
Thanks. Maybe this should be stated in NEWS.

**Comment by Nicholas-Mitchell** [comment]
@jabranham - I have `julia-mode` installed directly from melpa, but ESS still does not find it. Can I specify the path somewhere?

#### Summary of installations:
```
ess                20190121.1430 installed             Emacs Speaks Statistics
julia-mode         20190111.2044 dependency            Major mode for editing Julia source code
```
Both are found in `~/.emacs.s/elpa/`, which is on my `load-path`.

#### Setup

Emacs 26.1

Here is my `use-package` setup for ESS:

```elisp
  (use-package ess
    :load-path ("~/.emacs.d/ESS/lisp/")
    :commands R
    :ensure t
    :bind
    ("C-S-s-r C-S-s-r" . R)
    :init
    (require 'ess-site)
    :config
    (setq ess-eval-visibly-p 'nowait)
)
```

Am I doing something wrong? I commented out sections one-by-one, but still had the same error as always:

```
Error (use-package): ess/:init: Loading file /home/n1k31t4/.emacs.d/ESS/lisp/julia-mode.elc failed to provide feature ‘julia-mode
```

**Comment by jabranham** [comment]
@Nicholas-Mitchell if you've installed ess from melpa, it's probably at `~/.emacs.d/elpa/ess-2019XXX.XXX`, not at `~/.emacs.d/ESS/lisp`. Try removing that `:load-path` line and see if that works.

**Comment by Nicholas-Mitchell** [comment]
@jabranham  - thanks, you were right!
