### ISSUE TITLE
Activate goto-address-mode in inferior buffers?

### ISSUE THREAD

**Issue by vspinu** [emacs-ess/ESS#727]
With interactive applications (shiny in particularly) it's getting more common to show the link in the buffer like

```
Listening on http://127.0.0.1:7087
```

Shall we activate `goto-address-mode`? It registers with jit lock so the performance penalty is close to 0.

**Comment by jabranham** [comment]
I've had it activated for a year, maybe longer. Works well for me and I haven't noticed any drawbacks. I haven't checked it in non-gui Emacs though.
