### ISSUE TITLE
Not enough arguments for format string

### ISSUE THREAD

**Issue by kwstat** [emacs-ess/ESS#730]
I'm using ESS 18.10-1

Maybe related to #657 

Open an R buffer with this code:
```
library(dplyr)
out <- iris %>% group_by(Species)
```
The eval-line functions like M-n cause this message:
`progn: Not enough arguments for format string`

The ess-eval-region function does not give the message.

**Comment by jabranham** [comment]
Thanks for the bug report, fixed.
