### ISSUE TITLE
Why are `NA` in tibbles not using the `ess-constant-face` in iESS buffer?

### ISSUE THREAD

**Issue by prosoitos** [emacs-ess/ESS#734]
`NA` use the `ess-constant-face` (green in my settings) in both the ESS and iESS buffers, *except* in the printing of tibbles (see picture). I was curious why that was.

Note: if I run `M-x customize-face` on those `NA`, Emacs offers me to customize `(all faces)`. So even though those NA are of a different colour than the default face, they don't seem to be associated with any face.

![image](https://user-images.githubusercontent.com/4634851/47620107-ad7d6200-daa3-11e8-885b-c0b39a141f15.png)

**Comment by jabranham** [comment]
This is a tibbles thing. They've started putting colors in their output. You can control this by setting `options("crayon.enabled" = FALSE)`

**Comment by prosoitos** [comment]
Thank you @jabranham!!!

**Comment by lionel-** [comment]
> What is funny is that Emacs faces override their comment colour (variable types, etc.), but not the NA colour.

That strange, I don't see that:

![screen shot 2018-10-29 at 08 46 33](https://user-images.githubusercontent.com/4465050/47636047-58028d00-db57-11e8-9c4f-6c20f22c6787.png)

**Comment by prosoitos** [comment]
Oh, weird.

When I run R in the console (with crayon enabled of course), I get the same faces you are getting (so the full tibble colours):

![image](https://user-images.githubusercontent.com/4634851/47676411-ceb08200-db79-11e8-91ed-291d201196f3.png)

But in Emacs, I get:

![image](https://user-images.githubusercontent.com/4634851/47676464-ee47aa80-db79-11e8-8b7a-825593262f95.png)

So Emacs overrides all of the colours, except the `NA`. Which is why I was wondering why they were of a different colours in tibbles than anywhere else. If I had gotten the full tibbles faces, I would have probably realized that it was a tibble special thing.

For comparison, with crayon disabled, in Emacs I have:

![image](https://user-images.githubusercontent.com/4634851/47676565-336bdc80-db7a-11e8-81ab-eb401cb6f822.png)

**Comment by jabranham** [comment]
I think you two are seeing the same thing and @lionel-  just doesn't have font-lock for numbers turned on?

This is what I get when I enable the crayon stuff and iESS numbers:

![screenshot_20181029_150338](https://user-images.githubusercontent.com/11914377/47677003-09bbb100-db8c-11e8-97b7-97cd3f0981fc.png)

we're still incorrectly font-locking the operator signs, and on the right side our numbers face fights with our matrix faces.

**Comment by lionel-** [comment]
That's one difference but the more surprising difference is that the type annotations (just below the column names) are not fontified. That may be because I'm using xterm-color to decode ANSI escapes.

Oh I got it That's because they are printed with `crayon::silver()` which isn't supported by ansi-color.el, which is the reason I switched to xterm-color in the first place...
