### ISSUE TITLE
flymake - *.Rnw problem

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#735]
Even though plans are to remove `ess-noweb` eventually,  this is a recent issue in the master branch which should be fixed before the next patch release if possible.  However, it may be only my setup that's buggy to some extent:
If I open a `*.Rnw` file in ESS, since a few weeks I sometimes get an experience like the following.
To reproduce:  

1) Start emacs, and `M-x R` (set directory....). 
2) Now Open a *.Rnw file, e.g., as co-author of the `Matrix` package, I open  
    `.../Matrix/vignettes/Design-issues.Rnw`
Now, many messages are displayed  in the minibuffer about fontification of chunks, ... but then 
a nasty Emacs error message appears.  See below for a "cut'n'paste" from my `*Messages*` buffer

```
Type C-h m for help on ESS version 18.10.2
ess-tracebug mode enabled
noweb mode: use ‘M-x ess-noweb-describe-mode’ for further information
Fontifying from 0 to 12
Fontifying documentation chunks: chunk 0
Fontifying documentation chunks: chunk 1
Fontifying documentation chunks: chunk 2
Fontifying documentation chunks: chunk 3
Fontifying documentation chunks: chunk 4
Fontifying documentation chunks: chunk 5
Fontifying documentation chunks: chunk 6
Fontifying documentation chunks: chunk 7
Fontifying documentation chunks: chunk 8
Fontifying documentation chunks: chunk 9
Fontifying documentation chunks: chunk 10
Fontifying documentation chunks: chunk 11
Fontifying documentation chunks: chunk 12
About to do code chunks
Fontifying code chunks: chunk 1
Fontifying code chunks: chunk 3
Fontifying code chunks: chunk 5
Fontifying code chunks: chunk 7
Fontifying code chunks: chunk 9
Fontifying code chunks: chunk 11
Setting up syntax table
ess-noweb-font-lock mode: use ‘M-x ess-noweb-font-lock-describe-mode’ for more info
Applying style hooks...
Loading /usr/share/emacs/site-lisp/auctex/style/article.elc...done
Loading /usr/share/emacs/site-lisp/auctex/style/natbib.elc...done
Applying style hooks...done
noweb mode: use ‘M-x ess-noweb-describe-mode’ for further information
Fontifying from 0 to 12
Fontifying documentation chunks: chunk 0
Fontifying documentation chunks: chunk 1
Fontifying documentation chunks: chunk 2
Fontifying documentation chunks: chunk 3
Fontifying documentation chunks: chunk 4
Fontifying documentation chunks: chunk 5
Fontifying documentation chunks: chunk 6
Fontifying documentation chunks: chunk 7
Fontifying documentation chunks: chunk 8
Fontifying documentation chunks: chunk 9
Fontifying documentation chunks: chunk 10
Fontifying documentation chunks: chunk 11
Fontifying documentation chunks: chunk 12
About to do code chunks
Fontifying code chunks: chunk 1
Fontifying code chunks: chunk 3
Fontifying code chunks: chunk 5
Fontifying code chunks: chunk 7
Fontifying code chunks: chunk 9
Fontifying code chunks: chunk 11
Setting up syntax table
ess-noweb-font-lock mode: use ‘M-x ess-noweb-font-lock-describe-mode’ for more info
Applying style hooks...done
Followed link to ....(replaced by MM)..../Matrix/vignettes/Design-issues.Rnw
Error in post-command-hook (#[0 "\304\305\303\242\306#\210\307\302!\205\0r\302q\210\310\311\312\301\"\300\")\207" [nil (post-command on-display) #<buffer Design-issues.Rnw> (#0) remove-hook post-command-hook nil buffer-live-p flymake-start remove post-command] 4]): (wrong-type-argument hash-table-p nil)
```

Can anyone reproduce?
The error is ugly and uncomforting but actually not a big problem:  I then can open the file again and the error is not reproduced and I can work ok, Sweave, Tangle, pdflatex, etc. all from the nice `Noweb` menu.

**Comment by mmaechler** [comment]
I forgot to add that this problem does *not* appear if I don't start `R` first,  e.g., if I directly open the `*.Rnw` file via  `emacs ......./Matrix/vignettes/Design-issues.Rnw`

**Comment by mmaechler** [comment]
unfortunately that does not help.  The same error is produced.. and ditto if I add the same also to the `ess-noweb-mode-load-hook`.

Can't you reproduce?

**Comment by mmaechler** [comment]
(and it should happen more carefully in any case: Note that older emacsen do *not* have `flymake` and we had decided not require it,  so  `(flymake-mode  ...)` may only be called  `(if (featurep 'flymake) ...)`

**Comment by jabranham** [comment]
I can't reproduce this reliably but I do see it occasionally. `(setq ess-use-flymake nil)` seems to help or fix it.

It doesn't seem like it's worth anyone's time to track down what I imagine is a hard-to-fix bug in noweb since we're planning on obsoleting it.

**Comment by mmaechler** [comment]
@jabranham's proposal, also inside `ess-noweb-mode-hook`  does work.  However it is not a buffer local variable - but rather an ess-custom one, so changing it in the  `ess-noweb-mode-hook` spills over to all other modes.... Not what is desired here.   We'd need to have it work "buffer-locally" ... or define a new (custom?) variable to turn off flymake only in ess-noweb.
