### ISSUE TITLE
Remove ess-dde?

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#736]
I'm not quite sure what ess-dde is. Some sort of windows REPL for R?  Judging by the git log, there hasn't really been any substantive changes to that file in ...8? years? Does anyone know if it still works? Can we remove it?

**Comment by lionel-** [comment]
That's an old mode to interface with the Windows console for R. It is likely that it no longer works and the last time we discussed it on the mailing list we suggested removing it.

**Comment by vspinu** [comment]
Indeed. It should be removed.

**Comment by mmaechler** [comment]
Does any of the contributors here actually _use_  emacs+R on Windows  and know that it is no longer using it -- if not, to remain on the careful side, we should ask Vincent Goulet if he knows.  After all he builds the Emacs+ESS(+AucTeX+..)  binary that 95% or more of the Windows ESS users use..

**Comment by lionel-** [comment]
When Richard looked into it, he found that ESS-DDE has stopped working somewhere between ESS 5.14 and ESS 12.03. I think it's safe to say that there is not a single user of ESS DDE.

**Comment by lionel-** [comment]
AFAIK, our Windows users interact with R through comint just like Unix users.

**Comment by vspinu** [comment]
I think it should be removed. I doubt ess-DDE was much used before being broken in 12.03.  There are two sentences in ESS manual about DDE and none with instructions of how to actually set it up.

**Comment by jabranham** [comment]
It appears `ess-r-gui.el` depends on ess-dde. Does anyone know if the R gui is still used on Windows? I'm guessing not, since ess-dde is broken?

**Comment by jabranham** [comment]
I asked about this on ESS-help and haven't heard anything back, so I guess it's OK to remove ess-r-gui as well.

**Comment by mmaechler** [comment]
even more related, the recent message on ESS-help mentioned S-plus users on Linux(!) could no longer properly use ESS .. and the error message was about trying to use/access/...   `ess-dde` (!!)

**Comment by mmaechler** [comment]
Note that the users don't know which parts of ESS they use.  But the users have many more use cases for ESS than the union of ESS-core ..

**Comment by lionel-** [comment]
Which is a huge maintainability issue, especially without integration tests with proprietary softwares.

**Comment by lionel-** [comment]
Grepping for ess-dde, it now seems obvious it is used in Linux as well (ess-sp6 is for Linux while ess-sp6-w is for Windows, or am I missing something?).

However in ess-dde I see this preamble:

```
;; Code for dealing with running external processes on Windows 9x/NT
;; through ddeclient.
```

For more context: https://en.wikipedia.org/wiki/Dynamic_Data_Exchange

So how come this is used on Linux as well? Or do I misunderstand what ess-sp6.el is about?

Perhaps a more important question: is this really worth taking any of our time? We can't have that many S-Plus users, and they can still use the old ESS sources to interact with their old S-Plus softwares.

**Comment by jabranham** [comment]
The S/plus files are super confusing. I looked into the old S/S-plus files over [here](https://github.com/emacs-ess/ESS/pull/601#issuecomment-415176576) and decided it wasn't worth any more of my time to support proprietary software that isn't used very much. If people want to use S-plus they can grab old versions of ESS.

**Comment by vspinu** [comment]
Maintenance cost for a basic terminal front-end are minimal if we can grab a copy of S-plus. If no one can provide such a copy for linux and Window then I am afraid we have to remove S-plus from ESS. Kim (the reporter of the S-plus issue) informed me privately that ess-remote works. It's a viable option besides old ESS.
