### ISSUE TITLE
Remove ess-generics

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#737]
Port to cl-generics as discussed in #616 

- [X] ess-inf.el:970     :(ess-defgeneric ess-build-eval-command (string &optional visibly output file &rest args) b7be794b57aa81e5737b6699b28210bdf594e1f7
- [X] ess-inf.el:983     :(ess-defgeneric ess-build-load-command (file &optional visibly output &rest args) c470908f779edf8e084bf748692a789385b830f8
- [X] ess-inf.el:1117    :(ess-defgeneric ess-send-string (process string &optional visibly message type)
- [X] ess-inf.el:1159    :(ess-defgeneric ess-send-region (process start end &optional visibly message type)
- [X] ess-inf.el:1198    :(ess-defgeneric ess-load-file (&optional filename)
- [X] ess-inf.el:1243    :(ess-defgeneric ess-command (cmd &optional out-buffer sleep no-prompt-check wait proc force-redisplay)
- [X] ess-inf.el:1389    :(ess-defgeneric ess-eval-linewise
- [X] ess-inf.el:2174    :(ess-defgeneric ess-quit (&rest args) 937a5505d4b7af09a2ffdb4bef69ae4b07ee8753
- [X] ess-inf.el:2245    :(ess-defgeneric inferior-ess-reload (&optional start-args)
- [X] ess-inf.el:2686    :(ess-defgeneric ess-read-object-name (p-string)
- [X] ess-r-mode.el:1094 :(ess-defmethod R ess-build-eval-command (string &optional visibly output file namespace) b7be794b57aa81e5737b6699b28210bdf594e1f7
- [X] ess-r-mode.el:1102 :(ess-defmethod R ess-build-load-command (file &optional visibly output namespace) c470908f779edf8e084bf748692a789385b830f8
- [X] ess-r-mode.el:1168 :(ess-defmethod R ess-load-file (file)
- [X] ess-r-mode.el:1189 :(ess-defmethod R ess-send-region (proc start end visibly message type)
- [X] ess-r-mode.el:1353 :(ess-defmethod R ess-quit (&optional no-save) 937a5505d4b7af09a2ffdb4bef69ae4b07ee8753
- [X] ess-r-mode.el:1367 :(ess-defmethod R inferior-ess-reload (&optional start-args)
- [X] ess.el:613         :(ess-defgeneric ess-dump-object (object filename)
- [X] remove ess-generics.el

**Comment by jabranham** [comment]
I started with something simple to make sure we're all on the same page. Is this along the lines of what you were thinking @vspinu ?

```diff
diff --git a/lisp/ess-inf.el b/lisp/ess-inf.el
index a761ce9a..72f59f5e 100644
--- a/lisp/ess-inf.el
+++ b/lisp/ess-inf.el
@@ -2171,19 +2171,23 @@ to the command if BUFF is not given.)"
 
 ;;;*;;; Quitting
 
-(ess-defgeneric ess-quit (&rest args)
-  "Issue an exiting command to the inferior process, additionally
-also running \\[ess-cleanup]."
-  (interactive)
+(cl-defgeneric ess--quit (arg)
+  "Stops the inferior process"
   (ess-force-buffer-current "Process to quit: " nil 'no-autostart)
   (ess-interrupt)
   (ess-make-buffer-current)
-  (:override
-   (let ((proc (ess-get-process)))
-     (ess-cleanup)
-     (goto-char (marker-position (process-mark proc)))
-     (insert inferior-ess-exit-command)
-     (process-send-string proc inferior-ess-exit-command))))
+  (let ((proc (ess-get-process)))
+    (ess-cleanup)
+    (goto-char (marker-position (process-mark proc)))
+    (insert inferior-ess-exit-command)
+    (process-send-string proc inferior-ess-exit-command)))
+
+(defun ess-quit (&optional arg)
+  "Issue an exiting command to the inferior process.
+Runs `ess-cleanup'. ARG gets passed to the method, see
+`ess--quit'."
+  (interactive "P")
+  (ess--quit arg))
 
 (defun ess-interrupt ()
   "Interrupt the inferior process.
diff --git a/lisp/ess-r-mode.el b/lisp/ess-r-mode.el
index 1ada5033..210fca51 100644
--- a/lisp/ess-r-mode.el
+++ b/lisp/ess-r-mode.el
@@ -1350,12 +1350,16 @@ If it changes, we flush the cache.")
         (ess-command (format ".ess.ESSRversion <- '%s'\n" version)) ; cannot do this at R level
         (mapc #'ess--inject-code-from-file files)))))
 
-(ess-defmethod R ess-quit (&optional no-save)
+(cl-defmethod ess--quit (arg &context ((string= ess-dialect "R") (eql t)))
+  "With ARG, do not offer to save the workspace."
+  (ess-force-buffer-current "Process to quit: " nil 'no-autostart)
+  (ess-interrupt)
+  (ess-make-buffer-current)
   (let (cmd
         (sprocess (ess-get-process ess-current-process-name)))
     (when (not sprocess) (error "No ESS process running"))
     (ess-cleanup)
-    (setq cmd (format "base::q('%s')\n" (if no-save "no" "default")))
+    (setq cmd (format "base::q('%s')\n" (if arg "no" "default")))
     (goto-char (marker-position (process-mark sprocess)))
     (process-send-string sprocess cmd)))
 
```

**Comment by vspinu** [comment]
Not quite. I meant to extract the :override part into a internal cl-generic. The idea behind ess-generic is that the :override is modifiable and the code around it is inherited from the default method. 

We can call it `ess-quit--override`.

**Comment by jabranham** [comment]
I don't think I understand what you're saying. What I proposed above has `ess--quit` which gets modified in R buffers to run different code. How is what you're saying different?

**Comment by vspinu** [comment]
What you say is rebranding ess-quit into generic ess--quit, right? What I say, leave ess-quit as it is and make ess--quit-override generic for the `:override` part from inside `ess-quit`. So that instead of `(:override` there will be a call `ess--quit-override` of some sort. The crucial feature of ess-generic is that we can have this `:override` mechanism.

**Comment by jabranham** [comment]
OK, I think I see now. You're suggesting this, right?

```diff
diff --git a/lisp/ess-inf.el b/lisp/ess-inf.el
index a761ce9a..13342ed7 100644
--- a/lisp/ess-inf.el
+++ b/lisp/ess-inf.el
@@ -2171,19 +2171,23 @@ to the command if BUFF is not given.)"
 
 ;;;*;;; Quitting
 
-(ess-defgeneric ess-quit (&rest args)
-  "Issue an exiting command to the inferior process, additionally
-also running \\[ess-cleanup]."
-  (interactive)
+(cl-defgeneric ess-quit--override (arg)
+  "Stops the inferior process"
+  (let ((proc (ess-get-process)))
+    (ess-cleanup)
+    (goto-char (marker-position (process-mark proc)))
+    (insert inferior-ess-exit-command)
+    (process-send-string proc inferior-ess-exit-command)))
+
+(defun ess-quit (&optional arg)
+  "Issue an exiting command to the inferior process.
+Runs `ess-cleanup'. ARG gets passed to a language specific
+method, see `ess-quit--override'."
+  (interactive "P")
   (ess-force-buffer-current "Process to quit: " nil 'no-autostart)
   (ess-interrupt)
   (ess-make-buffer-current)
-  (:override
-   (let ((proc (ess-get-process)))
-     (ess-cleanup)
-     (goto-char (marker-position (process-mark proc)))
-     (insert inferior-ess-exit-command)
-     (process-send-string proc inferior-ess-exit-command))))
+  (ess-quit--override arg))
 
 (defun ess-interrupt ()
   "Interrupt the inferior process.
diff --git a/lisp/ess-r-mode.el b/lisp/ess-r-mode.el
index 1ada5033..df932500 100644
--- a/lisp/ess-r-mode.el
+++ b/lisp/ess-r-mode.el
@@ -1350,13 +1350,15 @@ If it changes, we flush the cache.")
         (ess-command (format ".ess.ESSRversion <- '%s'\n" version)) ; cannot do this at R level
         (mapc #'ess--inject-code-from-file files)))))
 
-(ess-defmethod R ess-quit (&optional no-save)
+(cl-defmethod ess-quit--override (arg &context ((string= ess-dialect "R") (eql t)))
+  "With ARG, do not offer to save the workspace."
   (let (cmd
         (sprocess (ess-get-process ess-current-process-name)))
     (when (not sprocess) (error "No ESS process running"))
     (ess-cleanup)
-    (setq cmd (format "base::q('%s')\n" (if no-save "no" "default")))
+    (setq cmd (format "base::q('%s')\n" (if arg "no" "default")))
     (goto-char (marker-position (process-mark sprocess)))
+    (insert cmd)
     (process-send-string sprocess cmd)))
 
 (defcustom inferior-ess-r-reload-hook nil
```

**Comment by vspinu** [comment]
Precisely.  This is basically a replacement for the classic emacs `(funcall 'xyz-function)` where `xyz-function` is locally set to provide some customized behavior. Now that we have cl-generics on context we can do much cooler stuff than simply dispatching on ess-dialect.

Specifically, there might be a good opportunity here to simplify the dispatch of the evaluation mechanism. Currently we have overlapping simple, tracebug and package evaluation clutched in not the most elegant way.
