### ISSUE TITLE
ess-autoloads.el not copied by make install

### ISSUE THREAD

**Issue by vigou3** [emacs-ess/ESS#741]
With ESS 18.10.2, `ess-autoloads.el` is created by `make install`, but not copied over to the lisp installation directory. I'm not sure if it is intended or not.

I tried manually copying the file to the ess lisp installation directory and it seems to work correctly. However (and this may well be a separate issue), loading ESS with `(load "ess-autoloads")` causes a problem with my redefinition of the variable `ess-swv-pdflatex-commands` in my .emacs init file. I suspect this could cause problem for others too.

Should I just stick to the "classic" initilization mechanism `(require "ess-site")`?

> (This is for my Emacs Modified for [Windows|macOS] distributions.)

**Comment by vspinu** [comment]
Hmm, autoloads should be copied. 

Regarding your custom configuration, one solution would be to append the custom setting into `ess.el` or `ess-mode.el` which are loaded by all files. This would work for variables only. If you redefine some functions they will be overwritten by the actual definitions in files which are loaded after ess-mode.el. If you redefine functions `(require 'ess-site)` seems to be the way to go. @jabranham, any ideas?

**Comment by jabranham** [comment]
>  loading ESS with (load "ess-autoloads") causes a problem with my redefinition of the variable ess-swv-pdflatex-commands in my .emacs init file.

What problem, exactly? Do you get an error message? Can you post how you're redefining `ess-swv-pdflatex-commands`?

**Comment by vigou3** [comment]
Ok, additional background. I set up a distribution of Emacs (using precompiled binaries) with ESS bundled after compiling it (ESS) from source. I have been doing for years and it works really well.

I include in the distribution a `site-start.el` file that contains, among other things, the following (comments stripped):

```
(setq-default inferior-R-args "--no-save ")
(setq-default ess-swv-plug-into-AUCTeX-p t)
(add-hook 'ess-mode-hook
	  '(lambda()
	     (add-hook 'write-contents-functions
		       (lambda ()
                         (ess-nuke-trailing-whitespace)))
	     (setq ess-nuke-trailing-whitespace-p t)))
(load "ess-autoloads")  # formerly (require 'ess-site)
```

That way, ESS works out of the box. 

Now, with the `(load "ess-autoloads")` approach, I get a `Symbol's value as variable is void: ess-swv-pdflatex-commands` error while loading my **personal** initialization file in which I add the XeLaTeX engine to the list of supported commands for Sweaving:

```
(setq ess-swv-pdflatex-commands
      (nconc '("xelatex")
	     ess-swv-pdflatex-commands))
```

I understand this may be because ESS is not fully loaded at startup. 

Given that my usage scenario is that ESS is loaded "site-wide" and not by users, I guess that using `(require 'ess-site)` remains the correct way to go.

**Comment by jabranham** [comment]
> I set up a distribution of Emacs (using precompiled binaries) with ESS bundled after compiling it (ESS) from source

I know, thanks for all your help distributing ESS! :-) 

 > I understand this may be because ESS is not fully loaded at startup.

Right, so `ess-swv-pdflatex-commands` isn't defined yet when that code gets executed. You could make this work by wrapping your ESS customization in `(with-eval-after-load "ess" <config here>)`. 

> Given that my usage scenario is that ESS is loaded "site-wide" and not by users, I guess that using (require 'ess-site) remains the correct way to go.

That's up to you, really. Having ESS required means that everything is defined so you won't run into those types of errors. Having it autoloaded will decrease the initial startup time.

As to the initial bug report, it looks like we're not copying the `.el` files over to the lispdir @vspinu WDYT?

```diff
diff --git a/lisp/Makefile b/lisp/Makefile
index 9c03519c..10fd0bb8 100644
--- a/lisp/Makefile
+++ b/lisp/Makefile
@@ -39,6 +39,7 @@ dist: all
 
 install: dist
 	-$(INSTALLDIR) $(LISPDIR)
+	$(INSTALL) $(EL) $(LISPDIR)
 	$(INSTALL) $(ELC) $(LISPDIR)
 	if [ -f /etc/debian_version -a -n "$(SITELISP)" -a ! -f "$(SITELISP)/ess-site.el" ] ; \
 	then \
```

**Comment by vigou3** [comment]
All right Alex, thanks. For the sake of simplicity for the end users, I'll just stick to requiring ESS.
