### ISSUE TITLE
Cannot open ess-rd.el

### ISSUE THREAD

**Issue by vigou3** [emacs-ess/ESS#742]
Loading ESS with `(require 'ess-site)` in a `site-lisp.el` file for a by compiled distribution of ESS results in the following error at startup (from the `*Messages*` buffer):

```
byte-code: Cannot open load file: No such file or directory, ess-rd.el
```

The file `ess-rd.elc` is present in the appropriate `lisp` directory.

Copying the original `ess-rd.el` in the aforementioned `lisp` directory solves the problem and Emacs and ESS start normally.

- GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-30
- ess-version: 18.10.2 [Released git: d4cd65da6dbf]

**Comment by jabranham** [comment]
So something is trying to load the non-byte-compiled file? That's weird. Can you post the backtrace please? If this error pops up when Emacs starts you can do `emacs --debug-init` to get it.

**Comment by jabranham** [comment]
Ah, nevermind. I found it. We're requiring `ess-rd.el` by name, which is bad. This has actually already been fixed in the `next` branch: c58199b659331a1819363499b1a126082c3890d6. It looks like 809a6cde4de488796fff8cc0241f62cab7736c01 stopped installing the .el files along with the .elc files, which also accounts for #741.

**Comment by vigou3** [comment]
Weird indeed.

I tried to get a backtrace of some sort, but I'm missing something, here. According to the docs, `--debug-init` works for the `.emacs` file, whereas in my case ESS is launched from `site-start.el`. Anyway, no backtrace available other than what I posted from the `*Messages*` buffer.

I also tried using `-f toggle-debug-on-error`; same result. Other ideas?

**Comment by vigou3** [comment]
Ok. For the time being I'll package distributions with ESS 18.10.2 and copy the `.el` files myself. Simple enough to do.
