### ISSUE TITLE
Julia complete code in ESS REPL error

### ISSUE THREAD

**Issue by stardiviner** [emacs-ess/ESS#745]
![image](https://user-images.githubusercontent.com/378699/48384614-22000400-e726-11e8-9093-2cf8d3c5588d.png)

This is the screenshot, I start a fresh new REPL with `julia` command commands from ESS. But it does not show methods like `Pkg.add` `Pkg.update` etc.

**Comment by jabranham** [comment]
This was closed by e92d3304cc974b7e06c1df0b47f988904d53f155

**Comment by stardiviner** [comment]
Thanks for quick fix.
