### ISSUE TITLE
?FuncName fails to render development help

### ISSUE THREAD

**Issue by mcaselli** [emacs-ess/ESS#749]
when developing a package (e.g. `devpkgname` using the `devtools` suite with `roxygen2`, after building documentation (`C-c C-w C-d`) and loading the package (`C-c C-w C-l`),  running `?FuncName` in the R session does not successfully display the documentation; instead I see in the minibuffer:

`Choose location: {FuncName | devpkgname | path/to/devpkgname/man/FuncName.Rd | render | html}`

regardless of the option selected, the 'other' buffer, titled `*help[R](FuncName)*` diplays: 
```
+ Error in attributes(.Data) <- c(attributes(.Data), attrib) : 
  'names' attribute [5] must be the same length as the vector [1]
```

I know the documentation is successfully being created, as the .Rd files are present, and if I open the project in Rstudio, Rstudio finds and displays the documentation successfully.

Thanks for the great product, and thanks in advance for the help!

`ess-version: 17.11 [Released git: d03efb64579f] (loaded from c:/Program Files/GNU Emacs 26.1/share/emacs/site-lisp/)`

**Comment by vspinu** [comment]
This was fixed in 18.10.
