### ISSUE TITLE
no *.el files included anymore?

### ISSUE THREAD

**Issue by dsteuer** [emacs-ess/ESS#755]
Hi! I got users asking the following:

(sorry in german, but I'm sure someone here can read it, too  )

```txt
Ich (und viele andere in meinem Team) verwenden 

https://build.opensuse.org/package/show/devel:languages:R:released/emacs-ess

für openSUSE 42.3. Seit dem Update von 17.11-2.1 auf 18.10.2-2.1 enthält das
Paket nur noch die kompilierten Lisp-Dateien (*.elc), die *.el-Dateien fehlen.
Ich vermute, dass dies der Grund dafür ist, dass das Laden (z.B. mittels
(require 'ess-site)) zu folgendem Fehler beim Aufstarten von Emacs (24.3.1)
führt:	

File error: Cannot open load file, ess-rd.el

Ich bin froh um jeden Hinweis, wie ich dieses Problem lösen könnte. Besten
Dank.
```

In ./lisp/Makefile there is $(INSTALL) $(ELC) $(LISPDIR) which installs only the *elc files
while before  there was 
$(INSTALL) `basename $$J .elc`.el $(LISPDIR); in some loop over all the files.

Is this problem related to emacs 24.3.1 ? 
Does it hurt to continue to install *el files along the *elc files?
What would be the easiest way to support the users here?

For the
Detlef

**Comment by dsteuer** [comment]
Sorry, the big letters were unintended ... used wrong way to quote

**Comment by eddelbuettel** [comment]
IIRC I had something like that too but that may have gone away with the switch to using `package.el` and *ELPA.  Worst case you can re-create what the `Makefile` used to do for you and `cp *.el` somewhere.

**Comment by mmaechler** [comment]
That was yet another bug introduced in the big "clean up spirit" applied to the `Makefile`s by people who assumed too much ... and has been fixed in the mean time, but unfortunately only after I've released `ESS 18.10.2`.   --> d8c11c6b9

**Comment by mmaechler** [comment]
oops ... and that was by me !!!    sorry for that blunder and for misattribution!!

**Comment by jabranham** [comment]
No problem, everyone makes mistakes :-)
