### ISSUE TITLE
ess-sp6w-d.el removed however ess.el and ess-sp6-d.el not cleaned

### ISSUE THREAD

**Issue by ShuguangSun** [emacs-ess/ESS#766]
It seems ess-sp6w-d.el was removed, however, it is still required in ess.el and ess-sp6-d.el

ess.el
line 57: (declare-function S+ "ess-sp6w-d")
=> (declare-function S+ "ess-sp6-d")

ess-sp6-d.el
line 44:  (when ess-microsoft-p (require 'ess-sp6w-d))
to delete

**Comment by jabranham** [comment]
Thanks, fixed.
