### ISSUE TITLE
confusing naming of inferior-r mode

### ISSUE THREAD

**Issue by nverno** [emacs-ess/ESS#789]
Other modes have names prefixed with `ess-inferior-{julia|stata}-mode-map` but R is `inferior-ess-r-mode-map`. They should all be the same right?

**Comment by jabranham** [comment]
I think that's my fault. In the Great Derived-Mode Rewrite I originally had them `ess-inferior-*` and someone said they should be `inferior-ess-*`. I must've changed R mode and forgot to update the others. I'll fix it later today.
