### ISSUE TITLE
`M-x ess-MM-fix-src` is broken

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#791]
Yes, it's a command I had created years ago to help people use good R programming style in *.R file buffers:

 use ` <- ` instead of `=`,  use TRUE, FALSE, not T, F, use spaces in other places, 
use correct emacs style number of "#" for comments etc.

and it is broken now,  `(setq debug-on-error t)`  gives

Debugger entered--Lisp error: (wrong-type-argument sequencep ess-r-customize-alist)
  mapc(#f(compiled-function (pair) #<bytecode 0x166983d>) ess-r-customize-alist)
  ess-setq-vars-local(ess-r-customize-alist)
  ess-mode()
  ess-dump-to-src(nil)
  ess-MM-fix-src(nil)

**Comment by vspinu** [comment]
Its a dependency issue. Calling `ess-mode` from `ess-dump-to-src` is almost surely a wrong thing. 

The following should fix it:

```el

(defun ess-dump-to-src (&optional dont-query verbose)
  "Make the changes in an S - dump() file to improve human readability."
  (interactive "P")
  (ess-replace-regexp-dump-to-src  "^\"\\([a-z.][a-z.0-9]*\\)\" *<-\n"
                                   "\n\\1 <- "
                                   dont-query verbose))
```


If we want to keep this function we should rename it into `ess-r-fix-source` or something.

**Comment by mmaechler** [comment]
1) Yes, thank you, the `(ess-mode)` is of course the culprit.   But it has been there for a reason, so rather than deleting it I'd rather replace it (as I have done locally) by something like
```  
(unless (eq major-mode 'ess-mode)
    (message "Not in an ess-mode; choosing R-mode for you")
    (R-mode))
```   
2) It's not just R.  R is a dialect of S ...  (and it's still extremely strange that `S-mode` is now an alias to `S+-mode` and that is only defined in file  `ess-sp6w-d.el`  where the `"w"` in that file name *and* the initial comments in that file emphasize that this is about "S-plus / S+ for Windows".
`S-mode` should really be defined in `ess-s-lang.el`
