### ISSUE TITLE
C-M-e  now "rarely" works -- and *context* dependently

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#793]
There are related open issues (e.g. #251), but this one is relative new behavior.   Working on one of my packages (`Bessel`, file `R/I-fn.R`),  I notice that  `C-M-a` (to go the beginning of the function I'm working on) typically works fine,  whereas  `C-M-e` typically only goes to the end of the first paragraph in that function... but not always.

In this example, it typically jumps too far, into the next function, or otherwise one paragraph too far:
```r
tt <- function(x, y, ...)
{
    ## HERE _1_
    ##
    ## ----------------------------------------------------------------------
    ## Arguments: x, y: bla bla bla
    ## ----------------------------------------------------------------------
    ## Author: Martin Maechler, Date: 15. Dec 2018

    ## HERE _2_: bla bla bla

    ## HERE _3_: blu blu blu
    stopifnot(x == round(x))

    r <- x^2

    x + sin(y) # etc
}

## and there is more,
foobar <- function(x, n = 4)
{
    ## just an intro paragraph...  C-M-e from above HERE _1_ jumps to next line!

    stopifnot(n == round(n))#  but then, from HERE _6_, it jumps to  line after '1+2' 

    ## and the result:
    x^n
}

## there's more and more
1+2

## last line  (possibly before the end of file)
```

**Comment by mmaechler** [comment]
Possibly relatedly:  
 `C-M-a`  also works when not inside a function,  but
 `C-M-e` gives an error if not inside a function

**Comment by jabranham** [comment]
Yeah, I saw that too. I've pushed a couple of commits that address the worst of this behavior but they're really meant as more of a stopgap until I (or someone else) get around to actually fixing this behavior.

**Comment by vspinu** [comment]
I don't see an elegant solution to this. `end-of-defun` insists on moving the pointer and doesn't return anything useful. I am afraid we made our life much harder by going down with the "standard". 

One possible way out of the current situation is to change the semantics of `ess-r-beggining/end-of-defun` to that of `ess-goto-beginning-of-function-or-para` and remove the latter. That would better resemble how beggining-of-defun` works in other languages and would considerably simplify the code. No user visible changes required.

**Comment by mmaechler** [comment]
Well, I hope there will be considerable user visible changes to the better.
The situation is so bad now... I've found another really bad example ... always working in "real code" (from packages tests).

**Comment by lionel-** [comment]
@vspinu I don't think beginning-of-defun involves the notion of paragraphs in other modes (I just checked with cc-mode and python-mode). I really want to get to the bottom of this but won't have time to work on ESS before February...

**Comment by lionel-** [comment]
Perhaps `defun-or-para` really is about paragraphs + whatever is needed to complete expressions from above and below.

**Comment by vspinu** [comment]
In other modes it does every sexp, as we cannot currently detect individual sexps I propose we stick with top level function forms and top level paragraphs for now. Latter, when you have time this could be improved to detection of the sexps proper.  

This defun navigation and, worst, function evaluation is so badly broken atm that we need a quick hack in the right direction asap.

**Comment by vspinu** [comment]
I am looking at it and will have something basic soonish for functions only. Leaving the `-defun` (aka sexp) detection to @lionel- .  I think we need to start from scratch on this one and build from there incrementally with loads of tests.
