### ISSUE TITLE
In a `*.Rd` buffer preview fails

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#795]
I'm pretty sure this a very recent bug (not e.g. in 18.10-2):

 thought it was only when there's no running *R* process,  but it also happens when I start emacs "calling" a *.Rd file.  Then do  `C-c C-p`  which is  `(Rd-preview-help)`.   That does ask me to start an R process which it then also does  (now strangely add package/project/directory name to the buffer name -- not that I'd like that !  now seeing `*R-specfun*`  when I'm working inside (R-forge) package `Bessel` which below a directory called `.../specfun/pkg/Bessel` ((so why on earth it takes "specfun" rather than "Bessel" ???)).  
Anyway, an R process then is even running, but it still ends in this error:
```el
Debugger entered--Lisp error: (error "No current ESS process")
  signal(error ("No current ESS process"))
  error("No current ESS process")
  ess-s-get-help-topics-function(nil)
  ess-r-help-add-links()
  ess-r-help-mode()
  ess--help-major-mode()
  Rd-preview-help(nil)
  funcall-interactively(Rd-preview-help nil)
  call-interactively(Rd-preview-help nil nil)
  command-execute(Rd-preview-help)
```

**Comment by jabranham** [comment]
Thanks, should be fixed. Let me know if 7f4849d4d49d333b7fae792e1e9fc07288cf5eea doesn't fix it for you though.
