### ISSUE TITLE
Lisp error: (void-function ess-inferior-julia-mode)

### ISSUE THREAD

**Issue by jagot** [emacs-ess/ESS#797]
This was introduced by 6d6f8d4331c4d22fbdc681d706f7296941f2c0f3, since `(ess--inferior-major-mode "julia")` was not updated to reflect this: https://github.com/emacs-ess/ESS/blob/master/lisp/ess-inf.el#L81

**Comment by jagot** [comment]
This probably applies to Stata as well.

**Comment by jabranham** [comment]
Fixed, thanks!
