### ISSUE TITLE
eldoc no longer showing any arguments

### ISSUE THREAD

**Issue by r2evans** [emacs-ess/ESS#804]
Thanks again for ESS, everybody. It's a mainstay for my day-to-day work!

I just updated to ESS-18.10.3snapshot on windows (GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30), and function arguments are no longer show in the echo area. This worked yesterday before the update.

This is happening for custom and base-R functions. I'm not seeing any errors/warnings, no undue pauses (that might indicate an attempt), no hiccups. It's just smooth as butter and ... silent. `ess-use-eldoc` is `t`, and I just changd `ess-eldoc-show-on-symbol` to `t` as well (was `nil`) but no change.

**Comment by vspinu** [comment]
When process is not busy, do you see `(inferior-ess-available-p)` returning nil by any chance? Is this on remote by any chance? There is a [hardcoded delay or 10ms](https://github.com/emacs-ess/ESS/blob/master/lisp/ess-inf.el#L393) in that function which might not be enough for you. I have some ideas of how to make it full proof but haven't had time so far. Could you please increase the delay and check if it helps?

**Comment by r2evans** [comment]
Yes, `(inferior-ess-available-p)` is `nil` with a non-busy R. I just typed in `data.frame(` and waited for 10 sec (not ms) with nothing happening. Then I increased 0.01 to 0.2 and it seems to be working now, thanks for that. Perhaps that should be in a variable somewhere? (I'm guessing 0.2 is way more than I needed, I decided to go quasi-nuclear. I'll likely finesse and may find a tipping point, if that'll be at all helpful.)

(BTW, thanks for the suggestion to edit ... I also found that my recent package-update erroneously installed second instances of a dozen MELPA packages, so I had both `ess-20181113.1414` and `ess-20190103.2054` (for instance) simultaneously installed. It didn't fix this ussue, but I'm sure it would have sprung a few other bugs elsewhere.)

**Comment by vspinu** [comment]
Would be nice if you can let me know your tipping point. What OS is this?

**Comment by r2evans** [comment]
(Sorry ... I didn't think ahead ... I installed your recently-committed change to test your code before realizing I lost the easy way to test for that tip-over point.)

**Comment by vspinu** [comment]
No problem. I was just curious. After using a process for a while (a few minutes, longer the better) do `(ess-process-get 'average-response-time)` in the inferior. This should provide an estimate of a response time in seconds on a simple `\n` request. For me on Ubuntu it's 0.008.
