### ISSUE TITLE
build error: Symbol’s value as variable is void: julia-function-regex

### ISSUE THREAD

**Issue by slyrus** [emacs-ess/ESS#805]
When I try to make ESS from the latest sources, I get:

```
julia-mode.el:645:30:Error: Symbol’s value as variable is void: julia-function-regex
Makefile:82: recipe for target 'julia-mode.elc' failed
make[1]: *** [julia-mode.elc] Error 1
make[1]: Leaving directory '/home/sly/.emacs.d/site-lisp/ESS/lisp'
Makefile:20: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by slyrus** [comment]
I have no idea if this the "right" fix or not and I don't use julia so can't test it, but putting the definition of julia-function-regex and jula-function-assignment-regex  inside a (eval-when-compile ...) form allows the build to succeed.

**Comment by slyrus** [comment]
bah! so... why do we clobber a user's julia.el upon make? seems a bit rude to trash my changes.

**Comment by nverno** [comment]
This will be fixed shortly, there is an open pull request JuliaEditorSupport/julia-emacs#68

**Comment by mmaechler** [comment]
It (the `julia-mode.el` compilation error) is still happening... and a pain for `ess` development. @nverno : can the "shortly" been made a bit shorter now, please ;-)

**Comment by jabranham** [comment]
Even better would be if Julia mode would have a stable tag we could use. They used to, but then deleted them. :-(

**Comment by mmaechler** [comment]
The upstream change (thanks @nverno) does fix this now.
Inside `ess/lisp/` do  
```
rm julia-*.el
make
```
(which gets the new *.el files from upstream)
