### ISSUE TITLE
Cannot find .load.R with ESS >= 18.10 on Aquamacs

### ISSUE THREAD

**Issue by braunm** [emacs-ess/ESS#807]
I am running Aquamacs 3.5dev on MacOS 10.14.2, based on Emacs 25.3.50.1.  The following issue does not appear with ESS 17.11, but it does with all subsequent ESS versions, and it appears in the stable Aquamacs version 3.4, but does not appear in Emacs for OSX 26.1. I also posted to the macosx-emacs mailing list, because it is not clear to me if this issue is best resolved in ESS or Aquamacs, or perhaps my own configuration.

When I launch an R process from Aquamacs, I get the following message:
```
load ESSR: + + + Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file ’/Users/dr/Nightly/master/aquamacs-emacs.git/lisp/aquamacs/edit-modes/ess-mode/etc/ESSR/R/.load.R’: No such file or directory
```
The most immediate consequence is that when I ask for an R help page (e.g., `?mean`), I get the following message in the emacs mini buffer:
```
Retrieving RDS aliases...done
Error in .ess.help("mean") : could not find function ".ess.help"`.
```
I traced the error back to a commit shortly after 17.11 was released, on 19 Nov 2017 (commit 151b003 is the first time it appeared).  There was a change in lisp/ess-utils.el related to "Only try to detect `ess-etc-directory` if not already set up.”  Unfortunately, my lisp skills are close to non-existent, so this is as far as I have been able to get in the debugging process.

Thanks,

Michael

**Comment by braunm** [comment]
I seem to have found a workaround by defining the following in my Preferences.el file:
`(setq ess-etc-directory "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/ess-18.10.2/etc")`
So I'll close this issue for now.

**Comment by vspinu** [comment]
Is this  with MELPA? If so, it's a serious issue and should be checked.  Your workaround will break next time you update ESS.

**Comment by jabranham** [comment]
> /Users/dr/Nightly/master/aquamacs-emacs.git/lisp/aquamacs/edit-modes/ess-mode/etc/ESSR/R/.load.R’

Does your version of aquamacs ship with ESS? Is it possible you have two different versions installed?

**Comment by braunm** [comment]
Aquamacs does ship with ESS 17.11.  So yes, when I update ESS, there are two versions on my computer.  Is there a way I could set the correct directory in a way that is not ESS version-specific? Should there not be a way to bypass the bundled ESS completely?

**Comment by jabranham** [comment]
@braunm I think this is an aquamacs problem, or possibly a problem with your config. I'm closing this issue to keep our issue tracker uncluttered, but feel free to keep asking questions here.

**Comment by braunm** [comment]
The issue was just fixed in a GitHub commit on the Aquamacs side.  Thanks for helping figure out the problem (which had to do with how ess-etc-directory was being set).

**Comment by jabranham** [comment]
Great, thanks for reporting back!
