### ISSUE TITLE
Org-mode remote R session broken in latest version

### ISSUE THREAD

**Issue by fkgruber** [emacs-ess/ESS#813]
Hello,
I't seems that the bug reported and fixed in #366 is back.  I'm having exactly the same issue when submitting code to a remote server. 
I using 
-  ESS: 18.10.2
- orgmode version 9.2 org-plus-contrib-20181230

When I tried to use :results value  I get and error. For example:
```
#+begin_src R :results value :session *R:4* :dir /ssh:host:/users/name/ 
  head(cars) 
#+end_src
```
I get

```
Error in ss(file, echo = visibly, local = local, print.eval = output, :
unused argument (spaced = FALSE)
```

it works fine with :results output.

Also if the R is running locally then :results value works fine:
```
#+begin_src R :session *Rlocal* :results value
head(cars)
#+end_src
```

```
#+RESULTS:
| speed | dist |
|-------+------|
|     4 |    2 |
|     4 |   10 |
|     7 |    4 |
|     7 |   22 |
|     8 |   16 |
|     9 |   10 |

```

**Comment by jabranham** [comment]
It works fine for me. Can you:

- On the remote machine, delete the directory `~/.config/ESSR/` and retry
- If that doesn't work, try ESS from MELPA (and make sure you re-delete that directory)

If none of that works, can you report back with some more information about your exact setup (OS of client and server, Emacs version, anything else that might be important)?

**Comment by fkgruber** [comment]
Hi
I tried installing ESS from melpa:  20190114.2220
removed the directory and still get the error
I'm using:
-  both local and remote are linux machine running ubuntu:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

-GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.30) of 2018-10-02

- orgmode version 9.2 org-plus-contrib-20181230

The way I'm testing this is the following:
- I use tramp to connect to the server: C-x C-f /ssh:serverip:~/
- to M-x R to open R in remote server

Then I created the following org file
```
#+TITLE:test 
#+PROPERTY: header-args :tangle yes :eval no-export
#+PROPERTY: header-args:R :session *R* :exports both :colnames yes  :dir /ssh:serverip:~/
#+OPTIONS: ^:{}
-----
* Test
#+begin_src R  :results value
head(cars)  
#+end_src

#+begin_src R :results output
  head(cars)
#+end_src

#+RESULTS:
:   speed dist
: 1     4    2
: 2     4   10
: 3     7    4
: 4     7   22
: 5     8   16
: 6     9   10

```

When I run the block with :results value I get
```
> 'org_babel_R_eoe'

[1] "org_babel_R_eoe"
> 
Error in ss(file, echo = visibly, local = local, print.eval = output,  : 
  unused argument (spaced = FALSE)
```

sessionInfo()
```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

locale:
 [1] LC_CTYPE=en_US.utf8       LC_NUMERIC=C             
 [3] LC_TIME=en_US.utf8        LC_COLLATE=en_US.utf8    
 [5] LC_MONETARY=en_US.utf8    LC_MESSAGES=en_US.utf8   
 [7] LC_PAPER=en_US.utf8       LC_NAME=C                
 [9] LC_ADDRESS=C              LC_TELEPHONE=C           
[11] LC_MEASUREMENT=en_US.utf8 LC_IDENTIFICATION=C      

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
> 
```
 
Let me know if there is any other information that could be useful.

**Comment by fkgruber** [comment]
One more thing, going back to ess 17.11 fixes the problem keeping everything else the same.

I'm wondering whether you use a different workflow to get R running remotely?

**Comment by vspinu** [comment]
What does your `~./config/ESS` remote directory contain? What does `.ess.ESSRversion` show in the remote `*R*`? 

We do have a [check](https://github.com/emacs-ess/ESS/blob/master/etc/ESSR/R/.basic.R#L103-L108) dedicated for `spaced` argument which appeared in 3.4. Can you print `.ess.source` in the remote `*R*` buffer and see if it matches with the github version?

**Comment by fkgruber** [comment]
> What does your `~./config/ESS` remote directory contain? What does `.ess.ESSRversion` show in the remote `*R*`?
> 
the .config/ESSR contains:
ESSRv1.3.rds

> We do have a [check](https://github.com/emacs-ess/ESS/blob/master/etc/ESSR/R/.basic.R#L103-L108) dedicated for `spaced` argument which appeared in 3.4. Can you print `.ess.source` in the remote `*R*` buffer and see if it matches with the github version?


the .ess.source looks exactly the same as the github:
```
> .ess.source
function (file, visibly = TRUE, output = FALSE, max.deparse.length = 300, 
    local = NULL, fake.source = FALSE, keep.source = TRUE, message.prefix = "") 
{
    if (is.null(local)) {
        local <- if (.ess.Rversion > "2.13") 
            parent.frame()
        else FALSE
    }
    ss <- if (.ess.Rversion >= "3.4") 
        base::source
    else if (.ess.Rversion >= "2.8") 
        function(..., spaced) base::source(...)
    else function(..., spaced, keep.source) base::source(...)
    on.exit({
        if (fake.source) .ess.file.remove(file)
    })
    out <- ss(file, echo = visibly, local = local, print.eval = output, 
        spaced = FALSE, max.deparse.length = max.deparse.length, 
        keep.source = keep.source)
    if (!fake.source) 
        cat(sprintf("%sSourced file %s\n", message.prefix, file))
    invisible(out$value)
}
```

What I noticed is that .ess.Rversion is
.ess.Rversion
[1]  3.4.4 

so that 
ss is being assigned base::source
which does not have a spaced option. Is this an R version problem?

```
base::source
function (file, local = FALSE, echo = verbose, print.eval = echo, 
    verbose = getOption("verbose"), prompt.echo = getOption("prompt"), 
    max.deparse.length = 150, chdir = FALSE, encoding = getOption("encoding"), 
    continue.echo = getOption("continue"), skip.echo = 0, keep.source = getOption("keep.source")) 
{
  
```

**Comment by vspinu** [comment]
ARH, this is a bug. I see where it comes from. The fix would need a bit of thinking.

**Comment by vspinu** [comment]
Should be fixed in master. Thanks! A really good catch.

**Comment by fkgruber** [comment]
thank you for fixing it so fast!
