### ISSUE TITLE
Incorrect prompt detection

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#814]
In an inferior R buffer, 

```R
summary(lm(mpg ~ wt, data = mtcars))
```

results in 

```
Call:
lm(formula = mpg ~ wt, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.5432 -2.3647 -0.1252  1.4096  6.8727 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  37.2851     1.8776  19.858  < 2e-16 ***
wt           -5.3445     0.5591  -9.559 1.29e-10 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.046 on 30 degrees of freedom
Multiple R-squared:  0.7528,	Adjusted R-squared:  0.7446 
F-statistic: 91.38 on 1 and 30 DF,  p-value: 1.294e-10
```

With the `Signif. ` part getting incorrectly recognized as a prompt. It gets font-locked as such and `C-c C-p` (M-x `comint-previous-prompt`) navigates back to it, rather than the previous prompt.

I think this is because of:

```elisp
(defvar inferior-S-prompt "[]a-zA-Z0-9.[]*\\(?:[>+.] \\)+"
  "Regexp used in S and R inferior and transcript buffers for prompt navigation.
Must be anchored to BOL.")
```

where `inferior-S-prompt` doesn't check that `]a-zA-Z0-9.[` comes after at least one `>` or `+`.

@vspinu Is there a reason we don't currently check for at least one `>` or `+` before `]a-zA-Z0-9.[`?

**Comment by vspinu** [comment]
The regexp is incorrect for simplicity reasons, I guess. There must be at least one >+ before ".".

**Comment by jabranham** [comment]
@vspinu - Awesome, thanks!
