### ISSUE TITLE
R error splits code frame

### ISSUE THREAD

**Issue by swhalemwo** [emacs-ess/ESS#816]
Thanks for this awesome program, couldn't do without it! Usually, I work with multiple frames (using i3), one of which runs the R process, and one or more with R code. For some time now (i unfortunately do not remember when it first occured), I have had the problem that when I execute a line or chunk of code in the code frame which produces an error, the code frame gets split in half, with the R process being shown in the new window. Since I already have a frame with the R process, I do not want this to happen. (My very clunky workaround so far is to have each code frame split consistently with the R process window shrunk to the lowest amount lines possible. This is workable as it is less 'flashy' then having a constant window splits, but wastes screen space). 

how i want it to work: 
![screenshot from 2019-01-17 15-19-20](https://user-images.githubusercontent.com/10373079/51324858-0853a380-1a6c-11e9-8bb9-7021bd285f4d.png)

what happens: 
![screenshot from 2019-01-17 15-19-44](https://user-images.githubusercontent.com/10373079/51324857-0853a380-1a6c-11e9-8ad1-bd897b096e01.png)

I'm using emacs 26.1.50 on ubuntu 16.04 with ESS 18.10.3 (I have also tried installing ESS through melpa, to no avail). The issue was the same for me on a newly installed VM (Lubuntu 18.10, emacs 25.2.2, ESS 18.10.3), so it seems unlikely that 

I found that my problem sounds identical to https://grokbase.com/t/r/ess-help/1319gq8w1m/ess-error-message-in-r-now-splitting-frame. When I prevent emacs from splitting frames (https://emacs.stackexchange.com/questions/5857/how-to-set-up-emacs-to-never-split-windows), the code buffer will not be split, but switches to the R-process 'as a whole'.

Does anybody have an idea what to do about it? Thanks in advance!

**Comment by jabranham** [comment]
This is a consequence of ESS respecting the `display-buffer` framework. You can read about how to control where buffers are displayer in info: `(info "(emacs) Window Choice")`. It looks like you'd be especially interested in this bit:

```
[...]
   • Otherwise, if the buffer is already displayed in an existing
     window, reuse that window.  Normally, only windows on the selected
     frame are considered, but windows on other frames are also reusable
     if you use the corresponding ‘reusable-frames’ action alist entry
     (*note Action Alists for Buffer Display: (elisp)Buffer Display
     Action Alists.).  See the next step for an example of how to do
     that.

   • Otherwise, optionally create a new frame and display the buffer
     there.  By default, this step is skipped.  To enable it, change the
     value of the option ‘display-buffer-base-action’ (*note Choosing a
     Window for Displaying a Buffer: (elisp)Choosing Window.) as
     follows:

          (customize-set-variable
           'display-buffer-base-action
           '((display-buffer-reuse-window display-buffer-pop-up-frame)
             (reusable-frames . 0)))

     This customization will also try to make the preceding step search
     for a reusable window on all visible or iconified frames.
[...]
```

So it looks like that changing `display-buffer-base-action` is what you want to do. Here's the documentation for what the `reusable-frames` entry does `(info "(elisp) Buffer Display Action Alists")`:

```
‘reusable-frames’
     The value specifies the set of frames to search for a window that
     can be reused because it already displays the buffer.  It can be
     set as follows:

        • ‘nil’ means consider only windows on the selected frame.
          (Actually, the last frame used that is not a minibuffer-only
          frame.)
        • ‘t’ means consider windows on all frames.
        • ‘visible’ means consider windows on all visible frames.
        • 0 means consider windows on all visible or iconified frames.
        • A frame means consider windows on that frame only.

     Note that the meaning of ‘nil’ differs slightly from that of the
     ALL-FRAMES argument to ‘next-window’ (*note Cyclic Window
     Ordering::).

     A major client of this is ‘display-buffer-reuse-window’, but all
     other action functions that try to reuse a window are affected as
     well.
```

**Comment by swhalemwo** [comment]
Great, thank you for the help! changing `display-buffer-base-action` to `display-buffer-use-some-frame` makes ESS handle the errors exactly the way I had in mind. (There's only a minor issue with reading help now though: previously, accessing package documentation (e.g. `?hist`) would split the process frame (which I quite liked); now it opens the documentation in another frame. But i think it's only a matter of getting used to it). Thanks again!

**Comment by jabranham** [comment]
The `display-buffer` framework is super flexible. You can modify `display-buffer-alist` to display help buffers in the same frame. I think there's an example in the file `newfeat.texi`, which you can see in Emacs with `(info "(ess) New features")`.

**Comment by vspinu** [comment]
I don't think using `display-buffer-use-some-frame` is a good default unless you really want  all new buffers to display in a different frame. It's an emacs wide configuration. 

In any case, we need a list of clear configuration instructions for how to achieve the range of old behaviors. We cannot expect that all users could figure the emacs obfuscated display configuration. It's not a trivial task. We could provide a bunch of our own display action functions as well. 

Another consequence of the above-mentioned change is that `C-c C-z` from a script buffer (when `*R*` is not visible) often replaces the current buffer with `*R*` buffer.

**Comment by jabranham** [comment]
There are already examples in `(info "(ess) Customizing startup")`. We can extend those, I suppose?

**Comment by jabranham** [comment]
> Another consequence of the above-mentioned change is that C-c C-z from a script buffer (when *R* is not visible) often replaces the current buffer with *R* buffer.

That's odd, and I don't see that behavior at all (with `display-buffer-alist` as nil). Have you changed any of the display-buffer variables?

**Comment by vspinu** [comment]
This has to do with `display-buffer-in-previous-window`. If you open `*R*` then cover it with an R script buffer, next C-c C-z should cover the script buffer. 

> There are already examples in

I think we need a separate section for those examples. Each time people ask for a pattern we would add an example there. 

For now, how to accomplish the OP's pattern without all intrusive `display-buffer-use-some-frame`? And how to make *R* buffer pop-up in a dedicated frame? Let's at least cover those options which were there before the change.

**Comment by jabranham** [comment]
I have to run now so can't answer fully but I like the idea of a new section for those examples.

> For now, how to accomplish the OP's pattern without all intrusive display-buffer-use-some-frame? 

Customize `display-buffer-alist`: 

```elisp
(add-to-list 'display-buffer-alist
             '("*R"
               (display-buffer-reuse-window display-buffer-pop-up-frame)
               (reusable-frames . 0)))
```

should do the trick but I haven't had time to  check and need to run now.

**Comment by vspinu** [comment]
> This has to do with display-buffer-in-previous-window.

Instead of putting the burden on users to fix this, we should add the second argument `(nil (inhibit-same-window . t))` to `pop-to-buffer` in our [`ess-switch-to-ESS`](https://github.com/emacs-ess/ESS/blob/master/lisp/ess-inf.el#L894) (and maybe other uses).

**Comment by mmaechler** [comment]
I strongly agree with @vspinu and indirectly the OP @swhalemwo that the change (with the current defaults of its customization) differs from decennial old previous behavior, and in some cases is really nonsensical... even if you work with one frame only (and three buffers): I've seen changed behavior for vaguely estimated 2-5 weeks and have been very frustrated the first few time it happened. Scenario  One *.R file buffer, 2 *R* processes (in my case typically *R-devel* and *R* with R 3.5.2).  Now I want to send the same chunk of R code, once to one *R*, then to the other.. of course via switching the buffer-related process (by some key my fingers know butter than my currently tired brain ;-)).  What then happens in some cases, is that I end up in an emacs that displays the two *R* process buffers, but *NOT* the *.R file buffer anymore, even that was exactly the place where I got the chunk of R code sent to the R process buffer... I'm currently too exhausted to describe detailed instruction to reproduce.

**Comment by jabranham** [comment]
OK, I added `inhibit-same-window` in `ess-switch-to-ESS` (which I think should fix your problem, @mmaechler ) and added a new section to the manual with examples. We can add in more examples if/when we get more requests.
