### ISSUE TITLE
In R help buffer, following "links" fails with "." inside links // "ESS help" instead of "R help"

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#836]
Many traditional R functions have a  `.` inside their name, and sometimes S3 methods are also explicitly referenced, e.g.,  (in the *.Rd source)  `\link{plot.default}`.
E.g. after `?png`  I'm interested in the `antialias` argument and that has a link to `X11.options`
when clicking that, I'm lead to the `?X11` help page - quite wrongly.

An other possibly related problem:  If on the  `?scan` help page, pressing `ss` to "skip to" `SEE ALSO`, when I now move the mouse to `read.table` 
I can do `h` (old style), but that only offers `read`
I can do `[RET]` (or mouse-1) and then I am lead to `read.table` (in "contradiction" to what `h` does)
*BUT* the  `read.table` help page now is *not* in "R help" mode, but in "ESS help" mode, and many things do not work at all in that "ESS help"

**Comment by jabranham** [comment]
`x11.Rd` has:

```
\name{x11}
\alias{x11}
\alias{X11}
\alias{X11.options}
```

so showing ?x11 and ?x11.options as the same page is correct I think. Or am I missing something? Seems to work correctly in other pages too. `?plot` has a link to `plot.default`, which takes you to the correct page.

The other bug reported should be fixed in d41b2f9a9462016454b417b25159937dd2f6b7d1

**Comment by mmaechler** [comment]
Hmm, ok, you are right...  though I thought it said it is going to `X11`, not to `X11.options`  and  I thought there were other such examples...   but I may have drawn a wrong conclusion.
I'll see..      Thank you for fixing the other problem
