### ISSUE TITLE
2-buffer situation wrong behavior

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#845]
A bugous situation that I encounter too often, notably when working with more than one R process buffer BUT it  is also easily reproducible (I hope) with just to `foo.R` file buffers and one `*R*` buffer:
```
emacs -f R  f1.R  f2.R
```
(which asks for the directory from where to start and I just type `[Enter]` so it takes "current").
The above ends with two (vertically split) buffers `f1.R` and `f2.R` .. they may well be non-existing files, but I'm almost sure it does not matter.  Point is in the lower buffer, `f2.R`. 
Now I type `1`  and `C-c C-n`  to send that one line to the `*R*` process buffer.

Now what happens is that my *active* script buffer `f2.R` is no longer displayed but rather "replaced" with the `*R*` process buffer  which of course shows the correct
```{r}
> 1
[1] 1
>
```

What should have happened instead is that the two buffer shown should have been the active script buffer and the active (here "the only")  R process buffer should have shown.   This is what had happened for the more than 20 years I've been using S-mode and then ESS ...

Note that this bug more often for me "bites" when I have several R script buffers and several R process buffers... and "of course" most if not all of the R script buffers have a "connected" R process buffer to which they send code chunks when I call one of the `ess-eval-*` functions (via key bindings of course).
Also in such cases I observe very strange behavior,  notably (as above) the script buffer from which I `ess-eval-*` being "replaced" by the (previously) invisible process buffer.

Correct behavior:  in  all `ess-eval-` ((and related)) events,  the two buffer shown should be the active R script buffer + the connected/related R process buffer.

**Comment by jabranham** [comment]
Thanks! Easily reproducible :-)

Should be fixed in 24be86fb92e5c222b68250c4ffa59497fefffed5, try that out and let me know if it isn't.

**Comment by vspinu** [comment]
Deja Vu.. @jabranham Is this the last occurrence of the `display-buffer` that we need to guard against the same window? Would you mind doing a quick grep?

**Comment by mmaechler** [comment]
Yes, thank Alex,  the situation seems sane now..
