### ISSUE TITLE
link fontification in R-help buffers: can we use \alias{} or at least \usage{} to be smarter?

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#847]
Consider `?dwilcox`.
In there, `s v` to jump to the  `Value:` section:  Of course all 4 functions [dpqr]wilcox()  are mentioned;
3 of them are rendered as links (wrongly), and `rwilcox` is not. ... and of course there are many other of such help pages where more than one function / object is documented, and in all those cases there's much too much fontified .. which is confusing, even sometimes for me, and even more if I open help pages for others (including teaching) in order to explain things based on the help page texts...

Now if the \alias{} info could be used, we'd know exactly what is on this page and we should hence not link-fontify...   A cheaper alternative would be to parse the "Usage:" section and typically guess correctly from there which objects are document on the given page....

**Comment by jabranham** [comment]
Yes, this is annoying. I'll work on it.
