### ISSUE TITLE
ess-remote: ‘ess-font-lock-keywords’ must be a symbol of a custom variable

### ISSUE THREAD

**Issue by sjbonner** [emacs-ess/ESS#849]
Hi all,

I haven't used ess-remote for a while, and I'm now encountering an error. After opening a shell, ssh'ing to the remote machine, executing ess-remote, and selecting the dialect as R I get the error: ‘ess-font-lock-keywords’ must be a symbol of a custom variable. I have tried with a blank configuration file to make sure it wasn't a customization error, but the same thing happens.

Here are the details of my system:

- OS: MacOS 10.14.3
- Emacs: 26.1 (9.0)
- ESS: 20190225.127 (loaded via melpa)

Any suggestions appreciated.

Thanks,

Simon

**Comment by jabranham** [comment]
Thanks, should be fixed in git master. Changes usually make their way to MELPA in 4-8 hours.
