### ISSUE TITLE
TAB completion not working 

### ISSUE THREAD

**Issue by AntonioFasano** [emacs-ess/ESS#850]
After the switch to polymode,  TAB completion is not working inside Rnw chunks (both first or second TAB) . My  settings are:

    (setq ess-tab-complete-in-script t)    
    (setq ess-first-tab-never-complete 'symbol) 

Polymode 20190111.1908, ESS: 18.10.3snapshot

**Comment by vspinu** [comment]
This is more appropriate for the pollymode tracker. 

Do you have a running process and it's associated with the buffer? (aka C-c C-z works?).

**Comment by AntonioFasano** [comment]
Yes and to clarify `M-TAB` and `C-M-i` do work, `TAB` does not.   
The former are associated to `complete-symbol` and the latter to `ess-indent-or-complete`.    
Perhaps `ess-indent-or-complete` is now replaced by a new Polymode function or the variables determining its behaviour have changed.

I am still confused about   Polymode and ESS interaction, since the [docs](https://polymode.github.io/installation/) do not cover Rnw configuration. My first thought was to post to Polymode guys, however, I see the R chunks in the Rnw documents use the `ess-r-mode`, which belongs here.

**Comment by vspinu** [comment]
I could reproduce. It was a bug on the ESS side. Thanks!
