### ISSUE TITLE
ess-transcript-mode: [Enter] fails to skip R output lines

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#853]
I've added a `foo.Rout` file with commit 243f6599eb15062804c8f14fee82891260cd6407
where you should quickly notice that one of the most important features of `ess-transcript-mode`, namely the function `ess-transcript-send-command-and-move` which is bound  `[Enter]`   does not work quite anymore as it should:  It no longer "jumps over" R output lines to the next  R prompt line starting with  `> `

**Comment by jabranham** [comment]
Thanks! This should be fixed. I also removed foo.Rout since this is the only thing we used it for, but if you want it left there just let me know and I'll add it back.
