### ISSUE TITLE
lintr >1.0.3 missing

### ISSUE THREAD

**Issue by dkulp2** [emacs-ess/ESS#856]
https://github.com/emacs-ess/ESS/blob/4aad54978a43e914ba69c8863e486b0cf2de5bba/lisp/ess-r-flymake.el#L89

When I try to use flymake, it complains that it needs lintr must be >v1.0.3. I've looked on [CRAN](https://cran.r-project.org/web/packages/lintr/index.html) and [github](https://github.com/jimhester/lintr/tags) and 1.0.3 seems to be the latest version.

**Comment by jabranham** [comment]
That's correct. We rely on lintr features that haven't been released
yet. You can install from github with
devtools::install_github("jimhester/lintr")

Alex
