### ISSUE TITLE
ess-r-versions (extended version set by user) fails if ESS is started by system `site-start`

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#857]
This must be a recent change (well, almost surely):  I have for ages had an extended version of `ess-r-versions` e.g., one  "R-shared"  (as indeed my default versions of self-compiled R are *not* shared), and e.g. have  R-shared-usr  in my PATH , a sym.link going from ~/bin/R-shared-usr  ->   /usr/bin/R   the latter of course *not* a self-compiled version of R.   This has worked till a few days ago .. albeit possibly in an emacs version that ran for a week or so (and hence had used what was "current ESS" when that emacs started).

So  in short:  `R-shared-usr`  works fine in an emacs `*shell*` because  ~/bin of course is in $PATH,
but it is no longer found via   `M-x R-shared-usr`  
.. and yes, I do set `ess-r-versions` before loading ESS...    any ideas ?

It's pretty crippling for me being used to call my many different R-* versions from ESS.

**Comment by jabranham** [comment]
Is `~/bin` in `exec-path`? We also don't make runners for files that return nil for any of the following, so perhaps that's what's wrong?

```elisp
(file-executable-p (expand-file-name "R-shared-usr" "~"))
(not (backup-file-name-p (expand-file-name "R-shared-usr" "~")))
(not (file-directory-p (expand-file-name "R-shared-usr" "~")))
```

**Comment by mmaechler** [comment]
Thank you @jabranham ... all that would have been a problem if it had been one  long ago ... 

I found the solution our IT manages Fedora packages not just at work but also for my laptop and "they" decided unfortunately to install the 'ess'  Fedora package ... even though we had agreed they would not do that...  This is a big PITA: The workaround is to start emacs from a shell explicitly with `--no-site-file`  so my version of ESS is loaded *after* my `~/.emacs` (which sets `ess-r-versions`).     But this really shows how unfortunate the current setup is:  The user must set `ess-r-versions` before ESS is loaded but for > 90% of today's Linux users, they'd install ESS as a package of their distribution (ubuntu, debian, fedora, openSuSe,...) and so that is installed in the system `site-start` directory and startup file and all that loads *before*  `~/.emacs`  and so for all those users,  changing `ess-r-versions` has no effect. 

I'm not closing the report, but have changed the title.  Some of you experienced e-lispers: We probably need a simple or even automatic way to update the S- and R- versions known to the system when ESS "sees" (by occasional checking ?)  that `ess-r-versions` has changed from the value it used when creating the versions...

**Comment by mmaechler** [comment]
In addition:  It is awkward, even "wrong" that the  [ESS]  menu (shown e.g. when you edit an `*.R` file) contains a way to tell ess/emacs to recreate versions, but the [iESS] menu does not have such a possibility, and typically I'd search there more often than in [ESS] .. but I do search the menus for things that are relatively rare, so it's good to have the menus.

**Comment by jabranham** [comment]
Done in #858
