### ISSUE TITLE
ESS does not respect display-buffer-base-action

### ISSUE THREAD

**Issue by antoine-levitt** [emacs-ess/ESS#861]
Related to https://github.com/emacs-ess/ESS/issues/823 and https://github.com/emacs-ess/ESS/issues/816

I have `(setq display-buffer-base-action '(display-buffer-same-window . nil))` in my .emacs because I really like to have everything in full screen. Some time ago ESS started forcing its way into using multiple windows, which I had to disable by redefining manually `ess-switch-to-ESS` to avoid forcing `inhibit-same-window`. I don't know what the rationale behind this change (https://github.com/jabranham/ESS/commit/62e9db36c3a75288dc6e1bcb09bb5291ece595a3) was, but can it be done in a way that is compatible with `display-buffer-base-action`?

**Comment by jabranham** [comment]
Using a separate window for the process buffer has been ESS's default for years. That commit was just fixing ESS to do that again after the switch to the display-buffer framework.

Since user customizations like `display-buffer-base-action` and `display-buffer-alist` get consulted after the ACTION argument of things like `pop-to-buffer`, there's no easy way to override this behavior. 

@vspinu Do you think it makes sense to add a defcustom allowing users to specify not to pass `inhibit-same-window` to these things?

**Comment by antoine-levitt** [comment]
Not sure why, but it definitely worked before (a few months ago)

**Comment by vspinu** [comment]
@antoine-levitt, so you basically use one buffer full screen all the time? That's a pretty peculiar pattern which I have seen only for android developers with really small screens. 

In any case, extra defcustom is an option but it's ugly. @jabranham are you sure there is no other way around?

**Comment by jabranham** [comment]
Sorry, answered this before having coffee this morning.

@antoine-levitt you can override this by specifying that R buffers shouldn't use a different window with something like this:

```elisp
(setq display-buffer-alist '(("R" . ((display-buffer-same-window) (inhibit-same-window . nil)))))
```

Let me know if that works for you and I'll add it as an example in the new display-buffer manual section.

**Comment by antoine-levitt** [comment]
Yup. Either I code or I REPL, but I don't need to have both open at the same time. I have very efficient keybindings for cycling between buffers (two-keys chords for displaying the previous, the previous previous, and the previous previous previous buffers) and I find it pretty convenient. The only place in my emacs config that has multiple windows is mu4e for mail. I don't know how common it is, but I like it :-)

**Comment by jabranham** [comment]
Actually, you'd need to specify that R files shouldn't open a new window either:

```elisp
(setq display-buffer-alist
      '(("*R" . ((display-buffer-same-window) (inhibit-same-window . nil)))
        ("\\.R$" . ((display-buffer-same-window) (inhibit-same-window . nil)))))
```

**Comment by antoine-levitt** [comment]
Yup, that works.
