### ISSUE TITLE
Error on M-x R

### ISSUE THREAD

**Issue by pooyahub** [emacs-ess/ESS#862]
Hi, After installing the latest release of ESS from MELPA today (2019-03-13) I cannot start an ESS process by typing `M-x R` and hitting ENTER.  I get the following message:
`cl-generic-ensure-function: ess-build-load-command is already defined as something else than a generic function
`
Any help would be appreciated.

**Comment by jabranham** [comment]
You've got an older version of ESS installed somehow. Delete `~/.emacs.d/elpa/ess-*` and uninstall any distro-provided ess, then reinstall from MELPA.

**Comment by pooyahub** [comment]
Solved.  Thanks!  You were right I had installed a distro-provided ess.
