### ISSUE TITLE
company for julia won't stop opening new julia backend

### ISSUE THREAD

**Issue by dsweber2** [emacs-ess/ESS#863]
I'm getting very intermittent support from company; often I will enter `company-mode` on a julia file, and it will work wonderfully. Then eventually (I'm not sure of a trigger) it will stop working, and literally every letter I type will try to launch julia again. If I let it launch in this case, it continues to try to spawn new backends until I leave company-mode. Each of those repls works just fine when I enter commands by hand. I'm running emacs as a server and using it remotely, if that matters at all.

 I installed via the melpa (Specifically, I've set melpa to http://melpa.milkbox.net/packages/).
ess version:  `18.10.3snapshot [git: cc1a2e1cacb2f387ecef7065b04860b1ad569157]`
emacs version: 25.2.2
OS: ubuntu 18.04.2
ess directly relevant lines in my .emacs file (may be others, there's a lot in there):
```
(require 'julia-repl) 
(add-hook 'julia-mode-hook 'julia-repl-mode) ;; always use minor mode
(setq julia-repl-executable-records
      '((default "/home/dsweber/julia-1.1.0/bin/julia"))) 
(setq inferior-julia-program-name "/home/dsweber/julia-1.1.0/bin/julia") 
```

**Comment by jabranham** [comment]
Also, what is the value of `major-mode` and `company-backends` in julia mode buffers where you experience this behavior?

**Comment by dsweber2** [comment]
it still happens when I've removed the julia-repl lines. Taking out `setq inferior...` just switched julia to the system version
`major-mode`: `ess-julia-mode`
`company-backends`: 
```
(company-ess-julia-objects
 (company-auctex-macros company-auctex-symbols company-auctex-environments)
 company-auctex-bibs company-auctex-labels company-dict company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-files
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-oddmuse company-dabbrev julia)
```
However, `company-backend` has value `nil` throughout, if that's relevant.

**Comment by jabranham** [comment]
Am I seeing that right that `julia` is an element of `company-backends`? I'm not a company user, but that seems like it's likely to be problematic. ESS only adds `company-ess-julia-objects` to company-backends`. Can you figure out how `julia` gets added?

**Comment by vspinu** [comment]
@jabranham 
> I'm not a company user, 

But what do you use instead?

**Comment by dsweber2** [comment]
It was in my .emacs file, a bit further down. When I removed it, company stopped working for julia period, and appears like it's not starting a backend. The `major-mode` and `company-backends` are otherwise the same (minus the `julia` in `company-backends`, obviously). @vspinu I assume you have company-mode working for julia? Is there anything obvious that I'm missing?

**Comment by dsweber2** [comment]
Actually, having tried launching julia by hand afterwards using `ess-eval-line`, it seems to be functional and stable

**Comment by vspinu** [comment]
I am not using julia, nor having bandwidth to figure out the setup ATM. Sorry. Hopefully Alex could squeeze a fix.

**Comment by jabranham** [comment]
>> I'm not a company user,

> But what do you use instead?

Just Emacs's built-in completion.

@dsweber2 company completion won't work unless there's a running inferior julia process, so I think it's working as expected now. Closing this, let me know if you still have an issue.
