### ISSUE TITLE
ESS inserts assign (<-) when opening newlines and files

### ISSUE THREAD

**Issue by GregorySchwartz** [emacs-ess/ESS#864]
Whenever I open an R file a "<-" is inserted into the first line of the document. Furthermore, `evil-open-below` automatically inserts a "<-" at the newline. Am I missing the options for these features and can they be better documented so I can disable them?

**Comment by jabranham** [comment]
This is almost assuredly not an ESS bug. Can you reproduce it from emacs -q loading only ESS?

**Comment by vspinu** [comment]
:) Never heard of it either. Maybe some document skeleton went bonkers.

**Comment by GregorySchwartz** [comment]
Nevermind, was an issue with setting `ess-smart-S-assign` to `nil` as a hook, which is no longer needed.
