### ISSUE TITLE
display-buffer quirk: `*R*` shown *twice* after restart

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#867]
Another quirk since our switch to use Emacs  display-buffer thoroughly:

Inside `*R*`, I do often kill R and restart it very quickly {I told ESS to call R with "--no-save" so it does not ask me}: 

 -  `C-c C-q`  calls `q("no")`  [for me]
-  `M-x R`    would restart R ... and it does,

*but* since our switch to use display-buffer , in that case I now get *twice* the same `*R*`  buffer (with the newly started R process) displayed in my Emacs  [2 buffers on top of each other].  This not only happens when before the restart `*R*` was the only visible buffer, but *even* and that is really a pain when I already had two buffers, say an ESS one `foofile.R` and the iESS `*R*`.  After restaring, the `fooFile.R` buffer is replaced [in display] by one of the two `*R*` buffers.

**Comment by mmaechler** [comment]
Further investigation shows:  

- `C-c C-q`, i.e., `(ess-quit)`  alone is the culprit: It leaves two identical `*R*`  buffers displayed.
- Inside there, it's `(ess-cleanup)`  called from `(ess-quite--override *)` which is the culprit: It does call `(display-buffer *)` in a way that's not correct in this case.   This is a relatively recent (Feb.22 ) change b2778ed23

**Comment by lionel-** [comment]
I have noticed this issue too.

**Comment by jabranham** [comment]
I'll take a look at this this weekend or early next week (unless someone
beats me to it)

**Comment by mmaechler** [comment]
As I found that  `(ess-cleanup)` was really only called from (the two versions of) `(ess-quit--override)`, I've simply reverted *that* small part of b2778ed.
