### ISSUE TITLE
ess-reload no longer reloads the inferior in the same buffer

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#869]
Since this change: https://github.com/emacs-ess/ESS/commit/b7372144b20cc7d5ebe18051fa96833f77b95e8f

**Comment by lionel-** [comment]
This fixes it, but I'm not sure why this makes a difference:

```diff
--- a/lisp/ess-r-mode.el
+++ b/lisp/ess-r-mode.el
@@ -1354,8 +1354,10 @@ selected (see `ess-r-set-evaluation-env')."
         (sprocess (ess-get-process ess-current-process-name)))
     (when (not sprocess) (error "No ESS process running"))
     (ess-cleanup)
-    (goto-char (marker-position (process-mark sprocess)))
-    (ess-send-string sprocess cmd t)))
+    (with-current-buffer (process-buffer sprocess)
+      (goto-char (marker-position (process-mark sprocess)))
+      (insert cmd)
+      (process-send-string sprocess cmd))))
 
 (defcustom inferior-ess-r-reload-hook nil
   "Hook run when reloading the R inferior buffer."
```

But this would then reopen https://github.com/emacs-ess/ESS/issues/771

Reloading R is crucial in any dev workflows to erase the interactive state, so I think it's more important that `ess-reload` works correctly than `ess-quit`.

Do people use `ess-quit` to save the workspace?

**Comment by lionel-** [comment]
Turning off visibility fixes it as well:

```diff
--- a/lisp/ess-r-mode.el
+++ b/lisp/ess-r-mode.el
@@ -1354,7 +1354,7 @@ selected (see `ess-r-set-evaluation-env')."
         (sprocess (ess-get-process ess-current-process-name)))
     (when (not sprocess) (error "No ESS process running"))
     (ess-cleanup)
-    (ess-send-string sprocess cmd t)))
+    (ess-send-string sprocess cmd nil)))
 
 (defcustom inferior-ess-r-reload-hook nil
   "Hook run when reloading the R inferior buffer."
```

**Comment by lionel-** [comment]
That's actually from https://github.com/emacs-ess/ESS/commit/4a50719ca81abc82bfab4317718f70bfa08a79c1

**Comment by mmaechler** [comment]
I've never noticed we have that - it's `inferior-ess-reload` btw  and its help says


> inferior-ess-reload is an interactive compiled Lisp function in ‘ess-inf.el’.
> It is bound to C-c C-e r, C-c C-e C-r.
> 
> (inferior-ess-reload &optional START-ARGS)
> 
> Reload the inferior process.
> START-ARGS gets passed to the dialect-specific
> ‘inferior-ess-reload-override’.

Note that it is *not* on the iESS menu so people will also not detect it easily (`ess-quit` *is* there).

However, there's another much graver problem with the current implementation:
It does *not* do what it promises.  When you run any version of R (and you know I have 100s), independently of the version of R the process runs, it will simply call "R" (M-x R)... something which is very often wrong for me.  If I run  `M-x R-3.5.0`  I want to restart that; if I run `M-x R-devel`  I want to restart that .. etc etc

**Comment by lionel-** [comment]
Do we have the runner information stored in the process buffer?
