### ISSUE TITLE
Inferior reloading always uses default runner

### ISSUE THREAD

**Issue by lionel-** [emacs-ess/ESS#871]
From @mmaechler https://github.com/emacs-ess/ESS/issues/869#issuecomment-474791774

To fix this we'd need to have the `inferior-ess-r-program` variable used to start the inferior stored in the process buffer.

**Comment by vspinu** [comment]
Not just that. Also the entire parameter list as it could be started with C-u.

**Comment by lionel-** [comment]
Good point.

**Comment by mmaechler** [comment]
Good points indeed.  Still should be fairly easily feasible, wouldn't it?

**Comment by lionel-** [comment]
Should also reuse inferior name.

**Comment by jabranham** [comment]
Can we just do something like this for the runner name? 

```diff
diff --git a/lisp/ess-mode.el b/lisp/ess-mode.el
index eb1fcf3c..b1e54d45 100644
--- a/lisp/ess-mode.el
+++ b/lisp/ess-mode.el
@@ -668,7 +668,8 @@ Function defined using `ess-define-runner'."
             (cond ((string= dialect "R")
                    (let ((inferior-ess-r-program (or path name)))
                      (require 'ess-r-mode)
-                     (run-ess-r start-args)))
+                     (run-ess-r start-args)
+                     (setq-local inferior-ess-r-program inferior-ess-r-program)))
                   ((string= dialect "S")
                    (let ((inferior-S+-program (or path name)))
                      (require 'ess-sp6-d)
```

I'm not sure we need to save the parameter list; we don't do this for M-x R do we?

**Comment by lionel-** [comment]
yup I was planning to do something like this.

I think it makes sense to save the parameter list though. I'm not sure what you mean about `M-x R`.

**Comment by mmaechler** [comment]
If I use  `C-u M-x R-3.5.0`   and then specify extra command line arguments to R, say "--no-save",  we'd want  the "restart R" to use those (and not ask the user again about them).
... or did I misunderstand what you were asking?

**Comment by jabranham** [comment]
Hmm... apparently I wasn't clear. I meant if you do `C-u M-x run-ess-r` and add some command line argument, then later restart that R, we don't re-apply that argument.

In other words, R's started via the runners and R started with run-ess-r should behave the same from the user's point of view. 

Is that clearer?

**Comment by lionel-** [comment]
hmm, maybe I'm still missing something, but I would expect we reapply the arguments specified by the user on startup.

**Comment by jabranham** [comment]
We don't currently though, not even for `run-ess-r` (which is how I imagine most users start R since it's the default). That's my only point :-) If we change it so that the runners reapply given arguments, we should update `run-ess-r` to do that as well.

**Comment by lionel-** [comment]
yup the mechanism will be general, PR incoming.

**Comment by mmaechler** [comment]
Great - thank you! --- confirmed working correctly for me, e.g., with  `M-x R-2.11.1`
