### ISSUE TITLE
Typos in the documentation

### ISSUE THREAD

**Issue by cobac** [emacs-ess/ESS#872]
[Here](https://github.com/emacs-ess/ESS/blob/d76f79418d0063d5dd338c0e1d274fc696f9f8d8/doc/ess.texi#L2246) *controls when completion is allowed* is repeated twice.
[Here ](https://github.com/emacs-ess/ESS/blob/d76f79418d0063d5dd338c0e1d274fc696f9f8d8/doc/ess.texi#L186) *something* is repeated twice.
______

Hello,
I am very new to contributing to projects via github. Should I rather submit pull requests with the corrections instead of opening issues?
Thank you everyone for your work.

**Comment by mmaechler** [comment]
Thank you @cobac for the report!

**Comment by cobac** [comment]
Only the first typo was fixed.

[Here ](https://github.com/emacs-ess/ESS/blob/8dd4353734b7f8d1460f68f2afd3974542619c00/doc/ess.texi#L186) *something* is still repeated twice.

**Comment by jabranham** [comment]
Fixed, thanks!
