### ISSUE TITLE
transcript mode -- now suddenly adds to bottom of file, instead of to *R* session buffer

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#877]
I just embarrassed myself quite a bit in front of my students in class (teaching mixed effects models):

I had prepared a `*.Rout` file  and wanted to go from "command to command"  using `[Enter]`.
This was completely destroyed because the result was *inserted* at the bottom and the next `[Enter]` was completley useless. 

Somebody must have changed a very crucial default behavior here.  *PLEASE* don't do that to us long time users!   .

**Comment by jabranham** [comment]
I don't see this. Is enter for you bound to `ess-transcript-send-command-and-move`?

**Comment by jabranham** [comment]
I just committed a fix for this function, hopefully it takes care of any oddities you've experienced.
