### ISSUE TITLE
Support for sweave files missing

### ISSUE THREAD

**Issue by tmalsburg** [emacs-ess/ESS#894]
The documentation on the project page ([section 11.13](https://ess.r-project.org/Manual/ess.html#Sweave-and-AUCTeX)) lists a number of functions that can be used when working with `.Rnw` files.  However, these functions are not loaded by default and only contained in `list/obsolete/`.  The MELPA package for ESS doesn't contain them at all (as of late).  This is a mismatch of documentation and code that should be resolved.

* Solution 1: Reinstate these functions such that they can be used as described in the documentation.  
* Solution 2: Remove these functions from the documentation.

I'm strongly in favor of the first solution. First, these functions are useful and work really well in my experience.  I see no reason to remove perfectly good code.  Second, the alternatives suggested in the documentation are very unsatisfying and in my experience much inferior.  Polymode is incredibly slow and unstable, especially when used with evil-mode, and markdown-mode obviously doesn't work with `.Rnw` files.

**Comment by lionel-** [comment]
Solution 3: Extract it in a separate package that is easier to contribute to, and potentially find a new maintainer. It could be distributed with ESS+.

>  I see no reason to remove perfectly good code.

This perfectly good code was not perfect, and unmaintained. Look at all the longstanding bugs that were closed:

https://github.com/emacs-ess/ESS/commit/e49611d36084596155e23f249ab5bf664f946b3b#diff-8428bd54fea74bb43087c3139fac03d3

**Comment by lionel-** [comment]
hmm was there also a copyright issue Alex? Extracting into a new package emacs-ess/essweave would solve this as well.

**Comment by tmalsburg** [comment]
Distributing it as a package of it's own would be great!  However, as long as that hasn't happened, I think the code should remain part of ESS, especially since all these bugs that you're referring to are apparently closed now.  I've been using this code for years and didn't have any problems.  Polymode is really not an option for me, so this is the only way I can do literate programming with R an LaTeX in Emacs.

**Comment by lionel-** [comment]
They're only closed because we have obsoleted sweave (and noweb), not because they have been fixed. Extracting into a package shouldn't be too difficult and can be done before the 19.04 release.

> Although, personally, I see this as a core functionality of ESS

It's not generic and only relevant to R so it isn't a core ESS functionality. It's more like a satellite of the R mode.

**Comment by tmalsburg** [comment]
I see.  New package sounds good.  The other remaining issue is then to fix the documentation.

**Comment by tmalsburg** [comment]
I'm not a GitHub power user but if there was a way to transfer the issues referenced in the commit above to the new package's repo that would be great.

**Comment by lionel-** [comment]
yup, there's a beta functionality for this

**Comment by mmaechler** [comment]
I agree with @tmalsburg that these functions should come back into being easily available  as long as there's not a better alternative ... and there isn't  for his use case (and I'd say for my use case, too; haven't recently used *.Rnw in ESS, but once I tried was shocked how little (nothing?) was possible with polymode for `*.[RS]nw`

**Comment by mmaechler** [comment]
(I *was* a bit unhappy with our closing of the issues.  Couldn't you mark an issue as "we will not address this ourselves"    and keep it open?)

**Comment by jabranham** [comment]
Right, the ess-sweave stuff does some pretty unforgivable things. I think spinning it out into another package makes sense. It can live under emacs-ess/ess-sweave and we can try to transfer the issues there.

**Comment by jabranham** [comment]
@vspinu @mmaechler is everyone on board with spinning the sweave files out into a separate package? If so, I should have time tomorrow or Friday to do so.

**Comment by vspinu** [comment]
Are we talking here about spliting the entire ess-noweb or only those 4 commands which generate pdf files? If the former I am against it because there will be always users installing both ess-noweb and polymode and running in all sort of conflicts. But, well if people want to maintain that monster, fine by me. 

If latter, ok, but it cannot get into ESS+ because of the conflicting shortcuts with polymode. Alternatively, one can add an integration of the old functionality into polymode from ESS or I can add those to polymode proper and make a user switch `poly-r-enable-ess-exporters` to enable those. 

> Polymode is incredibly slow and unstable, especially when used with evil-mode, and markdown-mode obviously doesn't work with .Rnw files.

None of this is true.  When was the last time you tried polymode? Judging from what you say, you don't even know that poly-r does provide a perfectly healthy mode for Rnw files, which is, btw, orders of magnitude faster and with more features than the old ess-noweb.

**Comment by vspinu** [comment]
>  haven't recently used *.Rnw in ESS, but once I tried was shocked how little (nothing?) was possible with polymode for *.[RS]nw

@mmaechler you keep posting such poignant comments since forever and I keep asking you, what do you want exactly, and what is missing more concretely? Is it missing or you just didn't get how it works? The available functionality is [documented](https://polymode.github.io/usage/) and if something is missing, please open a request and it will be added in due time if it make sense.

**Comment by jabranham** [comment]
> If the former I am against it because there will be always users installing both ess-noweb and polymode and running in all sort of conflicts.

How was this handled when ESS provided this and polymode did too? Surely the situation would be the same?

**Comment by vspinu** [comment]
It was handled by me trying to figure out if they use polymode or ess-noweb. 

I am against maintaining the relic, it's an unnecessary burden on us and potentially on other package maintainers which will be suffering when users will report obscure bugs.  MELPA has a thorough review process with high standards. People don't want junk there, and surely we don't want to be responsible for one.

**Comment by tmalsburg** [comment]
> None of this is true.

@vspinu please don't take my criticism of polymode personally.  I really appreciate your work on it.  However, please understand that writing large and complex `.Rnw` documents is a central part of my job.  Trust me, if there was a better solution than this old ESS code, I would switch immediately because I simply cannot afford to waste any time when writing articles.

>  When was the last time you tried polymode? 

I have tried polymode multiple times over the years because it looks like a super neat idea and very promising.  However, every single time I ran into serious issues.  Last time I tested it was three weeks ago together with a colleague in his vanilla Spacemacs setup.  Emacs behaved erratically in .Rmd documents and only there (we haven't tried .Rnw but I suspect it would have been the same).  We didn't have the time to track down what was causing these problems but concluded that polymode didn't work well with evil-mode because the problems were gone when we switched off either polymode or evil-mode.  I think one problem may be that evil states are not synchronized properly across chucks.  Not sure.

As much as I'd like to use polymode, I just cannot afford to spend time tracking down and reporting bugs.  This is not a hobby for me but work and I'm often on a tight schedule.   The code in ess-swv.el and ess-noweb.el may not be perfect and it may also not be the future, but for the being it's the only solution that the job done for me.

**Comment by tmalsburg** [comment]
I just tried polymode in my setup (with poly-noweb and poly-R) and  things have apparently improved.  So far no weird interactions with evil-mode.  However, weaving does not work properly.  See [polymode/polymode/#221](https://github.com/polymode/polymode/issues/221).

**Comment by vspinu** [comment]
As far as I know people are using polymode with evil/spacemacs successfully. The most recent issue was that the undo-tree was not behaving (polymode/polymode#214), but it seems to be fixed now. 

> @vspinu please don't take my criticism of polymode personally. 

I am not. It's just that I am not using polymode on daily basis myself and I rely exclusively on people reporting issues. So when I know that there are no major issues (and currently there are not) and someone suddenly complains that nothing works, it comes as a big surprise. 

> However, please understand that writing large and complex .Rnw documents is a central part of my job. 

There have been major improvements on speed a month or so ago. Working with huge documents and thousands of chunks should be a breeze. 

>  (we haven't tried .Rnw but I suspect it would have been the same

Markdown is way more complex than latex mode, so chances that Rnw works is way higher.

**Comment by jabranham** [comment]
> It was handled by me trying to figure out if they use polymode or ess-noweb.

Well that sounds not fun at all :-)

Anyway, to get this issue back to the original report: How do we want to deal with the sweave files? I think the options brought up here are (in no particular order):

- Remove them just from ESS from MELPA, this is the status quo
- Remove them
- Update the MELPA recipe to include them
- Distribute them as a separate package

Did I miss anything?

**Comment by slyrus** [comment]
> I am not. It's just that I am not using polymode on daily basis myself and I rely exclusively on people reporting issues. So when I know that there are no major issues (and currently there are not) and someone suddenly complains that nothing works, it comes as a big surprise.

Wait, you're not using polymode on a daily basis? Are there other maintainers who are?

**Comment by vspinu** [comment]
>  Are there other maintainers who are?

No. This is why it's very important to report bugs and UI requests on your side. There were instances when an obvious UI bug was lurking for months till I accidentally noticed it.

**Comment by mmaechler** [comment]
Given all the above, I tend to agree with @vspinu.  Fixing the MELPA recipe so `ess-noweb` remains there available and usable ... and keeping the `obsolete/*` complication [a change which still somehow mixes up 'make': it always remake 3 of the obsolete/*.elc unnecessarily]  as a signal that we don't want to invest more maintainer time into ess-noweb seems a very good solution to me.

**Comment by tmalsburg** [comment]
FWIW, I agree as well.

**Comment by jabranham** [comment]
Assume no one objects, I'll submit this patch tomorrow to the MELPA folks:

``` diff
diff --git a/recipes/ess b/recipes/ess
index 1921e1bc..f0022b2e 100644
--- a/recipes/ess
+++ b/recipes/ess
@@ -4,5 +4,5 @@
  :files ("*.el" "lisp/*.el"
          "doc/*.texi" "doc/info/dir"
          ("etc" "etc/*")
-         ("obsolete" "obsolete/*.el")
+         ("obsolete" "lisp/obsolete/*")
          (:exclude "etc/other")))
```

**Comment by vspinu** [comment]
looks right. Thanks.

**Comment by jabranham** [comment]
Should be fixed next MELPA update.

**Comment by izmirlig** [comment]
First of all, kudos to all of you for your sustained hard work!!! I landed upon this because I was looking for a workaround. In the interests of others like me, I hope it is alright with you if I post THIS FIX which worked:

add to .emacs-- done!

(use-package poly-R :ensure t)
