### ISSUE TITLE
inferior R use .history, not .Rhistory in Window 10

### ISSUE THREAD

**Issue by ShuguangSun** [emacs-ess/ESS#897]
When I start R, it reads and writes .history as history file, instead of .Rhistory
comint-input-ring-file-name in the inferior R buffer is ".../.history".
If I run the code below, it gets ".Rhistory". It seems the ess-dialect not correctly set before the comint-input-ring-file-name.
```elisp
(expand-file-name (if (eql t ess-history-file)
                                (concat "." ess-dialect "history")
                              ess-history-file)
                            ess-history-directory)
```

R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 15063)

**Comment by lionel-** [comment]
`ess-dialect` is sometimes `nil` since the switch to major modes but I haven't been able to pinpoint exactly when with a reproducible example.

**Comment by jabranham** [comment]
@ShuguangSun how do you start R? `M-x R`?

**Comment by ShuguangSun** [comment]
> 
> 
> @ShuguangSun how do you start R? `M-x R`?

Yes. `M-x R`

**Comment by ShuguangSun** [comment]
It read .Rhistory now.
