### ISSUE TITLE
Find the newest version of R available

### ISSUE THREAD

**Issue by AntonioFasano** [emacs-ess/ESS#903]
The function `R-newest`, intended to interactively find and run the newest version of R available, fails for me.

One likely cause is that `R-newest` is based on:

    (defun ess-find-newest-R ()
      "...omitted"
      (or ess-newest-R
          (message "Finding all versions of R on your system...")
          (setq ess-newest-R
                (ess-newest-r
                 (if ess-microsoft-p
                     (ess-rterm-prefer-higher-bit)
                   (add-to-list 'ess-r-created-runners
                                inferior-ess-r-program))))))

Since `(message "Finding...")` is always true, the remaining code is unreachable.  

ess-r-mode.el   
ess-version: 18.10.3snapshot [elpa: 20190422.1553]

**Comment by jabranham** [comment]
Thanks for the report, should be fixed.
