### ISSUE TITLE
[Feature Request] Rd mode font lock / syntax highlighting

### ISSUE THREAD

**Issue by eddelbuettel** [emacs-ess/ESS#906]
Every other mode ESS knows about gets color, this one doesn't. I think it should too.

**Comment by jabranham** [comment]
I'm not sure I understand. Rd-mode should be font-locked (and is for me). Are you saying everything in an Rd buffer gets the `default` face for you? If so, can you let me know the value of font-lock-defaults? It should be `(Rd-font-lock-keywords nil nil)`

**Comment by eddelbuettel** [comment]
I happned to have upgrade ess from melpa yesterday -- the new version does it indeed.  
My old one did not.  Never mind then,
