### ISSUE TITLE
indentation of basic if-else broken

### ISSUE THREAD

**Issue by vspinu** [emacs-ess/ESS#911]
```R
x <-
  if (a) b
else c
```

I am very surprised this doesn't pop in our tests. Do you see this?

**Comment by lionel-** [comment]
Isn't this https://github.com/emacs-ess/ESS/issues/520

**Comment by vspinu** [comment]
Indeed. I know we discussed and I actually thought it was fixed in code, rather than in my config.

The difference now is that `  (setq ess-align-blocks '(control-flow))` in ess-mode-hook is no longer taking effect. It's reset to buffer local `nil`.

**Comment by lionel-** [comment]
oh probably an effect of the switch to major modes. But shouldn't local variables be reset _before_ initialising the mode hierarchy? I'll try and take a look this week, hopefully it's an easy fix.

**Comment by vspinu** [comment]
Yes they should. The unclear part here is why that local variable creeps in in the first place, and why setting it in the hook which should run at the end is not taking effect.

**Comment by vspinu** [comment]
@jabranham, this is it indeed. How about the following trick. We have a buffer local ess--installed-style which we check when our indentation functions are called. If it differs from ess-style we install the style. No need to do buffer-local ess-style then, I guess.

**Comment by jabranham** [comment]
The buffer-local ess-style is necessary so that e.g. `.dir-locals` has effects, though, right? Or am I missing something?

**Comment by vspinu** [comment]
I would think that hack-local-variables would make it local anyhow. Not a big deal anyhow. The advantages of not setting it buffer-locally are minimal, but we could try.
