### ISSUE TITLE
loop ess-r-mode

### ISSUE THREAD

**Issue by Krisselack** [emacs-ess/ESS#912]
When trying to open a .R-file on windows7, it wont be recognised as such.
Running M-x R opens R without any issues.
Path to R was set properly in .emacs. However, R is not in the system path, as it is in user/documents/R (default install location) and I do not possess admin-privileges.

I use GNU Emacs 26.2 (build 1, x86_64-w64-mingw32) of 2019-04-13 from Goulet https://vigou3.gitlab.io/emacs-modified-windows/. 

The issue was also created here: https://gitlab.com/vigou3/emacs-modified-windows/issues/14

```
Compiling file c:/Users/xyc/.emacs.d/elpa/ess-20190506.1504/ess-help.el at Thu May  9 09:11:59 2019
ess-help.el:41:13:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode

Compiling file c:/Users/xyz/emacs.d/elpa/ess-20190506.1504/ess-inf.el at Thu May  9 09:12:00 2019
ess-inf.el:38:13:Error: Symbol’s chain of function indirections contains a loop: ess-r-mode
```

**Comment by jabranham** [comment]
You can get this error when you have ESS installed in two locations. Have you installed it both from Vincent's distribution and from MELPA?

**Comment by Krisselack** [comment]
Thanks a lot. Reinstalled emacs (without ess from melpa), now it works without a problem! After not finding R first I tinkered around a little bit and apparently installed melpa-ess....
