### ISSUE TITLE
Can't load package

### ISSUE THREAD

**Issue by JianleiZhang** [emacs-ess/ESS#917]
A error occurred when type 'M-x R RET'.

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-directory-p(nil)
  byte-code("\302\303\304\305\306\307\310\311\310\312&\011\210\302\313\304\314\306\303\315\316&\007\210\302\317\304\320\306\303\315\316&\007\210\302\321\304\322\306\303\315\316&\007\210\302\323\304\324\306\303\315\316&\007\210\302\325\304\326\306\303\315\316&\007\210\302\327\304\330\306\303\315\316&\007\210\302\331\304\332\306\327\315\316&\007\210\302\333\304\334\306\327\315\316&\007\210\302\335\304\336\306\303\315\337&\007\210\302\340\304\341\306\303\315\316&\007\210\302\342\304\343\306\303\315\316&\007\210\302\344\304\345\306\303\306\346\306\347\315\316\306\350&\015\210\302\347\304\351\306\303\315\316&\007\210\302\352\304\353\306\303\306\354\315\316&\011\210\355\300\356\357\360DD\361\306\303\362\363\364\365&\011\210\355\301\356\357\366DD\367\306\303\362\363\364\370&\011\210\371\372\010\"\210\371\372\373\374\375\010\"!\"\210\376\011!\204\365\0\377\303\201@\0\201A\0\011\"\201B\0#\210\355\201C\0\356\357\201D\0\ DD\201E\0\306\303\362\201F\0&\007\210\355\201G\0\356\357\201H\0\ DD\201I\0\306\303\362\201F\0&\007\210\355\201J\0\356\357\201K\0\ DD\201L\0\306\303\362\201F\0\364\201M\0&\011\210\355\201N\0\356\357\201O\0\ DD\201P\0\306\303\362\201Q\0\364\201R\0&\011\210\355\201S\0\356\357\201T\0\ DD\201U\0\306\303\362\201V\0&\007\207" [ess-lisp-directory ess-etc-directory custom-declare-group ess nil "ESS: Emacs Speaks Statistics." :group languages :link (info-link "(ESS)") (url-link "https://ess.r-project.org/") ess-edit "ESS: editing behavior, including coments/indentation." :prefix "ess-" ess-proc "ESS: process control." ess-command "ESS: Commands for various things." ess-help "ESS: help functions." ess-hooks "ESS: hooks for customization." ess-S "ESS: S Languages." ess-SPLUS "ESS: S-PLUS Dialect of S." ess-R "ESS: R Dialect of S." ess-Julia "ESS: Julia." "julia-" ess-sas "ESS: SAS." ess-Stata "ESS: Stata." ess-roxy "Mode for editing in-code Roxygen documentation." convenience ess-extras tools "Extra utilities for ESS" ess-faces "Faces and face options for ESS modes." faces custom-declare-variable funcall function #f(compiled-function () #<bytecode 0x13a286d>) "Directory containing ess-site.el(c) and other ESS Lisp files." ...] 14)
  require(ess-custom)
  byte-code("\300\301!\210\300\302!\210\300\303!\207" [require cl-lib comint ess-custom] 2)
  require(ess-utils)
  require(ess)
  byte-code("\300\301!\210\300\302!\210\303\304\305\306\307DD\310\311\312\313\314&\007\207" [require ess ess-inf custom-declare-variable ess-mode-hook funcall function #f(compiled-function () #<bytecode 0x13ca0e5>) "Hook for customizing ESS each time it is entered." :group ess-hooks :type hook] 8)
  require(ess-mode)
  byte-code("\303\304!\210\303\305!\210\303\306!\210\303\307!\210\303\310!\210\303\311!\210\303\312!\210\303\313!\210\303\314!\210\303\315!\210\303\316!\210\010\317Y\2036\0\303\320!\210\321\322\323\324#\210\325\324\031\211\032\203b\0\n@\021\322\011N\203[\0\323\011N\204[\0\326\323\011\322\011N#\210\nA\211\022\204D\0*\327\322\323\330#\210\331\323\324\332\333\334\335\336\337\340&\011\210\321\341\342\324#\210\325\324\031\211\032\203\242\0\n@\021\341\011N\203\233\0\342\011N\204\233\0\326\342\011\341\011N#\210\nA\211\022\204\204\0*\327\341\342\343#\210\331\342\344\345\337\340\335\346\347\350\351\352&\013\207" [emacs-major-version prop --dolist-tail-- require cl-lib compile ess-mode ess-help ess-s-lang ess-roxy ess-r-completion ess-r-syntax ess-r-package ess-trns ess-r-xref 26 ess-r-flymake defvaralias R-mode-hook ess-r-mode-hook nil (saved-value saved-variable-comment) put make-obsolete-variable "19.04" custom-declare-variable "Hook run when entering `ess-r-mode'." :options (electric-layout-local-mode) :type hook :group ess-R ess-r-versions ess-r-runner-prefixes "ESS 19.04" (let ((r-ver (quote ("R-1" "R-2" "R-3" "R-devel" "R-patched")))) (if (eq system-type (quote darwin)) (append r-ver (quote ("R32" "R64"))) r-ver)) "List of partial strings for versions of R to access within ESS.\nEach string specifies the start of a filename. If a filename\nbeginning with one of these strings is found on variable\n`exec-path', a command for that version of R is made available.\nFor example, if the file \"R-1.8.1\" is found and this variable\nincludes the string \"R-1\", a function called `R-1.8.1' will be\navailable to run that version of R. If duplicate versions of the\nsame program are found (which happens if the same path is listed\non variable `exec-path' more than once), they are ignored by\ncalling `delete-dups'. Set this variable to nil to disable\nsearching for other versions of R. Setting this variable directly\ndoes not take effect; use either \\[customize-option] or set the\nvalue by using `ess-r-runners-reset'." (repeat string) :set ess-r-runners-reset :initialize custom-initialize-default] 13)
  autoload-do-load((autoload "ess/lisp/ess-r-mode" ("/home/jlzhang/.emacs.d/el-get/.loaddefs.elc" . 38315) t nil) R)
  command-execute(R record)
  execute-extended-command(nil "R" "R")
  funcall-interactively(execute-extended-command nil "R" "R")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by jabranham** [comment]
How did you install ESS (from MELPA, a disto package, from source, etc)?

**Comment by JianleiZhang** [comment]
(el-get-bundle ess)
install ESS by el-get.
sorry for my english.

**Comment by jabranham** [comment]
I'm not familiar with el-get. ESS expects the etc directory to be set relative to the lisp directory. Can you take a look at where the etc directory is on your checkout? I think our auto-detection is failing on your machine:

```
  (let (dir)
    (dolist (d '("./etc/" "../../etc/ess/" "../etc/" "../etc/ess/"))
      (setq d (expand-file-name d ess-lisp-directory))
      (when (file-directory-p d)
        (setq dir d)))
    dir)
```

**Comment by JianleiZhang** [comment]
It's nil.
![image](https://user-images.githubusercontent.com/7637056/57535558-0e4ff600-7375-11e9-9a7f-5b9b10f67665.png)

**Comment by jabranham** [comment]
Can you do:

```
cd /path/to/ess
du
```

and post the output?

**Comment by npostavs** [comment]
@JianleiZhang

**Comment by npostavs** [comment]
I think this is a bug in the el-get recipe, it didn't quite override el-get's autoload mechnism correctly.

@JianleiZhang try uninstalling `ess` with `M-x el-get-uninstall RET ess RET` and then reinstalling using
```elisp
(el-get-bundle ess :autoloads nil)
```

**Comment by JianleiZhang** [comment]
> I think this is a bug in the el-get recipe, it didn't quite override el-get's autoload mechnism correctly.
> 
> @JianleiZhang try uninstalling `ess` with `M-x el-get-uninstall RET ess RET` and then reinstalling using
> 
> ```emacs-lisp
> (el-get-bundle ess :autoloads nil)
> ```

It's not work.

**Comment by JianleiZhang** [comment]
> Can you do:
> 
> ```
> cd /path/to/ess
> du
> ```
> 
> and post the output?

![image](https://user-images.githubusercontent.com/7637056/57588994-ca651880-754f-11e9-9714-7892dee7405b.png)

**Comment by npostavs** [comment]
> It's not work.

Okay, I just tried it myself, and it indeed doesn't work. Turns out the uninstall doesn't clear `.loaddefs.elc` properly in this case.

@JianleiZhang Please do `M-: (el-get-invalidate-autoloads) RET` then restart Emacs.

----

Some technical details: the problem is that el-get by default puts generated `;;;###autoloads` cookies statements from *all* package into `~/.emacs.d/el-get/.loaddefs.el`. So `ess-lisp-directory` gets the value `~/.emacs.d/el-get/` instead of the intended `~/.emacs.d/el-get/ess`. And because of that `ess-etc-directory` is `nil`.

@jabranham I think you will hit the same problem when installing via package.el in Emacs 27 with the new `package-quickstart` option which does a similar trick with autoloads. Do you really need to autoload `ess-lisp-directory`? It looks like it's working around some bugs in some strange install methods, e.g.,:

```elisp
;; Depending on how ESS is loaded the `load-path' might not contain
;; the `lisp' directory. For this reason we need to add it before we
;; start requiring ESS files
;;;###autoload
(add-to-list 'load-path ess-lisp-directory)
;; Add ess-lisp-directory/obsolete to load-path; files here will
;; automatically warn that they are obsolete when loaded.
;;;###autoload
(add-to-list 'load-path (file-name-as-directory (expand-file-name "obsolete" ess-lisp-directory)))
```

Do these statements really need to be autoloaded?

**Comment by JianleiZhang** [comment]
> > It's not work.
> 
> Okay, I just tried it myself, and it indeed doesn't work. Turns out the uninstall doesn't clear `.loaddefs.elc` properly in this case.
> 
> @JianleiZhang Please do `M-: (el-get-invalidate-autoloads) RET` then restart Emacs.
> 
> Some technical details: the problem is that el-get by default puts generated `;;;###autoloads` cookies statements from _all_ package into `~/.emacs.d/el-get/.loaddefs.el`. So `ess-lisp-directory` gets the value `~/.emacs.d/el-get/` instead of the intended `~/.emacs.d/el-get/ess`. And because of that `ess-etc-directory` is `nil`.
> 
> @jabranham I think you will hit the same problem when installing via package.el in Emacs 27 with the new `package-quickstart` option which does a similar trick with autoloads. Do you really need to autoload `ess-lisp-directory`? It looks like it's working around some bugs in some strange install methods, e.g.,:
> 
> ```emacs-lisp
> ;; Depending on how ESS is loaded the `load-path' might not contain
> ;; the `lisp' directory. For this reason we need to add it before we
> ;; start requiring ESS files
> ;;;###autoload
> (add-to-list 'load-path ess-lisp-directory)
> ;; Add ess-lisp-directory/obsolete to load-path; files here will
> ;; automatically warn that they are obsolete when loaded.
> ;;;###autoload
> (add-to-list 'load-path (file-name-as-directory (expand-file-name "obsolete" ess-lisp-directory)))
> ```
> 
> Do these statements really need to be autoloaded?

Thank you!
