### ISSUE TITLE
Spawning Child Process: Invalid argument

### ISSUE THREAD

**Issue by foogee** [emacs-ess/ESS#919]
On a Windows 10 machine I just installed emacs 25.3.1 via Chocolatey
I downloaded ESS 18.10.2 from the website
I installed R version 3.6.0 in "C:\Program Files\R"
My init.el file has the below code.
Every time I try to start R I get "Spawning child process: Invalid argument"
What could cause that?  

(setq ess-directory-containing-R "c:/Program Files/R/R-3.6.9/bin/x64/")
(require 'ess-site)
(setq inferior-R-program-name "C:/Program Files/R/R-3.6.9/bin/x64/Rterm.exe")

**Comment by vspinu** [comment]
What does `M-x toggle-debug-on-error` give you?

**Comment by foogee** [comment]
It does not give me anything, which seems common with the the spawning child process error. From what I've read this occurs when emacs can happen when emacs can't find the excecutable but I can't figure why that might be. I've tried debug-on-entry [ret] R [ret] M-x R but I don't see anything useful there, and that exhausts my debugging skills.

**Comment by foogee** [comment]
Shoot my bad I had a typo in my directory path!!!
