### ISSUE TITLE
ess-string-command returns '+' chars along with output

### ISSUE THREAD

**Issue by MilesMcBain** [emacs-ess/ESS#922]
When the `COM` arg to `ess-string-command` contains newlines, '+' chars are returned prefixed to the exptected string output.

This makes it difficult to write automations that recieve text from R and inject it into Emacs buffers. Here's a reprex:

```lisp
(defun ess-reprex ()
  (let ((r-process (ess-get-process))
        (r-output-buffer (get-buffer-create "*R-output*")))
    (ess-string-command
     "glue::glue(\"a\",\n,\"b\",\n\"c\")\n"
     r-output-buffer nil)
    (save-mark-and-excursion
      (goto-char (point-max))
      (newline)
      (insert-buffer r-output-buffer))
    ))
```

Run it and it will append `+ + abc` to the end of the current buffer.

If there are better ways to do this with ESS please let me know.

**Comment by vspinu** [comment]
Or just `ess-command` and retrieve the output from the returned buffer. Just strip the leading + +. No better way atm unfortunately. There is `ess-get-words-from-vector` which will return a list of strings if the R side returns a character vector.

**Comment by MilesMcBain** [comment]
Do you think ESS could provided a version that strips the '+'?

 I can do it, but I'd feel like I was creating something brittle.

**Comment by vspinu** [comment]
ESS has a simple [MPI](https://github.com/emacs-ess/ESS/blob/master/etc/ESSR/R/mpi.R#L1)

It's a barebones implementations intentionally kept simple and callback-free (in standard sense).

With the most current ESS you could do:

```R
.ess_mpi_eval("(ding)")
```
with the older:

```R
.ess_mpi_send("eval", "(ding)")
```

Replace `"(ding)"` with a lisp expression which you want to evaluate on the emacs side. Then send the whole string with `ess-command`. 

Note that this eval command is for hacks only and might be even removed in the future. The right way is to add your own handler to `ess-mpi-alist`. See the code; it's very simple.
