### ISSUE TITLE
Don't show the inferior on interactive eval

### ISSUE THREAD

**Issue by vspinu** [emacs-ess/ESS#924]
I am getting increasingly annoyed by our inconsistent show-iESS-on-eval behavior. Some commands do show the inferior, others don't. 

I think by default we should show the inferior only on error and have this behavior customizable globally. The idea is that if the user wants to see the output he or she can switch to the inferior and keep the buffer open. When the buffer is hidden, we assume that the user wants it hidden. This is more or less how other eval systems in emas behave.

**Comment by vspinu** [comment]
In fact, most eval commands don't show the inferior. Exceptions are `ess-load-file`, `ess-r-package` commands, and maybe a few others. The commands ending with `-and-go` are intended for eval +switch. 

So I would suggest to keep it simple and not even introduce new custom for this. Just fix the mis-behaving commands.

**Comment by lionel-** [comment]
Agreed, though evetually I think it'd be useful to be able to configure the behaviour on error.

**Comment by lionel-** [comment]
I noticed today I'm relying quite a lot on the inferior showing up when I load-all etc. I would appreciate the behaviour to be configurable.

**Comment by vspinu** [comment]
I do too. The idea is to replace the REPL output with a meaningful minibuffer message. In the case of load_all it's a bit tricky as you would need to replace it with two messages "Loading ...", then `"Loading ... done!". 

But maybe it's too much trouble for little gain, and we should leave ess-r-package commands as they are.

**Comment by lionel-** [comment]
Or maybe we just need to run a hook on process input?

**Comment by vspinu** [comment]
I have left the package tooling alone. Just removed REPL display in a few obvious places as discussed above.
