### ISSUE TITLE
inconsistent comint-bol in debugger

### ISSUE THREAD

**Issue by r2evans** [emacs-ess/ESS#926]
In the debugger, `Ctrl-A` now goes to the beginning of the line, not to just-right of the prompt. I believe that it used to go to the prompt, not to the true bol, but I don't know when exactly it changed. Is it just me? I don't have a lot of configuration changes

For instance, with the cursor currently at the `_`, if I press `ctrl-a`, the cursor should be placed under the `1`:

```r
> 1 + 2 + 3 _
```

This works. If in a debugger, though:

```r
> (function(){browser();1;})()
Called from: (function() {
    browser()
    1
  ...
Browse[1]> debug at #1: [1] 1
Browse[2]> _
```

then pressing `ctrl-a` puts the cursor under `B` of `Browse[2]`.

GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30

ess-version: 18.10.3snapshot [elpa: 20190521.2129] (loaded from c:/Users/r2/.emacs.d/elpa/ess-20190521.2129/)

**Comment by vspinu** [comment]
I see this as well but haven't had time to check. It's fairly recent.

**Comment by mmaechler** [comment]
Yes, I've seen the same, and indeed @vspinu, this is really recent.
For me, much worse than the `C-a` change is the change of  `C-c C-p`  (`comint-previous-prompt`)  which now goes back all the way to the last *non*-debug prompt, instead of to the last debugger prompt, typically  `Browse[2]`

**Comment by jabranham** [comment]
This happens because `inferior-ess-prompt` isn't permanently buffer-local, so in `inferior-ess`, it gets set by `ess-setq-vars-local`, then immediately unset when the major mode changes. We can fix this by setting it directly in `inferior-ess-r-mode`.
