### ISSUE TITLE
Extra newlines when running R in interactive Docker container

### ISSUE THREAD

**Issue by ndwarshuis** [emacs-ess/ESS#928]
I am trying to transparently run R in a docker container within ESS. To do this I have a script in PATH that overrides the R binary which reads a file called .rundocker in the current directory and launches the container when found.

The script (minimal example):
```
#! /bin/bash
if [ -f ".rundocker" ]; then
    image=$(cat .rundocker)
    ## necessary to allow container's R process to call source files
    ## in the ESS package directory
    emacs_home="$HOME/.emacs.d"
    emacs_mnt="type=bind,source=$emacs_home,target=$emacs_home"
    docker run \
           -ti --rm \
           --mount "$emacs_mnt" \
           "$image" \
           /usr/bin/R --quiet $@
else
    /bin/R --quiet "$@"
fi
```

The .rundocker file contains the target image in plain text (in this case either `r-base` and `rocker/r-base`).

This works when called interactively from a shell. I can call `Sys.info()` from the R process and see that I am running as the container's user (root).

I can also start it from within Emacs using M-x and verify that the R process is indeed in the container; however, I get something like this (starting R in the /tmp directory with a .rundocker, calling `Sys.info()`, and then hitting RET a few times):

```
> setwd('/tmp')
setwd('/tmp')
> 
> Sys.info()
Sys.info()
    ... etc etc
                               effective_user 
                                       "root" 
> 

> 

> 


```

The expected behavior is to not have an echoed command or extra newlines, as given when I call R natively without docker for the same input:
```
> setwd('/home/ndwar/Org')
> Sys.info()
    ... etc etc
                               effective_user 
                                      "ndwar" 
> 
> 
> 
> 
```

Since this might be a newline issue I already tried modifying the the docker command argument in the script to `/bin/sh -c "stty -onlcr && /usr/bin/R --quiet $*"` (rather than just `/usr/bin/R --quiet $@`) to to make the docker terminal return only \n and not \r\n as its newline character; however this did not seem to help.

So the question: is this an ESS bug or a configuration issue pertaining to how I am launching docker?

ESS version: 18.10.3
Emacs version: 26.2
Operating System: Arch Linux (kernel 4.19.40)
Docker version: 1:18.09.6
r-base docker image: 3.6.0
systemwide R: 3.6.0

**Comment by ndwarshuis** [comment]
I figured out this isn't a bug in ESS since simply executing `(process-send-string (get-process "R") "print(\"hello\")\n")` will give different outputs depending on whether or not the R process is running in docker

**Comment by vspinu** [comment]
Indeed, it is presumed that the process doesn't echo. 

I think your docker setup might be useful to others. Would be great to have it in the docs somewhere. I myself used docker through docker-tramp only.

**Comment by ndwarshuis** [comment]
Thank you and agreed. Should I open a pull request for the docs? If so where do you think is a good place for them?

**Comment by vspinu** [comment]
Would be great if you could open a PR for this. The remotes section is the right place. Please keep in mind that most of the users will have a shallow idea of how dockers work, so would be great if the docs were a bit more elaborate than what you had in the OP. Thanks a bunch for taking your time for this. It's really very useful.

**Comment by ndwarshuis** [comment]
Ok will do. As a related question, this is mostly a cosmetic question but in addition to the script I made ESS not send the setwd command to R that will go to the process directory (the script in the OP mounts the current host directory in /home/docker in the container, so setwd is not necessary and will usually point to a non-existent path).

My current way of doing this uses advice to noop the `ess-set-working-directory` command while `run-ess-r` is being called. It works fine enough but I'm wondering if there is an easier, more built-in way I am not seeing. I'm asking here because this would impact what I include in the doc addition.

**Comment by vspinu** [comment]
I think the best solution would be to create a custom runner `R-docker` and let bind relevant variables (`inferior-ess-r-program`, `ess-setwd-command` etc).
