### ISSUE TITLE
Possible solution to inferior font-locking

### ISSUE THREAD

**Issue by jabranham** [emacs-ess/ESS#929]
I saw this blog post the other day: http://www.modernemacs.com/post/comint-highlighting/

What do people think about reworking our inferior font-locking to do something like that? It seems simple to implement and good enough for most purposes. One thing I'd miss is the fontification of the matrix brackets in inferior-r (e.g. `[, 1]`), but we'd forever solve issues like #691 and related.

cc @lionel-

**Comment by lionel-** [comment]
That's interesting and this also seems like a solution that is portable to other backends. Note that would only solve part of the problem, the other unsolved part is the fontification of code and functions printed in the REPL.

**Comment by vspinu** [comment]
The blog post is about fontifying inferior input not output. It also relies on the `comint-last-prompt` which will end up highlighting snapshots of only those prompts which are explicitly entered at the REPL. 

The right approach is to enhance our `inferior-ess-fontify-region` to differentiate between input and output and fontify input with different set of keywords.

**Comment by jabranham** [comment]
Right, I should've mention this only fontifies input to the inferior process. We might want to leave fontification of output to the output itself, now that packages are trying to colorize their output more often (which, if you turn off leads to trouble like #759).

**Comment by lionel-** [comment]
I'm a bit reticent to give up on fontification of printed code. R has this very nice feature that language objects are inspectable at the REPL, so it'd be sad not to take advantage of it.

I think we need to get R to optionally prefix and suffix printed code with unique sequences. This way we can turn on fontification from the filter when we detect the opening tag. I've been wondering if using autoprint customiation (currently discussed on r-devel) would work, but I think it's simpler to have a different option for this. One potentially tricky part is what happens on interrupt / internal error. It might be hard to modify print.c to ensure the closing tag is always emitted, but I haven't really looked into it yet.

**Comment by lionel-** [comment]
Maybe this option should go further and allow emission of tags for other printed elements, such as character vectors etc. This way we can fontify strings when they represent data, but not in other outputs.

**Comment by vspinu** [comment]
Can this be closed? I don't think anyone will be looking at it soon. It's surely low priority and likely to be huge amount of work for little bang.
