### ISSUE TITLE
Eliminating unnecessary diversity in Emacs noweb modes

### ISSUE THREAD

**Issue by nrnrnr** [emacs-ess/ESS#93]
I am the author of noweb.  For some time I have been aware that noweb support for Emacs users has been in a parlous state.  I was very pleased to learn of your efforts to create an improved noweb-mode as part of ESS.

At present I am aware of at least three other competitors:
- Noweb is still shipping with a very old `noweb-mode.el` originally written by Thorsten Ohl and now maintained by me.  It is not something I am proud to be associated with.
- There was some effort to make `mmm-mode` support noweb, but that effort was never terribly effective, and the `mmm-mode` project appears to be just barely surviving.
- Dave Love wrote a truly impressive `noweb-mode.el` based on top of his `multi-mode` package.  It does some very impressive things with syntax highlighting and has other goodies, but unfortunately it is based on Emacs "indirect buffers," which are poorly documented and have proven unreliable in practice.  Worse, Dave seems to have dropped off the Net

I have been using ESS noweb mode on an experimental basis for a few weeks, probably amounting to no more than 10 hours in total.  I am experiencing intermittent failures, not just in noweb-related functionality, but in basic Emacs commands such as `kill-line` and `query-replace`.  It's possible that these issues occur because I have both `ess-noweb-mode` and `noweb-mode` installed on the same system.  It's possible that the issues occur because I'm using Emacs 23.4.  But setting these issues aside, I am excited by your work and I find my preliminary experience is very promising.  And if the issues were resolved, I'd be able to endorse your work to those of my users who use Emacs.

I am wondering if you would like to join forces?  The time I have available for noweb is very limited---I am rewarded very heavily for new work and not at all for improvements to noweb---but the chance to partner with somebody who has real Emacs skills is too promising to ignore.  Would you be interested in working together to refactor the code so it can stand independent of ESS, and perhaps to incorporate some of Dave Love's good ideas, and squeeze out some bugs?  I would love to be able to replace the old, crappy code I am distributing with something based on your work.

**Comment by vspinu** [comment]
Hi Norman,

Your example works well in my tests. The automatic chunk mode detection is there. You can do it now in a number of different ways (see [poly-noweb](https://github.com/polymode/poly-noweb)). The buffer local variable for the default mode is also there. The general docs have been [improved](https://polymode.github.io) and the technical docs will be there once the dust of the rewrite has settled. 

I am closing this one as we will be removing ess-noweb from ESS immediately after the next release later this month.

**Comment by Romendakil** [comment]
So it seems the noweb is really completely gone from ess now!? I took a brief look at polymode/poly-noweb but it is not available for my emacs, e.g. under a Ubuntu distribution.
