### ISSUE TITLE
Manual 3.5 : Controlling buffer display(RStudio)?

### ISSUE THREAD

**Issue by davidjayjackson** [emacs-ess/ESS#933]
Where does the Lisp code to give the look and feel of RStudio? I put it in my init.el and nothing happens? Does it go in "display-buffer-alist"?

I have to admin I like using emacs for my R coding .

TIA,
David

**Comment by nverno** [comment]
What "feel" are you referring to? For indentation you can set `ess-style` to `'RStudio-`

**Comment by davidjayjackson** [comment]
nverno,
Thanks for takling the time to reply to my post.

The manual has two code (in init.el)I'm trying to use:
1. Spits screen vertical using with the code on the left and R console on the right :
(setq display-buffer-alist
’(("*R"
(display-buffer-reuse-window display-buffer-pop-up-frame)
(reusable-frames . 0))))

2. And the other to give a layout similar to Rstudio:
(setq display-buffer-alist
‘(("*R Dired"
(display-buffer-reuse-window display-buffer-in-side-window)
(side . right)
(slot . -1)
(window-width . 0.33)
(reusable-frames . nil))
("*R"
(display-buffer-reuse-window display-buffer-at-bottom)
(window-width . 0.5)
(reusable-frames . nil))
("*Help"
(display-buffer-reuse-window display-buffer-in-side-window)
(side . right)
(slot . 1)
(window-width . 0.33)
(reusable-frames . nil))))

**Comment by vspinu** [comment]
That configuration only dictates in which position the buffers should appear. It doesn't create the permanent window configuration as R-studio does. Emacs philosophy is to show things (windows) on demand, only when they are needed.
