### ISSUE TITLE
completion with company

### ISSUE THREAD

**Issue by nverno** [emacs-ess/ESS#934]
What changes caused requiring `company-capf` to be deleted and `company-R-library` to no longer work correctly?  By no longer work correctly, there doesn't seem to be any company completion for packages after `packages=` in `require` or `library`.

The following used to work for me, completing packages first where appropriate and allowing `company-capf` as well,

`(company-R-args :with company-R-library company-R-objects :separate)`

It seems to rather restrictive it terms of user customization of `company-backends`.

**Comment by jabranham** [comment]
@nverno I think usually we remove company-capf from company-backends, don't we? 

If you've been putting that back in manually, we recently added `ess-r-package-completion` to `completion-at-point-functions`, perhaps that is interacting oddly?

**Comment by vspinu** [comment]
Things work as expected for me. We do delete company-capf probably because those are largely redundant.

**Comment by nverno** [comment]
Yea, I hadn't used it in a while, I thought it completed after `packages = `, but that isn't important.
