### ISSUE TITLE
shouldn't   flymake in `*.Rout` be *off* by default ?

### ISSUE THREAD

**Issue by mmaechler** [emacs-ess/ESS#936]
R transcript files, commonly named `*.Rout` (e.g as `R CMD BATCH  foo.R`  produces `foo.Rout`), are typically rather large than small.
As we have seen, `flymake` is sometimes a performance hog, and it would be really useful if this was *not* active by default in such file buffers.

**Comment by lionel-** [comment]
I think that makes sense, given that transcript files most likely shouldn't be restyled and kept as is.
