### ISSUE TITLE
ESS Command/Menu Summary: File and Edit

### ISSUE THREAD

**Issue by davidjayjackson** [emacs-ess/ESS#937]
Ok guys,
I started making a Menu / Command summary cheatsheet.
This first effort includes all the items on the File and Edit menus:

Filename: ess_command
Open Document Format : ess_command.odt
HTML format: ess_command.html
Github:
https://github.com/davidjayjackson/EmacsRDocs.git

**Comment by vspinu** [comment]
Thanks for letting us know, but ess mailing list is more appropriate for such notifications. Some people might find it useful. Github issues are for bugs and feature requests only. At ESS we are not interested in such summaries.
