### ISSUE TITLE
Colour printing is hanging R process

### ISSUE THREAD

**Issue by cfhammill** [emacs-ess/ESS#938]
Printing tibbles is no longer working with my recent upgrade to 20190612.1734 on emacs 25. I traced it to attempting to `cat` a colourized string.

Steps to reproduce

```
M-x R
cat("\033[90m# A tibble: 6 x 2\033[39m")
```

This hangs indefinitely.

Any ideas what I can do?

**Comment by cfhammill** [comment]
I should add it becomes unresponsive to `C-c C-c`

**Comment by cfhammill** [comment]
Disabling crayon with `options(crayon.enabled = FALSE)` appears to fix it.

**Comment by fmichonneau** [comment]
I can reproduce this.

**Comment by japhir** [comment]
Also reproducing on my end, the fix works for now.

**Comment by jabranham** [comment]
Bisecting suggests 8a8b5d94a903814fc6aa06db197eaad236df43e1 is to blame but I haven't looked into it past that yet.

cc @vspinu

**Comment by vspinu** [comment]
Indeed. I didn't realize that \033 is 27 in octal. Should be fixed.
