### ISSUE TITLE
M-n in R debugger

### ISSUE THREAD

**Issue by r2evans** [emacs-ess/ESS#940]
Possibly related to #926 (not sure, but it seems to have happened in between before that fix and now).

In a debugger, often (but *not always?*) `M-n` advances the debugger but the highlighted portion blinks but does not advance. Usually I can type `n` on the console and it then changes the highlighted-line in the accompanying source window.

```
GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30
ess-version: 18.10.3snapshot [elpa: 20190612.1734] (loaded from c:/Users/r2/.emacs.d/elpa/ess-20190612.1734/)
```

**Comment by vspinu** [comment]
`M-N` is equivalent to typing `n` in the REPL. Have a look at the two most recent source locations at the REPL. It's likely that those are the same, or maybe one of the locations could not have been found, but then you should have seen a message.

**Comment by r2evans** [comment]
I understand that the two are the same, I was trying to say that while they should behave the same, they did not: when repeated `M-n` did not advance the highlight (though the line being executed *did* advance), a simple `n` broke that cycle and restored normal function. I'm trying see *if* and *how* I can demonstrate it in a reproducible way ... and having problems with doing so. If I can't figure something out shortly, I'll likely close as yet another windows/emacs thing. Thanks, @vspinu.

**Comment by vspinu** [comment]
Hmm. So, you say the source reference from the inferior is not picked up, even though it's there and it's correct? I could imagine such a situation indeed. That would mean a bug for sure.

**Comment by r2evans** [comment]
Not quite: the source file is opened, and the first line of the appropriate function is highlighted correctly. Successive `M-n` flashes the highlight but does not advance it (when it should), while the R console shows the next line of code to be processes is correct and no longer the same as what is highlighted.

Sorry, put this on hold for now ... I'm about to board a flight and have not come up with reproducible steps. Please allow me to get back to you when I have more. Thanks!

**Comment by r2evans** [comment]
I haven't seen this in a while, perhaps it was spurious behavior on my end or some other code edit fixed it. Thanks, @vspinu
