### ISSUE TITLE
Julia: pretty colors

### ISSUE THREAD

**Issue by antoine-levitt** [emacs-ess/ESS#945]
Julia has nice colors (eg bold on backtraces, `@code_warntype`, etc) which the inferior mode in ESS doesn't display. I tried hijacking comint-exec-1 to avoid setting the terminal type to "dumb", but that made ESS freeze.

**Comment by vspinu** [comment]
Comint understands ansi colors. If julia sends them, the colors should show.

**Comment by antoine-levitt** [comment]
It doesn't, for some reason. Adding `--color=yes` to inferior-julia-args is better: it shows bold text, but still no colors. I thought this was because of the `TERM=dumb` thing, but it doesn't look like it because `TERM=dumb julia --color=yes` from terminal does send colors. Any idea how to debug this?

**Comment by antoine-levitt** [comment]
Hm, so it's more complicated than I thought: it shows some colors, but not all. In any case, the same happens in `shell` so I guess it's not ESS-specific; closing this issue.

**Comment by nverno** [comment]
I see see the colors (maybe not all?) in `shell` by setting XTERM=xterm-256 and using `xterm-color`'s `xterm-color-filter` (`ansi-color` may work as well, I don't use it anymore)

**Comment by antoine-levitt** [comment]
It's the same: when I type something stupid (eg qsedazeoj) I get "ERROR: UndefVarError: qsedazeoj not defined" with ERROR in bold. When I do the same at a xterm, I get the sentence in red.

**Comment by nverno** [comment]
Yea, I see the reds/blues in emacs' `shell` running julia, eg. [screenshot](https://imgur.com/a/UHlUIcW)

**Comment by antoine-levitt** [comment]
I can confirm it works with `xterm-color`. Just follow the instructions on https://github.com/atomontage/xterm-color, substituting inferior-ess-julia-mode-hook for shell-mode-hook, and add `--color=yes` to inferior-julia-args.
