### ISSUE TITLE
Stata hanging with line continuations

### ISSUE THREAD

**Issue by roblem** [emacs-ess/ESS#946]
Generally stata works fine with ESS however there are some instances when line continuation output possibly clashes with the default secondary prompt

For example:
```stata
mata 
for (i=1; i<=5; i++) {
  i
}
end
```
yields this in the REPL stata command window with emacs hanging:
```
mata
------------------------------------------------- mata (type end to exit) ----------------
: for (i=1; i<=5; i++) {
for (i=1; i<=5; i++) {
> 
```
To recover a usable prompt requires a `C-g`, a downarrow and then a `}` RET to close the loop. 

Thinking the hang might be due to ESS interpreting the "> " as a prompt somehow and based on #831, I refined the secondary prompt by changing 
``
 (inferior-ess-secondary-prompt . "> \\|--more--")
``

in `ess-stata-mode.el`.

Unfortunately, things continue to hang with the secondary prompt change when running for loops in mata.

FYI: This analogous code at a stata prompt (rather than mata) works just fine:
```stata
forvalues x = 1/5 {
  di `x'
}
```

**Comment by jabranham** [comment]
I'm not familiar with mata at all. What is the secondary prompt in mata?

**Comment by jabranham** [comment]
I just pushed a commit that hopefully fixes this issue, let me know if you still experience it.

**Comment by roblem** [comment]
This commit didn't fix it.  Same behaviour as before.

First, Stata has two "modes" (these are my terms): 
1) stata (what 95% of people use exclusively) and uses the prompt `.`
2) mata is a linear algebra environment not unlike matlab with a prompt `:` 
It is possible to do work in one mode, switch to the other and do work, and then switch back.

The problems are arising in mata.  Here is a more detailed description about what is happening:

1. Invoke mata by
```stata
. mata
```
gives the mata prompt:
```
------------------------------------------------- mata (type end to exit) -----
:
```
If I paste (or C-m-x) this valid multiline loop code
```
for (i=1; i<=5; i++) {
  i
}
```
into the REPL and press `Enter` emacs hangs, requiring a Cntr-G to recover control.  It then puts me into an interactive mode, with only the first line of the loop registering and I need to interactively finish the loop code.  The following picture shows what is going on in the REPL with some annotations:

![mata_ess_issue](https://user-images.githubusercontent.com/1871086/60493038-65ef4b80-9cac-11e9-9779-ab4ded978f60.png)

```

**Comment by jabranham** [comment]
Thanks for the very detailed example. It would be amazing to get an annotated picture with every bug report :-)

Anyway, I think I know the issue and have provided a fix. Test it out and let me know if it still doesn't work.

**Comment by roblem** [comment]
Still hangs.  Should the inferior-ess-secondary-prompt include a `>` somehow?

**Comment by jabranham** [comment]
Sorry for taking a while to get back to you about this. Just pushed something that hopefully fixes this, let me know if you still experience it.

Solving issues with stata is like playing whack-a-mole since I don't have a copy to test on...
