### ISSUE TITLE
Error from ess-narrow-to-defun-or-para

### ISSUE THREAD

**Issue by dpritchLibre** [emacs-ess/ESS#949]
In ESS version 20190702.1827 from MELPA, I get the following error when invoking `ess-narrow-to-defun-or-para` when point is inside of an R function:
```
Wrong type argument: integer-or-marker-p, nil
```
The definition of `ess-narrow-to-defun-or-para` is:
```
(defun ess-narrow-to-defun-or-para ()
  "Make text outside current function invisible.
If text is already narrowed, this is removed before narrowing to the
current function."
  (interactive)
  (save-excursion
    (widen)
    (let* ((beg (ess-goto-beginning-of-function-or-para))
           (end (ess-goto-end-of-function-or-para)))
      (narrow-to-region beg end))))
```
Furthermore, the definition of `ess-goto-beginning-of-function-or-para` is:
```
(defun ess-goto-beginning-of-function-or-para ()
  "If inside a function go to the beginning of it.
Otherwise go to the beginning of paragraph."
  (interactive)
  (let ((start-pos (point))
        beg end)
    (beginning-of-defun)
    (setq beg (point))
    (end-of-defun)
    (setq end (point))
    (goto-char beg)
    (unless (and (< beg start-pos)
                 (> end start-pos))
      (let ((par-pos (save-excursion
                       (goto-char start-pos)
                       (forward-comment most-negative-fixnum)
                       (backward-paragraph)
                       (forward-comment most-positive-fixnum)
                       (point))))
        (if (< end par-pos)
            (goto-char par-pos)
          (goto-char beg))))))

```
It appears that the command
```
(unless (and (< beg start-pos)
             (> end start-pos))
  ...)
```
returns `nil` when the conditional is satisfied, which is then being assigned to the variable `beg` in the `ess-narrow-to-defun-or-para` function call.  This in turn causes an error when the command `(narrow-to-region beg end)` is invoked.  So one possible solution would be to be sure to always return the value of `(point)` from `ess-goto-beginning-of-function-or-para`.

There is also a similar issue with `ess-goto-end-of-function-or-para` that would need to be addressed.

**Comment by dpritchLibre** [comment]
I would be happy to submit a pull request that would add the command `(point)` to the end of `ess-goto-beginning-of-function-or-para` and to `ess-goto-end-of-function-or-para` if that would be helpful.

**Comment by jabranham** [comment]
Thanks for the report, should be fixed!
