### ISSUE TITLE
void-variable xref-backend-identifier-at-point

### ISSUE THREAD

**Issue by stephanpdx** [emacs-ess/ESS#957]
I just upgraded to Ubuntu 18.04 and with that, to emacs 25.2.2.  When loading ess via (require 'ess-site), I now get the following error: 

    Lisp error: (void-variable xref-backend-identifier-at-point)
 
ESS version: 20180624.235

**Comment by jabranham** [comment]
> ESS version: 20180624.235

Update ESS or recompile the version you have. I think that should fix the issue.

**Comment by stephanpdx** [comment]
Recompiling worked -- thanks!
