### ISSUE TITLE
Rd mode uses percent for comment-start

### ISSUE THREAD

**Issue by kwstat** [emacs-ess/ESS#958]
In Rd mode, ESS is setting comment-start to "% ".

The setting is in here: https://github.com/emacs-ess/ESS/blob/master/lisp/ess-rd.el

I find this annoying and wish it were set to "# " so that I can comment code in the examples section. Is this a reasonable change?

**Comment by jabranham** [comment]
I don't think it makes sense to change it to # in Rd buffers since % is for comments. What might make sense is to add a command to edit the examples in an R-mode buffer (similar to #756).

**Comment by vspinu** [comment]
Indeed. This is the domain of multi-modes. AFAIKpPolymode works well with Rd files by default. Any reasons for why you don't use it?

**Comment by kwstat** [comment]
I use polymode for Rmd, but polymode for Rd breaks font-locking for Rd files and I haven't figured out why.

**Comment by kwstat** [comment]
I've upgraded to the latest polymode packages from melpa and had to re-do some parts of .emacs configurations.  Seems to be working now.  Thanks.
