### ISSUE TITLE
Request: include support for R package magrittr

### ISSUE THREAD

**Issue by uhkeller** [emacs-ess/ESS#96]
The R package magrittr defines the pipe-forwarding binary operator %>% that makes for much more readable code in my experience. It would be nice if ESS could provide support for this operator by a) providing a key binding for it and b) highlighting it as it does other operators.

**Comment by gtuckerkellogg** [comment]
`magrittr` is important in the Hadleyverse in part because other packages like `dplyr` also adopt the pipe.  While the highlighting @gaborcsardi  showed above works, can anyone suggest some elisp to indent after `%>%` properly in ESS?  Right now ESS indentation of a pipeline looks like

    library(dplyr)
    foo <-  filter(mtcars, gear > 3) %>%
            filter(cyl < 6) %>%
                filter(carb == 2)

That is, every use of `%>%` increases the indentation.  The examples I've seen documenting `%>%` keep all the pipes at a single level, that is:

    foo <-  filter(mtcars, gear > 3) %>%
            filter(cyl < 6) %>%
            filter(carb == 2)

If support for `%>%` is under consideration for ESS, it would be great to address the indentation at the same time.

**Comment by vspinu** [comment]
Have a look at  `ess-first-continued-statement-offset`  and   `ess-continued-statement-offset`. I have 

```
foo <-
    filter(mtcars, gear > 3) %>%
      filter(cyl < 6) %>%
      filter(carb == 2)
```

With the following style:

```

(add-to-list 'ess-style-alist
             '(my-style
               (ess-indent-level . 4)
               (ess-first-continued-statement-offset . 2)
               (ess-continued-statement-offset . 0)
               (ess-brace-offset . -4)
               (ess-expression-offset . 4)
               (ess-else-offset . 0)
               (ess-close-brace-offset . 0)
               (ess-brace-imaginary-offset . 0)
               (ess-continued-brace-offset . 0)
               (ess-arg-function-offset . 4)
	       (ess-arg-function-offset-new-line . '(4))
               ))

(setq ess-default-style 'my-style)
```

**Comment by gtuckerkellogg** [comment]
Fantastic, thanks!

**Comment by kwstat** [comment]
For what it's worth...with key-chord-mode, I make it easier to type the pipe operator by using two quick ">" keystrokes:

```
(require 'key-chord)
(key-chord-mode 1)
(key-chord-define-global ">>" "%>%")
```

**Comment by vspinu** [comment]
I have added `ess-keyword:%op%` to the ESS>font-lock menu and corresponding `ess-%op%-face`.

As to the binding, smart operators is not ESS's business. I am experimenting with `key-combo` now.  It it implements `ess-smart-underscore` cycling idea on a much larger scale and looks very promisin . This is what I have right now:

```
(require 'key-combo)

(defvar key-combo-ess-default
  (append key-combo-common-default
	  '((">"  . (" > " " %>% "))
	    ("$"  . ("$" " %$% "))
	    ("<>" . " %<>% ")
	    ("*"  . ("*" " * "))
	    ("^"  . ("^" " ^ "))
	    ("/"  . ("/" " / "))
	    ("~" . " ~ ")
	    (":" . (":" "::" ":::"))
	    (":="  . " := ") ; data.table
	    ;; ("inn" . " %in% ") ; doesn't work
	    ("->"  . " -> "))))

(key-combo-define-hook '(ess-mode-hook inferior-ess-mode-hook)
		       'ess-key-combo-load-default
		       key-combo-ess-default)
```

**Comment by dahtah** [comment]
Using key-combo is a really good solution. The above didn't quite work on my setup, though (Emacs 24.4.1). Here's a working version: 

```
(require 'key-combo)

(key-combo-mode 1)

(add-hook 'ess-mode-hook
	    '(lambda()
	       (key-combo-mode t)))

(add-hook 'inferior-ess-mode-hook
	    '(lambda()
	       (key-combo-mode t)))

(defvar key-combo-ess-default
      '((">"  . (" > " " %>% "))
        ("$"  . ("$" " %$% "))
        ("<>" . " %<>% ")
        ("*"  . ("*" " * "))
	("%" . ("%" "%*%" "%%"))
        ("^"  . ("^" " ^ "))
        ("/"  . ("/" " / "))
        ("~" . " ~ ")
        (":" . (":" "::" ":::"))
        (":="  . " := ") ; data.table
        ("->"  . " -> ")))

(key-combo-define-hook '(ess-mode-hook inferior-ess-mode-hook)
               'ess-key-combo-load-default
               key-combo-ess-default)

```

**Comment by sumandoc** [comment]
Simple solution is to put this line in your `init.el` file:

`(global-set-key (kbd "C-S-m") (lambda () (interactive) (insert "%>%")))`

It will provide the same binding as `rstudio` for pipe operator of magrittr.
