### ISSUE TITLE
Evaluation display issues in Emacs 26.2

### ISSUE THREAD

**Issue by jkroes** [emacs-ess/ESS#963]
Open vanilla emacs with -q. Load ess. Open an iESS buffer. Open test.R in another buffer:

```
x <- function() {
    print(1)
    print(2)
}
x()
print('finished')
```
Run C-C C-C (evaluate region or para. or function & step) on the function definition, and ```. + >``` is inserted in the iESS buffer on the current line for the original prompt:

``` 
 > setwd('/Users/justinkroes/.emacs.d/')
!> . + >
```
Run it on the function call, and the same thing happens, but now no step occurs in the source code buffer:
```
 > setwd('/Users/justinkroes/.emacs.d/')
!> . + > . + >
```
Run it on the print function, and all of a sudden, below this, the output you expected earlier appears:
```
 > setwd('/Users/justinkroes/.emacs.d/')
!> . + > . + > x <- function() {
 +     print(1)
 +     print(2)
 + }
 > x()
 [1] 1
 [1] 2
 > print('finished')
 [1] "finished"
 >
```
On subsequent tries, even the function definition and call didn't appear in the iESS buffer--just the print results.

**Comment by jkroes** [comment]
Update: Using graphical Emacs and putting a line between these statements allowed for better output in the iESS buffer, but I'm still confused as to why newlines would make the difference in evaluation display.

**Comment by jkroes** [comment]
Update: 
Without lines between the three statements in test.R:
```
> setwd('/Users/justinkroes/.emacs.d')
> . + > . + > x <- function() {
+     print(1)
+     print(2)
+ }
> x()
[1] 1
[1] 2
> print('finished')
[1] "finished"
```
With lines between them:
```
> . + > 
> x()
[1] 1
[1] 2
> 
> print('finished')
[1] "finished"
> 
```
In the former, there are two extraneous prompts, but the function definition shows up. In the latter, there is one extraneous prompt and no function definition.

**Comment by jkroes** [comment]
Update 2:
C-c C-b (whole buffer) seems to work. But it still inserts a whole ton of plus signs on the first prompt:
```
  20 > setwd('/Users/justinkroes/.emacs.d')
! 21 > + + + + + + + > x <- function() {
  22 +     print(1)
  23 +     print(2)
  24 + }
  25 > x()
  26 [1] 1
  27 [1] 2
  28 > print('finished')
  29 [1] "finished"
  30 >
```

**Comment by vspinu** [comment]
The function source is not shown in the iESS. Why do you need it?

**Comment by jkroes** [comment]
Mainly because it's helpful for visually locating sections of code within the iESS buffer after submitting a buffer or source file. The function source appears if you evaluate line-by-line using C-RET, so I expected similar behavior for larger blocks. I still have to play around with the debugging facilities, though, so this may ultimately be an ancillary issue.

**Comment by vspinu** [comment]
The primary reason why source is not shown is because the function definitions are instrumented (in order to have source references on error/debugging etc.) It's not a rocket science to implement the display but it seems like a complication to an already quite complicated sub-system. The evaluation system should be rewritten at some point anyhow.

**Comment by jkroes** [comment]
Alright, I'll close this for now.
