### ISSUE TITLE
How does the R debugger work?

### ISSUE THREAD

**Issue by jkroes** [emacs-ess/ESS#964]
I couldn't find any information on this in the ess manual, and I have no idea how to debug R scripts from the documentation.

**Comment by nverno** [comment]
Did you see the `ess-tracebug` node in the ESS manual?  It has information and a short tutorial

**Comment by vspinu** [comment]
https://ess.r-project.org/Manual/ess.html#ESS-tracebug. The ess debugger is a lightweight layer over R's built-in debugger, whatever you can do with ess debugger you can do with simply typing  debugger commands in the console.

**Comment by jkroes** [comment]
Sorry for the late response. I discovered that @vspinu is spot on about the debugger being a wrapper around R's built-in debugging functions. This should be made explicit in the manual. Coming from RStudio, the R debugger functions are abstracted away from the user. If an error is hit, the user can click on "Rerun with debug," and the program will run and stop at the error. Coming from RStudio, I naively expected this behavior as opposed to having to manually set a breakpoint or insert browse() into my code. It was also confusing that breakpoints are inserted on a line, which shifts subsequent code down, and skips numbers when line numbers are enabled. Luckily, I made a guess that both RStudio and ESS might rely on built-in R debugging functions. I found the documentation for these, tested them, then compared them to the ESS commands. I still have not been able to use ess-debug-command-up, which isn't really documented, and have resorted to calling recover() from within the interactive debugger to navigate up and down the call stack.

**Comment by vspinu** [comment]
There have been a few new debugger functions introduced since ess debugger layer was written. It surely needs a face lift. 

> also that it is equivalent to "n" or next at the prompt.

Indeed, the doc is wrong. Opened a more generic #965 for this. 

Regarding R-studio debugger, I am not entirely sure but I think the way it works is by instrumenting the entire code of the function and evaluating the code behind the user back. Last time I checked it didn't look to me that they rely on R's built in.
