### ISSUE TITLE
in julia source code, structs are not indented

### ISSUE THREAD

**Issue by wgmitchener** [emacs-ess/ESS#971]
I'm using emacs-26.2-2.fc31.x86_64 with emacs-ess-17.11-3.fc31.noarch. When editing julia source code, I can get it to indent functions, but it doesn't indent structs at all.

struct Example
x::Float64 # should be indented when I hit tab but it doesn't work
end

**Comment by jabranham** [comment]
Indentation is taken care of by julia-mode. You'll need to ask about this on their bug tracker.

**Comment by wgmitchener** [comment]
Indentation works in julia mode without ESS.

**Comment by vspinu** [comment]
Your ESS is out of date. We started building on top of julia-mode.el in 2018 AFAICR.

With the most recent ess your example indents correctly for me.

**Comment by wgmitchener** [comment]
Okay, I'll file a request with Fedora.
