### ISSUE TITLE
ess does not load

### ISSUE THREAD

**Issue by xvtstephen** [emacs-ess/ESS#972]
installed ess with apt install ess
```
(base) stephen@stephen-Aspire-5250:~$ find /usr/share -name ess-mode.el
/usr/share/emacs/site-lisp/ess/ess-mode.el
(base) stephen@stephen-Aspire-5250:~$ uname -a
Linux stephen-Aspire-5250 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
ess does not load when I edit an R file, so I added (require 'ess-site) according to the instruction in another post on this forum and it says No such file or directory: ess-site
so I added the path in my .emacs
```
(add-to-list 'load-path "/usr/share/emacs/site-lisp/")
(require 'ess-site)

```
still no luck, same error.

**Comment by jabranham** [comment]
You would need to add `/usr/share/emacs/site-lisp/ess/"` to `load-path` since that's where ess is on your machine.

**Comment by xvtstephen** [comment]
it worked, thanks.
