### ISSUE TITLE
`ess-execute-screen-options` set alternate width

### ISSUE THREAD

**Issue by mmuurr** [emacs-ess/ESS#976]
I love how ESS can auto-adjust the R process's width to match the emacs window width (with ess-execute-screen-options), but ... I'd like to set the process to that width **minus 2 characters** (or 3 characters, or 1 character, etc.).

Is this doable with the current ESS implementation?

([stackoverflow post with the same question.](https://stackoverflow.com/questions/59727367/emacs-ess-ess-execute-screen-options-to-width-2?noredirect=1#comment105604922_59727367))

**Comment by jabranham** [comment]
Not currently, but I've implemented that in #977.

**Comment by jabranham** [comment]
Just landed in master, please let us know if you find any issues with it.
