### ISSUE TITLE
ess-r-flymake won't be available

### ISSUE THREAD

**Issue by m0m0khan** [emacs-ess/ESS#979]
Hi all,

When I open emacs, I get the following error:

`Warning (ess): ESS was compiled with older version of Emacs;
    `ess-r-flymake' won't be available`

Can you guys help me here to solve it?

Thanks

**Comment by jabranham** [comment]
You'll need to recompile ESS. If you've installed from MELPA, a simple
reinstall should do the trick.

**Comment by m0m0khan** [comment]
Thanks! It worked!
