### ISSUE TITLE
running org-babel-execute-src-block no longer produces relevant figure output in session

### ISSUE THREAD

**Issue by japhir** [emacs-ess/ESS#980]
Creating images from org source blocks in R used to work like a charm, but now something is going wrong with my version of ess (`ess-version: 18.10.3snapshot [elpa: 20200103.915] (loaded from /home/japhir/.emacs.d/elpa/ess-20200103.915/)`):

Here's an example org file:
```
#+TITLE: Test org babel figure output
#+property: header-args:R :session *R:test* :exports both :results output :eval no-export
#+options: ^:{}

#+begin_src R :results output graphics :file test.png
  library(dplyr)
  library(ggplot2)
  ggplot(iris, aes(x =  Sepal.Width, y = Sepal.Length)) +
    geom_point()
#+end_src

#+RESULTS:
```

Where before, this used to create a link to the new file test.png, now it does create the file but no longer inserts the link under results. It even replaces a previously created image link with nothing if it used to be there.

If I C-c C-c on the source block, the `*Messages*` buffer tells me:
```
executing R code block...
ess-tracebug mode enabled
Code block produced no output.
Reverting buffer ‘test.png’.
```
The output of my ess session buffer looks like this:
```
R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> setwd('/home/japhir')
> png(filename="test.png"); tryCatch({
library(dplyr)
library(ggplot2)
ggplot(iris, aes(x =  Sepal.Width, y = Sepal.Length)) +
  geom_point()
},error=function(e){plot(x=-1:1, y=-1:1, type='n', xlab='', ylab='', axes=FALSE); text(x=0, y=0, labels=e$message, col='red'); paste('ERROR', e$message, sep=' : ')}); dev.off()
'org_babel_R_eoe'
png(filename="test.png"); tryCatch({
+ library(dplyr)
+ library(ggplot2)
+ ggplot(iris, aes(x =  Sepal.Width, y = Sepal.Length)) +
+   geom_point()
+ },error=function(e){plot(x=-1:1, y=-1:1, type='n', xlab='', ylab='', axes=FALSE); text(x=0, y=0, labels=e$message, col='red'); paste('ERROR', e$message, sep=' : ')}); dev.off()
> 

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

null device 
          1 
> 'org_babel_R_eoe'

[1] "org_babel_R_eoe"
> 
```

**Comment by japhir** [comment]
Because it is still writing the file in the background, for now I can C-c C-c on a source code block to execute the block, then undo the removal of the `#+RESULTS` line and `org-redisplay-inline-images` to make this work as intended.

**Comment by frederic-santos** [comment]
Imho, this is not an ESS issue. This is related to a recent Org-mode update ([see here](https://orgmode.org/Changes.html)):

> The "file" `:results` value is now mandatory for a code block returning a link to a file. The `:file` or `:file-ext` header arguments no longer imply a "file" result is expected. 

Try to replace your code block by this one:
```
#+begin_src R :results graphics file :file test.png
  library(dplyr)
  library(ggplot2)
  ggplot(iris, aes(x =  Sepal.Width, y = Sepal.Length)) +
    geom_point()
#+end_src
```
Everything should work as expected.

**Comment by Cumol** [comment]
I also had to look for this and found it in the recent org-mode update.

Its quite a big change for people using source blocks. Should be highlighted better next time.

**Comment by frederic-santos** [comment]
I had the same bad surprise :) But annoying "incompatible changes" often happen with Org-mode, and Org-mode is perhaps the only package (or even software) for which I always carefully read the release notes after each new version.
But I think this issue can be closed now!

**Comment by japhir** [comment]
Thanks so much for solving this issue for me, even though it had nothing to do with ess!
