### ISSUE TITLE
Is ess-r-flymake-linters being ignored?

### ISSUE THREAD

**Issue by jmburgos** [emacs-ess/ESS#982]
I am trying to select which linters are being used, and to modify some of the parameters (line length, for example).  But it seems that ESS is ignoring the content of the ess-r-flymake-linters variable.    

For starters, the original value of this variable is 
`("closed_curly_linter = NULL" "commas_linter = NULL" "commented_code_linter = NULL" "infix_spaces_linter = NULL" "line_length_linter = NULL" "object_length_linter = NULL" "object_name_linter = NULL" "object_usage_linter = NULL" "open_curly_linter = NULL" "pipe_continuation_linter = NULL" "single_quotes_linter = NULL" "spaces_inside_linter = NULL" "spaces_left_parentheses_linter = NULL" "trailing_blank_lines_linter = NULL" "trailing_whitespace_linter = NULL")`

... which should indicate that none of the linters are active.  But when loading some R code, all linters are active and running with default values (line length=80, for example).  

Changing the value of ess-r-flymake-linters has no effect on the number of active linters or their behaviour.  I tried changing it to

`(ess-r-flymake-linters "lintr::with_defaults(line_length_linter = line_length_linter(120))")`

and to 

` (ess-r-flymake-linters '("line_length_linter=line_length_linter(120))"))`

In both cases all lintrers are working, and I get a warning if the line length is above 80 charcters.

Many thanks!

**Comment by jabranham** [comment]
The second should work but you've got an extra parens in the text you pasted here. Try:

```
(setq ess-r-flymake-linters '("line_length_linter = line_length_linter(120)"))
```

**Comment by jabranham** [comment]
Closing since no response, let me know if you still have an issue with this.

**Comment by pglpm** [comment]
I did discover this problem today, exactly as described. 
- Ubuntu 20.04
- GNU Emacs 29.4 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20
- ess-version:  [elpa: 20240821.1952]
