### ISSUE TITLE
autocomplete does not find the right R-version

### ISSUE THREAD

**Issue by GeoBer** [emacs-ess/ESS#988]
My "company" has recently changed the access to the latest R version: this requires loading a specific module. I have added this to my .bashrc file. When I start emacs from the main applications icon, the autocomplete does not find the correct R version, but if I start emacs from a simple desktop terminal the right R version is available. I have the following in my .emacs file:
(add-to-list 'load-path "/home/bermage1/ess-18.10.2/lisp/")
(load "ess-site")
(require 'ess-jags-d)
(require 'ess-bugs-d)
The "company" R versions available from the applications link, and the one available through my bashrc are not the same: how can I add the R version I want to run to the ess-r-autocompletion.el  or any other solution that works?
Many thanks,

Georgina

**Comment by jabranham** [comment]
You can point `inferior-ess-r-program` to the R binary.

**Comment by GeoBer** [comment]
Lovely! it worked: thank you so much.
