### ISSUE TITLE
indentation bug following +

### ISSUE THREAD

**Issue by gongzhitaao** [emacs-ess/ESS#99]
I had the same problem as discussed in the [Stackoverflow post](https://stackoverflow.com/questions/12805873/changing-indentation-in-emacs-ess)

Simply put,

I want

```
some.plot <- ggplot(..., aes(x=..., y=...)) +
    one_layer(...) +
    another_layer(...) +
    ...
```

But I got

```
some.plot <- ggplot(..., aes(x=..., y=...)) +
    one_layer(...) +
        another_layer(...) +
            ...
```

This seems to have something to do with `ess-continued-statement-offset`.

Emacs Version: `24.3.1`
ESS Version: `14.05`

ESS is installed through Emacs package manager.

**Comment by daroczig** [comment]
Does it work with `RRR` mode as well for you? Seems to work fine when I `C-c C-e s` to `default` mode, but not with `RRR`

**Comment by vspinu** [comment]
`C-c C-e s` resets all those variables.

**Comment by daroczig** [comment]
Thank you @vspinu!  Unfortunately, I deleted my comment just before you replied -- because I found your really helpful answer at http://emacs.1067599.n5.nabble.com/indentation-of-ggplot-code-and-ess-13-09-02-td322315.html#a322335 -- which resolved the issue.
