### ISSUE TITLE
build ESSDIR configuration gets overwritten

### ISSUE THREAD

**Issue by seregaxvm** [emacs-ess/ESS#990]
Current Makefile from `master` branch does not respect `ESSDIR` value from Makeconf file.
It gets unconditionally overwritten [here](https://github.com/seregaxvm/ESS/blob/master/Makefile#L8).

**Comment by vspinu** [comment]
Yeh, ESSDIR is now used with two meanings. It was an internal variable before the (relatively) recent cleanup of the Makefiles.
