### ISSUE TITLE
as.numeric coercion crashes inside package development directory

### ISSUE THREAD

**Issue by pietrodito** [emacs-ess/ESS#991]
## Reproductible steps
 ### Install emacs 26.3 from Arch extra repo:
 https://www.archlinux.org/packages/extra/x86_64/emacs/
 
 ### Install latest version of R 3.6..3-1 from Arch extra repo:
 https://www.archlinux.org/packages/extra/x86_64/r/
 #### And also `gcc-fortran` needed to build some R packages
 https://www.archlinux.org/packages/core/x86_64/gcc-fortran/
 
 ### Install the `devtools` R package from CRAN:
 https://cran.r-project.org/web/packages/devtools/index.html
 
 ### Install only `ess` package in emacs from melpa
 #### My `.emacs` (from https://melpa.org/#/getting-started)
 ```{emacs-lisp}
 (require 'package)
 (let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                     (not (gnutls-available-p))))
        (proto (if no-ssl "http" "https")))
   (when no-ssl (warn "\
 Your version of Emacs does not support SSL connections,
 which is unsafe because it allows man-in-the-middle attacks.
 There are two things you can do about this warning:
 1. Install an Emacs version that does support SSL and be safe.
 2. Remove this warning from your init file so you won't see it again."))
   (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
   ;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
   ;; and `package-pinned-packages`. Most users will not need or want to do this.
   ;;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
   )
 (package-initialize)
 ```
 #### Then doing `package-install` and `ess` inside of emacs
 
 ### Inside empty directory
 #### R file opened in emacs `issue.R`
 ```
 as.numeric("a", "1")
 ```
 If I eval this single line with `ess-eval-line`:
#### Output on R process
 ```
 > as.numeric(c("a", "1"))
 [1] NA  1
 Warning message:
 NAs introduced by coercion 
 > 
 ```
 
 ### Inside a package development directory
 #### Creation of a package directory with `devtools
 ```
 > devtools::create('apackage')
 ```
 #### R script `./apackage/issue.R`
 ```
 as.numeric("a", "1")
 ```
 If I eval this single line with `ess-eval-line`:
 
 #### Output on R process
 ```
 > as.numeric(c("a", "1"))
 Error in eval(ei, envir) : 
   (converted from warning) NAs introduced by coercion
 ```
 
Any ideas?

**Comment by vspinu** [comment]
Thanks for this. It was a messup on our side, a trailing (debug, I guess) `option(warn=2)` in the code

**Comment by pietrodito** [comment]
Let me thank you for all the good work!
