### ISSUE TITLE
flymake + lintr: possible to ignore note-type warnings?

### ISSUE THREAD

**Issue by vnckppl** [emacs-ess/ESS#992]
`x = 1`

results in the warning: 

> Use <-, not =, for assignment.
 
Is it possible to configure emacs such that this warning is not displayed?

**Comment by jabranham** [comment]
Not directly, I think. You can of course omit certain linters via
ess-r-flymake-linters but I don't think there's an easy way to ignore
all warnings of type :note.

This seems like it might be a useful addition to upstream Emacs;
consider filing a bug report (M-x report-emacs-bug) to request this
feature.

**Comment by jabranham** [comment]
I'm closing this since it's more of a flymake issue than an ESS issue.
